Repository ToolJet/ToolJet, pull requests merged in 2022-04, with the labels that each got.

#2711 Add check for null or empty string group name on creation
  server/src/services/group_permissions.service.ts
Labels: run-ci

#2701 Added autoFocus attribute in input element to support enter functionality in the create version modal
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#2688 Chore: Trim version load
  server/src/main.ts
  server/src/services/apps.service.ts
Labels: run-ci

#2493 update passport and run npm audit fix
  .tool-versions
  frontend/src/Editor/Box.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/websocketConnection.js
  server/package-lock.json
  server/package.json
Labels: run-ci

#2722 fix: add transition to search input
  frontend/src/_styles/custom.scss
  frontend/src/_ui/Search/Search.jsx
Labels: run-ci

#2758 [docs] Added spinner widget docs
  docs/docs/widgets/spinner.md
  docs/static/img/widgets/spinner/spinner.png
Labels: documentation

#2725 made confirm page scrollable
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2678 Style fix for Dashboard Nav link menu placement
  frontend/src/_components/Header.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2734 chore: create component for version create modal
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/InitVersionCreateModal.jsx
Labels: needs testing, run-ci

#2665 [Bugfix] resolves crash for table cell types expecting input type array
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci, tested

#2653 [Bugfix]: data resets or current table data is updated the selectedRow and selectedRowId is still populated with the previous data.
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci, tested

#2597 Feature/update timer behaviour
  frontend/src/Editor/Components/Timer.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: run-ci

#2768 alignment fix for codehinter tooltip
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: run-ci

#2765 Hiding custom validation error message when visibility of dropdown widget is set to false
  frontend/src/Editor/Components/DropDown.jsx
Labels: run-ci

#2724 Feature :: Integration rethinkDB
  docs/docs/data-sources/rethinkdb.md
  docs/static/img/datasource-reference/rethink/rethink_auth.png
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/rethinkdb/.gitignore
  plugins/packages/rethinkdb/README.md
  plugins/packages/rethinkdb/__tests__/index.js
  plugins/packages/rethinkdb/lib/icon.svg
  plugins/packages/rethinkdb/lib/index.ts
  plugins/packages/rethinkdb/lib/manifest.json
  plugins/packages/rethinkdb/lib/operations.json
  plugins/packages/rethinkdb/lib/types.ts
  plugins/packages/rethinkdb/package-lock.json
  plugins/packages/rethinkdb/package.json
  plugins/packages/rethinkdb/tsconfig.json
Labels: run-ci

#2761 Improved pagination for the dark mode
  frontend/src/_components/Pagination.jsx
Labels: run-ci, tested

#2773 [Feature]: Baserow integration
  docs/docs/data-sources/baserow.md
  docs/static/img/datasource-reference/baserow/baserow-create-row.png
  docs/static/img/datasource-reference/baserow/baserow-delete-row.png
  docs/static/img/datasource-reference/baserow/baserow-get-row.png
  docs/static/img/datasource-reference/baserow/baserow-intro.gif
  docs/static/img/datasource-reference/baserow/baserow-list-fields.png
  docs/static/img/datasource-reference/baserow/baserow-list-rows.png
  docs/static/img/datasource-reference/baserow/baserow-move-row.png
  docs/static/img/datasource-reference/baserow/baserow-update-row.png
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/baserow/.gitignore
  plugins/packages/baserow/README.md
  plugins/packages/baserow/__tests__/index.js
  plugins/packages/baserow/lib/icon.svg
  plugins/packages/baserow/lib/index.ts
  plugins/packages/baserow/lib/manifest.json
  plugins/packages/baserow/lib/operations.json
  plugins/packages/baserow/lib/types.ts
  plugins/packages/baserow/package-lock.json
  plugins/packages/baserow/package.json
  plugins/packages/baserow/tsconfig.json
Labels: run-ci, tested

#2784 [Feature]: Hide tabs in Tab widget
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2322 [Improvement] migrates to react-select: selection dropdown component
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/OAuth/Authentication.jsx
  frontend/src/_ui/OAuth/index.js
  frontend/src/_ui/Select/SelectComponent.jsx
  frontend/src/_ui/Select/index.js
  frontend/src/_ui/Select/styles.js
Labels: run-ci, tested

#2757 Style updates for styles tab in inspector
  frontend/src/_styles/theme.scss
Labels: run-ci

#2816 [docs] Updated Baserow and CouchDB docs
  docs/docs/data-sources/baserow.md
  docs/docs/data-sources/couchdb.md
  docs/static/img/datasource-reference/couchdb/create.png
  docs/static/img/datasource-reference/couchdb/creating.png
  docs/static/img/datasource-reference/couchdb/delete.png
  docs/static/img/datasource-reference/couchdb/deleting.png
  docs/static/img/datasource-reference/couchdb/get_view.png
  docs/static/img/datasource-reference/couchdb/list.png
  docs/static/img/datasource-reference/couchdb/listing.png
  docs/static/img/datasource-reference/couchdb/retreive.png
  docs/static/img/datasource-reference/couchdb/retrieving.png
  docs/static/img/datasource-reference/couchdb/update.png
  docs/static/img/datasource-reference/couchdb/updating.png
  docs/static/img/datasource-reference/couchdb/view.png
Labels: documentation

#2826 [Bugfix] On dispatching Undo ⌘Z or Redo ⌘+shift+Z actions to a component on the editor should also update the internal state or props for the children.
  frontend/src/Editor/Editor.jsx
Labels: run-ci, tested

#2796 Improving codehinter UX for better typing
  frontend/src/Editor/CodeBuilder/utils.js
Labels: run-ci

#2835 Fix: #2702 - set newGroupName to null on cancel
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
Labels: run-ci

#2718 Add missing sourceOptions to Snowflake to fix the warehouse/database/schema/role when connecting
  plugins/packages/snowflake/lib/index.ts
  plugins/packages/snowflake/package.json
Labels: run-ci

#2846 Add count of elements to new datasource modal
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci

#2636 [Feature] Implemented SSL certificate option in PostgreSQL data-source
  plugins/packages/postgresql/lib/index.ts
  plugins/packages/postgresql/lib/manifest.json
  plugins/packages/postgresql/lib/types.ts
Labels: needs testing, run-ci

#2660 [Bugfix]: Allow firing onSearch event of Table widget irrespective of server-side search is set to true or false.
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
Labels: run-ci, tested

#2847 [docs] renamed deployment directory to setup
  .env.example
  README.md
  deploy/docker/.env.example
  deploy/ec2/.env
  docs/docs/contributing-guide/setup/Mac OS.md
  docs/docs/contributing-guide/setup/docker.md
  docs/docs/contributing-guide/setup/ubuntu.md
  docs/docs/data-sources/google.sheets.md
  docs/docs/intro.md
  docs/docs/setup/_category_.json
  docs/docs/setup/architecture.md
  docs/docs/setup/client.md
  docs/docs/setup/docker.md
  docs/docs/setup/ec2.md
  docs/docs/setup/env-vars.md
  docs/docs/setup/google-cloud-run.md
  docs/docs/setup/heroku.md
  docs/docs/setup/kubernetes-aks.md
  docs/docs/setup/kubernetes-gke.md
  docs/docs/setup/kubernetes.md
  docs/static/img/setup/heroku/appname.png
  docs/static/img/setup/heroku/build.png
  docs/static/img/setup/heroku/deployapp.png
  docs/static/img/setup/heroku/login.png
Labels: documentation

#2517 feat: Add realtime collaboration
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App/App.jsx
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Cursor.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/Editor/RealtimeCursors.jsx
  frontend/src/Editor/RealtimeEditor.jsx
  frontend/src/_helpers/constants.js
  frontend/src/_helpers/websocketConnection.js
  frontend/src/_services/appVersion.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Avatar/index.jsx
  server/package-lock.json
  server/package.json
  server/src/events/events.gateway.ts
  server/src/events/events.module.ts
  server/src/events/yjs.gateway.ts
Labels: run-ci, tested

#2106 [Bugfix] stripe query selection dropdown menu should display the selected component value on saving the query
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2858 [docs] changed sidebar position for setup
  docs/docs/security.md
  docs/docs/setup/_category_.json
  docs/docs/tutorial/_category_.json
Labels: documentation

#2694 Feature: Add data transfer object layer to validate and sanitize user inputs
  frontend/package-lock.json
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/_services/authentication.service.js
  frontend/src/_services/user.service.js
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/all-exceptions-filter.ts
  server/src/controllers/app.controller.ts
  server/src/controllers/apps.controller.ts
  server/src/controllers/data_queries.controller.ts
  server/src/controllers/data_sources.controller.ts
  server/src/controllers/folders.controller.ts
  server/src/controllers/group_permissions.controller.ts
  server/src/controllers/metadata.controller.ts
  server/src/controllers/organization_users.controller.ts
  server/src/controllers/users.controller.ts
  server/src/dto/app-authentication.dto.ts
  server/src/dto/app-update.dto.ts
  server/src/dto/create-comment.dto.ts
  server/src/dto/create-folder.dto.ts
  server/src/dto/create-thread.dto.ts
  server/src/dto/data-query.dto.ts
  server/src/dto/data-source.dto.ts
  server/src/dto/group-permission.dto.ts
  server/src/dto/invite-new-user.dto.ts
  server/src/dto/user-onboarding.dto.ts
  server/src/dto/user.dto.ts
  server/src/dto/version-create.dto.ts
  server/src/helpers/utils.helper.ts
  server/src/main.ts
  server/src/services/apps.service.ts
  server/src/services/auth.service.ts
  server/src/services/organization_users.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/data_queries.e2e-spec.ts
  server/test/controllers/users.e2e-spec.ts
  server/test/jest-e2e.json
  server/test/test.helper.ts
Labels: run-ci, testing

#2869 Fix User group not creating on press enter
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
Labels: run-ci

#2867 bugfix :: disable cursor when pagination icons are disabled
  frontend/src/Editor/Components/Table/Pagination.jsx
Labels: run-ci

#2820 [Feature] Added a feature to show maintenance state of an app
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarGlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/_services/app.service.js
  frontend/src/_styles/theme.scss
  server/migrations/1649860649643-AddIsMaintenanceOnToApp.ts
  server/src/controllers/apps.controller.ts
  server/src/dto/app-update.dto.ts
  server/src/entities/app.entity.ts
  server/src/services/apps.service.ts
Labels: run-ci

#2880 Fix: Thread/Comment edit and delete
  server/src/controllers/comment.controller.ts
  server/src/controllers/thread.controller.ts
  server/src/dto/comment.dto.ts
  server/src/dto/thread.dto.ts
  server/src/entities/thread.entity.ts
  server/src/repositories/comment.repository.ts
  server/src/repositories/thread.repository.ts
  server/src/services/comment.service.ts
  server/src/services/thread.service.ts
Labels: run-ci, tested

#2728 Feature: OpenApi plugin
  docs/docs/data-sources/openapi.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_helpers/ref_resolver.js
  frontend/src/_services/openapi.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/OpenAPI/Oauth.jsx
  frontend/src/_ui/OpenAPI/OpenapiAuth.jsx
  frontend/src/_ui/OpenAPI/index.js
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/openapi/.gitignore
  plugins/packages/openapi/README.md
  plugins/packages/openapi/__tests__/index.js
  plugins/packages/openapi/lib/icon.svg
  plugins/packages/openapi/lib/index.ts
  plugins/packages/openapi/lib/manifest.json
  plugins/packages/openapi/lib/operations.json
  plugins/packages/openapi/lib/types.ts
  plugins/packages/openapi/package-lock.json
  plugins/packages/openapi/package.json
  plugins/packages/openapi/tsconfig.json
Labels: frontend, run-ci, plugins, tested

#2898 fix: realtime update for global settings
  frontend/src/Editor/Editor.jsx
Labels: needs testing, run-ci

#2853 [Feature] Notion plugin 🚀
  docs/docs/data-sources/notion.md
  plugins/package.json
  plugins/packages/notion/.gitignore
  plugins/packages/notion/README.md
  plugins/packages/notion/__tests__/index.js
  plugins/packages/notion/lib/icon.svg
  plugins/packages/notion/lib/index.ts
  plugins/packages/notion/lib/manifest.json
  plugins/packages/notion/lib/operations.json
  plugins/packages/notion/lib/operations.ts
  plugins/packages/notion/lib/types.ts
  plugins/packages/notion/package-lock.json
  plugins/packages/notion/package.json
  plugins/packages/notion/tsconfig.json
Labels: run-ci, plugins, tested

#2911 style: hide resolved icon if not the thread owner
  frontend/src/Editor/Comment/CommentHeader.jsx
Labels: needs testing, run-ci

#2900 [Bugfix] Tabs widget's Highlight text color doesn't change
  frontend/src/Editor/Components/Tabs.jsx
Labels: bug, run-ci, widget

#2877 fixed Text Widget not showing zero and false
  frontend/src/Editor/Components/Text.jsx
Labels: run-ci

#2667 Added a field for sending JSON body with Rest Api Queries
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/GroupHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/Tabs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/_helpers/utils.js
  plugins/packages/restapi/lib/index.ts
Labels: run-ci, tested

#2844 Fix key-value input increment when no items are added
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
Labels: run-ci, tested

#2917 [chore] fixes eslint warning and errors
  frontend/src/Editor/Components/DaterangePicker.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/Editor/RealtimeCursors.jsx
  frontend/src/Editor/RealtimeEditor.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
Labels: run-ci

#2915 fix: able to edit app post version released
  frontend/src/Editor/Editor.jsx
Labels: run-ci, tested

#2926 Feature: Add backend validation to prevent editing released version
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci, tested

#2934 Fix: New sign up throws error on confirmation page
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
Labels: run-ci
