Repository ToolJet/ToolJet, pull requests merged in 2022-10, with the labels that each got.

#4228 [added] TextWidget default color
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#4103 fix: add max file size validator for user avatar
  server/src/controllers/users.controller.ts
Labels: run-ci

#4111 Datepicker calender dark theme
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/_styles/theme.scss
Labels: good first issue, frontend, run-ci, widget

#4270 [Bugfix]throw error with response body instead of response fro Oauth
  plugins/packages/restapi/lib/index.ts
Labels: run-ci

#4074 Add happy path spec for number input widget
  cypress-tests/cypress/constants/texts/button.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/login.js
  cypress-tests/cypress/constants/texts/numberInput.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/fixtures/fake.js
  frontend/src/Editor/Components/NumberInput.jsx
Labels: cypress

#4236 Removed duplicate onHover
  frontend/src/_helpers/appUtils.js
Labels: run-ci

#4155 An event should be fired when columns are editable and any cell value gets an update by the user
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
Labels: enhancement, run-ci, tested, table

#4151 [improvements] Table - exposed active sort options and add an event
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
Labels: enhancement, run-ci, widget, tested, table

#3943 [Feature/plugin] Zendesk integration 🚀
  docs/docs/data-sources/zendesk.md
  docs/sidebars.js
  docs/static/img/datasource-reference/zendesk/zendesk.gif
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/Zendesk.jsx
  plugins/package.json
  plugins/packages/zendesk/.gitignore
  plugins/packages/zendesk/README.md
  plugins/packages/zendesk/__tests__/index.js
  plugins/packages/zendesk/lib/icon.svg
  plugins/packages/zendesk/lib/index.ts
  plugins/packages/zendesk/lib/manifest.json
  plugins/packages/zendesk/lib/operations.json
  plugins/packages/zendesk/lib/types.ts
  plugins/packages/zendesk/package.json
  plugins/packages/zendesk/tsconfig.json
  server/src/services/data_sources.service.ts
Labels: do not merge, run-ci, plugins

#4323 [Bugfix] Widgets dropped to the Modal as its children, should be able to drag to the bottom with scroll active
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: needs testing, run-ci

#4098 [ hotfix ] : [ Table Widget ] filter pop-up and dropdown inside it are not scrollable
  frontend/src/Editor/Components/Table/Filter.jsx
Labels: bug, frontend, run-ci, widget, hotfix

#4130 [Enhancement] : [Table widget] Adding filters
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/custom-filter.js
Labels: frontend, run-ci, widget, tested, table

#4335 [Bugfix]: Fixes server side search for table
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, tested, table

#4337 Ability to use Server side sort for table widget
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: enhancement, widget, table

#4135 [improvement] Table : adds number as a cell type
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/_helpers/utils.js
Labels: enhancement, run-ci, needs documentation, table

#4247 Updated default text color for table widget
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#4104 Enhancement :: table events :: onHover
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
Labels: enhancement, widget

#4134 [ Enhancement ] : [ Table widget ] added support to download data in excel
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/theme.scss
Labels: enhancement, frontend, needs testing, run-ci, widget, table

#4263 [improvement] Table: exposes updatedData with current Table and latest data updates
  frontend/src/Editor/Components/Table/Table.jsx
Labels: enhancement, needs testing, run-ci, widget, needs documentation

#4365 [Hotfix] Oauth rest api circular error
  plugins/packages/restapi/lib/index.ts
Labels: hotfix

#4349 [Improvements] Table: Adds Support for Server side filtering
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, widget, table

#4356 Added border color property to button styles
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#4300 Feature/list view border color
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, run-ci

#4090 [feature]:: Mariadb plugin
  docs/docs/data-sources/mariadb.md
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/mariadb/.gitignore
  plugins/packages/mariadb/README.md
  plugins/packages/mariadb/__tests__/index.js
  plugins/packages/mariadb/lib/icon.svg
  plugins/packages/mariadb/lib/index.ts
  plugins/packages/mariadb/lib/manifest.json
  plugins/packages/mariadb/lib/operations.json
  plugins/packages/mariadb/lib/types.ts
  plugins/packages/mariadb/package-lock.json
  plugins/packages/mariadb/package.json
  plugins/packages/mariadb/tsconfig.json
  server/package-lock.json
Labels: run-ci, plugins, tested, create-review-app

#4326 all: fix spelling
  README.md
  app.json
  cli/src/commands/plugin/create.ts
  cli/src/commands/plugin/delete.ts
  cli/src/commands/plugin/install.ts
  cypress-tests/cypress/constants/selectors/datePicker.js
  cypress-tests/cypress/constants/texts/dashboard.js
  cypress-tests/cypress/support/utils/datePickerWidget.js
  deploy/helm/templates/tooljet/hpa.yaml
  deploy/helm/values.yaml
  docs/docs/data-sources/bigquery.md
  docs/docs/data-sources/couchdb.md
  docs/docs/data-sources/firestore.md
  docs/docs/data-sources/mongodb.md
  docs/docs/data-sources/notion.md
  docs/docs/how-to/access-users-groups.md
  docs/docs/how-to/upload-files-aws.md
  docs/docs/how-to/upload-files-gcs.md
  docs/docs/setup/kubernetes-aks.md
  docs/docs/tutorial/manage-users-groups.md
  docs/docs/tutorial/sharing-and-deploying.md
  docs/docs/tutorial/workspace-environment-variables.md
  docs/docs/widgets/circular-progressbar.md
  docs/docs/widgets/file-picker.md
  docs/docs/widgets/pagination.md
  docs/docs/widgets/statistics.md
  docs/docs/widgets/tree-select.md
  docs/static/img/tutorial/sharing/embed.png
  frontend/assets/translations/en.json
  frontend/assets/translations/fr.json
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/Components/Calendar.jsx
  frontend/src/Editor/Components/CalendarPopover.jsx
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/HomePage/Configs/AppIcon.json
  frontend/src/_helpers/utils.js
  plugins/packages/restapi/lib/index.ts
  plugins/packages/rethinkdb/lib/index.ts
  plugins/packages/rethinkdb/lib/operations.json
  plugins/packages/smtp/lib/operations.json
  server/data-migrations/LockMigrationsTable1.ts
  server/migrations/LockMigrationsTable1.ts
  server/src/controllers/data_queries.controller.ts
  server/src/services/app_import_export.service.ts
  server/templates/s3-file-explorer/definition.json
  server/templates/store-catalogue-management-dashboard/manifest.json
  server/test/controllers/group_permissions.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
Labels: hacktoberfest

#4202 Added Border color style property to Container widgets
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#4371 [localization]translated component manager in french
  frontend/assets/translations/fr.json
Labels: hacktoberfest-accepted

#4287 [localization] translate strings in Indonesian
  frontend/assets/translations/id.json
  frontend/assets/translations/languages.json
Labels: hacktoberfest-accepted

#4221 Hide Apps tab for Admin (#2634)
  frontend/src/Editor/Components/Container.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
Labels: run-ci, tested

#4364 fixes: exposes the latest currentData in the table
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci, tested, table

#4308 [localization] translate strings (editor & header) section in Indonesian
  frontend/assets/translations/id.json
Labels: hacktoberfest-accepted, translation

#4398 Show user list for all groups other than all users
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
Labels: run-ci, tested

#4284 Feature :: Table - option to hide columns
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/theme.scss
Labels: table

#4142 Feature :: Table sort disable/enable
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/actions.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: enhancement, widget

#4083 Enhancements :: Table bugfixes and option for pagination number added
  frontend/package-lock.json
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
Labels: enhancement, run-ci, widget, ui

#4327 [ Feature ] :: Reorder Table columns using drag and drop
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/theme.scss
Labels: enhancement, run-ci, table

#4092 [ Improvement ] :: Table widget
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: enhancement, frontend, widget

#4408 Bugfix :: Table sort not visible
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/theme.scss
Labels: bug, needs testing

#4418 Fix :: user group table ui breaking
  frontend/src/_styles/theme.scss
Labels: needs testing, run-ci

#4427 Fix:: resizer not visible in preview mode :: [ Table widget ]
  frontend/src/_styles/theme.scss
Labels: needs testing

#4406 [hotfix] Fixed oauth refresh token issue
  plugins/packages/restapi/lib/index.ts
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
Labels: backend, run-ci

#4426 Table : Update exposed variables terminology for table widget on column sort is applied
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci, table

#4430 [Bugfix] show or hide pagination footer only if client or server side pagination is enabled
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci, table

#4342 [Bug]: Triggered Selection Only On Main Canvas
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: bug, run-ci, tested, ui, editor

#4432 [docs] added mariadb and other improvements
  docs/docs/actions/control-component.md
  docs/docs/data-sources/mariadb.md
  docs/docs/widgets/button.md
  docs/docs/widgets/date-range-picker.md
  docs/docs/widgets/text-input.md
  docs/docs/widgets/text.md
  docs/sidebars.js
  docs/static/img/datasource-reference/mariadb/connection.png
  docs/static/img/datasource-reference/mariadb/query.png
  docs/static/img/widgets/date-range/event.png
  docs/static/img/widgets/text-input/events.png
Labels: documentation

#4112 Add happy path spec for password input widget
  cypress-tests/cypress/constants/texts/passwordInput.js
  cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/commonWidget.js
  frontend/src/Editor/Components/PasswordInput.jsx
Labels: cypress

#3987 bug fixed : table widget is not consistent with the dark theme
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_styles/theme.scss
Labels: bug, frontend, run-ci, widget, react

#4271 [ Enhancement ]: Ability to export versioned apps ( frontend )
  frontend/src/HomePage/ExportAppModal.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_services/app.service.js
  frontend/src/_styles/theme.scss
Labels: frontend, feature request, javascript, run-ci, tested, react

#4468 Fix flaky cypress specs on v1.27.0
  cypress-tests/cypress/support/utils/commonWidget.js
Labels: cypress

#4359 [localization]: Translate Profile Settings Page in French (#4185)
  frontend/assets/translations/fr.json
Labels: hacktoberfest, translation

#4307 Rename Environment Variables to Workspace Variables
  frontend/assets/translations/en.json
  frontend/assets/translations/fr.json
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/_components/Organization.jsx
Labels: hacktoberfest-accepted

#4294 [Bugfix] Clear groups input field after creating a new group
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
Labels: hacktoberfest-accepted

#4198 On Change added to NumberInput
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#4416 [ bug fixed ]: [ Table widget ] selecting option from badge column breaks the widget
  frontend/src/Editor/Components/Table/CustomSelect.jsx
Labels: bug, good first issue, frontend, javascript, run-ci, widget, tested, react

#4445 [ bug fixed ] : Editor throws [ TypeError: Cannot read properties of undefined ] warning in the console
  frontend/src/_helpers/utils.js
Labels: bug, frontend, javascript, run-ci

#4514 [ Hotfix ] :: App breaking while reconnecting sheets
  frontend/src/_components/Googlesheets.jsx
  plugins/packages/googlesheets/lib/index.ts
  plugins/packages/openapi/lib/index.ts
  plugins/packages/restapi/lib/index.ts
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
Labels: run-ci

#4511 [Bug]: Fixed Bug on Query Panel Height
  frontend/src/Editor/QueryManager/QueryPanel.jsx
Labels: bug, run-ci, tested, ui, editor, hotfix

#4502 [Bug]: Disabled picking browsers language in localisation
  frontend/src/index.jsx
Labels: bug, run-ci, hotfix, translation

#4473 [Bug]: Displayed Newly Added Data Source in Query Manager
  frontend/src/Editor/QueryManager/DataSourceLister.jsx
Labels: bug, run-ci, tested, ui, editor

#4410 fixes: scroll issue for subcontainer layer for modal
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: bug, run-ci, widget

#4585 Bugfix :: clickhouse added twice in sidebar :: [ docs ]
  docs/docs/data-sources/athena.md
  docs/sidebars.js
Labels: documentation

#4587 fix(LoginPage): missing whitespace
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
Labels: run-ci

#4566 Add Ukrainian localisation
  frontend/assets/translations/languages.json
  frontend/assets/translations/uk.json
Labels: run-ci

#4551 fix :: GCS template crashing
  server/templates/gcs-file-explorer/manifest.json
Labels: run-ci

#4491 Fix underscore between deploy buttons (close #4490)
  README.md
Labels: hacktoberfest-accepted

#4339 [bugfix] Fixed single workspace organization menu issue
  frontend/src/_components/Organization.jsx
Labels: run-ci

#4487 [BUG]Fixes rich text editor select heading re-direct to dashboard
  frontend/src/Editor/Components/DraftEditor.jsx
Labels: run-ci

#4401 Toast position fixed
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
Labels: hacktoberfest-accepted, run-ci

#4584 Fix: issue4179 translate login and signup in French
  frontend/assets/translations/fr.json
Labels: run-ci, translation

#4519 [ bug fixed ]: [ Table widget ] Filter popup is not attached near filter button but attached to bottom.
  frontend/src/_styles/theme.scss
Labels: bug, frontend, javascript, run-ci, ui, table, react

#4568 Fixed Google Cloud Run deployment guide
  docs/docs/setup/google-cloud-run.md
Labels: documentation

#4540 [improvement] Codehinter : The cursor should be auto set to middle of {{ }} with the auto completion
  frontend/src/Editor/CodeBuilder/utils.js
Labels: needs testing, run-ci, testing

#4538 Update theme.css
  frontend/src/_styles/theme.scss
Labels: hacktoberfest-accepted, run-ci

#4372 Layout accordion of widget inspector in Table widget should be open default
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: hacktoberfest-accepted

#4190 Adds background color property to password input editor
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest, hacktoberfest-accepted, run-ci

#4255 toggle button added for time selection and date selection in date picker widget, related to #3576
  docs/docs/widgets/datepicker.md
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, run-ci

#4191 feat: Add customizable border color for text input component
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, run-ci

#4615 bug: fixed error message when editing workspace with same name
  frontend/src/_components/Organization.jsx
Labels: run-ci

#4589 Show version name while deleting
  frontend/assets/translations/en.json
  frontend/assets/translations/es.json
  frontend/assets/translations/fr.json
  frontend/assets/translations/id.json
  frontend/assets/translations/it.json
  frontend/assets/translations/ru.json
  frontend/src/Editor/AppVersionsManager.jsx
Labels: needs testing, run-ci

#4622 [Bugfix]: Widget inspector Toggle element (Fx): component stops receiving updates after the every first
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: bug, needs testing, run-ci, tested

#4620 [Bugix]: Trailing white spaces at the end of the input should not update the widget definitions on the blur event
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: needs testing, run-ci, widget, tested

#4641 Hotfix for Python trasnformation
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#4645 [docs] python transformation
  docs/docs/tutorial/transformations.md
  docs/static/img/tutorial/transformations/jstransform.png
  docs/static/img/tutorial/transformations/ogdata.png
  docs/static/img/tutorial/transformations/tdata.png
Labels: documentation

#4648 fix: pick env from public_config for marketplace
  frontend/src/App/App.jsx
  frontend/webpack.config.js
  server/src/services/app_config.service.ts
Labels: run-ci

#4547 Feature :: Table image column type addition
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/_styles/theme.scss
Labels: enhancement, table

#4549 Fix :: Closing of textarea ontype Table widget
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: table

#4346 [ bug fixed ] : File is saved as csv while type is selected as text on event handler
  frontend/src/_helpers/appUtils.js
  frontend/src/_lib/generate-file.js
Labels: bug, good first issue, frontend, javascript, run-ci, tested

#4669 Chore: Add eslintignore for frontend
  frontend/.eslintignore
Labels: run-ci

#4509 [cypress] Fix failing manage SSO spec in single workspace #4390
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/support/utils/manageSSO.js
Labels: cypress, hacktoberfest-accepted

#4654 Replacd the woocommerce connection screenshot from dark to light one
  docs/static/img/datasource-reference/woocommerce/woocomerce-auth.png
Labels: hacktoberfest-accepted

#4643 gifs for Keyboard Shortcuts Added
  docs/docs/tutorial/keyboard-shortcuts.md
  docs/static/img/tutorial/keyboard-shortcuts/Ctrl+C.gif
  docs/static/img/tutorial/keyboard-shortcuts/Ctrl+D.gif
  docs/static/img/tutorial/keyboard-shortcuts/Ctrl+Shift+Z.gif
  docs/static/img/tutorial/keyboard-shortcuts/Ctrl+V.gif
  docs/static/img/tutorial/keyboard-shortcuts/Ctrl+Z.gif
  docs/static/img/tutorial/keyboard-shortcuts/bkspc.gif
  docs/static/img/tutorial/keyboard-shortcuts/esc.gif
Labels: hacktoberfest-accepted

#4232 [added] Translated global strings in french #4169
  frontend/assets/translations/fr.json
Labels: hacktoberfest-accepted

#4229 [localization] issue-4188 added spanish keys for card app
  frontend/assets/translations/es.json
Labels: hacktoberfest-accepted

#4513 Improve toast message shortcut on component deletion
  frontend/src/Editor/Editor.jsx
Labels: hacktoberfest-accepted, needs testing, run-ci

#4651 feat: Add DTO for organization create
  server/src/controllers/organizations.controller.ts
  server/src/dto/organization-create.dto.ts
Labels: hacktoberfest-accepted, run-ci

#4658 Fixed failing manage SSO spec in multi workspace
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js
  frontend/src/ManageSSO/GeneralSettings.jsx
Labels: cypress, hacktoberfest-accepted

#4649 [followup] [transformation]persist data without saving the query
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
Labels: run-ci, tested

#4667 Fixed failing dashboard specs
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/manageGroups.js
  cypress-tests/cypress/constants/texts/manageUsers.js
  cypress-tests/cypress/e2e/dashboard/dashboard.cy.js
  cypress-tests/cypress/e2e/dashboard/manageGroups.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/userPermissions.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/userPermissions.cy.js
  cypress-tests/cypress/fixtures/fake.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/userPermissions.js
  frontend/src/HomePage/AppCard.jsx
  frontend/src/_components/Pagination.jsx
  frontend/src/_ui/Toast/index.js
Labels: cypress
