Repository ToolJet/ToolJet, pull requests merged in 2022-02, with the labels that each got.

#2051 Fix global settings toggle
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#2048 Improvement: option to resize the debugger popover (Left sidebar)
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
Labels: run-ci

#2008 Fix: Make query manager dropdown visible in dark mode
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#2057 [improvement]updated svg icon of config handler
  frontend/assets/images/icons/settings.svg
  frontend/src/Editor/ConfigHandle.jsx
Labels: run-ci

#2053 Added a toggle to hide axes of chart widget
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/Inspector/Components/Chart.jsx
Labels: run-ci

#2061 Hide text overflow for button widget
  frontend/src/Editor/Components/Button.jsx
Labels: run-ci

#2060 enhancement :: new onboarding ui design
  frontend/assets/images/onboarding.svg
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/HomePage/TemplateCard.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2072 Added border radius property to dropdown widget
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2077 Added border radius property to the table widget
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#1975 Improvement: added onRowClicked event to listview
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2078 fix: rangepicker default value
  frontend/src/Editor/Components/DaterangePicker.jsx
Labels: run-ci

#2059 Fx button for code hinter fields that will flip them to corresponding UI components
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/AlignButtons.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/CodeBuilder/Elements/Components/ToolTip.jsx
  frontend/src/Editor/CodeBuilder/Elements/FxButton.jsx
  frontend/src/Editor/CodeBuilder/Elements/Json.jsx
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/CodeBuilder/Elements/Toggle.jsx
  frontend/src/Editor/CodeBuilder/Elements/utils.js
  frontend/src/Editor/CodeBuilder/TypeMapping.js
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#2084 fixing icon/image in dark mode in onboarding page
  frontend/assets/images/dark-mode-onboarding.svg
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2082 ui changes in comments section
  frontend/src/Editor/CommentNotifications/Content.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Mentions/index.js
Labels: run-ci

#2064 Added selected text color property to the dropdown widget
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2073 Added a border radius property to multi-select widget
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2088 Fix: app card skeleton design
  frontend/src/HomePage/AppList.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1947 [improvement] Query Panel - new design
  frontend/assets/images/icons/circular-info.svg
  frontend/assets/images/icons/editor/play.svg
  frontend/assets/images/icons/plus.svg
  frontend/assets/images/icons/query-trash-icon.svg
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/BaseUrl.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/GroupHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabHeaders.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabParams.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/Tabs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_styles/colors.scss
  frontend/src/_styles/mixins.scss
  frontend/src/_styles/tabler.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Alert/Alert.jsx
  frontend/src/_ui/Alert/index.js
  frontend/src/_ui/Search/Search.jsx
  frontend/src/_ui/Search/index.js
  plugins/packages/airtable/lib/operations.json
  plugins/packages/dynamodb/lib/operations.json
  plugins/packages/elasticsearch/lib/operations.json
  plugins/packages/firestore/lib/operations.json
  plugins/packages/gcs/lib/operations.json
  plugins/packages/googlesheets/lib/operations.json
  plugins/packages/minioapi/lib/operations.json
  plugins/packages/mongo/lib/operations.json
  plugins/packages/mysql/lib/operations.json
  plugins/packages/postgresql/lib/operations.json
  plugins/packages/s3/lib/operations.json
  plugins/packages/sendgrid/lib/operations.json
  plugins/packages/twilioapi/lib/operations.json
  plugins/packages/typesenseapi/lib/operations.json
Labels: run-ci

#2101 Fix: Plot from json toggle button from chart widget doesn’t work as expected - Didn't show hidden content even after toggle back to false
  frontend/src/Editor/Inspector/Components/Chart.jsx
Labels: run-ci

#2092 Prevents multiple widget handles from being shown
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#2094 Update QueryManager.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#2114 Added border radius property to range picker
  frontend/src/Editor/Components/DaterangePicker.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#1970 Add clone component functionality
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#2006 [Bugfix] component names should be generated uniquely
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/_hooks/use-Focus.jsx
Labels: run-ci

#2133 fix: remove widgets from appDef when tab widget deleted
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#2120 Fix: Autosave definition on version release
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
Labels: run-ci

#2127 [Bugfix] Query panel: remove blue border from select dropdown component
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
Labels: run-ci

#2137 fix: add comment on top of widget
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2116 Improvement: Changed widget handle UI
  frontend/assets/images/icons/settings.svg
  frontend/assets/images/icons/trash-light.svg
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2096 Tooljet CLI deployment and sanity check
  cli/.eslintrc.js
  cli/README.md
  cli/package-lock.json
  cli/package.json
  cli/src/commands/plugin/create.ts
  cli/src/commands/plugin/delete.ts
  cli/src/commands/plugin/install.ts
  cli/src/index.ts
  cli/test/commands/plugin/create.test.ts
  cli/test/helpers/init.js
  cli/test/tsconfig.json
  cli/tsconfig.json
  docs/docs/contributing-guide/creating-a-plugin.md
  frontend/src/Editor/DataSourceManager/SourceComponents/index.js
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  plugins/_templates/plugin/new/index.ejs.t
  plugins/_templates/plugin/new/manifest.ejs.t
  plugins/_templates/plugin/new/packagejson.ejs.t
Labels: run-ci

#2086 Adds guided walkthrough for new users
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#2144 Updated dnd to follow pointer position
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/CustomDragLayer.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#2140 [improvements/fixes] Dark theme fixes
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/Comment/CommentFooter.jsx
  frontend/src/Editor/Comment/CommentHeader.jsx
  frontend/src/Editor/CommentNotifications/index.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/Inspector/Elements/Color.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/HomePage/Modal.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/_styles/colors.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Mentions/index.js
Labels: draft, run-ci

#2122 Bugfix :: ui issues part of code edit (fx) feature inclusion & number type addition
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Number.jsx
  frontend/src/Editor/CodeBuilder/TypeMapping.js
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2138 Add position absolute to comment loader
  frontend/src/Editor/Comment/CommentFooter.jsx
  frontend/src/Editor/Comment/index.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/_ui/Mentions/index.js
Labels: run-ci

#2157 Fixes an issue that causes customObjects being resolved incorrectly
  frontend/src/_helpers/utils.js
Labels: run-ci

#2159 fix: star rating color property
  frontend/src/Editor/Components/StarRating/index.js
Labels: run-ci

#2152 Minor style corrections for Fx inputs
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/AlignButtons.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/CodeBuilder/Elements/Number.jsx
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/CodeBuilder/Elements/Toggle.jsx
Labels: run-ci

#2162 Fix: Button should only show the spinner when it is loading
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2163 [Bugfix] style fixes querypanel
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/BaseUrl.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/_styles/theme.scss
  plugins/packages/firestore/lib/operations.json
Labels: run-ci

#2165 updating onboarding with template choosing option
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/HomePage.jsx
Labels: run-ci

#2171 fixes rest-api query methods
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
Labels: run-ci

#2170 Feature/convert multiple fields to fx
  frontend/src/Editor/Components/components.js
  server/migrations/1644229722021-SetFxActiveToTrueForFxFieldsConvertedToUI.ts
Labels: run-ci

#2179 Changed folders skeleton design
  frontend/src/HomePage/Folders.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2175 Fix: Transform label and toggle should be in one row
  frontend/src/Editor/QueryManager/Transformation.jsx
Labels: run-ci

#2180 Fix: marker color for chart didn't change
  frontend/src/Editor/Components/Chart.jsx
Labels: run-ci

#2190 [Docs] Keyboard shortcuts
  docs/docs/tutorial/keyboard-shortcuts.md
  docs/docs/tutorial/tracking.md
Labels: documentation

#2188 [BUG-2187] Plugins manifest.json isLoading type should be boolean
  frontend/src/Editor/DataSourceManager/SourceComponents/Runjs.schema.json
  plugins/_templates/plugin/new/manifest.ejs.t
  plugins/packages/airtable/lib/manifest.json
  plugins/packages/bigquery/lib/manifest.json
  plugins/packages/dynamodb/lib/manifest.json
  plugins/packages/dynamodb/package.json
  plugins/packages/elasticsearch/lib/manifest.json
  plugins/packages/firestore/lib/manifest.json
  plugins/packages/gcs/lib/manifest.json
  plugins/packages/googlesheets/lib/manifest.json
  plugins/packages/graphql/lib/manifest.json
  plugins/packages/minioapi/lib/manifest.json
  plugins/packages/mongo/lib/manifest.json
  plugins/packages/mssql/lib/manifest.json
  plugins/packages/mysql/lib/manifest.json
  plugins/packages/postgresql/lib/manifest.json
  plugins/packages/redis/lib/manifest.json
  plugins/packages/restapi/lib/manifest.json
  plugins/packages/s3/lib/manifest.json
  plugins/packages/sendgrid/lib/manifest.json
  plugins/packages/slack/lib/manifest.json
  plugins/packages/stripe/lib/manifest.json
  plugins/packages/twilioapi/lib/manifest.json
  plugins/packages/typesenseapi/lib/manifest.json
Labels: run-ci

#2191 [Feature] Create record operation for Airtable
  docs/docs/data-sources/airtable.md
  docs/static/img/datasource-reference/airtable/airtable-create.png
  plugins/packages/airtable/lib/index.ts
  plugins/packages/airtable/lib/operations.json
Labels: run-ci

#2197 Fix failing specs on oauth and templates
  server/test/controllers/library_apps.e2e-spec.ts
  server/test/controllers/oauth.e2e-spec.ts
Labels: run-ci

#2154 fix: plugin naming for minio, mongodb, twilio, typesense
  plugins/create-client-entry.js
  plugins/create-server-entry.js
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/minio/README.md
  plugins/packages/minio/__tests__/minioapi.test.js
  plugins/packages/minio/lib/icon.svg
  plugins/packages/minio/lib/index.ts
  plugins/packages/minio/lib/manifest.json
  plugins/packages/minio/lib/operations.json
  plugins/packages/minio/lib/operations.ts
  plugins/packages/minio/lib/types.ts
  plugins/packages/minio/package-lock.json
  plugins/packages/minio/package.json
  plugins/packages/minio/tsconfig.json
  plugins/packages/mongo/__tests__/mongo.test.js
  plugins/packages/mongodb/.gitignore
  plugins/packages/mongodb/README.md
  plugins/packages/mongodb/__tests__/mongodb.test.js
  plugins/packages/mongodb/lib/icon.svg
  plugins/packages/mongodb/lib/index.ts
  plugins/packages/mongodb/lib/manifest.json
  plugins/packages/mongodb/lib/operations.json
  plugins/packages/mongodb/lib/types.ts
  plugins/packages/mongodb/package-lock.json
  plugins/packages/mongodb/package.json
  plugins/packages/mongodb/tsconfig.json
  plugins/packages/twilio/README.md
  plugins/packages/twilio/__tests__/twilioapi.test.js
  plugins/packages/twilio/lib/icon.svg
  plugins/packages/twilio/lib/index.ts
  plugins/packages/twilio/lib/manifest.json
  plugins/packages/twilio/lib/operations.json
  plugins/packages/twilio/lib/types.ts
  plugins/packages/twilio/package-lock.json
  plugins/packages/twilio/package.json
  plugins/packages/twilio/tsconfig.json
  plugins/packages/typesense/README.md
  plugins/packages/typesense/__tests__/typesenseapi.test.js
  plugins/packages/typesense/lib/icon.svg
  plugins/packages/typesense/lib/index.ts
  plugins/packages/typesense/lib/manifest.json
  plugins/packages/typesense/lib/operations.json
  plugins/packages/typesense/lib/operations.ts
  plugins/packages/typesense/lib/types.ts
  plugins/packages/typesense/package-lock.json
  plugins/packages/typesense/package.json
  plugins/packages/typesense/tsconfig.json
Labels: run-ci

#2199 Fixed scroll problem of invitation page
  frontend/src/InvitationPage/InvitationPage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2214 chore: add source-map to devtool for prod
  frontend/webpack.config.js
Labels: run-ci

#2220 deps: update sentry sdk to 6.17.6
  frontend/package-lock.json
  frontend/package.json
  server/package-lock.json
  server/package.json
Labels: run-ci

#2217 fix: vulnerabilities in plugins package json
  plugins/package-lock.json
Labels: run-ci

#2206 Added a spinner to show before rendering template images
  frontend/package-lock.json
  frontend/package.json
  frontend/src/HomePage/TemplateLibraryModal/TemplateDisplay.jsx
  frontend/src/_components/ImageWithSpinner.jsx
  frontend/src/_components/index.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#2229 Show app name as window title when launched
  frontend/src/Editor/Viewer.jsx
Labels: run-ci

#2243 Adds support for JSON string in firestore bulk update query
  plugins/packages/firestore/lib/index.ts
Labels: run-ci

#2211 Fix/codehinter fields scroll
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1998 [Bugfix] Typing "this" or "window" or "app" on any code box will crash the app completely
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/_helpers/utils.js
Labels: run-ci

#2266 [hotfix] adds update operation with sheet name
  plugins/packages/googlesheets/lib/index.ts
  plugins/packages/googlesheets/lib/operations.json
  plugins/packages/googlesheets/lib/operations.ts
Labels: run-ci

#2261 Feature: Snowflake integration
  docs/docs/data-sources/snowflake.md
  docs/static/img/datasource-reference/snowflake/snowflake-connect.png
  docs/static/img/datasource-reference/snowflake/snowflake-query.png
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/snowflake/.gitignore
  plugins/packages/snowflake/README.md
  plugins/packages/snowflake/__tests_/index.js
  plugins/packages/snowflake/lib/icon.svg
  plugins/packages/snowflake/lib/index.ts
  plugins/packages/snowflake/lib/manifest.json
  plugins/packages/snowflake/lib/operations.json
  plugins/packages/snowflake/lib/types.ts
  plugins/packages/snowflake/package-lock.json
  plugins/packages/snowflake/package.json
  plugins/packages/snowflake/tsconfig.json
Labels: run-ci

#2230 Fix: Remove trailing slashes on tooljet host on invite email
  server/src/services/email.service.ts
Labels: run-ci

#2283 Feature: Adds toojet hub telemetry endpoint
  .env.example
  docs/docs/deployment/env-vars.md
  server/src/controllers/metadata.controller.ts
  server/src/services/metadata.service.ts
Labels: run-ci

#2287 adds the not equals and not matches filters to the table widget
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci

#2294 fix space between query pane and widget section
  frontend/src/_styles/theme.scss
Labels: run-ci

#2289 fixes icon and text alignment for query-pane datasource selection
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#2311 [Chore] resolves lint warnings/errors
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/CodeBuilder/Elements/Toggle.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Timer.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/_components/Header.jsx
Labels: run-ci

#2314 disable preview and create query button when no datasource selected
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#2263 Feature: smtp data source plugin
  docs/docs/data-sources/smtp.md
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/smtp/.gitignore
  plugins/packages/smtp/README.md
  plugins/packages/smtp/__tests_/index.js
  plugins/packages/smtp/lib/icon.svg
  plugins/packages/smtp/lib/index.ts
  plugins/packages/smtp/lib/manifest.json
  plugins/packages/smtp/lib/operations.json
  plugins/packages/smtp/lib/types.ts
  plugins/packages/smtp/package-lock.json
  plugins/packages/smtp/package.json
  plugins/packages/smtp/tsconfig.json
Labels: run-ci

#2319 [Bugfix] Modal won't reappear after closing it with ESC
  frontend/src/Editor/Components/Modal.jsx
Labels: run-ci

#2324 [docs] minor formatting fixes in snowflake
  docs/docs/data-sources/snowflake.md
Labels: documentation

#2330 [docs] updated n8n and smtp
  docs/docs/data-sources/n8n.md
  docs/docs/data-sources/smtp.md
  docs/static/img/datasource-reference/n8n/basicauth.png
  docs/static/img/datasource-reference/n8n/headerauth.png
  docs/static/img/datasource-reference/n8n/query.png
  docs/static/img/datasource-reference/smtp/connect.png
  docs/static/img/datasource-reference/smtp/query1.png
  docs/static/img/datasource-reference/smtp/query2.png
Labels: documentation

#2341 [docs] updated typesense and elasticsearch
  docs/docs/data-sources/elasticsearch.md
  docs/docs/data-sources/typesense.md
  docs/static/img/datasource-reference/elasticsearch.png
  docs/static/img/datasource-reference/elasticsearch/connect.png
  docs/static/img/datasource-reference/elasticsearch/elastic-search.png
  docs/static/img/datasource-reference/elasticsearch/get.png
  docs/static/img/datasource-reference/elasticsearch/index.png
  docs/static/img/datasource-reference/elasticsearch/query.png
  docs/static/img/datasource-reference/elasticsearch/update.png
  docs/static/img/datasource-reference/typesense/collection.png
  docs/static/img/datasource-reference/typesense/connect.png
  docs/static/img/datasource-reference/typesense/delete.png
  docs/static/img/datasource-reference/typesense/get.png
  docs/static/img/datasource-reference/typesense/index.png
  docs/static/img/datasource-reference/typesense/query.png
  docs/static/img/datasource-reference/typesense/search.png
  docs/static/img/datasource-reference/typesense/update.png
Labels: documentation

#2335 Feature: upgrade to webpack-dev-server 4
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
Labels: run-ci

#2346 Bugfix - Add tooltip to query panel and use ellipsis when the name is too long
  frontend/src/Editor/Editor.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2351 Hotfix: Handle primary key type on mysql and postgres bulk update
  plugins/packages/mysql/lib/index.ts
  plugins/packages/postgresql/lib/index.ts
Labels: run-ci

#2349 Hotfix/fix action for dropdown
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
Labels: run-ci

#2310 [Bugfix] multi-line SQL queries generated with Javascript
  frontend/src/_helpers/__tests__/appUtils.test.js
  frontend/src/_helpers/appUtils.js
  server/src/services/data_queries.service.ts
Labels: run-ci

#2344 Revise docker-compose dev setup for windows
  docker-compose.yaml
  docs/docs/contributing-guide/setup/docker.md
Labels: run-ci

#2333 Feature: Add remove from folder option to apps dashboard
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_services/folder.service.js
  server/src/controllers/folder_apps.controller.ts
  server/src/services/folder_apps.service.ts
  server/test/controllers/folder_apps.e2e-spec.ts
  server/test/services/folder_apps.service.spec.ts
  server/test/services/users.service.spec.ts
  server/test/test.helper.ts
Labels: run-ci

#2366 [Docs] updated calendar and chart
  docs/docs/widgets/calendar.md
  docs/docs/widgets/chart.md
  docs/static/img/widgets/calendar/calendar-day.png
  docs/static/img/widgets/calendar/calendar-week.png
  docs/static/img/widgets/calendar/calendar.png
  docs/static/img/widgets/calendar/calendar1.png
  docs/static/img/widgets/calendar/events.png
  docs/static/img/widgets/calendar/layout.png
  docs/static/img/widgets/calendar/styles.png
  docs/static/img/widgets/chart/bar.png
  docs/static/img/widgets/chart/barc.png
  docs/static/img/widgets/chart/from_json.png
  docs/static/img/widgets/chart/jsonschema.png
  docs/static/img/widgets/chart/layout.png
  docs/static/img/widgets/chart/line.png
  docs/static/img/widgets/chart/linec.png
  docs/static/img/widgets/chart/pfjson.png
  docs/static/img/widgets/chart/pie.png
  docs/static/img/widgets/chart/piec.png
  docs/static/img/widgets/chart/plot_from_json.png
  docs/static/img/widgets/chart/styles.png
Labels: documentation

#2361 Changed Auto Saved text to Saved
  frontend/src/Editor/Editor.jsx
Labels: run-ci
