Repository ToolJet/ToolJet, pull requests merged in 2022-12, with the labels that each got.

#4140 Feature: Versioned exports
  frontend/src/HomePage/ExportAppModal.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_services/app.service.js
  frontend/src/_styles/theme.scss
  server/src/controllers/app_import_export.controller.ts
  server/src/controllers/apps.controller.ts
  server/src/modules/apps/apps.module.ts
  server/src/services/app_import_export.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
  server/test/test.helper.ts
Labels: run-ci, tested

#4868 [Bugfix] Multipages: Version switching crashes if the target version does not contain the current page
  frontend/src/Editor/Editor.jsx
Labels: bug

#4887 [Bugfix] Multipages: widget inspector event popover unmounts
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: bug

#4591 Feature :: SelectRow CSA :: [ Table ]
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: table

#4497 Changed "show bulk update actions" label in Table (#4496)
  docs/docs/how-to/bulk-update-multiple-rows-in-table.md
  docs/docs/widgets/table.md
  frontend/assets/translations/en.json
  frontend/assets/translations/id.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
  server/templates/github-star-ranking/definition.json
  server/templates/job-application-tracker/definition.json
  server/templates/s3-file-explorer/definition.json
  server/templates/store-catalogue-management-dashboard/definition.json
  server/templates/whatsapp-and-sms-crm/definition.json
Labels: hacktoberfest-accepted, run-ci, tested

#4866 [Feature]: Open widget manager on dropping the widget into canvas
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: frontend, needs testing, run-ci, editor, react

#4693 add remove object method for Minio
  docs/docs/data-sources/minio.md
  plugins/packages/minio/lib/index.ts
  plugins/packages/minio/lib/operations.json
  plugins/packages/minio/lib/operations.ts
Labels: run-ci

#4713 Feature/multi select search groups
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_components/FilterPreview.jsx
  frontend/src/_components/MultiSelect.jsx
  frontend/src/_components/index.js
  frontend/src/_services/groupPermission.service.js
  frontend/src/_services/index.js
  frontend/src/_styles/widgets/multi-select.scss
  server/src/controllers/group_permissions.controller.ts
  server/src/services/group_permissions.service.ts
  server/test/controllers/group_permissions.e2e-spec.ts
Labels: needs testing, run-ci, tested

#4799 Bugfix :: Bulk selection function in table column hide dropdown
  frontend/src/Editor/Components/Table/Table.jsx
Labels: tested

#4911 [Bug]: Fix for Blank Image on Image Widget
  frontend/src/Editor/Components/Image.jsx
Labels: bug, javascript, run-ci, widget, editor, react

#4786 [Bug]: Exposed Default View Properly on Calendar Widget
  frontend/src/Editor/Components/Calendar.jsx
Labels: bug, javascript, needs testing, run-ci, widget, react

#4595 [Feature]: Form Widget
  docs/docs/widgets/form.md
  docs/sidebars.js
  docs/static/img/widgets/form/formwidget.png
  docs/static/img/widgets/form/prop.png
  docs/static/img/widgets/form/styles.png
  frontend/assets/images/icons/widgets/form.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Form.jsx
  frontend/src/Editor/Inspector/Components/Form.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
Labels: frontend, needs testing, run-ci, widget, editor, needs documentation, active-review-app

#4878 [docs ]how-to: insert & load img/pdf using base64 data
  docs/docs/how-to/loading-image-pdf-from-db.md
  docs/docs/widgets/custom-component.md
  docs/sidebars.js
  docs/static/img/how-to/load-base64/filepicker.png
  docs/static/img/how-to/load-base64/get.png
  docs/static/img/how-to/load-base64/insert.png
  docs/static/img/how-to/load-base64/pdf.png
Labels: documentation

#4918 [doc] how-to: use inspector, custom s3 service
  docs/docs/data-sources/s3.md
  docs/docs/how-to/s3-custom-endpoint.md
  docs/docs/how-to/use-inspector.md
  docs/sidebars.js
  docs/static/img/how-to/s3-custom/connection.png
  docs/static/img/how-to/use-inspector/components.png
  docs/static/img/how-to/use-inspector/data0.png
  docs/static/img/how-to/use-inspector/data1.png
  docs/static/img/how-to/use-inspector/globals.png
  docs/static/img/how-to/use-inspector/inspector.png
  docs/static/img/how-to/use-inspector/path.png
  docs/static/img/how-to/use-inspector/pin.png
  docs/static/img/how-to/use-inspector/resize.png
  docs/static/img/how-to/use-inspector/sections.png
Labels: documentation

#4925 User SSO onboarding using cypress
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO/ssoOnboarding.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/package.json
Labels: cypress

#4872 Modify Manage SSO spec in single workspace
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO/ssoOnboarding.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/package.json
Labels: cypress

#4865 Modify manage sso spec in multi workspace
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO/ssoOnboarding.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/package-lock.json
  cypress-tests/package.json
Labels: cypress

#4833 Feature - Multi Environment support
  frontend/src/Editor/Editor.jsx
  frontend/src/_services/dataquery.service.js
  frontend/src/_services/datasource.service.js
  plugins/packages/restapi/lib/index.ts
  server/data-migrations/1630003364070-TurnOnSSLForEveryPostgresDataSource.ts
  server/data-migrations/1639734070615-BackfillDataSourcesAndQueriesForAppVersions.ts
  server/data-migrations/1667076251897-BackfillDataSources.ts
  server/data-migrations/1669054493160-moveDataSourceOptionsToEnvironment.ts
  server/data-migrations/1669055405494-removePluginFromDataQuery.ts
  server/data-migrations/1669919175280-removeRepetitionInDataSourceAndQuery.ts
  server/migrations/1667070216520-createEnvironments.ts
  server/migrations/1667075911289-createDatasourceOptions.ts
  server/src/app.module.ts
  server/src/controllers/apps.controller.ts
  server/src/controllers/data_queries.controller.ts
  server/src/controllers/data_sources.controller.ts
  server/src/dto/data-query.dto.ts
  server/src/dto/data-source.dto.ts
  server/src/entities/app.entity.ts
  server/src/entities/app_environments.entity.ts
  server/src/entities/app_user.entity.ts
  server/src/entities/app_version.entity.ts
  server/src/entities/comment.entity.ts
  server/src/entities/comment_user.entity.ts
  server/src/entities/data_query.entity.ts
  server/src/entities/data_source.entity.ts
  server/src/entities/data_source_options.entity.ts
  server/src/entities/folder_app.entity.ts
  server/src/entities/thread.entity.ts
  server/src/helpers/utils.helper.ts
  server/src/modules/app_environments/app_environments.module.ts
  server/src/modules/apps/apps.module.ts
  server/src/modules/auth/query-auth.guard.ts
  server/src/modules/data_queries/data_queries.module.ts
  server/src/modules/data_sources/data_sources.module.ts
  server/src/modules/library_app/library_app.module.ts
  server/src/modules/org_environment_variables/org_environment_variables.module.ts
  server/src/services/app_environments.service.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
  server/templates/template-converter.js
  server/test/services/app_import_export.service.spec.ts
  server/test/test.helper.ts
Labels: run-ci

#4942 [v2-beta/Improvement]add support actions switch page
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/_helpers/utils.js
Labels: needs testing, run-ci, active-review-app

#4945 [v2-beta-Improvement] delete confirmation
  frontend/src/Editor/Editor.jsx
Labels: run-ci, active-review-app

#4962 fixes: app crash on selecting page switch event for query manager
  frontend/src/Editor/Inspector/Components/Form.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: needs testing, tested, active-review-app

#4961 Fix for all failing specs (multi-env)
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/test/controllers/app_users.e2e-spec.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/data_queries.e2e-spec.ts
  server/test/controllers/data_sources.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
  server/test/test.helper.ts
Labels: run-ci

#4954 [Bugfix] Fix typo in docs
  docs/docs/widgets/table.md
Labels: tested

#4994 [v2-beta bug] REST API query preview error
  frontend/src/_helpers/appUtils.js
  frontend/src/_services/dataquery.service.js
  server/data-migrations/1669055405494-removePluginFromDataQuery.ts
  server/src/controllers/data_queries.controller.ts
  server/src/services/data_sources.service.ts
Labels: run-ci

#4809 [ Bug fixed ]: [ warning in console ] Unsupported style property 'word-break'
  frontend/src/App/App.jsx
Labels: bug, good first issue, frontend, javascript, run-ci, tested, react, suspend-review-app

#4818 [ bug fixed ]: canvas background color is not getting applied in the viewer mode
  frontend/src/Editor/Viewer.jsx
Labels: bug, frontend, javascript, run-ci, tested, react, suspend-review-app

#4988 [ Feature Added ]: [ Dropdown widget ] expose the label property
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: frontend, feature request, javascript, needs testing, run-ci, react

#4989 [ Feature added ]: [ Text widget ] exposed text property
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: good first issue, frontend, feature request, javascript, needs testing, run-ci, react

#4690 [Feature] Runpy : support for running Python code as a query
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/DataSourceManager/SourceComponents/Runpy.schema.json
  frontend/src/Editor/DataSourceManager/SourceComponents/index.js
  frontend/src/Editor/Icons/runpy.svg
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/QueryManager/DataSourceLister.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runpy.jsx
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/dataquery.service.js
Labels: feature request, run-ci, tested, needs documentation, active-review-app

#4908 [Feature] :: Allow users to be filtered via status
  frontend/ee/components/UsersPage/UsersFilter.jsx
  frontend/src/_services/organization.service.js
  server/src/controllers/organizations.controller.ts
  server/src/services/organizations.service.ts
Labels: run-ci, tested, suspend-review-app

#4896 [doc] Run Python code
  docs/docs/data-sources/custom-js.md
  docs/docs/data-sources/run-py.md
  docs/sidebars.js
  docs/static/img/datasource-reference/custom-javascript/custom-javascript.png
  docs/static/img/datasource-reference/custom-javascript/run-js.png
  docs/static/img/datasource-reference/custom-python/run-py.png
  docs/static/img/datasource-reference/custom-python/runpyg.gif
Labels: documentation

#4893 [Enhancement]: Query Builder Improvements
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/QueryPanel.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/Editor/Viewer/Confirm.jsx
  frontend/src/_styles/theme.scss
Labels: enhancement, frontend, javascript, tested, ui, editor, react

#4906 [ Bug fixed ] : [ Table widget ] download as excel exports extra columns
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, frontend, javascript, needs testing, run-ci, widget, table, react

#4597 [ Enhancement ] : Adding PDF downloading option in Table widget
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Components/Table/Table.jsx
Labels: frontend, feature request, javascript, needs testing, run-ci, react, active-review-app

#4981 [Bugfix/v2-beta] app freeze on attaching a page switch action to a page which switches to the same page
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/SettingsModal.jsx
Labels: bug, active-review-app, multipages

#4982 fixes: For empty apps with a single page, the preview page is breaking.
  frontend/src/Editor/Viewer.jsx
Labels: bug

#4983 [Bugfix/v2-beta] Multipages: Page name should have at-least 1 character
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
Labels: bug, multipages

#5015 [Bugfix] viewer pages drawer add text wrap style for page name
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
Labels: bug, multipages

#5016 [Bugfix] Multipages - able to import older apps(v1) to multipage apps (v2)
  server/lib/single-page-to-and-from-multipage-definition-conversion.ts
Labels: bug, active-review-app, multipages

#4997 [fix] Redirect URL didn't work for preview apps
  frontend/src/AppLoader/AppLoader.jsx
  frontend/src/Editor/Viewer.jsx
  server/src/controllers/apps.controller.ts
  server/src/controllers/org_environment_variables.controller.ts
  server/src/decorators/app.decorator.ts
  server/src/interceptors/valid.app.interceptor.ts
  server/src/modules/auth/app-auth.guard.ts
Labels: run-ci

#4999 [Bug fixed ] :[ Table widget ] Badge column type is always editable in table row regardless of the editable property
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: bug, good first issue, frontend, javascript, run-ci, widget, tested, table, react, suspend-review-app

#4985 [Bugfix]: Updated Local State After Deleting the Child Widget in Form
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Form.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
Labels: bug, javascript, widget, editor, react, active-review-app

#4757 [ Enhancement ] : Query panel UI design
  frontend/assets/images/icons/no-queries-added.svg
  frontend/assets/translations/en.json
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/CustomToggleSwitch.jsx
  frontend/src/Editor/QueryManager/Preview.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/BaseUrl.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/GroupHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabHeaders.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabParams.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/Tabs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/SearchBox.jsx
  frontend/src/_styles/colors.scss
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Select/styles.js
Labels: enhancement, frontend, run-ci, ui, react, active-review-app

#4933 Feature :: onboarding self hosted users
  frontend/assets/images/onboardingassets/Icons/info.svg
  frontend/assets/images/onboardingassets/Illustrations/Dots.svg
  frontend/assets/images/onboardingassets/Illustrations/app_image.png
  frontend/assets/images/onboardingassets/Illustrations/background.jpg
  frontend/src/App/App.jsx
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/OnBoardingForm/AdminSetup.jsx
  frontend/src/OnBoardingForm/ContinueButton.jsx
  frontend/src/OnBoardingForm/ContinueButtonSelfHost.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnBoardingInput.jsx
  frontend/src/OnBoardingForm/OnBoardingRadioInput.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/OnBoardingForm/OnboardingBubblesSH.jsx
  frontend/src/OnBoardingForm/OnboardingPassword.jsx
  frontend/src/OnBoardingForm/SignupStatusCard.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/SetupScreenSelfHost.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
  frontend/src/_helpers/constants.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/authentication.service.js
  frontend/src/_styles/theme.scss
  server/src/controllers/app.controller.ts
  server/src/controllers/organizations.controller.ts
  server/src/dto/user.dto.ts
  server/src/helpers/user_lifecycle.ts
  server/src/modules/auth/first-user-signup-disable.guard.ts
  server/src/modules/auth/first-user-signup.guard.ts
  server/src/modules/users/users.module.ts
  server/src/services/auth.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/onboarding/form-auth.e2e-spec.ts
  server/test/controllers/onboarding/git-sso-auth.e2e-spec.ts
  server/test/controllers/onboarding/google-sso-auth.e2e-spec.ts
  server/test/test.helper.ts
Labels: enhancement, run-ci, active-review-app

#5019 [Bugfix] internal storage toast | trigger toasts for running preview db queries
  frontend/src/_helpers/appUtils.js
Labels: run-ci, active-review-app, internal-storage

#4995 [Feature] :: Allow users to invite users in bulk
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/_services/organization_user.service.js
  server/package-lock.json
  server/package.json
  server/src/controllers/organization_users.controller.ts
  server/src/dto/invite-new-user.dto.ts
  server/src/helpers/utils.helper.ts
  server/src/services/organizations.service.ts
  server/src/services/users.service.ts
Labels: run-ci, tested, suspend-review-app

#5008 Make encrypted fields editable
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/Toggle/index.js
  server/src/services/data_sources.service.ts
Labels: run-ci, tested, suspend-review-app

#5010 [improvement] Multipages : sync undo redo to page level
  frontend/src/Editor/Editor.jsx
Labels: run-ci, intermediate-issue, active-review-app

#5021 fix: show confirmation box if filter options are empty in query
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: internal-storage

#5028 [Refactor/Bugfix] database query
  frontend/src/Editor/QueryManager/QueryEditors/ToolJetDb/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/ToolJetDb/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/ToolJetDb/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/ToolJetDb/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/ToolJetDb/UpdateRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/ToolJetDb/operations.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_styles/queryManager.scss
Labels: needs testing, run-ci, refactor, active-review-app, internal-storage

#4840 Fix :: Drag issue table columns properties :: [ Table widget ]
  frontend/assets/images/icons/dragicon.svg
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: tested, table, suspend-review-app

#4790 [improvement] Workspace environment variables didn't work in RunJs queries
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/_helpers/utils.js
Labels: enhancement, tested, suspend-review-app

#5032 [ Bug fixed ] : not able to view single query upon clicking on breadcrum
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: bug, frontend, javascript, editor, react

#5031 [ Bug fixed ] : able to rename a query name to existing one
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: bug, frontend, javascript, editor, react

#4941 Fix SSO signup spec
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO/ssoOnboarding.cy.js
  cypress-tests/cypress/support/commands.js
Labels: cypress

#5043 [[Fix]]: last name null issues
  frontend/src/Editor/Comment/index.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/_ui/Mentions/index.js
  server/src/services/organizations.service.ts
Labels: run-ci

#4931 [docs] customized `setup` index page
  docs/docs/setup/index.md
  docs/package-lock.json
  docs/src/components/DocsCard/DocsCard.css
  docs/src/components/DocsCard/DocsCard.jsx
  docs/src/components/DocsCard/DocsCardList.jsx
  docs/src/components/DocsCard/index.js
  docs/static/img/setup/icons/client.svg
  docs/static/img/setup/icons/digitalocean.svg
  docs/static/img/setup/icons/docker.svg
  docs/static/img/setup/icons/ec2.svg
  docs/static/img/setup/icons/ecs.svg
  docs/static/img/setup/icons/env-vars.svg
  docs/static/img/setup/icons/google-cloud-run.svg
  docs/static/img/setup/icons/heroku.svg
  docs/static/img/setup/icons/http-proxy.svg
  docs/static/img/setup/icons/kubernetes.svg
  docs/static/img/setup/icons/tooljet-subpath.svg
  docs/static/img/setup/icons/try-tooljet.svg
  docs/yarn.lock
Labels: documentation, enhancement

#5048 Chore: Render preview with supervisord
  .env.example
  .github/workflows/render-preview-deploy.yml
  deploy/docker/supervisord.conf
  docker/preview.Dockerfile
  server/scripts/boot.sh
Labels: active-review-app

#5004 fix: 4966 edit comments
  frontend/src/_ui/Mentions/index.js
Labels: run-ci

#5034 [Improvement] Internal storage - table validations
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/_services/tooljetDatabase.service.js
  server/src/controllers/tooljet_db.controller.ts
  server/src/dto/create-postgrest-table.dto.ts
  server/src/modules/casl/abilities/tooljet-db-ability.factory.ts
  server/src/services/tooljet_db.service.ts
Labels: enhancement, active-review-app, suspend-review-app, internal-storage

#5040 Internal storage - Pagination for Database table
  frontend/assets/images/icons/add-row.svg
  frontend/assets/images/icons/chevron-left.svg
  frontend/assets/images/icons/chevron-right.svg
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/Paginations.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_styles/components.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Select/SelectComponent.jsx
  server/src/services/postgrest_proxy.service.ts
Labels: run-ci, active-review-app, suspend-review-app, internal-storage

#5060 [v2-beta] Fix for user last name displayed as null in comments body
  frontend/src/Editor/Comment/CommentBody.jsx
Labels: run-ci

#5055 [Bugfix]internal storage - column validations
  server/src/dto/create-postgrest-table.dto.ts
Labels: bug, active-review-app, internal-storage

#5064 [ Bug fixed ] : [ Table ] some columns entries are missing in the downloaded file
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, frontend, javascript, run-ci, tested, table, react, active-review-app

#5080 Tooljet db query - Filter condition should resolved dynamic variables used in the editor
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
Labels: bug, active-review-app, internal-storage

#5087 [Bugfix] updated toast context
  frontend/src/_ui/Drawer/index.jsx
Labels: bug, active-review-app, internal-storage

#5077 [Hotfix]: Fixes Showing Toast Message on Query Success in Viewer
  frontend/src/_helpers/appUtils.js
Labels: bug, javascript, tested, editor, hotfix, active-review-app

#5086 [V2-Beta] Plugins connection caching fix
  server/src/services/app_environments.service.ts
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
Labels: run-ci

#5053 improvements to pagination
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Forms/FilterForm.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/Paginations.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
  frontend/src/_helpers/postgrestQueryBuilder.js
  frontend/src/_ui/Select/SelectComponent.jsx
Labels: enhancement, run-ci, active-review-app, internal-storage

#5073 fix: homepage design changes
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/Header.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/_components/OrganizationManager/CustomSelect.jsx
  frontend/src/_components/OrganizationManager/List.jsx
  frontend/src/_components/SearchBox.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Header/index.jsx
  frontend/src/_ui/Layout/index.jsx
  frontend/src/_ui/Select/styles.js
  server/src/controllers/apps.controller.ts
  server/src/services/apps.service.ts
  server/src/services/folders.service.ts
Labels: active-review-app

#5104 [Improvement] Populate default values for new rows
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
Labels: enhancement, active-review-app, internal-storage

#5105 [Multipage] removes search icon
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
Labels: multipages

#5102 [Improvement] tooljet query - delete operation
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_helpers/appUtils.js
Labels: enhancement, internal-storage

#5112 [ Feature request ] : Add a loader for run button in query panel
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: feature request, javascript, run-ci, ui, react

#5050 Bugfix :: onboarding v2 ui bugfixes in form
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/OnBoardingForm/AdminSetup.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/SuccessInfoScreen/SetupScreenSelfHost.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
  frontend/src/_helpers/constants.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/onboarding.scss
  frontend/src/_styles/theme.scss
Labels: enhancement, suspend-review-app

#5106 Merge develop to v2-beta
  .github/workflows/render-suspend-labeler.yml
  cypress-tests/cypress/support/utils/common.js
  docs/docs/how-to/bulk-update-multiple-rows-in-table.md
  docs/src/css/custom.css
  frontend/package-lock.json
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_helpers/appUtils.js
Labels: do not merge, on hold

#5038 [v2-beta] Improvement - Editor
  frontend/src/AppLoader/AppLoader.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/_components/SearchBox.jsx
  server/src/controllers/apps.controller.ts
Labels: run-ci, suspend-review-app

#5079 [v2 docs] superadmin
  docs/static/img/enterprise/superadmin/archive.png
  docs/static/img/enterprise/superadmin/archwork.png
  docs/static/img/enterprise/superadmin/instance.png
  docs/static/img/enterprise/superadmin/instancesettings.png
  docs/static/img/enterprise/superadmin/makesa.png
  docs/static/img/enterprise/superadmin/personal.png
  docs/static/img/enterprise/superadmin/workspacedrop.png
  docs/versioned_docs/version-2.0.0-beta/Enterprise/superadmin.md
  docs/versioned_sidebars/version-2.0.0-beta-sidebars.json
Labels: documentation

#5110 fix: scroll in debugger panel
  .github/workflows/render-preview-deploy.yml
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/Footer.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/TooljetDatabase/Sidebar/index.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/_components/Profile.jsx
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Pagination/index.jsx
Labels: active-review-app
