Repository ToolJet/ToolJet, pull requests merged in 2022-05, with the labels that each got.

#2940 [docs] added how to guide for bulk updating multiple rows
  docs/docs/how-to/bulk-update-multiple-rows-in-table.md
  docs/docs/how-to/oauth2-authorization.md
  docs/docs/how-to/upload-files-gcs.md
  docs/static/img/how-to/bulk-update-multiple/columns.png
  docs/static/img/how-to/bulk-update-multiple/event.png
  docs/static/img/how-to/bulk-update-multiple/options.png
  docs/static/img/how-to/bulk-update-multiple/postgres1.png
  docs/static/img/how-to/bulk-update-multiple/runjs1.png
  docs/static/img/how-to/bulk-update-multiple/showData.png
  docs/static/img/how-to/bulk-update-multiple/success.png
  docs/static/img/how-to/bulk-update-multiple/update.png
Labels: documentation

#2942 Fix error in create version modal
  frontend/src/Editor/AppVersionsManager.jsx
Labels: run-ci

#2790 [Feature] option to delete a data source 🚀
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/_services/datasource.service.js
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/theme.scss
  server/src/controllers/data_sources.controller.ts
  server/src/modules/casl/abilities/apps-ability.factory.ts
  server/src/services/data_sources.service.ts
  server/test/controllers/data_sources.e2e-spec.ts
Labels: run-ci, tested

#2950 exposed variable of timer is set to default value after reset
  frontend/src/Editor/Components/Timer.jsx
Labels: run-ci

#2963 [docs]updated Notion
  docs/docs/data-sources/notion.md
  docs/static/img/datasource-reference/notion/api.png
  docs/static/img/datasource-reference/notion/block_q.png
  docs/static/img/datasource-reference/notion/db_q.png
  docs/static/img/datasource-reference/notion/db_retrieve.png
  docs/static/img/datasource-reference/notion/page_q.png
  docs/static/img/datasource-reference/notion/querying.png
  docs/static/img/datasource-reference/notion/share.png
  docs/static/img/datasource-reference/notion/user_q.png
Labels: documentation

#2964 Fix invalid error message for user group
  server/src/services/group_permissions.service.ts
  server/test/controllers/group_permissions.e2e-spec.ts
  server/test/services/group_permissions.service.spec.ts
Labels: run-ci, testing

#2965 #2946 / Fix validation error when running docs locally
  docs/docusaurus.config.js
Labels: run-ci

#2961 fixed addition of application to folder more than once
  server/src/services/folder_apps.service.ts
  server/test/controllers/folder_apps.e2e-spec.ts
Labels: run-ci, tested

#2789 [Improvement/feature] New Inspector popup UI
  frontend/assets/images/icons/editor/left-sidebar/components.svg
  frontend/assets/images/icons/editor/left-sidebar/globals.svg
  frontend/assets/images/icons/editor/left-sidebar/pinnedoff.svg
  frontend/assets/images/icons/editor/left-sidebar/queries.svg
  frontend/assets/images/icons/editor/left-sidebar/variables.svg
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPinnedButton.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/_components/CopyToClipboard/CopyToClipboard.jsx
  frontend/src/_components/CopyToClipboard/index.js
  frontend/src/_styles/colors.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNodeArray.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNodeIndicator.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNodeObject.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNodeValue.jsx
  frontend/src/_ui/JSONTreeViewer/JSONTreeViewer.jsx
  frontend/src/_ui/JSONTreeViewer/index.js
  plugins/package-lock.json
Labels: run-ci, tested

#2967 Fix query order
  server/src/services/data_queries.service.ts
  server/test/controllers/data_queries.e2e-spec.ts
Labels: run-ci, tested

#2973 style: add undo redo actions
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Icons/desktop-selected.svg
  frontend/src/Editor/Icons/mobile-selected.svg
  frontend/src/Editor/WidgetManager.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2971 created VerticalDivider widget
  frontend/assets/images/icons/widgets/verticaldivider.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/Components/verticalDivider.jsx
Labels: run-ci

#2984 chore: add env to enable/disable multiplayer feature
  .env.example
  deploy/docker/.env.example
  docs/docs/setup/env-vars.md
  frontend/src/App/App.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/_helpers/__tests__/appUtils.test.js
  frontend/webpack.config.js
  server/src/app.module.ts
  server/src/events/events.module.ts
  server/src/main.ts
Labels: run-ci

#3001 hotfix: new added/deleted query doesn't update on query manager
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#2882 added loading state in Statistics Widget
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#3006 [docs] how to: upload and download files using aws s3
  docs/docs/how-to/bulk-update-multiple-rows-in-table.md
  docs/docs/how-to/upload-files-aws.md
  docs/sidebars.js
  docs/static/img/how-to/upload-files-aws/download.png
  docs/static/img/how-to/upload-files-aws/dropdown.png
  docs/static/img/how-to/upload-files-aws/getBuckets.png
  docs/static/img/how-to/upload-files-aws/listObjects.png
  docs/static/img/how-to/upload-files-aws/table.png
  docs/static/img/how-to/upload-files-aws/ui.png
  docs/static/img/how-to/upload-files-aws/uploadToS3.png
Labels: documentation

#2948 [Feature] Added textSize style to the text widget
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/components.js
  server/migrations/1651820577708-PopulateTextSize.ts
Labels: run-ci

#2908 [feature] Added maximum canvas height property
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarGlobalSettings.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci, tested

#3003 Netlify configs changes
  netlify.toml
Labels: bug, run-ci

#3010 style: add save text to header
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Avatar/index.jsx
  frontend/src/_ui/Spinner/index.js
Labels: run-ci

#3013 Made Timeline widget scrollable on shrinking the height or width of the widget
  frontend/src/Editor/Components/Timeline.jsx
Labels: run-ci

#2960 [Feature]: Custom Component Widget
  docs/docs/widgets/custom-component.md
  docs/static/img/widgets/custom-component/custom-component.png
  frontend/assets/images/icons/widgets/customcomponent.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
  frontend/src/Editor/Components/CustomComponent/iframe.html
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Components/CustomComponent.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/webpack.config.js
  server/src/main.ts
Labels: run-ci

#3026 [Bugfix] Googlesheets plugin returns undefined errors sometime
  plugins/packages/googlesheets/lib/index.ts
Labels: bug, run-ci, plugins

#2979 Ability to select multiple widgets from canvas and change their position
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/EditorKeyHooks.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_hooks/useKeyHooks.js
  plugins/package-lock.json
Labels: needs testing, run-ci

#3027 [inspector] followup to #2789
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNodeValue.jsx
  frontend/src/_ui/JSONTreeViewer/JSONTreeViewer.jsx
Labels: run-ci

#2992 Relabelling organization with workspace
  .env.example
  app.json
  docs/docs/password-login/password-login.md
  docs/docs/setup/env-vars.md
  docs/docs/sso/general-settings.md
  docs/docs/sso/github.md
  docs/docs/sso/google.md
  docs/docs/tutorial/adding-a-datasource.md
  docs/docs/tutorial/manage-users-groups.md
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/_components/Organization.jsx
  server/ee/services/oauth/oauth.service.ts
  server/migrations/1650485473528-PopulateSSOConfigs.ts
  server/src/controllers/organizations.controller.ts
  server/src/modules/auth/multi-organization.guard.ts
  server/src/services/app_config.service.ts
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/seeds.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/oauth.e2e-spec.ts
  server/test/controllers/organizations.e2e-spec.ts
  server/test/controllers/users.e2e-spec.ts
Labels: needs testing, run-ci, tested

#3035 [Feature]: PDF Widget
  docs/docs/widgets/pdf.md
  docs/sidebars.js
  frontend/assets/images/icons/widgets/pdf.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/PDF.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#3040 [Improvement] Suggestion hints
  frontend/src/Editor/CodeBuilder/utils.js
Labels: run-ci

#2828 [BUGFIX] 2740 - fix refreshing selected datasource component
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: tested

#2999 Avoid creation of system group names
  server/src/services/group_permissions.service.ts
  server/test/controllers/group_permissions.e2e-spec.ts
Labels: run-ci, tested

#3032 solved border radius & alignment issue after selecting file
  frontend/src/Editor/Components/FilePicker.jsx
Labels: run-ci

#3061 Fix: Always enable preview button
  frontend/src/Editor/Editor.jsx
Labels: run-ci, tested

#3072 [hotfix] Resolved canvas height issue
  frontend/src/Editor/Container.jsx
Labels: frontend, run-ci

#2866 [ Feature ]:: Woocommerce Integration 🚀
  docs/docs/data-sources/woocommerce.md
  docs/static/img/datasource-reference/woocommerce/woocomerce-auth.png
  frontend/package-lock.json
  plugins/create-operations-file.js
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/woocommerce/.gitignore
  plugins/packages/woocommerce/README.md
  plugins/packages/woocommerce/__tests__/index.js
  plugins/packages/woocommerce/lib/icon.svg
  plugins/packages/woocommerce/lib/index.ts
  plugins/packages/woocommerce/lib/manifest.json
  plugins/packages/woocommerce/lib/operation.ts
  plugins/packages/woocommerce/lib/operations/definitions.ts
  plugins/packages/woocommerce/lib/operations/index.ts
  plugins/packages/woocommerce/lib/operations/properties.ts
  plugins/packages/woocommerce/lib/types.ts
  plugins/packages/woocommerce/package-lock.json
  plugins/packages/woocommerce/package.json
  plugins/packages/woocommerce/tsconfig.json
  server/package-lock.json
Labels: run-ci, plugins, tested

#3078 Added custom headers for access token URL (REST API Oauth2)
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/OAuth/Authentication.jsx
  frontend/src/_ui/OAuth/index.js
  plugins/packages/restapi/lib/manifest.json
  server/src/services/data_queries.service.ts
Labels: backend, run-ci, plugins, tested

#3103 Add editor and viewer metrics to telemetry
  server/src/entities/user.entity.ts
  server/src/services/metadata.service.ts
Labels: run-ci

#3054 [BUG] Error while switching organization
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/_components/Organization.jsx
  server/ee/services/oauth/oauth.service.ts
Labels: run-ci

#3080 [Bug]: Updated cursor on hovering image widget
  frontend/src/Editor/Components/Image.jsx
Labels: run-ci

#3059 added default value in the toggle widget
  frontend/src/Editor/Components/Toggle.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2944 [Feature] Added an option to save edited queries to avoid losing values by state changes 🚀
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: enhancement, frontend, run-ci, tested

#3100 Added bulk update feature to SQL data source
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mssql/lib/operations.json
  plugins/packages/mssql/lib/types.ts
Labels: enhancement, run-ci, plugins

#3021 [Improvement] : Filepicker widget
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#3109 [docs] minor update: client side pagination
  docs/docs/widgets/table.md
Labels: documentation

#3089 [Feature] Update Manage user Archive and Unarchive button style
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
Labels: needs testing, run-ci

#3088 [Bugfix] Hide action options section if there are no options
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci

#3046 [Improvement] Filepicker widget : The file picker should reject files with existing file names.
  frontend/src/Editor/Components/FilePicker.jsx
Labels: run-ci

#3106 [Feature] Now users can edit created version's name 🚀
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/_services/appVersion.service.js
  server/src/controllers/apps.controller.ts
  server/src/services/apps.service.ts
Labels: enhancement, backend, run-ci, tested

#3126 Task: Add deployment platform for telemetry
  app.json
  deploy/docker/.env.example
  deploy/ec2/.env
  deploy/helm/templates/tooljet/deployment.yaml
  deploy/kubernetes/AKS/deployment.yaml
  deploy/kubernetes/GKE/deployment.yaml
  deploy/kubernetes/deployment.yaml
  frontend/src/App/App.jsx
  server/src/services/metadata.service.ts
Labels: run-ci

#3129 [BUG] Hide authorization header for Rest API
  plugins/packages/common/lib/index.ts
  plugins/packages/common/lib/utils.helper.ts
  plugins/packages/restapi/lib/index.ts
Labels: run-ci, plugins

#3133 [Bug] Fix for hiding sensitive data - REST API
  plugins/packages/common/lib/utils.helper.ts
Labels: run-ci, plugins

#3120 Update Manage user Archive and Unarchive button style
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
Labels: run-ci

#3140 fix: datasources/data-queries refresh when websocket is disconnected
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#3134 [docs] integrated algolia-docsearch
  docs/docusaurus.config.js
  docs/package.json
  docs/src/css/custom.css
  docs/static/index.html
  docs/yarn.lock
Labels: documentation, frontend

#3146 [docs] removed algolia's code block
  docs/static/index.html
Labels: documentation, frontend

#3145 [Docs]: Responsive video container for widgets and data source
  docs/docs/data-sources/google.sheets.md
  docs/docs/widgets/button.md
  docs/docs/widgets/table.md
Labels: bug, good first issue, up-for-grabs

#3087 [docs] :: multi workspace docs
  docs/docs/password-login/_category_.json
  docs/docs/tutorial/multiworkspace.md
  docs/docs/user-authentication/general-settings.md
  docs/docs/user-authentication/password-login.md
  docs/docs/user-authentication/sso/_category_.json
  docs/docs/user-authentication/sso/github.md
  docs/docs/user-authentication/sso/google.md
  docs/sidebars.js
  docs/static/img/multiworkspace/Tooljet-workspace.png
  docs/static/img/multiworkspace/multi-workspace.gif
Labels: documentation, run-ci

#3091 Feature :: SSO & multi workspace helper page
  frontend/src/App/App.jsx
  frontend/src/RedirectSso/RedirectSso.jsx
  frontend/src/RedirectSso/index.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#3173 [docs] updated docker formatting
  docs/docs/setup/docker.md
Labels: documentation
