Repository ToolJet/ToolJet, pull requests merged in 2022-07, with the labels that each got.

#3068 [Feature] Organisation level environment variables 🚀
  frontend/src/App/App.jsx
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/ManageOrgVars/VariableForm.jsx
  frontend/src/ManageOrgVars/VariablesTable.jsx
  frontend/src/ManageOrgVars/index.js
  frontend/src/_components/Organization.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_services/index.js
  frontend/src/_services/org_environment_variable.service.js
  frontend/src/_styles/theme.scss
  server/migrations/1652541462886-CreateOrgEnvironmentVariablesTable.ts
  server/migrations/1654150623035-AddOrgEnvironmentVariablesGroupPermissions.ts
  server/migrations/1654150855780-BackfillAddOrgEnvironmentVariablesGroupPermissions.ts
  server/src/app.module.ts
  server/src/controllers/org_environment_variables.controller.ts
  server/src/dto/environment-variable.dto.ts
  server/src/entities/group_permission.entity.ts
  server/src/entities/org_envirnoment_variable.entity.ts
  server/src/modules/casl/abilities/org-environment-variables-ability.factory.ts
  server/src/modules/casl/casl.module.ts
  server/src/modules/data_queries/data_queries.module.ts
  server/src/modules/data_sources/data_sources.module.ts
  server/src/modules/org_environment_variables/org_environment_variables.module.ts
  server/src/modules/organizations/organizations.module.ts
  server/src/services/data_queries.service.ts
  server/src/services/group_permissions.service.ts
  server/src/services/org_environment_variables.service.ts
  server/src/services/organizations.service.ts
  server/src/services/seeds.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/oauth.e2e-spec.ts
  server/test/controllers/org_environment_variables.e2e-spec.ts
  server/test/services/data_queries.service.spec.ts
  server/test/test.helper.ts
Labels: frontend, backend, needs testing, run-ci

#3448 [Feature]: Component Specific Actions
  frontend/src/Editor/ActionTypes.js
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Select/SelectComponent.jsx
  frontend/src/_ui/Select/styles.js
Labels: run-ci

#3464 added docs for color picker widget
  docs/docs/widgets/color-picker.md
  docs/sidebars.js
  docs/static/img/widgets/color-picker/colorpicker.png
  docs/static/img/widgets/color-picker/colorpickerdefaultvalue.png
  docs/static/img/widgets/color-picker/colorpickerinspector.png
  docs/static/img/widgets/color-picker/colorpickerpopup.png
Labels: run-ci

#3462 added docs for html widget
  docs/docs/widgets/html.md
  docs/sidebars.js
  docs/static/img/widgets/html/html-rawhtml.png
  docs/static/img/widgets/html/html.png
Labels: run-ci

#3460 Docs: adding docs for vertical separator widget
  docs/docs/widgets/vertical-divider.md
  docs/sidebars.js
  docs/static/img/widgets/vertical-divider/vertical-divider.png
Labels: run-ci

#3466 [Docs]: Datepicker widget video
  docs/docs/widgets/datepicker.md
Labels: documentation, good first issue, up-for-grabs, ui

#3456 Feature: Add support for http proxy
  docs/sidebars.js
  server/package-lock.json
  server/package.json
  server/src/main.ts
Labels: run-ci

#3170 Bugfix :: stripe refund post not working
  plugins/packages/stripe/lib/index.ts
  plugins/packages/stripe/package-lock.json
Labels: run-ci, tested

#3472 [docs] Google - OpenID Connect
  docs/docs/user-authentication/sso/openid/azuread.md
  docs/docs/user-authentication/sso/openid/google-openid.md
  docs/docs/user-authentication/sso/openid/okta.md
  docs/docs/user-authentication/sso/openid/setup.md
  docs/sidebars.js
  docs/static/img/sso/google-openid/authorized-redirect-urls.png
  docs/static/img/sso/google-openid/authorized-urls.png
  docs/static/img/sso/google-openid/create-oauth.png
  docs/static/img/sso/google-openid/create-project.png
  docs/static/img/sso/google-openid/oauth-type.png
  docs/static/img/sso/google-openid/openid.png
  docs/static/img/sso/google-openid/scope.png
Labels: documentation

#3508 [Docs]: Modal widget's video
  docs/docs/widgets/modal.md
Labels: documentation, good first issue, up-for-grabs, widget, ui

#3381 [Feature]: Re-Order Events
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/_hooks/useDraggableInPortal.js
Labels: frontend, run-ci

#3436 [ Feature ]:: runjs included all actions
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: run-ci

#3450 [Bugfix] Table Date Picker column should not display anything if the data is empty
  frontend/src/Editor/Components/Table/Datepicker.jsx
Labels: run-ci, create-review-app

#3407 [Improvement] Leftsidebar inspector
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  frontend/src/_ui/JSONTreeViewer/JSONTreeViewer.jsx
Labels: run-ci, tested

#3427 [Feature]: Added box-shadow property
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/BoxShadow.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/CodeBuilder/TypeMapping.js
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/WidgetManager/components.js
  frontend/src/Editor/component-properties-resolution.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#3558 [improvement] Improved suggestive hints for the app builder
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/_helpers/utils.js
Labels: needs testing, run-ci

#3491 Added clearFiles action to the file picker widget
  docs/docs/widgets/file-picker.md
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: frontend, run-ci

#3575 [HotFix] Mysql plugin not throwing error
  plugins/packages/mysql/lib/index.ts
Labels: run-ci, plugins

#3503 Added setLocation component action to the map widget
  docs/docs/widgets/map.md
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: frontend, run-ci

#3478 [Feature]: Timeline Component Property Validation
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3561 FilePicker : added props and styles validation
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3416 Copy button added for links in manage sso / general settings
  frontend/assets/images/icons/copy-dark.svg
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#3563 Text Editor: added props and styles validations
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3564 Dropdown : added props and style validations
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3548 Container Widget : added props and style validation
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3571 [Hotfix] Number widget: min and max value updates inside listview widget
  frontend/src/Editor/Components/NumberInput.jsx
Labels: run-ci

#3252 [Feature]: Copy/Paste widgets
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/EditorKeyHooks.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/_helpers/appUtils.js
Labels: frontend, needs testing, run-ci

#3530 [enhancement]JSON tree component : handles "Property accessors, for properties starting with numeric digit"
  frontend/src/_ui/JSONTreeViewer/JSONTreeViewer.jsx
Labels: enhancement, tested

#3480 Added component specific 'setColor' action to Color Picker
  docs/docs/widgets/color-picker.md
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3452 Added a feature for updating the group names
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_styles/theme.scss
  server/src/dto/group-permission.dto.ts
  server/src/services/group_permissions.service.ts
  server/test/controllers/group_permissions.e2e-spec.ts
Labels: frontend, backend, run-ci, tested

#3484 feat: add notification center
  frontend/src/Editor/Comment/CommentBody.jsx
  frontend/src/Editor/CommentNotifications/Content.jsx
  frontend/src/_components/Header.jsx
  frontend/src/_components/NotificationCenter/Notification.jsx
  frontend/src/_components/NotificationCenter/index.jsx
  frontend/src/_helpers/http-client.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/commentNotifications.service.js
  frontend/src/_services/index.js
  frontend/src/_styles/theme.scss
  server/migrations/1656312830147-CreateCommentUsers.ts
  server/src/app.module.ts
  server/src/controllers/comment.controller.ts
  server/src/controllers/comment_users.controller.ts
  server/src/dto/comment-user.dto.ts
  server/src/entities/comment_user.entity.ts
  server/src/modules/comment_users/comment_users.module.ts
  server/src/modules/comments/comment.module.ts
  server/src/services/comment.service.ts
  server/src/services/comment_users.service.ts
Labels: run-ci

#3545 #2567 - Feature/add database instance option to mssql
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mssql/lib/manifest.json
  plugins/packages/mssql/lib/types.ts
Labels: run-ci, plugins, create-review-app

#3560 Text Input : added props and style validation
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3565 Chart : added props and styles validations
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3489 added component specific action - setText and clear
  docs/docs/widgets/textarea.md
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3512 Added component specific actions of radio button widget
  docs/docs/widgets/radio-button.md
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3606 [docs]: Updated Tabs video
  docs/docs/widgets/tabs.md
Labels: documentation, enhancement, good first issue, up-for-grabs, widget, ui

#3607 [docs]: Updated List view video
  docs/docs/widgets/listview.md
Labels: documentation, enhancement, good first issue, up-for-grabs, widget, ui

#3485 fix: show version create popup when deleting a widget on released version
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#3375 Added confirm input in profile settings
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, create-review-app

#3538 Text Widget : prop and style validation
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3507 [Component specific action] Added setTab component action to Tabs widget
  docs/docs/widgets/tabs.md
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci

#3104 Add validation for input fields on the profile settings page
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci, tested

#3487 added component-specific action to set and clear value
  docs/docs/widgets/text-input.md
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3441 Instance level SSO for Multi-Workpsace
  .env.example
  docs/docs/setup/env-vars.md
  docs/docs/user-authentication/user-lifecycle.md
  docs/static/img/user-lifecycle/sso-flow.png
  docs/static/img/user-lifecycle/switch.png
  frontend/ee/components/LoginPage/GitSSOLoginButton.jsx
  frontend/ee/components/LoginPage/GoogleSSOLoginButton.jsx
  frontend/src/App/App.jsx
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/ManageSSO/Form.jsx
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/Oauth/Authorize.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/_components/LoginLoader.jsx
  frontend/src/_components/Organization.jsx
  frontend/src/_components/index.js
  frontend/src/_helpers/cookie.js
  frontend/src/_helpers/handle-response.js
  frontend/src/_helpers/index.js
  frontend/src/_services/authentication.service.js
  frontend/src/_services/organization.service.js
  frontend/src/_styles/theme.scss
  server/ee/controllers/oauth.controller.ts
  server/ee/services/oauth/oauth.service.ts
  server/migrations/1656268228782-OrganizationsInheritSSO.ts
  server/src/controllers/app.controller.ts
  server/src/controllers/organizations.controller.ts
  server/src/entities/organization.entity.ts
  server/src/entities/user.entity.ts
  server/src/modules/auth/jwt.strategy.ts
  server/src/modules/auth/multi-organization.guard.ts
  server/src/services/app_config.service.ts
  server/src/services/auth.service.ts
  server/src/services/organization_users.service.ts
  server/src/services/organizations.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/oauth.e2e-spec.ts
  server/test/controllers/oauth/oauth-git-instance.e2e-spec.ts
  server/test/controllers/oauth/oauth-git.e2e-spec.ts
  server/test/controllers/oauth/oauth-google-instance.e2e-spec.ts
  server/test/controllers/oauth/oauth-google.e2e-spec.ts
  server/test/controllers/organizations.e2e-spec.ts
Labels: run-ci

#3496 added component specific action to Dropdown Widget
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3523 [ Feature ] :: component specific action :: multiselect widget
  docs/docs/widgets/multiselect.md
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#2782 Feature/component property validation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/DaterangePicker.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/components.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/Editor/component-properties-validation.js
  frontend/src/_helpers/appUtils.js
Labels: run-ci

#3633 [Bugfix] Hide node indicator for Date types
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
Labels: bug, tested

#3443 feat: trigger mail when user is mentioned in comment
  frontend/src/Editor/Comment/CommentBody.jsx
  frontend/src/Editor/Comment/CommentFooter.jsx
  frontend/src/Editor/Comment/index.jsx
  frontend/src/Editor/CommentNotifications/Content.jsx
  frontend/src/Editor/Comments.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/_components/Header.jsx
  frontend/src/_components/NotificationCenter/Notification.jsx
  frontend/src/_components/NotificationCenter/index.jsx
  frontend/src/_helpers/http-client.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/commentNotifications.service.js
  frontend/src/_services/index.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Mentions/index.js
  server/migrations/1656312830147-CreateCommentUsers.ts
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/assets/email-templates/comment-mention.html
  server/src/controllers/comment.controller.ts
  server/src/controllers/comment_users.controller.ts
  server/src/dto/comment-user.dto.ts
  server/src/dto/comment.dto.ts
  server/src/dto/invite-new-user.dto.ts
  server/src/entities/comment.entity.ts
  server/src/entities/comment_user.entity.ts
  server/src/modules/comment_users/comment_users.module.ts
  server/src/modules/comments/comment.module.ts
  server/src/services/comment.service.ts
  server/src/services/comment_users.service.ts
  server/src/services/email.service.ts
  server/src/services/organizations.service.ts
  server/test/controllers/organizations.e2e-spec.ts
Labels: run-ci

#3589 Added hide logic to widget properties accordion menu item when it contains no items
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
Labels: run-ci

#3639 Updated the hide tab content in widgets folder
  docs/docs/widgets/tabs.md
Labels: documentation

#3635 [hotfix] Public apps are redirecting to login page while using environment variables inside an app
  frontend/src/Editor/Viewer.jsx
  frontend/src/_services/org_environment_variable.service.js
  server/src/controllers/org_environment_variables.controller.ts
  server/src/decorators/app.decorator.ts
  server/src/modules/org_environment_variables/is-public.guard.ts
  server/src/modules/org_environment_variables/org_environment_variables.module.ts
  server/src/modules/organizations/organizations.module.ts
  server/src/services/org_environment_variables.service.ts
Labels: run-ci

#3649 Add badge icon on comment left sidebar item
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarItem.jsx
  frontend/src/_styles/left-sidebar.scss
Labels: run-ci

#3631 [docs]: Text-input video
  docs/docs/widgets/text-input.md
Labels: documentation, enhancement, good first issue, widget

#3650 [docs]: Number input video
  docs/docs/widgets/number-input.md
Labels: documentation, enhancement, good first issue, widget

#3676 [docs]: Youtube link correction
  docs/docs/widgets/listview.md
Labels: bug, documentation, good first issue

#3689 Update text-input.md
  docs/docs/widgets/text-input.md
Labels: documentation, good first issue, up-for-grabs

#3674 Bug Fixed : Folder icon is now clearly visible in darkmode/issue_3647
  frontend/assets/images/icons/folder.svg
  frontend/src/HomePage/Folders.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#3682 [bug-fix] The editor didn't show the currently selected version after the browser refreshed 🐞
  frontend/src/Editor/Editor.jsx
Labels: frontend, run-ci

#3685 [Bugfix]: Tabs widget - Not able to navigate to all the tabs for reduced widget widths
  frontend/src/Editor/Components/Tabs.jsx
Labels: tested

#3352 SSO for GitHub Enterprise self hosted
  .env.example
  deploy/docker/.env.example
  docs/docs/setup/env-vars.md
  docs/docs/user-authentication/sso/github.md
  docs/docs/user-authentication/sso/google.md
  docs/static/img/sso/git/manage-sso-1.png
  docs/static/img/sso/git/manage-sso-2.png
  frontend/ee/components/LoginPage/GitSSOLoginButton.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/ManageSSO/Git.jsx
  server/ee/services/oauth/git_oauth.service.ts
  server/ee/services/oauth/oauth.service.ts
  server/src/entities/sso_config.entity.ts
  server/src/services/app_config.service.ts
  server/src/services/organizations.service.ts
  server/test/controllers/oauth/oauth-git-instance.e2e-spec.ts
  server/test/controllers/oauth/oauth-git.e2e-spec.ts
Labels: backend, run-ci, tested

#3662 Bug Fix : converted ms into second by multiplying it with 1000 for success notification
  frontend/src/_helpers/appUtils.js
Labels: run-ci

#3683 [docs]added missing woocommerce in sidebar
  docs/docs/data-sources/woocommerce.md
  docs/sidebars.js
Labels: documentation
