Repository ToolJet/ToolJet, pull requests merged in 2022-08, with the labels that each got.

#3695 [docs] updated `graphql` data source docs
  docs/docs/data-sources/graphql.md
  docs/static/img/datasource-reference/graphql/add-source.gif
  docs/static/img/datasource-reference/graphql/graphql-ds.png
  docs/static/img/datasource-reference/graphql/graphql-query.png
Labels: documentation

#3604 Bug Fix : Image going out of widget container for border type as thumbnail
  frontend/src/Editor/Components/Image.jsx
Labels: run-ci, tested

#3665 [Feature]: Area Selection on Drag
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_styles/theme.scss
Labels: needs testing, run-ci

#3668 Bug Fix :Date Picker event not firing the correct parameters.
  frontend/src/Editor/Components/Datepicker.jsx
Labels: run-ci

#3717 [docs]:Replaced correct video link and title
  docs/docs/widgets/datepicker.md
  docs/docs/widgets/modal.md
Labels: documentation, good first issue, widget

#3722 Hide user details in home and groups page
  server/src/controllers/apps.controller.ts
  server/src/services/apps.service.ts
  server/src/services/folders.service.ts
  server/src/services/group_permissions.service.ts
  server/test/controllers/group_permissions.e2e-spec.ts
Labels: run-ci

#3721 [docs]: Fixed multiple text errors
  docs/docs/widgets/listview.md
Labels: bug, documentation, good first issue, widget

#3719 [docs]: Updated checkbox YT video
  docs/docs/widgets/checkbox.md
Labels: documentation, enhancement, good first issue, widget

#3718 [docs]: Updated password YT video
  docs/docs/widgets/password-input.md
Labels: documentation, enhancement, good first issue, widget

#3659 Place text 'unsaved changes' instead of loader for whole saving process in editor.
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#3641 Bug Fixed : request confirmation before running keeps showing loader, when click cancel
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci, tested

#3730 fix: lint fixes in chart jsx
  frontend/src/Editor/Inspector/Components/Chart.jsx
Labels: run-ci

#3673 [[ Enhancement ]]: FilePicker - added onFileLoaded and onFileDeselected events
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
Labels: run-ci

#3373 [Feature]: CodeHinter preview for listItem, cellValue
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Context/EditorContextWrapper.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/Utils.js
Labels: frontend, run-ci

#3533 [Feature]: Tree Select Widget
  docs/docs/widgets/treeselect.md
  docs/sidebars.js
  docs/static/img/widgets/tree-select/events.png
  docs/static/img/widgets/tree-select/layout.png
  docs/static/img/widgets/tree-select/styles.png
  docs/static/img/widgets/tree-select/tree-select.gif
  frontend/assets/images/icons/widgets/treeselect.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci, tested

#3737 [docs]: Updated Tooltip Info for all widgets
  docs/docs/tutorial/organization-environment-variables.md
  docs/docs/widgets/button-group.md
  docs/docs/widgets/button.md
  docs/docs/widgets/calendar.md
  docs/docs/widgets/chart.md
  docs/docs/widgets/checkbox.md
  docs/docs/widgets/circular-progress-bar.md
  docs/docs/widgets/container.md
  docs/docs/widgets/date-range-picker.md
  docs/docs/widgets/datepicker.md
  docs/docs/widgets/dropdown.md
  docs/docs/widgets/file-picker.md
  docs/docs/widgets/image.md
  docs/docs/widgets/listview.md
  docs/docs/widgets/modal.md
  docs/docs/widgets/multiselect.md
  docs/docs/widgets/number-input.md
  docs/docs/widgets/password-input.md
  docs/docs/widgets/radio-button.md
  docs/docs/widgets/star.md
  docs/docs/widgets/tags.md
  docs/docs/widgets/text-input.md
  docs/docs/widgets/text.md
  docs/docs/widgets/textarea.md
  docs/static/img/tooltip.png
Labels: documentation, enhancement, good first issue, up-for-grabs, widget

#3749 [chore] ESLint fixes
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/Elements/BoxShadow.jsx
  frontend/src/Editor/CodeBuilder/Elements/Toggle.jsx
  frontend/src/Editor/Components/ButtonGroup.jsx
  frontend/src/Editor/Components/KanbanBoard/CardPopover.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/DataSourceManager/SourceComponents/index.js
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/QueryManager/DataSourceLister.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/RedirectSso/RedirectSso.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_ui/Select/SelectComponent.jsx
  frontend/src/_ui/card/Card.jsx
  server/.eslintrc.js
Labels: run-ci

#3765 [docs] updated bg-color property in tabs
  docs/docs/tutorial/keyboard-shortcuts.md
  docs/docs/widgets/tabs.md
  docs/static/img/widgets/tabs/tabsbg.png
Labels: documentation

#3766 Bug fixed : If Google & GitHub signup is disabled there shouldn’t be the ------OR-------
  frontend/src/SignupPage/SignupPage.jsx
Labels: run-ci

#3663 [Bugfix] fixes component state updates: radio button as listview child
  frontend/src/Editor/Components/RadioButton.jsx
Labels: tested

#3715 Refactor: Container and SubContainer Drag and Drop Layer
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/CustomDragLayer.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/SubCustomDragLayer.jsx
  frontend/src/Editor/snapToGrid.js
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested

#3739 Bug Fixed : Image is not visible after setting visibility to false and refreshing the page
  frontend/src/Editor/Components/Image.jsx
Labels: run-ci

#3758 [Bug]: Widget name updation
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: run-ci, tested

#3771 [docs]: Update toggle switch video
  docs/docs/widgets/toggle-switch.md
Labels: documentation, enhancement, good first issue, widget

#3618 Added check to see if workspace name exists, and blocks duplicates
  frontend/src/_components/Organization.jsx
Labels: do not merge, run-ci, tested, create-review-app

#3687 Enhancement : added pdf downloading feature
  frontend/src/Editor/Components/PDF.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#3761 Bug Fixed : Parent component overlaps the Dropdown component
  frontend/src/_ui/Select/SelectComponent.jsx
Labels: run-ci

#3716 [improvement] Listview widget - Adds default children when dropped for the first time
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_hooks/use-mount.jsx
Labels: run-ci, tested

#3757 [Bugfix] Syntax Errors in Query Transformation and adds them to the Debugger
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested

#3713 Updated the table UI
  frontend/assets/images/icons/search.svg
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci

#3778 [Bug]: Fix to display table widget on the viewer
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci

#3793 Security issue fix
  server/src/controllers/organization_users.controller.ts
Labels: run-ci

#3769 [docs]: Updated Tooltip info
  docs/docs/widgets/code-editor.md
  docs/docs/widgets/custom-component.md
  docs/docs/widgets/divider.md
  docs/docs/widgets/html.md
  docs/docs/widgets/iframe.md
  docs/docs/widgets/image.md
  docs/docs/widgets/kanban.md
  docs/docs/widgets/map.md
  docs/docs/widgets/pdf.md
  docs/docs/widgets/qr-scanner.md
  docs/docs/widgets/range-slider.md
  docs/docs/widgets/rich-text-editor.md
  docs/docs/widgets/spinner.md
  docs/docs/widgets/statistics.md
  docs/docs/widgets/steps.md
  docs/docs/widgets/timeline.md
  docs/docs/widgets/timer.md
  docs/docs/widgets/toggle-switch.md
  docs/docs/widgets/vertical-divider.md
Labels: bug, documentation, good first issue, widget

#3790 Bug Fixed : Tabs background is not consistent in the dark theme
  frontend/src/Editor/Components/Tabs.jsx
Labels: run-ci

#3785 perf: optimize webpack bundle output
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
  server/package-lock.json
  server/package.json
  server/src/main.ts
Labels: run-ci

#3782 [Improvement] Adds actions to suggestive hints for RunJS
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/QueryManager/QueryEditors/Runjs.jsx
Labels: needs testing, run-ci

#3768 [Bugfix] If the query is successfully run, success toast should be fired despite its triggered by any source.
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested

#3382 fix: Update logic for queries filter
  frontend/src/Editor/Editor.jsx
Labels: run-ci, create-review-app

#3804 [docs]: Radio button video
  docs/docs/widgets/radio-button.md
Labels: documentation, enhancement, good first issue, widget

#3806 [Bugfix] Hides app creator and creation time for viewers
  frontend/src/HomePage/AppCard.jsx
Labels: needs testing, run-ci

#3392 Enhancement : added all the css prop for the text in the styles section of the Text Widget
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  server/migrations/1656924847186-addingCssPropsToTextWidget.ts
Labels: run-ci

#3759 [docs] added missing actions in action reference
  docs/docs/actions/close-modal.md
  docs/docs/actions/control-component.md
  docs/docs/actions/copy-to-clipboard.md
  docs/docs/actions/go-to-app.md
  docs/docs/actions/logout.md
  docs/docs/actions/open-webpage.md
  docs/docs/actions/run-query.md
  docs/docs/actions/set-localstorage.md
  docs/docs/actions/set-table-page.md
  docs/docs/actions/set-variable.md
  docs/docs/actions/show-alert.md
  docs/docs/actions/show-modal.md
  docs/docs/actions/unset-variable.md
  docs/docs/tutorial/workspace-environment-variables.md
  docs/sidebars.js
  docs/static/img/actions/closemodal/closemodal.png
  docs/static/img/actions/controlcomponent/button.png
  docs/static/img/actions/controlcomponent/clear.png
  docs/static/img/actions/controlcomponent/inspector.png
  docs/static/img/actions/controlcomponent/jsoption.png
  docs/static/img/actions/controlcomponent/set.png
  docs/static/img/actions/controlcomponent/updated.png
  docs/static/img/actions/copytoclipboard/copytoclipboard.png
  docs/static/img/actions/gotoapp/gotoapp.png
  docs/static/img/actions/localstorage/1.png
  docs/static/img/actions/localstorage/2.png
  docs/static/img/actions/localstorage/3.png
  docs/static/img/actions/localstorage/5.png
  docs/static/img/actions/localstorage/6.png
  docs/static/img/actions/localstorage/sample-app-1.png
  docs/static/img/actions/localstorage/sample-app-2.png
  docs/static/img/actions/localstorage/sample-app-3.png
  docs/static/img/actions/localstorage/sample-app-4.png
  docs/static/img/actions/localstorage/sample-app-5.png
  docs/static/img/actions/logout/logout.png
  docs/static/img/actions/open-webpage/open.png
  docs/static/img/actions/run-query/run-query.png
  docs/static/img/actions/settablepage/settablepage.png
  docs/static/img/actions/setvar/setvar.png
  docs/static/img/actions/show-alert/show-alert.png
  docs/static/img/actions/showmodal/showmodal.png
  docs/static/img/actions/unsetvar/unsetvar.png
Labels: documentation

#3814 [Bug]: Added TypeScript definitions for compression
  server/package-lock.json
  server/package.json
Labels: run-ci

#3809 Wrap DB queries inside manager to enable rollback
  server/ee/services/oauth/oauth.service.ts
  server/src/controllers/group_permissions.controller.ts
  server/src/helpers/utils.helper.ts
  server/src/services/app_users.service.ts
  server/src/services/auth.service.ts
  server/src/services/group_permissions.service.ts
  server/src/services/organization_users.service.ts
  server/src/services/organizations.service.ts
  server/src/services/users.service.ts
  server/test/services/group_permissions.service.spec.ts
Labels: run-ci

#3798 fix: heroku deployment
  frontend/package-lock.json
  frontend/package.json
  package.json
Labels: run-ci

#3786 [Feature]: Default Children for Tab Widget
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
Labels: run-ci

#3820 [Security] Hide response of group permission create API
  server/src/controllers/group_permissions.controller.ts
  server/src/services/group_permissions.service.ts
  server/test/controllers/group_permissions.e2e-spec.ts
Labels: run-ci

#3826 [Hot Fix] GitHub API end point correction
  server/ee/services/oauth/git_oauth.service.ts
Labels: run-ci

#3823 [Feature]: Added Rotate Button in an Image Widget
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: enhancement, run-ci, widget, ui, hotfix

#3830 fixed datamanager search input autofocus on load issue
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci

#3483 update the Text widget docs
  docs/docs/widgets/text.md
Labels: run-ci

#3622 [Bug fix] : FIlePicker - if Parse content is disabled, the "File type" dropdown should be hidden
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Inspector/Components/FilePicker.jsx
Labels: run-ci, tested

#3842 [improvement] handle xlsx parsing for filepicker
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: enhancement, run-ci, widget

#3838 [bug-fix] Resolved header Flash issue
  frontend/src/Editor/Viewer.jsx
Labels: bug, frontend, run-ci

#3858 [docs] Update intro page & upgraded docusauras version
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: documentation, enhancement

#3840 [Enhancement]: Reset Image Rotation & Zoom when the URL is updated
  frontend/src/Editor/Components/Image.jsx
Labels: enhancement, run-ci, widget, hotfix

#3773 [Feature]: Cut & Paste Widgets
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/EditorKeyHooks.jsx
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, editor

#3794 [Refactor/Improvement] Debugger
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  frontend/src/_ui/JSONTreeViewer/JSONTreeViewer.jsx
Labels: run-ci, tested, refactor

#3796 [Bug]: Fixed PDF Unstable Issue
  frontend/src/Editor/Components/PDF.jsx
Labels: run-ci, widget, tested

#3812 [Bug]: Fixed Page Crash while Inspecting the widget with CSA
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci

#3821 [Feature]: Close Button for Toast Message
  frontend/src/App/App.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Toast/index.js
Labels: frontend, run-ci, ui

#3833 [Bug]: Fixed Textarea Initialisation
  frontend/src/Editor/Components/TextArea.jsx
Labels: bug, run-ci, widget

#3862 Bug fixed : [MutliSelect widget] Label text not clearly visible in dark mode
  frontend/src/Editor/Components/Multiselect.jsx
Labels: frontend, run-ci, widget

#3836 fix: hide user data from comments module
  server/src/entities/comment.entity.ts
  server/src/services/comment.service.ts
Labels: run-ci

#3861 Bug Fixed : Success message not displayed clearly in dark mode in advanced option for queries
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: frontend, run-ci

#3872 [Bugfix] For **Run the query on page load** and **Request confirmation before running the query.**, toasts are displayed in the preview apps.
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
Labels: bug, frontend, needs testing, run-ci

#3875 Changed text color for creator name and time in the application card in the the homepage
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci

#3825 [Fixed] Bug: User can reset their password with a space
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  server/src/dto/app-authentication.dto.ts
Labels: bug, run-ci

#3851 [docs]: Dropdown widget video
  docs/docs/widgets/dropdown.md
Labels: documentation, enhancement, good first issue, widget

#3850 [docs]: Date Range Picker widget video
  docs/docs/widgets/date-range-picker.md
Labels: documentation, enhancement, good first issue, widget

#3879 Bug fixed : Date range picker input element is not visible in the dark theme
  frontend/src/Editor/Components/DaterangePicker.jsx
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci

#3897 Hotfix: subpath link formation
  frontend/src/_helpers/http-client.js
  frontend/webpack.config.js
  server/src/app.module.ts
Labels: run-ci

#3849 Updated Minio icon svg
  docs/static/img/datasource-reference/minio-connect.png
  plugins/packages/minio/lib/icon.svg
Labels: run-ci, datasource, plugins

#3895 Bug fixed : grey border at the bottom of the dashboard
  frontend/src/_styles/theme.scss
Labels: bug, frontend, run-ci, ui

#3882 refactor: babel-parser
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
Labels: run-ci

#3414 [enhancement] Handle internal database exceptions in a better way
  server/src/all-exceptions-filter.ts
Labels: backend, run-ci

#3886 [Hotfix] Not able to select date with Datepicker widget
  frontend/src/Editor/Components/Datepicker.jsx
Labels: bug, needs testing, run-ci, hotfix

#3874 [docs] white label doc (EE feature)
  docs/docs/Enterprise/white-label.md
  docs/sidebars.js
  docs/static/img/enterprise/white-label/appeditor.png
  docs/static/img/enterprise/white-label/applogo.png
  docs/static/img/enterprise/white-label/favicon.png
Labels: documentation
