Repository ToolJet/ToolJet, pull requests merged in 2022-03, with the labels that each got.

#2367 Fix: App version export order
  server/src/services/app_import_export.service.ts
Labels: run-ci, tested

#2368 Fix: App version preview
  frontend/src/Editor/Editor.jsx
Labels: run-ci, tested

#2371 Feature: Make editing version as last updated version
  server/src/entities/app.entity.ts
Labels: run-ci, tested

#2379 [docs] updated heroku 1 click deploy
  docs/docs/deployment/heroku.md
  docs/static/img/deployment/heroku/appname.png
  docs/static/img/deployment/heroku/build.png
  docs/static/img/deployment/heroku/deployapp.png
  docs/static/img/deployment/heroku/login.png
Labels: documentation

#2338 Fix: Client entrypoint
  frontend/src/_helpers/history.js
  frontend/webpack.config.js
Labels: run-ci

#2391 [docs] embedded video: Self Host ToolJet on Heroku
  docs/docs/deployment/heroku.md
Labels: documentation

#2413 Fix: Token present in referrer header
  frontend/src/App/App.jsx
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/ConfirmationPage/index.js
  frontend/src/InvitationPage/index.js
Labels: run-ci, tested

#2423 [docs] updated checkbox
  docs/docs/widgets/checkbox.md
  docs/static/img/widgets/checkbox/checkbox.gif
  docs/static/img/widgets/checkbox/events.png
  docs/static/img/widgets/checkbox/layout.png
  docs/static/img/widgets/checkbox/styles.png
Labels: documentation

#2425 Fix: Spec failure
  server/src/controllers/apps.controller.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci

#2417 test: add pagination tests
  frontend/package.json
  frontend/src/_components/Pagination.jsx
  frontend/src/_components/__tests__/Pagination.test.js
Labels: run-ci

#2408 [Bugfix] Adding extra whitespace at the end or beginning of any field for object type resolves as a string
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: run-ci

#2406 Feature/2372 - add text alignment option to dropdown
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2436 Fix QR scanner firing event without QR
  frontend/src/Editor/Components/QrScanner/QrScanner.jsx
Labels: run-ci

#1919 Feature/range slider widget
  frontend/assets/images/icons/widgets/rangeslider.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/RangeSlider.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/DraggableBox.jsx
Labels: run-ci

#2426 Improvement: Added responseHeaders to restapi's exposed data
  frontend/src/_helpers/appUtils.js
  plugins/packages/restapi/lib/index.ts
Labels: run-ci

#2434 Json preview of query pane is slowing down the app
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: tested

#2390 Bugfix :: UI for comments section in editor updated as per design
  frontend/src/Editor/Comments.jsx
  frontend/src/_ui/Mentions/index.js
Labels: frontend, run-ci

#2460 add option to hide secondary value
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2461 remove the password from the apps request
  server/src/controllers/apps.controller.ts
Labels: run-ci

#2463 [Hotfix] SQL Server data-source doesn't connect to the azure based SQL servers
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mssql/lib/manifest.json
  plugins/packages/mssql/lib/types.ts
Labels: run-ci

#2465 Bugfix :: Making app "create new version" dropdown into a scrollable container
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2473 [docs] added Slack Code of Conduct(etiquettes)
  docs/docs/contributing-guide/code-of-conduct.md
  docs/docs/contributing-guide/slackcoc.md
  docs/docs/contributing-guide/tutorials/creating-a-plugin.md
Labels: documentation

#2475 Hotfix: Make use of entityManager within migration backfill
  server/migrations/1641446596775-SetImageBorderTypeToNone.ts
  server/migrations/1644229722021-SetFxActiveToTrueForFxFieldsConvertedToUI.ts
Labels: run-ci

#2476 [Hotfix] resolves widget width inside modal(resize issue)
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#2492 Feature: Version deletion
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/_services/appVersion.service.js
  server/src/controllers/apps.controller.ts
  server/src/modules/casl/abilities/apps-ability.factory.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci

#2392 Feature/2268 - create a data source plugin for mailgun
  .gitignore
  .tool-versions
  .vscode/launch.json
  docs/docs/data-sources/mailgun.md
  docs/docs/data-sources/minio.md
  docs/docs/data-sources/mongodb.md
  docs/docs/data-sources/mssql.md
  docs/docs/data-sources/mysql.md
  docs/docs/data-sources/n8n.md
  docs/docs/data-sources/postgresql.md
  docs/docs/data-sources/redis.md
  docs/docs/data-sources/restapi.md
  docs/docs/data-sources/s3.md
  docs/docs/data-sources/sendgrid.md
  docs/docs/data-sources/smtp.md
  docs/docs/data-sources/snowflake.md
  docs/docs/data-sources/typesense.md
  docs/static/img/datasource-reference/mailgun/mailgun-datasource.png
  frontend/package-lock.json
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/mailgun/.gitignore
  plugins/packages/mailgun/README.md
  plugins/packages/mailgun/__tests_/index.js
  plugins/packages/mailgun/lib/icon.svg
  plugins/packages/mailgun/lib/index.ts
  plugins/packages/mailgun/lib/manifest.json
  plugins/packages/mailgun/lib/operations.json
  plugins/packages/mailgun/lib/types.ts
  plugins/packages/mailgun/package-lock.json
  plugins/packages/mailgun/package.json
  plugins/packages/mailgun/tsconfig.json
Labels: run-ci

#2487 enhancement/bug: show loading state while submitting password reset form
  frontend/src/ResetPassword/ResetPasswordPage.jsx
Labels: run-ci

#2502 [Chore] plugins: fixes lint warning and errors
  plugins/packages/airtable/__tests__/airtable.test.js
  plugins/packages/bigquery/__tests__/index.js
  plugins/packages/common/__tests__/utils.test.js
  plugins/packages/couchdb/__tests_/index.js
  plugins/packages/couchdb/lib/index.ts
  plugins/packages/couchdb/lib/types.ts
  plugins/packages/couchdb/package-lock.json
  plugins/packages/dynamodb/__tests__/dynamodb.test.js
  plugins/packages/elasticsearch/__tests__/elasticsearch.test.js
  plugins/packages/firestore/__tests__/firestore.test.js
  plugins/packages/gcs/__tests__/gcs.test.js
  plugins/packages/googlesheets/__tests__/googlesheets.test.js
  plugins/packages/graphql/__tests__/graphql.test.js
  plugins/packages/mailgun/__tests_/index.js
  plugins/packages/mailgun/lib/index.ts
  plugins/packages/minio/__tests__/minioapi.test.js
  plugins/packages/mongodb/__tests__/mongodb.test.js
  plugins/packages/mssql/__tests__/mssql.test.js
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mysql/__tests__/mysql.test.js
  plugins/packages/n8n/__tests__/index.js
  plugins/packages/postgresql/__tests__/postgresql.test.js
  plugins/packages/redis/__tests__/redis.test.js
  plugins/packages/restapi/__tests__/restapi.test.js
  plugins/packages/s3/__tests__/s3.test.js
  plugins/packages/sendgrid/__tests__/sendgrid.test.js
  plugins/packages/slack/__tests__/slack.test.js
  plugins/packages/smtp/__tests__/index.js
  plugins/packages/snowflake/__tests__/index.js
  plugins/packages/stripe/__tests__/stripe.test.js
  plugins/packages/twilio/__tests__/twilioapi.test.js
  plugins/packages/typesense/__tests__/typesenseapi.test.js
Labels: run-ci

#2388 Feature/oracledb plugin
  Aptfile
  app.json
  deploy/ec2/setup_machine.sh
  docker/production.Dockerfile
  docker/server.Dockerfile
  docker/server.Dockerfile.dev
  docs/docs/data-sources/oracledb.md
  frontend/package-lock.json
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/oracledb/.gitignore
  plugins/packages/oracledb/README.md
  plugins/packages/oracledb/__tests_/index.js
  plugins/packages/oracledb/lib/icon.svg
  plugins/packages/oracledb/lib/index.ts
  plugins/packages/oracledb/lib/manifest.json
  plugins/packages/oracledb/lib/operations.json
  plugins/packages/oracledb/lib/types.ts
  plugins/packages/oracledb/package-lock.json
  plugins/packages/oracledb/package.json
  plugins/packages/oracledb/tsconfig.json
  server/package-lock.json
Labels: run-ci, tested

#2505 Hide query panel tabs if a data source is not selected.
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#2504 improvement: now widget search result will be show as one list
  frontend/src/Editor/WidgetManager.jsx
Labels: run-ci

#2386 hotfix: Edited changes not shown when switching versions
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Editor.jsx
Labels: run-ci, tested

#2510 Fix: Version creation on empty/invalid version from id
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Editor.jsx
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci

#2485 Split app export query to simpler faster ones
  server/src/services/app_import_export.service.ts
Labels: run-ci

#2499 Bugfix: Resolved azure outlook oauth issue
  server/src/services/data_queries.service.ts
Labels: run-ci

#2519 [Bugfix] Fixes : widgets get focused on viewer mode when hovered
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2522 chore: remove cypress from plugins [eslint]
  plugins/.eslintrc.js
  plugins/package-lock.json
  plugins/package.json
Labels: run-ci

#2513 [Bugfix] Querypanel : Codehinter fields placeholder is not aligned
  frontend/src/_styles/theme.scss
Labels: run-ci

#2489 make the server port configurable in the frontend project
  docs/docs/deployment/env-vars.md
  frontend/webpack.config.js
Labels: run-ci

#2531 ui: add tooltip for fx button
  frontend/src/Editor/CodeBuilder/Elements/FxButton.jsx
Labels: run-ci

#2472 Changed rest api query builder design
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/GroupHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabHeaders.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabParams.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/Tabs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, ready to merge

#2560 [Hotfix] : Fixes Unusual behaviour of widgets inside a container (reposition and resize issue)
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#2566 Bug-2565 cli error on plugin create
  cli/README.md
  cli/package-lock.json
  cli/package.json
  cli/src/commands/plugin/create.ts
Labels: run-ci

#2469 [UI improvement] :: Datasource selector in query manager updated from dropdown to cards
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/DataSourceLister.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/_styles/theme.scss
  plugins/packages/typesense/lib/icon.svg
Labels: run-ci, tested

#2586 Updated Slack code of conduct
  docs/docs/contributing-guide/_category_.json
  docs/docs/contributing-guide/slackcoc.md
  docs/docs/sso/_category_.json
Labels: documentation

#2577 fix: ignore OAuth hd field when SSO_RESTRICTED_DOMAIN not set
  server/ee/services/oauth/oauth.service.ts
Labels: run-ci

#2608 Feature: Add support for specifying file upload encoding
  frontend/src/Editor/Components/FilePicker.jsx
  plugins/packages/gcs/lib/operations.json
  plugins/packages/gcs/lib/operations.ts
Labels: run-ci

#2601 [ Enhancement ] :: Making fixed headers for query panel and properties/styles sidebar
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2557 [Stylefix] fixes codehinter field margin for text
  frontend/src/_styles/theme.scss
Labels: run-ci

#2590 Feature :: influxDB integration
  docs/docs/data-sources/influxdb.md
  docs/static/img/datasource-reference/influxdb/influxauth.png
  docs/static/img/datasource-reference/influxdb/operations.png
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/influxdb/.gitignore
  plugins/packages/influxdb/README.md
  plugins/packages/influxdb/__tests__/index.js
  plugins/packages/influxdb/lib/icon.svg
  plugins/packages/influxdb/lib/index.ts
  plugins/packages/influxdb/lib/manifest.json
  plugins/packages/influxdb/lib/operations.json
  plugins/packages/influxdb/lib/types.ts
  plugins/packages/influxdb/package-lock.json
  plugins/packages/influxdb/package.json
  plugins/packages/influxdb/tsconfig.json
Labels: run-ci, tested

#2617 Bugfix :: App crash while adding same datasource previously added.
  frontend/src/_components/DynamicForm.jsx
Labels: run-ci

#2610 Chore: Revise metadata fetch setup for telemetry
  frontend/src/App/App.jsx
  server/src/controllers/metadata.controller.ts
  server/src/services/metadata.service.ts
Labels: run-ci

#2536 Feature: Added refresh token functionality to Rest API OAuth flow
  plugins/packages/restapi/lib/index.ts
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
Labels: run-ci

#2595 Improvement: Exposed dark mode as mode
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
Labels: run-ci

#2638 fix: auto save when component def changes
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: run-ci

#2641 [Bigfix] Fixes edited version's component definition's schema gets altered
  server/src/controllers/apps.controller.ts
Labels: run-ci, tested

#2643 Bugfix page should be scrollable from everywhere
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
Labels: run-ci

#2619 Adding react-datepicker library instead of react-datetime library in datepicker widget
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/_styles/colors.scss
  frontend/src/_styles/theme.scss
Labels: run-ci

#2669 [docs] revised Appwrite doc
  docs/docs/data-sources/appwrite.md
  docs/docs/data-sources/couchdb.md
  docs/docs/data-sources/influxdb.md
  docs/docs/data-sources/oracledb.md
Labels: documentation

#2682 [docs] improved how-to upload files using GCS
  docs/docs/how-to/upload-files-gcs.md
Labels: documentation

#2685 made the tag and options of dropdown widget aligned horizontally
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#2687 Fix: Table events not being associated on version create
  server/src/services/apps.service.ts
Labels: run-ci

#2690 [docs] revised influxdb and oracledb datasources
  docs/docs/data-sources/influxdb.md
  docs/docs/data-sources/oracledb.md
  docs/static/img/datasource-reference/oracledb/oracleauth.png
Labels: documentation

#2683 Added issue form for documentation
  .github/ISSUE_TEMPLATE/03_documentation_report.yml
Labels: documentation

#2677 fix: sanitize html input for comments
  frontend/src/Editor/Comment/index.jsx
Labels: run-ci

#2693 Fixed issue form
  .github/ISSUE_TEMPLATE/03_documentation_report.yml
Labels: documentation

#2515 Bugfix :: Fixing app freeze issue while giving empty array as default value for Dropdown widget
  frontend/src/Editor/Components/DropDown.jsx
Labels: bug, frontend, tested

#2622 Bugfix :: Datasource are listed when query panel height is changed by dragging.
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: tested
