Repository ToolJet/ToolJet, pull requests merged in 2022-01, with the labels that each got.

#1796 Chore: Run ci only when label is added
  .github/workflows/ci.yml
Labels: run-ci

#1752 add python installable + npm ^7.2.0
  deploy/ec2/setup_machine.sh
  docker/client.Dockerfile
  docker/client.Dockerfile.dev
  docker/production.Dockerfile
  docker/server.Dockerfile
  docker/server.Dockerfile.dev
Labels: do not merge

#1839 added dark theme to querymanager dropdown lists
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Select/index.js
Labels: run-ci

#1808 [Home Page Design Changes] App listing style
  frontend/assets/images/icons/app-icons/apps.svg
  frontend/assets/images/icons/app-icons/business.svg
  frontend/assets/images/icons/app-icons/calender.svg
  frontend/assets/images/icons/app-icons/chart-bar.svg
  frontend/assets/images/icons/app-icons/code.svg
  frontend/assets/images/icons/app-icons/cpu.svg
  frontend/assets/images/icons/app-icons/database.svg
  frontend/assets/images/icons/app-icons/file-analytics.svg
  frontend/assets/images/icons/app-icons/flame.svg
  frontend/assets/images/icons/app-icons/presentation.svg
  frontend/assets/images/icons/app-icons/report-search.svg
  frontend/assets/images/icons/app-icons/settings.svg
  frontend/assets/images/icons/app-icons/users.svg
  frontend/assets/images/icons/app-icons/world.svg
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/Configs/AppIcon.json
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/Header.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/HomePage/Modal.jsx
  frontend/src/_components/SearchBox.jsx
  frontend/src/_components/ToolTip.jsx
  frontend/src/_components/index.js
  frontend/src/_hooks/useDebounce.js
  frontend/src/_hooks/useHover.js
  frontend/src/_services/app.service.js
  frontend/src/_styles/theme.scss
  server/src/services/folders.service.ts
Labels: run-ci

#1891 Chore: invoke ci action if label is present
  .github/workflows/ci.yml
Labels: run-ci

#1873 Feature: App version management ui revamp
  .github/workflows/ci.yml
  README.md
  docs/docs/data-sources/mongodb.md
  docs/docs/widgets/number-input.md
  docs/docs/widgets/table.md
  docs/docusaurus.config.js
  docs/static/img/tooljet-og-image.png
  frontend/assets/images/icons/editor/bulb-sharp.svg
  frontend/assets/images/icons/editor/deploy-rocket.svg
  frontend/assets/images/icons/widgets/listview.svg
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Mongodb.schema.json
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/Editor/SaveAndPreview.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/component-properties-resolution.js
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/HomePage/Modal.jsx
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_components/SearchBox.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/appVersion.service.js
  frontend/src/_styles/theme.scss
  server/migrations/1641809680591-AddApplicationIconColumn.ts
  server/package-lock.json
  server/package.json
  server/plugins/datasources/mongodb/index.ts
  server/src/controllers/apps.controller.ts
  server/src/entities/app.entity.ts
  server/src/modules/casl/abilities/apps-ability.factory.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/test.helper.ts
Labels: run-ci

#1821 Improvement/inspector datasource modal
  frontend/assets/images/icons/close.svg
  frontend/assets/images/icons/no-results.svg
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_ui/card/Card.jsx
  frontend/src/_ui/card/index.js
  plugins/packages/minioapi/lib/manifest.json
Labels: run-ci

#1887 Feature: Added new widget - circular progressbar
  docs/docs/widgets/circular-progress-bar.md
  docs/static/img/widgets/circular-progressbar/circular-progress.gif
  frontend/assets/images/icons/widgets/circularprogressbar.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/CirularProgressbar.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#1764 [Feature] file parser option for FilePicker widget [csv support]
  docs/docs/widgets/filepicker.md
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Components/FilePicker.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: run-ci

#1904 Add namespace @tooljet-plugins
  plugins/_templates/plugin/new/packagejson.ejs.t
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/airtable/lib/index.ts
  plugins/packages/airtable/package-lock.json
  plugins/packages/airtable/package.json
  plugins/packages/common/package.json
  plugins/packages/dynamodb/lib/index.ts
  plugins/packages/dynamodb/package.json
  plugins/packages/elasticsearch/lib/index.ts
  plugins/packages/elasticsearch/package.json
  plugins/packages/firestore/lib/index.ts
  plugins/packages/firestore/package.json
  plugins/packages/gcs/lib/index.ts
  plugins/packages/gcs/package.json
  plugins/packages/googlesheets/lib/index.ts
  plugins/packages/googlesheets/package.json
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/package.json
  plugins/packages/minioapi/lib/index.ts
  plugins/packages/minioapi/package-lock.json
  plugins/packages/minioapi/package.json
  plugins/packages/mongo/lib/index.ts
  plugins/packages/mongo/package.json
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mssql/package.json
  plugins/packages/mysql/lib/index.ts
  plugins/packages/mysql/package.json
  plugins/packages/postgresql/lib/index.ts
  plugins/packages/postgresql/package.json
  plugins/packages/redis/lib/index.ts
  plugins/packages/redis/package.json
  plugins/packages/restapi/lib/index.ts
  plugins/packages/restapi/package.json
  plugins/packages/s3/lib/index.ts
  plugins/packages/s3/package.json
  plugins/packages/sendgrid/lib/index.ts
  plugins/packages/sendgrid/package.json
  plugins/packages/slack/lib/index.ts
  plugins/packages/slack/package.json
  plugins/packages/stripe/lib/index.ts
  plugins/packages/stripe/package.json
  plugins/packages/twilioapi/lib/index.ts
  plugins/packages/twilioapi/package.json
  plugins/packages/typesenseapi/lib/index.ts
  plugins/packages/typesenseapi/package.json
Labels: run-ci

#1899 Allow dropdown option to be selected on Enter key press (Query Manager)
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#1897 Add docs for creating new packages
  docs/docs/contributing-guide/creating-a-plugin.md
Labels: draft

#1856 enhancement : style for loading state updated in home app card
  frontend/src/HomePage/AppList.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1883 feature : spinner widget
  frontend/assets/images/icons/widgets/spinner.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Spinner.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/_styles/theme.scss
Labels: feature request, run-ci

#1868 enhancement : homepage import made as dropdown
  frontend/src/HomePage/Header.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1784 Feature: Auto save editor and version management revamp
  frontend/assets/images/icons/editor/auto-save.svg
  frontend/assets/images/icons/editor/bulb-sharp.svg
  frontend/assets/images/icons/editor/deploy-rocket.svg
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/Editor/SaveAndPreview.jsx
  frontend/src/_services/appVersion.service.js
  frontend/src/_styles/theme.scss
  server/package-lock.json
  server/src/controllers/apps.controller.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/test.helper.ts
Labels: run-ci

#1855 Improvement: Changed search-input design of templates model
  frontend/src/HomePage/TemplateLibraryModal/AppList.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1915 [Bugfix]: fixes tab issues datasource modal
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci

#1913 Move husky & eslint to dev deps
  package.json
Labels: run-ci

#1924 Remove cypress from frontend directory
  frontend/.eslintrc.json
  frontend/cypress.json
  frontend/cypress/fixtures/example.json
  frontend/cypress/plugins/index.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/CodeBuilder/CodeHinter.spec.jsx
Labels: run-ci

#1861 Add source options types for plugins
  plugins/_templates/plugin/new/index.ejs.t
  plugins/_templates/plugin/new/types.ejs.t
  plugins/packages/airtable/lib/index.ts
  plugins/packages/airtable/lib/types.ts
  plugins/packages/dynamodb/lib/index.ts
  plugins/packages/dynamodb/lib/types.ts
  plugins/packages/elasticsearch/lib/index.ts
  plugins/packages/elasticsearch/lib/types.ts
  plugins/packages/firestore/lib/index.ts
  plugins/packages/firestore/lib/types.ts
  plugins/packages/gcs/lib/index.ts
  plugins/packages/gcs/lib/types.ts
  plugins/packages/googlesheets/lib/index.ts
  plugins/packages/googlesheets/lib/types.ts
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/lib/types.ts
  plugins/packages/minioapi/lib/index.ts
  plugins/packages/minioapi/lib/types.ts
  plugins/packages/mongo/lib/index.ts
  plugins/packages/mongo/lib/types.ts
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mssql/lib/types.ts
  plugins/packages/mysql/lib/index.ts
  plugins/packages/mysql/lib/types.ts
  plugins/packages/postgresql/lib/index.ts
  plugins/packages/postgresql/lib/types.ts
  plugins/packages/redis/lib/index.ts
  plugins/packages/redis/lib/types.ts
  plugins/packages/restapi/lib/types.ts
  plugins/packages/s3/lib/index.ts
  plugins/packages/s3/lib/types.ts
  plugins/packages/sendgrid/lib/index.ts
  plugins/packages/sendgrid/lib/types.ts
  plugins/packages/slack/lib/index.ts
  plugins/packages/slack/lib/types.ts
  plugins/packages/stripe/lib/index.ts
  plugins/packages/stripe/lib/types.ts
  plugins/packages/twilioapi/lib/index.ts
  plugins/packages/twilioapi/lib/types.ts
  plugins/packages/typesenseapi/lib/index.ts
  plugins/packages/typesenseapi/lib/types.ts
Labels: run-ci

#1935 [BUG-1934] Mongbdb label issue fix
  plugins/packages/mongo/lib/operations.json
Labels: run-ci

#1834 Feature : statistics widget
  docs/docs/widgets/statistics.md
  docs/static/img/widgets/statistics/statistics.gif
  frontend/assets/images/icons/widgets/downstatistics.svg
  frontend/assets/images/icons/widgets/statistics.svg
  frontend/assets/images/icons/widgets/upstatistics.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/components.js
Labels: enhancement, run-ci

#1927 Fix: version find getting latest rec when not found
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci

#1936 Chore: Make ci run for main and develop without label
  .github/workflows/ci.yml
Labels: run-ci

#1933 Fix: OnClick doesn't fire event on SVG icons of Datasource manager modal
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_ui/card/Card.jsx
Labels: run-ci

#1937 Update Chart.jsx
  frontend/src/Editor/Inspector/Components/Chart.jsx
Labels: run-ci

#1940 Bugfix/statistics widget style change not reflecting in dark mode , visibilty option not working
  frontend/src/Editor/Components/Spinner.jsx
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#1953 Chore: Docker compose plugins dev
  .github/workflows/ci.yml
  docker-compose.yaml
  docker/client.Dockerfile.dev
  docker/plugins.Dockerfile.dev
  docker/server.Dockerfile.dev
  docs/docs/contributing-guide/setup/docker.md
  package.json
  plugins/package-lock.json
  plugins/package.json
  plugins/tsconfig.json
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: run-ci

#1837 Github OAuth integration
  .env.example
  docs/docs/sso/github.md
  docs/docs/sso/google.md
  docs/static/img/sso/git/client-id.png
  docs/static/img/sso/git/client-secret.png
  docs/static/img/sso/git/create-project.png
  frontend/assets/images/sso-buttons/git.svg
  frontend/assets/images/sso-buttons/unknown.svg
  frontend/ee/components/LoginPage/GitSSOLoginButton.jsx
  frontend/ee/components/LoginPage/GoogleSSOLoginButton.jsx
  frontend/package-lock.json
  frontend/src/App/App.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/Oauth/Authorize.jsx
  frontend/src/Oauth/Configs/Config.json
  frontend/src/Oauth/index.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/authentication.service.js
  frontend/src/_styles/theme.scss
  server/ee/controllers/oauth.controller.ts
  server/ee/services/oauth/git_oauth.service.ts
  server/ee/services/oauth/google_oauth.service.ts
  server/ee/services/oauth/index.ts
  server/ee/services/oauth/models/user_response.ts
  server/ee/services/oauth/oauth.service.ts
  server/migrations/1632468258787-PopulateUserGroupsFromOrganizationRoles.ts
  server/migrations/1642432246029-CreateSSOField.ts
  server/package-lock.json
  server/package.json
  server/src/entities/user.entity.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/jwt.strategy.ts
  server/src/services/app_config.service.ts
  server/src/services/users.service.ts
  server/test/controllers/oauth.e2e-spec.ts
  server/test/test.helper.ts
Labels: run-ci

#1914 Fix: Namespaced data source connectivity issues
  frontend/src/Editor/QueryManager/QueryManager.jsx
  plugins/package-lock.json
  plugins/packages/elasticsearch/lib/index.ts
  plugins/packages/elasticsearch/lib/manifest.json
  plugins/packages/elasticsearch/lib/types.ts
  plugins/packages/elasticsearch/package-lock.json
  plugins/packages/elasticsearch/package.json
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mssql/package.json
  plugins/packages/mysql/package.json
  plugins/packages/redis/lib/index.ts
Labels: run-ci

#1955 [Bugfix] Event manager: The text should be specific to a component
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci

#1957 Dynamic positioning for config handle
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1967 Created a new category in widgets sidebar
  frontend/src/Editor/WidgetManager.jsx
Labels: enhancement, run-ci

#1971 Add runjs icon
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Icons/runjs.svg
Labels: run-ci

#1959 Removes extra space after dark mode switcher on left sidebar
  frontend/src/_styles/left-sidebar.scss
Labels: run-ci

#1968 Bugfix/ on new app creation v1 should be default name and pressing enter should create version
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#1928 Remove react scripts
  docker/client.Dockerfile.dev
  frontend/package-lock.json
  frontend/package.json
Labels: run-ci

#1983 [Bugfix] Homepage 'no results' not legible for app search
  frontend/src/HomePage/AppList.jsx
Labels: run-ci

#1980 [Bugfix] Pagination subtext color
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_components/Pagination.jsx
Labels: run-ci

#1977 [Bugfix] All applications background color is inconsistent
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#1973 [BUG-1941] typeorm findone fix
  server/migrations/1639734070615-BackfillDataSourcesAndQueriesForAppVersions.ts
  server/src/services/app_import_export.service.ts
  server/src/services/app_users.service.ts
  server/src/services/apps.service.ts
  server/src/services/comment.service.ts
  server/src/services/credentials.service.ts
  server/src/services/data_queries.service.ts
  server/src/services/group_permissions.service.ts
  server/src/services/organization_users.service.ts
  server/src/services/seeds.service.ts
  server/src/services/thread.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/data_queries.e2e-spec.ts
  server/test/controllers/data_sources.e2e-spec.ts
  server/test/controllers/group_permissions.e2e-spec.ts
  server/test/controllers/users.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
  server/test/services/users.service.spec.ts
  server/test/test.helper.ts
Labels: bug, run-ci

#1987 Fixes widget crash when added to subcontainers
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#1985 Code suggestions should replace only the last word
  frontend/src/Editor/CodeBuilder/utils.js
Labels: run-ci

#1999 fixes: sendGrid plugin: setApiKey not a function
  plugins/packages/sendgrid/lib/index.ts
Labels: run-ci

#1930 [Bugfix] On clicking Go to all datasources, UI renders the same compone…
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci

#1972 Bugfix/border radius style included for multiple widgets
  frontend/src/Editor/Components/CodeEditor.jsx
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/_styles/theme.scss
Labels: run-ci

#1780 Adds support for custom variables
  frontend/src/Editor/ActionTypes.js
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: run-ci

#2022 Added background color property to image widget
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2032 Bugfix :: fixing all issues with release version modal
  frontend/src/Editor/AppVersionsManager.jsx
Labels: run-ci

#2020 Fix: sub-container didn't track exposed data of listview when removing child widgets
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci

#2050 Added padding property to the image widget
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2029 Added padding property to charts widget
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2030 fix: re-render of container
  frontend/src/Editor/Editor.jsx
Labels: run-ci
