Repository ToolJet/ToolJet, pull requests merged in 2022-11, with the labels that each got.

#4670 [Marketplace] AWS S3
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/_ui/card/Card.jsx
  marketplace/package-lock.json
  marketplace/plugins/s3/.gitignore
  marketplace/plugins/s3/README.md
  marketplace/plugins/s3/__tests__/index.js
  marketplace/plugins/s3/lib/icon.svg
  marketplace/plugins/s3/lib/index.ts
  marketplace/plugins/s3/lib/manifest.json
  marketplace/plugins/s3/lib/operations.json
  marketplace/plugins/s3/lib/query_operations.ts
  marketplace/plugins/s3/lib/types.ts
  marketplace/plugins/s3/package.json
  marketplace/plugins/s3/tsconfig.json
  server/src/assets/marketplace/plugins.json
  server/src/dto/create-plugin.dto.ts
  server/src/helpers/plugins.helper.ts
  server/src/main.ts
Labels: run-ci, marketplace

#4552 Added a modal with warning message on disabling password
  frontend/src/ManageSSO/Form.jsx
  frontend/src/ManageSSO/ManageSSO.jsx
Labels: hacktoberfest-accepted, run-ci, tested

#4588 Copy to clipboard
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: hacktoberfest-accepted, run-ci, tested

#4607 Fix: Login redirect on subpath
  frontend/src/Editor/AppVersionsManager.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/_components/LanguageSelection.jsx
  frontend/src/_helpers/history.js
  frontend/src/_services/authentication.service.js
  frontend/src/index.ejs
  server/src/modules/auth/app-auth.guard.ts
Labels: run-ci

#4193 Feature: Number input text color
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, run-ci, tested

#4175 Add border color property to number input widget
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest, hacktoberfest-accepted, run-ci, tested

#4613 Folder Name Length Validation
  frontend/src/HomePage/Folders.jsx
  server/src/services/folders.service.ts
Labels: hacktoberfest-accepted, run-ci

#4678 [Bug]: Reverting Canvas Max Width Limit
  frontend/src/Editor/LeftSidebar/SidebarGlobalSettings.jsx
  server/templates/gcs-file-explorer/definition.json
Labels: bug, run-ci, tested, editor

#4701 [Hotfix]: Reverting Canvas Max Width Limit
  frontend/src/Editor/LeftSidebar/SidebarGlobalSettings.jsx
  server/templates/gcs-file-explorer/definition.json
Labels: bug, editor

#4477 Improvements :: Table widget
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: tested, table

#4218 Add onChange event to passwordInput
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, needs testing, run-ci, tested

#4697 Queries fail when triggered on page load and self triggering queries crashes the app
  frontend/src/Editor/Editor.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: bug, frontend, run-ci, tested

#4698 [Bugfix] : validating query name on throws error for non-existing queries
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: tested

#4580 Small fixes for Server-side filter button (#4571)
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, run-ci, tested

#4706 [chore] eslint fixes
  frontend/src/Editor/Comment/CommentActions.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Inspector/Components/Icon.jsx
  frontend/src/Editor/QueryManager/QueryPanel.jsx
  frontend/src/Editor/RealtimeEditor.jsx
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/_components/Header.jsx
Labels: duplicate, run-ci

#4709 fix: query manager loading when marketplace plugin is uninstalled
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  server/migrations/1664535394459-addForeignKeyForPlugin.ts
Labels: run-ci

#4720 [Marketplace] Plugins: camelize the source data and decamelize the options
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: bug, needs testing, run-ci, marketplace

#4703 [Bugfix] Datasource Manager: stale connection msg should be removed on back
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  server/src/main.ts
Labels: bug, tested

#4725 [Bugfix] Datasource connection form is not render when clicking from Sidebar popover
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: bug, needs testing, run-ci

#4715 Fixed and modified failing cypress spec
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/login.js
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/constants/texts/login.js
  cypress-tests/cypress/constants/texts/manageUsers.js
  cypress-tests/cypress/e2e/authentication/login.cy.js
  cypress-tests/cypress/e2e/dashboard/manageGroups.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/userPermissions.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/userPermissions.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/login.js
  cypress-tests/cypress/support/utils/manageUsers.js
  frontend/ee/components/UsersPage/UsersFilter.jsx
  frontend/src/_components/Pagination.jsx
Labels: cypress

#4610 Add storage.googleapis.com as a verified source
  server/src/main.ts
Labels: run-ci

#4689 Fixed failing profile spec
  cypress-tests/cypress/constants/selectors/profile.js
  cypress-tests/cypress/constants/texts/profile.js
  cypress-tests/cypress/e2e/dashboard/profile.cy.js
  cypress-tests/cypress/fixtures/Image/tooljet.png
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/e2e.js
  cypress-tests/cypress/support/utils/profile.js
  cypress-tests/package-lock.json
  cypress-tests/package.json
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_components/Header.jsx
Labels: cypress

#4745 fix: failing e2e test case
  server/src/services/apps.service.ts
Labels: run-ci

#4749 Fixed the widget specs failed on v1.28.3
  cypress-tests/cypress/e2e/editor/widget/datePickerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
Labels: cypress

#4742 [doc] updated tab
  docs/docs/widgets/tabs.md
  docs/static/img/widgets/tabs/events.png
Labels: documentation

#4738 [doc] updated number-input doc
  docs/docs/widgets/number-input.md
  docs/static/img/widgets/number-input/event.png
Labels: documentation

#4747 [Bug]: Fixed triggering query on page load if other queries are added/deleted
  frontend/src/Editor/Editor.jsx
  frontend/src/_helpers/utils.js
Labels: bug, frontend, run-ci, tested, editor

#4389 [enahancement] Added app loader page
  frontend/src/App/App.jsx
  frontend/src/AppLoader/AppLoader.jsx
  frontend/src/AppLoader/index.js
  frontend/src/Editor/Icons/viewer-logo.svg
  frontend/src/Editor/Viewer.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/_components/PrivateRoute.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_services/app.service.js
  frontend/src/_styles/theme.scss
  frontend/src/index.ejs
  server/src/controllers/apps.controller.ts
  server/src/modules/casl/abilities/apps-ability.factory.ts
Labels: frontend, run-ci, tested

#4753 [docs] minor update in keyboard shortcuts
  docs/docs/tutorial/keyboard-shortcuts.md
Labels: documentation

#4752 [doc] marketplace for plugin
  docs/docs/marketplace.md
  docs/docs/setup/env-vars.md
  docs/sidebars.js
  docs/static/img/marketplace/datasource.png
  docs/static/img/marketplace/installed.png
  docs/static/img/marketplace/marketplacemain.png
Labels: documentation

#4675 Change Position of show search box
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: hacktoberfest-accepted

#4763 [docs] app menu options
  docs/docs/tutorial/app-menu-options.md
  docs/sidebars.js
  docs/static/img/tutorial/app-menu-options/app-menu.png
  docs/static/img/tutorial/app-menu-options/change-icon.png
  docs/static/img/tutorial/app-menu-options/delete.png
  docs/static/img/tutorial/app-menu-options/export.png
  docs/static/img/tutorial/app-menu-options/movetofolder.png
Labels: documentation

#4759 [doc] updated widgets
  docs/docs/widgets/calendar.md
  docs/docs/widgets/chart.md
  docs/docs/widgets/number-input.md
  docs/docs/widgets/password-input.md
  docs/static/img/widgets/calendar/calendar.png
Labels: documentation

#4756 [docs] updated button and button group
  docs/docs/widgets/button-group.md
  docs/docs/widgets/button.md
  docs/static/img/widgets/button-group/button-group.png
  docs/static/img/widgets/button-group/events.png
  docs/static/img/widgets/button-group/layout.png
  docs/static/img/widgets/button-group/properties.png
  docs/static/img/widgets/button-group/styles.png
  docs/static/img/widgets/button/styles.png
Labels: documentation

#4758 chore: update @tooljet/cli version
  package-lock.json
  package.json
Labels: run-ci

#4203 adds `On change` event in color picker component
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/DataSourceManager/TestConnection.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: good first issue, frontend, javascript, hacktoberfest-accepted, run-ci, tested, create-review-app, react

#4761 Added data-cy to google sheet connection modal.
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/_components/Googlesheets.jsx
  frontend/src/_ui/Radio/index.js
Labels: cypress, run-ci

#4730 [docs] table improvements
  docs/README.md
  docs/docs/widgets/table.md
Labels: documentation

#4777 Chore: Setup workflow runs from forks
  .github/workflows/render-preview-deploy.yml
  .github/workflows/render-suspend-labeler.yml
Labels: destroy-review-app

#4776 [docs] how-to access user's location in tooljet apps
  docs/docs/how-to/access-users-location.md
  docs/sidebars.js
  docs/static/img/how-to/access-location/data.png
  docs/static/img/how-to/access-location/map.png
  docs/static/img/how-to/access-location/newapp.png
  docs/static/img/how-to/access-location/prompt.png
  docs/static/img/how-to/access-location/runjs.png
Labels: documentation

#4640 fixed chart loading spinner is not at the centre vertically
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/_styles/custom.scss
Labels: hacktoberfest-accepted, run-ci, tested

#4636 Fixed Alert, break lines if there are no spaces in the message
  frontend/src/App/App.jsx
Labels: hacktoberfest-accepted, run-ci, tested

#4440 styles: fixes in workspace dark mode
  frontend/src/_styles/theme.scss
Labels: bug, good first issue, javascript, hacktoberfest-accepted, run-ci, tested, create-review-app, react

#4734 [ Bug fixed ] : On updating any group permissions, active tab switches to Apps
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
Labels: bug, good first issue, frontend, javascript, run-ci, tested, react

#4674 fix: popout editor closing for tables
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: hacktoberfest-accepted, run-ci, tested

#4194 Added Background Color to Text Input
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: good first issue, frontend, javascript, hacktoberfest-accepted, run-ci, tested, create-review-app, react

#4766 feat: Add update version button on installable plugin
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/_services/plugins.service.js
  server/package-lock.json
  server/src/assets/marketplace/plugins.json
  server/src/dto/update-plugin.dto.ts
  server/src/services/files.service.ts
  server/src/services/plugins.service.ts
Labels: run-ci

#4611 Fixed dark mode on table's `Striped` and `Striped & Bordered` table type mode
  frontend/src/Editor/Components/Table/Table.jsx
Labels: hacktoberfest-accepted, run-ci, tested

#4438 [ Hotfix ] :: Hard to resize table columns
  frontend/src/_styles/theme.scss
Labels: tested, table

#4192 Enhancement : [RangeSlider widget] Bind onChange event
  frontend/src/Editor/Components/RangeSlider.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: bug, frontend, javascript, hacktoberfest-accepted, run-ci, tested, create-review-app, react

#4792 Added data-cy for table widget elements
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Components/Table/IndeterminateCheckbox.jsx
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
  frontend/src/Editor/Inspector/Elements/Components/ToolTip.jsx
Labels: cypress, run-ci

#4793 [docs] widget updates
  docs/docs/widgets/button.md
  docs/docs/widgets/checkbox.md
  docs/docs/widgets/circular-progressbar.md
  docs/docs/widgets/code-editor.md
  docs/docs/widgets/color-picker.md
  docs/docs/widgets/container.md
  docs/docs/widgets/custom-component.md
  docs/docs/widgets/date-range-picker.md
  docs/docs/widgets/datepicker.md
  docs/docs/widgets/divider.md
  docs/docs/widgets/dropdown.md
  docs/docs/widgets/file-picker.md
  docs/static/img/widgets/color-picker/colorpickerpopup.png
  docs/static/img/widgets/color-picker/events.png
  docs/static/img/widgets/color-picker/picker.png
  docs/static/img/widgets/container/styles.png
  docs/static/img/widgets/datepicker/date-picker.png
  docs/static/img/widgets/datepicker/datepicker.png
  docs/static/img/widgets/dropdown/event.png
  docs/static/img/widgets/dropdown/events.png
  docs/static/img/widgets/dropdown/prop.png
  docs/static/img/widgets/dropdown/props.png
  docs/static/img/widgets/dropdown/style.png
  docs/static/img/widgets/dropdown/styles.png
  docs/static/img/widgets/filepicker/events.png
  docs/static/img/widgets/filepicker/layout.png
  docs/static/img/widgets/filepicker/options.png
  docs/static/img/widgets/filepicker/picker.png
  docs/static/img/widgets/filepicker/styles.png
Labels: documentation

#4755 [improvements] Multi-page applications
  frontend/assets/images/icons/3dots-menu.svg
  frontend/assets/images/icons/alert-info.svg
  frontend/assets/images/icons/delete.svg
  frontend/assets/images/icons/duplicate.svg
  frontend/assets/images/icons/editor/left-sidebar/page.svg
  frontend/assets/images/icons/eye.svg
  frontend/assets/images/icons/home.svg
  frontend/assets/images/icons/input.svg
  frontend/assets/images/icons/save.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/EditInput.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/EditModal.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/RenameInput.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.js
  frontend/src/Editor/LeftSidebar/SidebarPinnedButton.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/_components/SortableList/SortableList.jsx
  frontend/src/_components/SortableList/components/SortableItem.jsx
  frontend/src/_components/SortableList/components/SortableOverlay.jsx
  frontend/src/_components/SortableList/components/index.js
  frontend/src/_components/SortableList/index.js
  frontend/src/_styles/components.scss
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/LeftSidebar/Button.jsx
  frontend/src/_ui/LeftSidebar/Header.jsx
  frontend/src/_ui/LeftSidebar/index.js
  frontend/src/_ui/Search/Search.jsx
Labels: feature request, run-ci

#4806 [docs] updated widgets
  docs/docs/widgets/html.md
  docs/docs/widgets/icon.md
  docs/docs/widgets/iframe.md
  docs/docs/widgets/image.md
  docs/docs/widgets/kanban-board.md
  docs/docs/widgets/link.md
  docs/static/img/widgets/html/html-rawhtml.png
  docs/static/img/widgets/html/html.png
  docs/static/img/widgets/html/raw.png
  docs/static/img/widgets/image/props.png
Labels: documentation

#4770 Onboarding revamp test cases
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/oauth/oauth-git-instance.e2e-spec.ts
  server/test/controllers/oauth/oauth-git.e2e-spec.ts
  server/test/controllers/oauth/oauth-google-instance.e2e-spec.ts
  server/test/controllers/oauth/oauth-google.e2e-spec.ts
  server/test/controllers/onboarding/form-auth.e2e-spec.ts
  server/test/controllers/onboarding/git-sso-auth.e2e-spec.ts
  server/test/controllers/onboarding/google-sso-auth.e2e-spec.ts
  server/test/controllers/organizations.e2e-spec.ts
  server/test/test.helper.ts
Labels: run-ci

#4813 Automation for table elements
  cypress-tests/cypress/constants/selectors/table.js
  cypress-tests/cypress/constants/texts/table.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/table.js
Labels: cypress

#4830 Fix error on handling rest api request without response
  plugins/packages/restapi/lib/index.ts
Labels: run-ci

#4803 Multipage : hide page and unhide page feature
  frontend/assets/images/icons/eye-off.svg
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.js
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/_styles/components.scss
Labels: run-ci

#4802 add: duplicate page
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.js
  frontend/src/Editor/LeftSidebar/index.js
Labels: run-ci

#4836 [docs]minor fix
  docs/docs/how-to/run-action-from-runjs.md
  docs/sidebars.js
Labels: documentation
