Repository ToolJet/ToolJet, pull requests merged in 2022-06, with the labels that each got.

#3161 added default table type prop to table-bordererd in component.js
  frontend/src/Editor/Components/components.js
Labels: run-ci

#2977 Feature :: Button group widget
  docs/docs/widgets/button-group.md
  docs/sidebars.js
  frontend/assets/images/icons/widgets/buttongroup.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/ButtonGroup.jsx
  frontend/src/Editor/Components/components.js
  frontend/src/_styles/theme.scss
Labels: run-ci, widget

#2807 Bugfix :: Canvas background made programmable and fix for alpha not working
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarGlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/_styles/theme.scss
Labels: needs testing

#3167 [bugfix] Now the app exit modal will not show if there isn't anything to save
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/index.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: bug, frontend, run-ci

#3118 fixed : FX button misaligned with the corresponding text
  frontend/src/Editor/CodeBuilder/Elements/AlignButtons.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/CodeBuilder/Elements/Number.jsx
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/CodeBuilder/Elements/Toggle.jsx
Labels: run-ci

#3093 Added Variables field for graphql plugin
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/lib/operations.json
  plugins/packages/graphql/lib/types.ts
Labels: run-ci, plugins

#3096 [Feature]: Added universal props for widgets with Tooltip
  docs/docs/contributing-guide/tutorials/create-widget.md
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeBuilder.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/components.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/Editor/component-properties-resolution.js
  frontend/src/_helpers/appUtils.js
Labels: run-ci

#2920 feat: add user avatar
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/Editor/RealtimeCursors.jsx
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_components/Header.jsx
  frontend/src/_services/user.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Avatar/index.jsx
  package-lock.json
  package.json
  server/migrations/1651048832554-AddAvatarIdToUser.ts
  server/migrations/1651056032050-CreateFiles.ts
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/controllers/files.controller.ts
  server/src/controllers/users.controller.ts
  server/src/dto/create-file.dto.ts
  server/src/dto/update-file.dto.ts
  server/src/entities/file.entity.ts
  server/src/entities/user.entity.ts
  server/src/main.ts
  server/src/modules/apps/apps.module.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/casl/casl.module.ts
  server/src/modules/data_queries/data_queries.module.ts
  server/src/modules/data_sources/data_sources.module.ts
  server/src/modules/files/files.module.ts
  server/src/modules/folders/folders.module.ts
  server/src/modules/group_permissions/group_permissions.module.ts
  server/src/modules/organizations/organizations.module.ts
  server/src/modules/users/users.module.ts
  server/src/services/auth.service.ts
  server/src/services/files.service.ts
  server/src/services/users.service.ts
  server/test/__mocks__/avatar.png
  server/test/controllers/files.e2e-spec.ts
  server/test/controllers/users.e2e-spec.ts
  server/test/test.helper.ts
Labels: run-ci, tested

#3155 [Feature]: Copy text from CodeHinter preview
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#3190 Workspace invite and user onboarding flow changes
  frontend/src/App/App.jsx
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/_services/app.service.js
  server/src/dto/user.dto.ts
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/organizations.service.ts
  server/test/controllers/app.e2e-spec.ts
Labels: run-ci

#3150 [BUG] Account level security issue
  frontend/src/App/App.jsx
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/_services/app.service.js
  frontend/src/_services/user.service.js
  server/src/controllers/app.controller.ts
  server/src/controllers/organization_users.controller.ts
  server/src/controllers/users.controller.ts
  server/src/dto/accept-organization-invite.dto.ts
  server/src/dto/user.dto.ts
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/organization_users.service.ts
  server/src/services/organizations.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/users.e2e-spec.ts
Labels: run-ci

#3076 [Feature]: Inline style support for custom component
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Inspector/Components/CustomComponent.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/Editor/component-properties-resolution.js
Labels: run-ci

#3198 [docs] fixed typos in try ToolJet
  docs/docs/setup/docker-local.md
Labels: documentation

#3196 Corrected spellings in heroku deployment guide
  docs/docs/setup/heroku.md
Labels: bug, good first issue, up-for-grabs

#3201 [docs] renamed sidebar title of `Docker Local` to `Try Tooljet locally`
  docs/docs/setup/docker-local.md
Labels: documentation

#3189 [docs] changed search-bar position to left
  docs/docusaurus.config.js
Labels: documentation

#3216 [Bug] Relabelling Git and workspace
  docs/docs/user-authentication/sso/github.md
  frontend/src/ConfirmationPage/ConfirmationPage.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/ManageSSO.jsx
  frontend/src/Oauth/Configs/Config.json
  frontend/src/RedirectSso/RedirectSso.jsx
Labels: run-ci

#3224 [Feature]: Move & Resize Portal
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/_components/Portal/Portal.jsx
  frontend/src/_hooks/use-portal.jsx
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci

#3206 fixes leftsidebar inspector crash for n depth nodes with actions
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
Labels: needs testing, run-ci

#3230 Remove frontend display name validation (#2494)
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
Labels: run-ci

#3222 Added environment variable to view/hide account setup link
  docs/docs/setup/env-vars.md
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  server/ee/services/oauth/oauth.service.ts
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/organizations.service.ts
  server/test/controllers/app.e2e-spec.ts
Labels: run-ci, create-review-app

#3210 fix: re-render when cursor hovered on canvas
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/Editor/RealtimeCursors.jsx
  frontend/src/Editor/RealtimeEditor.jsx
  frontend/src/_hooks/use-event-listener.jsx
  frontend/src/_hooks/use-focus.jsx
  frontend/src/_hooks/use-mouse-position.jsx
  server/src/events/yjs.gateway.ts
Labels: run-ci, tested

#3218 Added url-encoded body support to restapi plugin
  plugins/packages/restapi/lib/index.ts
Labels: run-ci, plugins

#3049 [Feature] Kanban board widget
  docs/docs/widgets/kanban.md
  docs/sidebars.js
  docs/static/img/widgets/kanban/kanban-events.png
  docs/static/img/widgets/kanban/kanban.png
  docs/static/img/widgets/kanban/layout.png
  docs/static/img/widgets/kanban/properties.png
  docs/static/img/widgets/kanban/styles.png
  docs/static/img/widgets/kanban/variables.png
  frontend/assets/images/icons/editor/edit.svg
  frontend/assets/images/icons/widgets/kanbanboard.svg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/KanbanBoard/Board.jsx
  frontend/src/Editor/Components/KanbanBoard/Card.jsx
  frontend/src/Editor/Components/KanbanBoard/CardPopover.jsx
  frontend/src/Editor/Components/KanbanBoard/Column.jsx
  frontend/src/Editor/Components/KanbanBoard/KanbanBoard.jsx
  frontend/src/Editor/Components/KanbanBoard/utils.js
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#3164 Invited user should be able to login and activate account using SSO
  docs/docs/user-authentication/general-settings.md
  docs/docs/user-authentication/user-lifecycle.md
  docs/sidebars.js
  docs/static/img/user-lifecycle/accept-invite-sw.png
  docs/static/img/user-lifecycle/archive-user.png
  docs/static/img/user-lifecycle/invite-link-mw.png
  docs/static/img/user-lifecycle/signup-mw.png
  docs/static/img/user-lifecycle/single-ws-signup.png
  docs/static/img/user-lifecycle/sso-enable-signup-sw.png
  docs/static/img/user-lifecycle/sso-onboard-sw.png
  docs/static/img/user-lifecycle/switch.png
  docs/static/img/user-lifecycle/unarchive-sw.png
  docs/static/img/user-lifecycle/unarchive-user-mw.png
  docs/static/img/user-lifecycle/user-invite-sw.png
  docs/static/img/user-lifecycle/user-mw.png
  server/ee/services/oauth/oauth.service.ts
  server/src/modules/auth/jwt.strategy.ts
  server/src/services/auth.service.ts
  server/src/services/organization_users.service.ts
  server/src/services/organizations.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/oauth.e2e-spec.ts
Labels: backend, run-ci, tested

#3244 display current version in the dashboard
  frontend/src/App/App.jsx
  frontend/src/_components/Header.jsx
Labels: run-ci

#3227 [Bug]: Broken Table Border
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#3115 [Feature]: Trigger actions from RunJS
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: run-ci

#3298 [hotfix] Table widget's column text colour option didn't work as expected
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci

#3289 [hotfix] Date range picker is showing error inside the modal
  frontend/src/Editor/Components/DaterangePicker.jsx
Labels: bug, run-ci, widget

#2938 added HTML-CSS widget
  frontend/assets/images/icons/widgets/Html.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Html.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci

#3131 [Feature]: Run query while Creating/Saving
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci

#3132 [Feature] Added ability to update and delete app folders
  cypress/constants/selectors/common.js
  frontend/src/HomePage/FolderMenu.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/_services/folder.service.js
  frontend/src/_styles/theme.scss
  server/migrations/1653391166172-AddFolderUpdateAndDeletePermissionsToGroupPermissions.ts
  server/migrations/1653474337657-BackfillFolderDeleteFolderUpdatePermissionsAsTruthyForAdminGroup.ts
  server/src/controllers/folders.controller.ts
  server/src/entities/group_permission.entity.ts
  server/src/modules/casl/abilities/folders-ability.factory.ts
  server/src/services/folders.service.ts
  server/src/services/group_permissions.service.ts
  server/src/services/organizations.service.ts
  server/src/services/seeds.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/folders.e2e-spec.ts
  server/test/controllers/oauth.e2e-spec.ts
  server/test/test.helper.ts
Labels: frontend, backend, run-ci, tested

#3272 User account level security issue
  server/src/controllers/organization_users.controller.ts
  server/src/services/organization_users.service.ts
  server/src/services/users.service.ts
  server/test/controllers/organization_users.e2e-spec.ts
Labels: backend, run-ci

#3301 Feature :: Bigquery revamp
  docs/docs/data-sources/bigquery.md
  docs/static/img/datasource-reference/bigquery/bq-delete.png
  docs/static/img/datasource-reference/bigquery/bq-insert.png
  docs/static/img/datasource-reference/bigquery/bq-update.png
  docs/static/img/datasource-reference/bigquery/bq-view.png
  plugins/packages/bigquery/lib/index.ts
  plugins/packages/bigquery/lib/operations.json
  plugins/packages/bigquery/lib/types.ts
Labels: run-ci, plugins, tested

#3304 Fixed fx text alignment
  frontend/src/Editor/CodeBuilder/Elements/AlignButtons.jsx
Labels: run-ci

#3110 3066 incorrect message while enabling disabling password
  frontend/src/ManageSSO/Form.jsx
Labels: run-ci

#3325 [ Bugfix ]:: Typo in toast success in manage sso
  frontend/src/ManageSSO/Form.jsx
Labels: run-ci

#3285 Feature: Format json on export
  frontend/src/HomePage/HomePage.jsx
Labels: run-ci

#3326 [Bugfix] Fixes LeftSide Inspector issues
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
Labels: run-ci, tested

#3287 Enhancement : added border radius property in the styles property of the List View Widget
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  server/migrations/1655279771926-listViewWidgetAddingBorderRadiusProperty.ts
Labels: run-ci

#3330 Added query name to run query confirmation box #3310
  frontend/src/Editor/Editor.jsx
Labels: run-ci

#3303 Added Package Name and Version
  package-lock.json
  package.json
Labels: run-ci

#3358 [Bug]: CodeHinter Portal Issue for Lower Resolution
  frontend/src/_styles/theme.scss
Labels: frontend, run-ci, tested

#3296 [docs] how-to/change column text color using variables
  docs/docs/how-to/access-cellvalue-rowdata.md
  docs/sidebars.js
  docs/static/img/how-to/change-text-color/apiendpoint.png
  docs/static/img/how-to/change-text-color/cellvalue.png
  docs/static/img/how-to/change-text-color/columns.png
  docs/static/img/how-to/change-text-color/data.png
  docs/static/img/how-to/change-text-color/inspectord.png
  docs/static/img/how-to/change-text-color/newapp.gif
  docs/static/img/how-to/change-text-color/price.png
  docs/static/img/how-to/change-text-color/restapi.png
  docs/static/img/how-to/change-text-color/rowData.png
  docs/static/img/how-to/change-text-color/runquery.png
  docs/static/img/how-to/change-text-color/table.png
Labels: documentation

#3338 Enhancement : displaying version name in the dashboard
  frontend/src/App/App.jsx
  frontend/src/_components/Header.jsx
  frontend/src/_styles/colors.scss
Labels: run-ci

#3349 Compute visibility of children of inner tabs in nested tabs scenario
  frontend/src/Editor/Components/Tabs.jsx
Labels: draft

#3370 [Docs]: Replaced Text widget's video
  docs/docs/widgets/text.md
Labels: documentation, good first issue, up-for-grabs, widget

#3180 Undefined error in multiple cases
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: needs testing, run-ci

#3339 Cypress test for the manage sso page multi workspace
  cypress/constants/selectors/manageSSO.js
  cypress/constants/texts/manageSSO.js
  cypress/integration/dashboard/multi-workspace/manageSSO.spec.js
  cypress/support/utils/manageSSO.js
  frontend/src/ManageSSO/GeneralSettings.jsx
Labels: run-ci

#3394 [docs] moved architecture under Setup in `Contributing guide`
  docs/docs/contributing-guide/setup/architecture.md
  docs/docs/contributing-guide/setup/macos.md
  docs/sidebars.js
Labels: documentation

#3397 [docs] added info in try-tooljet doc
  docs/docs/setup/docker-local.md
Labels: documentation

#3342 [bugfix] Now users can't create multiple versions with the same name for an app
  frontend/src/Editor/AppVersionsManager.jsx
  server/migrations/1655726247638-AddUniqueConstraintToVersionName.ts
  server/src/entities/app_version.entity.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/data_sources.e2e-spec.ts
Labels: bug, backend, run-ci

#3274 Feature : Color Picker Widget
  frontend/assets/images/icons/widgets/colorPicker.svg
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/custom.scss
Labels: run-ci

#3229 Enhancement: Replacing react-select-search library for event managers with react-select library
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci

#3369 Now the table will show the user groups ordered by created time
  server/src/services/group_permissions.service.ts
Labels: bug, backend, run-ci

#3400 [Docs] Adds ESLint setup for ToolJet
  docs/docs/contributing-guide/troubleshooting/eslint.md
  docs/sidebars.js
Labels: documentation

#3351 style: Fix postgres icon
  plugins/packages/postgresql/lib/icon.svg
Labels: run-ci, create-review-app

#3412 [Docs]: Chart widget video
  docs/docs/widgets/chart.md
Labels: documentation, good first issue, up-for-grabs

#3399 Fixed ManageSSO left menu background color in Dark-theme.
  frontend/src/_components/Menu.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, create-review-app

#3281 Feature :: Amazon Athena plugin
  docs/docs/data-sources/athena.md
  docs/sidebars.js
  docs/static/img/datasource-reference/athena/athena-connection.png
  docs/static/img/datasource-reference/athena/athena-query.png
  frontend/package-lock.json
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/athena/.gitignore
  plugins/packages/athena/README.md
  plugins/packages/athena/__tests__/index.js
  plugins/packages/athena/lib/icon.svg
  plugins/packages/athena/lib/index.ts
  plugins/packages/athena/lib/manifest.json
  plugins/packages/athena/lib/operations.json
  plugins/packages/athena/lib/types.ts
  plugins/packages/athena/package-lock.json
  plugins/packages/athena/package.json
  plugins/packages/athena/tsconfig.json
  server/package-lock.json
Labels: run-ci, plugins, tested

#3428 show password checkbox gets enabled only on clicking on the Checkbox
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci

#3214 [Bugfix] Fixed Signup email case sensitive issue
  server/migrations/1654596810662-ConvertAllUserEmailsToLowercaseAndDeleteDuplicateUsers.ts
  server/src/dto/app-authentication.dto.ts
  server/src/dto/invite-new-user.dto.ts
  server/src/dto/user-onboarding.dto.ts
  server/src/helpers/utils.helper.ts
Labels: bug, backend, run-ci

#3300 Password retry limit
  docs/docs/setup/env-vars.md
  docs/docs/user-authentication/password-login.md
  frontend/src/App/App.jsx
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/ManageSSO/Form.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/_services/authentication.service.js
  server/migrations/1655320273619-PasswordPolicyRetryCount.ts
  server/src/controllers/app.controller.ts
  server/src/entities/user.entity.ts
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/users.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/data_queries.e2e-spec.ts
  server/test/controllers/group_permissions.e2e-spec.ts
Labels: backend, run-ci, tested

#3445 [bugfix] ConvertAllUserEmailsToLowercaseAndDeleteDuplicateUsers migration is failing now
  server/migrations/1654596810662-ConvertAllUserEmailsToLowercaseAndDeleteDuplicateUsers.ts
Labels: bug, backend, run-ci
