Repository ToolJet/ToolJet, pull requests merged in 2023-07, with the labels that each got.

#6530 Feature :: Exposing button text in button widget
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested, suspend-review-app, appbuilder

#6452 Exposed the selected cell value in the inspector for Table component
  frontend/src/Editor/Components/Table/Table.jsx
Labels: feature request, run-ci, tested, suspend-review-app

#6852 Avoiding event propagation for cell consisting input element in table to avoid unintentional row selection while editing cell values
  frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app

#6608 Default value for annotation in bounded box widget
  frontend/src/Editor/Components/BoundedBox/BoundedBox.jsx
  frontend/src/Editor/Components/BoundedBox/RenderHighlight.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: tested, suspend-review-app, appbuilder

#6856 Bugfix :: On mobile mode canvas margin color accidentally got changed from previos one
  frontend/src/Editor/Editor.jsx
Labels: run-ci, tested, documented, appbuilder

#6884 adding env changes in cypress workflow
  .github/workflows/cypress.yml
Labels: tested

#6787 Feature :: Form widget with JSON input
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Form.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Form/FormUtils.js
  frontend/src/Editor/Components/StarRating/index.js
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, suspend-review-app, appbuilder

#6863 Updated automation script for table widget with new CSA actions
  cypress-tests/cypress.config.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/table.js
Labels: cypress

#6823 fix: search box placeholder padding
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app, documented

#6676 The position of icon to expand the code editor in new window is fixed
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: tested, documented

#6808 fix: show layout accordion settings by default for custom component widget
  frontend/src/Editor/Inspector/Components/CustomComponent.jsx
Labels: tested, documented

#6635 fix: Calendar popover in dark mode
  frontend/src/Editor/Components/Calendar.jsx
  frontend/src/Editor/Components/CalendarPopover.jsx
Labels: tested, documented

#6825 fix:#6720 text of the name of global datasource listitem overflows
  frontend/src/GlobalDatasources/LIstItem/index.jsx
  frontend/src/_styles/global-datasources.scss
Labels: tested, documented

#6687 add authentication in GraphQL as RestAPI
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/lib/manifest.json
Labels: needs testing, plugins, suspend-review-app

#6824 Improvement - adds ability to resolve workspace variables in GDS connection forms
  frontend/assets/images/icons/tj-info-warning.svg
  frontend/src/Editor/DataSourceManager/SourceComponents/index.js
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Alert/Alert.jsx
  frontend/src/_ui/Input/index.js
  frontend/src/_ui/Textarea/index.js
  server/src/controllers/data_sources.controller.ts
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
Labels: run-ci, tested, suspend-review-app, platform

#6443 improvement - support to add groups when inviting a new user to a workspace
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsersDrawer.jsx
  frontend/src/_services/organization_user.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Multiselect/Multiselect.jsx
Labels: run-ci, tested, suspend-review-app, platform

#6776 [fix] Save button remains in loading state when attempting to update credentials in local DS on released apps
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci, tested, suspend-review-app

#6867 Chore: Add datasources count for telemetry
  server/src/services/metadata.service.ts
Labels: marketplace

#6910 Added automation to CSA actions for components
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/support/utils/events.js
Labels: cypress

#6912 Fixed cypress for v2.9.0 app builder.
  cypress-tests/cypress-app-builder.config.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/datePickerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/multiselectHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/queries.js
Labels: cypress, run-cypress-app-builder, active-review-cypress-app

#6908 fix: appending base URL query params on redirect
  frontend/src/Editor/Viewer.jsx
Labels: tested

#6914 Bugfix :: Annotation not populated when multiple bounded box are dropped to canvas
  frontend/src/Editor/Components/BoundedBox/BoundedBox.jsx
Labels: tested, active-review-app

#6923 Fixed platform test cases for release v2.9.0
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/e2e/authentication/forgotPassword.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: cypress, run-cypress-workspace, active-review-cypress-app

#6926 fix: update componentid inside widget details on duplication of page
  frontend/src/Editor/Editor.jsx
Labels: tested, active-review-app

#6938 [docs] JSON schema for form component
  docs/docs/widgets/form.md
  docs/static/img/widgets/form/basicschema.png
  docs/static/img/widgets/form/button.png
  docs/static/img/widgets/form/checkbox.png
  docs/static/img/widgets/form/datepickerschema.png
  docs/static/img/widgets/form/daterange.png
  docs/static/img/widgets/form/dropdown.png
  docs/static/img/widgets/form/filepicker.png
  docs/static/img/widgets/form/form2.png
  docs/static/img/widgets/form/multiselect.png
  docs/static/img/widgets/form/newprop.png
  docs/static/img/widgets/form/numberinput.png
  docs/static/img/widgets/form/password.png
  docs/static/img/widgets/form/radio.png
  docs/static/img/widgets/form/star.png
  docs/static/img/widgets/form/submitbuttonschema.png
  docs/static/img/widgets/form/text.png
  docs/static/img/widgets/form/textarea.png
  docs/static/img/widgets/form/textinput.png
  docs/static/img/widgets/form/toggle.png
  docs/versioned_docs/version-2.9.0/widgets/form.md
Labels: documentation

#6941 Hotfix - Fix issue with RegExp pattern for server variable validation
  server/src/services/data_queries.service.ts
Labels: run-ci, hotfix, platform

#6958 [docs] NoSQL operations: HarperDB
  docs/docs/marketplace/plugins/harperdb.md
  docs/static/img/marketplace/plugins/harperdb/nosql_delete.png
  docs/static/img/marketplace/plugins/harperdb/nosql_insert.png
  docs/static/img/marketplace/plugins/harperdb/nosql_update.png
  docs/static/img/marketplace/plugins/harperdb/searchbyconditions.png
  docs/static/img/marketplace/plugins/harperdb/searchbyhash.png
  docs/static/img/marketplace/plugins/harperdb/searchbyvalue.png
Labels: documentation

#6895 Increased user session time to 10 days
  .env.example
  server/src/services/session.service.ts
Labels: run-ci, tested, suspend-review-app

#6883 ENABLE_PRIVATE_APP_EMBED: Changed same-site value to none for auth cookie on
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/_helpers/cookie.js
  server/src/services/app_config.service.ts
  server/src/services/auth.service.ts
Labels: run-ci, roadmap, platform

#6762 [Improvements] Environment changes
  frontend/assets/images/info.svg
  frontend/src/Editor/AppVersionsManager/CustomSelect.jsx
  frontend/src/Editor/AppVersionsManager/List.jsx
  frontend/src/Editor/AppVersionsManager/ReleasedVersionError.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_services/app_environment.service.js
  frontend/src/_styles/theme.scss
  server/data-migrations/1686826460358-BackFillAppEnvironmentsPriorityColumn.ts
  server/data-migrations/1686829426671-BackFillCurrentEnvironmentId.ts
  server/migrations/1655726247638-AddUniqueConstraintToVersionName.ts
  server/migrations/1656083459220-tabsWidth.ts
  server/migrations/1686818129241-AddPriorityAndEnabledColumnsToAppEnvironments.ts
  server/migrations/1686829292855-AddCurrentEnvironmentIdToAppVersions.ts
  server/src/controllers/app_environments.controller.ts
  server/src/controllers/apps.controller.ts
  server/src/controllers/global_data_sources.controller.ts
  server/src/dto/data-source.dto.ts
  server/src/dto/version-create.dto.ts
  server/src/dto/version-edit.dto.ts
  server/src/entities/app_environments.entity.ts
  server/src/entities/app_version.entity.ts
  server/src/helpers/utils.helper.ts
  server/src/services/app_environments.service.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/data_sources.service.ts
  server/src/services/seeds.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/folders.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
  server/test/test.helper.ts
Labels: run-ci, tested, suspend-review-app, platform, run-cypress-workspace, suspend-review-cypress-app

#6982 platform-v1.1 - fixes: iframe link is only rendered
  frontend/src/Editor/ManageAppUsers.jsx
Labels: run-ci, tested, active-review-app

#6983 Dynamic page height
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_styles/theme.scss
Labels: tested, product approved

#6980 Added cypress test for GDS user privileges
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/dataSource.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/dataSource.js
  cypress-tests/cypress/e2e/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/postgreSql.js
Labels: cypress, run-cypress-workspace, active-review-cypress-app

#6999 Fixes app crash with modal component
  .version
  frontend/src/Editor/Components/Modal.jsx
  server/.version
Labels: tested, active-review-app

#6993 Fixed cypress for app builder on Platform v1.1
  cypress-tests/cypress/constants/texts/version.js
  cypress-tests/cypress/e2e/editor/app-version/version.cy.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/e2e/exportImport/export.cy.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/inspector.js
  cypress-tests/cypress/support/utils/version.js
Labels: cypress, run-cypress-app-builder, active-review-cypress-app

#7013 Added data-cy for user invite form
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
Labels: run-ci, data-cy, cypress

#6960 Hotfix: Setup local static assets
  .version
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-100.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-100italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-200.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-200italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-300.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-300italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-500.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-500italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-600.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-600italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-700.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-700italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-italic.woff2
  frontend/assets/fonts/ibm-plex-sans-v19-latin/ibm-plex-sans-v19-latin-regular.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-100.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-200.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-300.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-500.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-600.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-700.woff2
  frontend/assets/fonts/inter-v12-latin/inter-v12-latin-regular.woff2
  frontend/assets/fonts/roboto-v30-latin/roboto-v30-latin-100.woff2
  frontend/assets/fonts/roboto-v30-latin/roboto-v30-latin-300.woff2
  frontend/assets/fonts/roboto-v30-latin/roboto-v30-latin-500.woff2
  frontend/assets/fonts/roboto-v30-latin/roboto-v30-latin-regular.woff2
  frontend/assets/fonts/source-code-pro-v22-latin/source-code-pro-v22-latin-regular.woff2
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/tabler.scss
  frontend/src/_styles/theme.scss
  frontend/src/index.ejs
  server/.version
Labels: tested, hotfix, suspend-review-app

#6875 Feature/dynamodb plugin update item
  plugins/packages/dynamodb/lib/index.ts
  plugins/packages/dynamodb/lib/operations.json
  plugins/packages/dynamodb/lib/operations.ts
  plugins/packages/dynamodb/lib/types.ts
Labels: needs testing, run-ci, active-review-app, documented

#6870 Bug/postgres gui bulkupdate null issue
  plugins/packages/postgresql/lib/index.ts
Labels: run-ci, tested, active-review-app

#7011 Added cypress test for user onboarding with user groups
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageGroups.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/dataSource.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageUsers.js
Labels: cypress, run-cypress-workspace, suspend-review-cypress-app

#7026 Hot fix : custom filters not getting applied in the table
  .version
  frontend/src/Editor/Components/Table/custom-filter.js
  server/.version
Labels: run-ci, tested, hotfix, run-cypress-app-builder, suspend-review-cypress-app, Table component

#7034 [docs] globals update(ee)
  docs/docs/how-to/use-inspector.md
  docs/static/img/how-to/use-inspector/env.png
  docs/versioned_docs/version-2.10.0/how-to/use-inspector.md
Labels: documentation

#6646 Move showComments and currentLayout to zustand store
  frontend/src/Editor/AppVersionsManager/CreateVersionModal.jsx
  frontend/src/Editor/BoxDragPreview.jsx
  frontend/src/Editor/CommentNotifications/index.jsx
  frontend/src/Editor/Comments.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/CustomDragLayer.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/HeaderActions.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/Editor/WidgetManager.jsx
  frontend/src/_stores/editorStore.js
Labels: run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app, product approved

#6994 Fix :: update position of debugger in left sidebar
  frontend/src/Editor/LeftSidebar/index.jsx
Labels: run-ci, tested, suspend-review-app, documented, appbuilder, product approved

#6907 Fixed widget position calculation on resize
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci, tested, run-cypress-app-builder, suspend-review-cypress-app, product approved

#6489 Add support for one level of nested data in the table component
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/autogenerateColumns.js
Labels: run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app, product approved

#6812 Move the entire current state to Zustand store
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/KanbanBoard/KanbanBoard.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Inspector/ActionConfigurationPanels/GotoApp.jsx
  frontend/src/Editor/Inspector/ActionConfigurationPanels/SwitchPage.jsx
  frontend/src/Editor/Inspector/Components/CustomComponent.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/SettingsModal.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/Components/Transformation.jsx
  frontend/src/Editor/QueryManager/QueryEditors/GRPC.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabHeaders.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabParams.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/Tabs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runpy.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_stores/currentStateStore.js
  frontend/src/_ui/HttpHeaders/QueryEditor.jsx
Labels: run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app, product approved

#7032 Fixed left sidebar inspector gets blurred when query panel is opened
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
Labels: tested, suspend-review-app, documented, appbuilder, product approved

#5398 [plugin] Datasource plugin for Azure blob storage
  docs/docs/data-sources/azureblobstorage.md
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/azureblobstorage/.gitignore
  plugins/packages/azureblobstorage/README.md
  plugins/packages/azureblobstorage/__tests__/index.js
  plugins/packages/azureblobstorage/lib/icon.svg
  plugins/packages/azureblobstorage/lib/index.ts
  plugins/packages/azureblobstorage/lib/manifest.json
  plugins/packages/azureblobstorage/lib/operations.json
  plugins/packages/azureblobstorage/lib/operations.ts
  plugins/packages/azureblobstorage/lib/types.ts
  plugins/packages/azureblobstorage/package-lock.json
  plugins/packages/azureblobstorage/package.json
  plugins/packages/azureblobstorage/tsconfig.json
Labels: draft, plugins, tested, suspend-review-app, documented

#6903 Feature :: Restrict certain components from being added onto certain container-components
  frontend/src/Editor/Components/Calendar.jsx
  frontend/src/Editor/Components/CalendarPopover.jsx
  frontend/src/Editor/Components/Kanban/Components/Item.jsx
  frontend/src/Editor/Components/Kanban/Components/Modal.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/restrictedWidgetsConfig.js
Labels: run-ci, tested, needs documentation, documented, appbuilder, run-cypress-app-builder, suspend-review-cypress-app, product approved

#6961 Feature added to introduce Link column type in table
  frontend/src/Editor/Components/Table/Link.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
Labels: feature request, run-ci, tested, active-review-app, documented, product approved

#7033 Parameters support on RunJS
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
  frontend/src/Editor/Components/CustomComponent/iframe.html
  frontend/src/Editor/Inspector/ActionConfigurationPanels/RunjsParamters.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterDetails.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterForm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterList.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/Runjs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  frontend/src/Editor/QueryManager/constants.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/colors.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/bulkIcons/Remove.jsx
  frontend/src/_ui/Icon/solidIcons/PlusRectangle.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
Labels: tested, suspend-review-app, product approved

#7057 [docs] licensing
  docs/docs/licensing.md
  docs/sidebars.js
  docs/static/img/licensing/licensingpage1.png
  docs/static/img/licensing/licensingpage2.png
  docs/static/img/licensing/licensingpage3.png
  docs/static/img/licensing/licensingpage4.png
  docs/versioned_docs/version-2.10.0/licensing.md
  docs/versioned_sidebars/version-2.10.0-sidebars.json
Labels: documentation

#7068 Fix failing specs on app builder 1.2
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/dataSource.js
Labels: cypress

#6619 Default row selection in table on page reload
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: feature request, run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app, product approved

#6665 Using tab to navigate through editable cells on the table
  frontend/src/Editor/Components/Table/Datepicker.jsx
  frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
  frontend/src/Editor/Components/Table/Tags.jsx
  frontend/src/_styles/theme.scss
Labels: bug, run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app, product approved

#7006 Remove redirection to homepage and make page accessible on accessing hidden pages via actions & URL
  frontend/src/Editor/Viewer.jsx
Labels: run-ci, tested, suspend-review-app, documented, appbuilder, product approved

#6667 fix: datepicker time text colour
  frontend/src/Editor/Components/Datepicker.jsx
Labels: tested, documented, product approved

#6809 Issue : Adding support to generate PDF file using generate file action
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_lib/generate-file.js
Labels: run-ci, tested, suspend-review-app, documented, product approved

#6696 Fixed Chart layout accordion issue
  frontend/src/Editor/Inspector/Components/Chart.jsx
Labels: tested, documented

#6633 fix: Popup for request confirmation dark mode in viewer mode
  frontend/src/Editor/Viewer.jsx
Labels: tested, documented

#6575 fix: Dashboard naming inconsistency for Edit folder link and popup
  frontend/src/HomePage/Folders.jsx
Labels: tested, suspend-review-app

#5324 [Improvement] Auth flow improvements for RestAPI, OpenAPI & GraphQL
  frontend/package-lock.json
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/OpenAPI/Oauth.jsx
  frontend/src/_ui/OpenAPI/OpenapiAuth.jsx
  frontend/src/_ui/OpenAPI/index.js
  plugins/package-lock.json
  plugins/packages/common/lib/index.ts
  plugins/packages/common/lib/oauth.ts
  plugins/packages/common/lib/query_result.type.ts
  plugins/packages/common/lib/utils.helper.ts
  plugins/packages/common/package-lock.json
  plugins/packages/common/package.json
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/lib/manifest.json
  plugins/packages/openapi/lib/index.ts
  plugins/packages/openapi/lib/manifest.json
  plugins/packages/openapi/package-lock.json
  plugins/packages/openapi/package.json
  plugins/packages/restapi/lib/index.ts
  server/src/services/data_queries.service.ts
Labels: run-ci, plugins, tested, active-review-app, documented

#7084 [docs] badge updates in paid features' docs
  docs/docs/Enterprise/audit_logs.md
  docs/docs/Enterprise/superadmin.md
  docs/docs/Enterprise/white-label.md
  docs/docs/copilot.md
  docs/docs/licensing.md
  docs/docs/release-management/multi-env.md
  docs/docs/user-authentication/sso/openid/setup.md
  docs/versioned_docs/version-2.10.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.10.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.10.0/Enterprise/white-label.md
  docs/versioned_docs/version-2.10.0/copilot.md
  docs/versioned_docs/version-2.10.0/licensing.md
  docs/versioned_docs/version-2.10.0/release-management/multi-env.md
  docs/versioned_docs/version-2.10.0/user-authentication/sso/openid/setup.md
Labels: documentation

#7110 [docs]fix broken link for topbar in overview of app-builder
  docs/docs/app-builder/overview.md
  docs/versioned_docs/version-2.0.0/app-builder/overview.md
  docs/versioned_docs/version-2.1.0/app-builder/overview.md
  docs/versioned_docs/version-2.10.0/app-builder/overview.md
  docs/versioned_docs/version-2.2.0/app-builder/overview.md
  docs/versioned_docs/version-2.3.0/app-builder/overview.md
  docs/versioned_docs/version-2.4.0/app-builder/overview.md
  docs/versioned_docs/version-2.5.0/app-builder/overview.md
  docs/versioned_docs/version-2.6.0/app-builder/overview.md
  docs/versioned_docs/version-2.8.0/app-builder/overview.md
  docs/versioned_docs/version-2.9.0/app-builder/overview.md
  docs/versioned_docs/version-2.9.4/app-builder/overview.md
Labels: documentation

#7048 Changes in cypress workflow to run it parallel
  .github/workflows/cypress.yml
Labels: tested

#6904 Remove validation for last name of users, Resolved: update user details bug
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/SettingsPage/SettingsPage.jsx
  server/src/dto/user.dto.ts
Labels: run-ci, tested, suspend-review-app

#5679 Upgraded preview email package
  server/package-lock.json
  server/package.json
Labels: run-ci

#7081 HOTFIX: Dropzone Filepicker issue for bulk upload
  frontend/src/ManageOrgUsers/FileDropzone.jsx
Labels: run-ci, tested, active-review-cypress-app

#7055 [improvement] Redirection to workspace URL on logout
  frontend/src/_services/authentication.service.js
Labels: run-ci, tested

#7113 [BugFix] Fix dynamic form breaking in case "react-component-headers" form type outside of the editor
  frontend/src/Editor/Editor.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_stores/editorStore.js
Labels: tested

#7105 style: position parameter popup inside query editor
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterDetails.jsx
Labels: tested

#7112 [fix] Crashing the app when we try to change the dropdown of create version
  frontend/src/Editor/AppVersionsManager/List.jsx
  server/src/controllers/app_environments.controller.ts
Labels: run-ci, tested

#7083 Bugfix :: Box shadow not getting applied for datepicker widget
  frontend/src/Editor/Components/Datepicker.jsx
Labels: run-ci, tested, active-review-app, suspend-review-app

#7043 [hotfix] App isn't redirecting to the the home page if the user doesn't have access to the app but the user is already authenticated to the same workspace
  frontend/src/AppLoader/AppLoader.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/utils.js
Labels: run-ci, tested, run-cypress-app-builder, suspend-review-cypress-app

#7085 fix: round element width to multiple of gridwidth
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: tested

#7109 fix: delay before save fn to wait for input blur
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/Runjs.jsx
Labels: tested

#7104 Fixed platform cypress test case for release v2.10.3
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/postgreSql.js
Labels: cypress, run-cypress-workspace, active-review-cypress-app

#7121 Support for backward compatibility for nested data in the table
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/autogenerateColumns.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested

#7118 Fixed cypress App Builder for v2.10.3
  .version
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/queries.js
  server/.version
Labels: cypress, run-cypress-app-builder, active-review-cypress-app

#6957 Hotfix - fixes: server vars resolver client-side
  frontend/src/_helpers/utils.js
Labels: run-ci, tested

#7151 [docs] Custom styles
  docs/docs/app-builder/customcss.md
  docs/sidebars.js
  docs/static/img/v2-beta/app-builder/customcss/customcss.gif
  docs/static/img/v2-beta/app-builder/customcss/selectors.png
  docs/static/img/v2-beta/app-builder/customcss/settings.png
  docs/static/img/v2-beta/app-builder/customcss/styledapp.gif
  docs/versioned_docs/version-2.10.0/app-builder/customcss.md
  docs/versioned_docs/version-2.11.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.11.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.11.0/Enterprise/white-label.md
  docs/versioned_docs/version-2.11.0/app-builder/customcss.md
  docs/versioned_docs/version-2.11.0/copilot.md
  docs/versioned_docs/version-2.11.0/licensing.md
  docs/versioned_docs/version-2.11.0/release-management/multi-env.md
  docs/versioned_docs/version-2.11.0/user-authentication/sso/openid/setup.md
  docs/versioned_docs/version-2.8.0/app-builder/customcss.md
  docs/versioned_docs/version-2.9.0/app-builder/customcss.md
  docs/versioned_docs/version-2.9.4/app-builder/customcss.md
  docs/versioned_sidebars/version-2.10.0-sidebars.json
  docs/versioned_sidebars/version-2.11.0-sidebars.json
  docs/versioned_sidebars/version-2.8.0-sidebars.json
  docs/versioned_sidebars/version-2.9.0-sidebars.json
  docs/versioned_sidebars/version-2.9.4-sidebars.json
Labels: documentation

#7152 [docs]SSO:LDAP
  docs/docs/user-authentication/sso/ldap.md
  docs/sidebars.js
  docs/static/img/sso/ldap/disabled.png
  docs/static/img/sso/ldap/fields.png
  docs/static/img/sso/ldap/firstlogin.gif
  docs/static/img/sso/ldap/login.png
  docs/static/img/sso/ldap/settings.png
  docs/static/img/sso/ldap/url.png
  docs/versioned_docs/version-2.11.0/user-authentication/sso/ldap.md
  docs/versioned_sidebars/version-2.11.0-sidebars.json
Labels: documentation

#7159 [docs] Share (app builder)
  docs/docs/app-builder/share.md
  docs/sidebars.js
  docs/static/img/v2-beta/app-builder/share/edit.png
  docs/static/img/v2-beta/app-builder/share/embeddtj.gif
  docs/static/img/v2-beta/app-builder/share/modal.png
  docs/static/img/v2-beta/app-builder/share/shareon.png
  docs/versioned_docs/version-2.10.0/app-builder/share.md
  docs/versioned_docs/version-2.11.0/app-builder/share.md
  docs/versioned_docs/version-2.8.0/app-builder/share.md
  docs/versioned_docs/version-2.9.0/app-builder/share.md
  docs/versioned_docs/version-2.9.4/app-builder/share.md
  docs/versioned_sidebars/version-2.10.0-sidebars.json
  docs/versioned_sidebars/version-2.11.0-sidebars.json
  docs/versioned_sidebars/version-2.8.0-sidebars.json
  docs/versioned_sidebars/version-2.9.0-sidebars.json
  docs/versioned_sidebars/version-2.9.4-sidebars.json
Labels: documentation

#7102 Bug fixed table component crashes while clicking on "Add New Row" button while there no table data
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: bug, run-ci, tested, Table component

#7154 Fixed cypress test for workspace redirection
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/dataSource.js
Labels: cypress, run-cypress-workspace

#7165 [fix] Local datasource is crashing for cloned apps.
  .github/workflows/cypress.yml
  frontend/src/_components/DynamicForm.jsx
Labels: run-ci, tested, active-review-app
