Repository ToolJet/ToolJet, pull requests merged in 2023-04, with the labels that each got.

#5848 Modified cypress test for onboarding phone number feature
  cypress-tests/cypress/e2e/selfHost/selfHostSignUp.cy.js
  cypress-tests/cypress/support/utils/onboarding.js
Labels: documented

#5890 Added automation for edit row feature in Database
  cypress-tests/cypress/constants/selectors/database.js
  cypress-tests/cypress/constants/texts/database.js
  cypress-tests/cypress/e2e/database/database.cy.js
  cypress-tests/cypress/support/utils/database.js
Labels: testcase

#5919 [docs] how-to: run multiple actions using runjs
  docs/docs/how-to/run-action-from-runjs.md
  docs/docs/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-1.x.x/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-1.x.x/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-2.0.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.0.0/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-2.1.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.1.0/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-2.2.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.2.0/how-to/run-query-at-specified-intervals.md
Labels: documentation

#5927 [docs] updated how-tos in 2.3 docs
  docs/docs/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.3.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.3.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.3.0/how-to/run-query-at-specified-intervals.md
  docs/versioned_sidebars/version-2.3.0-sidebars.json
Labels: documentation

#5938 [docs] updated slack url in the entire docs
  docs/docs/contributing-guide/setup/docker.md
  docs/docs/data-sources/custom-js.md
  docs/docs/setup/index.md
  docs/docs/setup/v2-migration.md
  docs/docs/tooljet_database.md
  docs/docusaurus.config.js
  docs/versioned_docs/version-1.x.x/contributing-guide/setup/docker.md
  docs/versioned_docs/version-1.x.x/data-sources/custom-js.md
  docs/versioned_docs/version-1.x.x/intro.md
  docs/versioned_docs/version-1.x.x/setup/index.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.0.0/data-sources/custom-js.md
  docs/versioned_docs/version-2.0.0/setup/docker.md
  docs/versioned_docs/version-2.0.0/setup/index.md
  docs/versioned_docs/version-2.0.0/setup/v2-migration.md
  docs/versioned_docs/version-2.0.0/tooljet_database.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.1.0/data-sources/custom-js.md
  docs/versioned_docs/version-2.1.0/setup/docker.md
  docs/versioned_docs/version-2.1.0/setup/index.md
  docs/versioned_docs/version-2.1.0/setup/v2-migration.md
  docs/versioned_docs/version-2.1.0/tooljet_database.md
  docs/versioned_docs/version-2.2.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.2.0/data-sources/custom-js.md
  docs/versioned_docs/version-2.2.0/setup/docker.md
  docs/versioned_docs/version-2.2.0/setup/index.md
  docs/versioned_docs/version-2.2.0/setup/v2-migration.md
  docs/versioned_docs/version-2.2.0/tooljet_database.md
  docs/versioned_docs/version-2.3.0/contributing-guide/l10n.md
  docs/versioned_docs/version-2.3.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.3.0/data-sources/custom-js.md
  docs/versioned_docs/version-2.3.0/setup/docker.md
  docs/versioned_docs/version-2.3.0/setup/index.md
  docs/versioned_docs/version-2.3.0/setup/v2-migration.md
  docs/versioned_docs/version-2.3.0/tooljet_database.md
Labels: documentation

#5937 [README] updated Slack Community URL
  .github/ISSUE_TEMPLATE/03_documentation_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
  docs/README.md
Labels: documentation

#5936 Bugfix :: Fix for connection getting lost in snowflake
  plugins/packages/snowflake/lib/index.ts
Labels: active-review-app, documented

#5948 API Support for getting data source options under a datasource
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/LIstItem/index.jsx
  frontend/src/GlobalDatasources/index.jsx
  frontend/src/_services/app_environment.service.js
  frontend/src/_services/globalDatasource.service.js
  frontend/src/_services/index.js
  server/src/controllers/app_environments.controller.ts
  server/src/controllers/global_data_sources.controller.ts
  server/src/modules/app_environments/app_environments.module.ts
  server/src/modules/casl/abilities/global-datasource-ability.factory.ts
Labels: run-ci, tested, suspend-review-app

#5957 Fixes app import on different workspace
  frontend/src/_services/dataquery.service.js
  server/src/services/app_import_export.service.ts
Labels: tested

#5962 [fix] Auth token cookies conflict issue (yjs and session cookies)
  server/src/modules/auth/authorize-workspace-guard.ts
  server/src/modules/auth/jwt.strategy.ts
  server/src/modules/auth/organization-auth.guard.ts
  server/src/modules/auth/session-auth-guard.ts
  server/src/services/auth.service.ts
  server/src/services/session.service.ts
  server/test/controllers/app.e2e-spec.ts
Labels: run-ci

#5904 Improvement - handle resolved data structures from pyproxies
  frontend/src/_helpers/appUtils.js
Labels: tested, active-review-app, documented

#5974 Added data-cy to fix cypress specs on v2.3.1
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
Labels: data-cy

#5930 Fixed the typo in event handler screen in page menu
  cypress-tests/cypress/constants/texts/multipage.js
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/SettingsModal.jsx
Labels: run-ci, tested, documented

#5971 Fixes query duplication on import on apps having multiple versions
  server/src/services/app_import_export.service.ts
Labels: tested, active-review-app, documented

#5988 [chore] Eslint fixes
  .eslintignore
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/MarketplacePage/index.jsx
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
  marketplace/.eslintrc
  marketplace/.eslintrc.js
  marketplace/.gitignore
  marketplace/plugins/github/lib/index.ts
  marketplace/plugins/github/lib/query_operations.ts
  marketplace/plugins/github/lib/types.ts
  marketplace/plugins/openai/lib/query_operations.ts
  marketplace/plugins/plivo/lib/index.ts
  marketplace/plugins/plivo/lib/types.ts
  marketplace/scripts/upload-to-s3.js
  marketplace/tsconfig.json
  plugins/.eslintignore
  plugins/.eslintrc.js
Labels: run-ci, documented

#5877 Adding scroll for container widget
  docs/docs/widgets/container.md
  docs/static/img/widgets/container/container.png
  docs/static/img/widgets/container/scrollcontainer.png
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_styles/theme.scss
Labels: tested, active-review-app, documented

#5996 [docs] update user session expiry env var
  docs/docs/setup/env-vars.md
  docs/versioned_docs/version-2.4.0/setup/env-vars.md
Labels: documentation

#6015 Added data-cy for modal components
  frontend/src/Editor/Components/Modal.jsx
Labels: data-cy

#6001 Added automation for modal component
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/modal.js
Labels: testcase

#5753 Fix: Tooljet database filter conditions using same column
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
Labels: bug, run-ci, tested, active-review-app, documented

#6022 Fix for Authorize Oauth API not accessible for user with app read permission
  server/src/controllers/data_sources.controller.ts
Labels: tested

#5976 [docs] how-to: intentionally fail a RunJS query
  docs/docs/how-to/intentionally-fail-js-query.md
  docs/sidebars.js
  docs/static/img/how-to/failjs/failjs.gif
  docs/versioned_docs/version-1.x.x/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.0.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.1.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.2.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.3.0/how-to/intentionally-fail-js-query.md
  docs/versioned_sidebars/version-1.x.x-sidebars.json
  docs/versioned_sidebars/version-2.0.0-sidebars.json
  docs/versioned_sidebars/version-2.1.0-sidebars.json
  docs/versioned_sidebars/version-2.2.0-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
Labels: documentation

#5965 [doc] global datasources
  docs/docs/Enterprise/superadmin.md
  docs/docs/data-sources/overview.md
  docs/docs/getting-started.md
  docs/docs/org-management/permissions.md
  docs/docs/tutorial/manage-users-groups.md
  docs/static/img/datasource-reference/overview/changescope.png
  docs/static/img/datasource-reference/overview/connection.png
  docs/static/img/datasource-reference/overview/create.png
  docs/static/img/datasource-reference/overview/default.png
  docs/static/img/datasource-reference/overview/edit.png
  docs/static/img/datasource-reference/overview/error.png
  docs/static/img/datasource-reference/overview/global.png
  docs/static/img/datasource-reference/overview/globalquery.png
  docs/static/img/datasource-reference/overview/leftsidebar.png
  docs/static/img/datasource-reference/overview/popup.png
  docs/static/img/datasource-reference/overview/queryadd.png
  docs/static/img/datasource-reference/overview/switch.png
  docs/static/img/datasource-reference/overview/view.png
  docs/static/img/tutorial/manage-users-groups/dspermission.png
  docs/static/img/tutorial/manage-users-groups/gdspermission.png
  docs/versioned_docs/version-2.0.0/getting-started.md
  docs/versioned_docs/version-2.1.0/getting-started.md
  docs/versioned_docs/version-2.2.0/getting-started.md
  docs/versioned_docs/version-2.3.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.3.0/data-sources/overview.md
  docs/versioned_docs/version-2.3.0/org-management/permissions.md
  docs/versioned_docs/version-2.3.0/tutorial/manage-users-groups.md
Labels: documentation

#5917 [docs] how-to: use s3 pre-signed url to upload docs
  docs/docs/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/sidebars.js
  docs/static/img/how-to/uses3presignedurl/copysigned.png
  docs/static/img/how-to/uses3presignedurl/dropdown.png
  docs/static/img/how-to/uses3presignedurl/eventhandlerrunjs2.png
  docs/static/img/how-to/uses3presignedurl/eventhandlerupload.png
  docs/static/img/how-to/uses3presignedurl/fetchfiles.png
  docs/static/img/how-to/uses3presignedurl/getbuckets.png
  docs/static/img/how-to/uses3presignedurl/newversion.png
  docs/static/img/how-to/uses3presignedurl/runjs1.png
  docs/static/img/how-to/uses3presignedurl/runjs2.png
  docs/static/img/how-to/uses3presignedurl/s3connect.png
  docs/static/img/how-to/uses3presignedurl/template.png
  docs/static/img/how-to/uses3presignedurl/upload.png
  docs/static/img/how-to/uses3presignedurl/uploadbutton.png
  docs/versioned_docs/version-1.x.x/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/versioned_docs/version-2.0.0/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/versioned_docs/version-2.1.0/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/versioned_docs/version-2.2.0/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/versioned_sidebars/version-1.x.x-sidebars.json
  docs/versioned_sidebars/version-2.0.0-sidebars.json
  docs/versioned_sidebars/version-2.1.0-sidebars.json
  docs/versioned_sidebars/version-2.2.0-sidebars.json
Labels: documentation

#6035 Remove oauth token data from app export
  server/src/services/app_import_export.service.ts
  server/test/controllers/data_sources.e2e-spec.ts
Labels: run-ci, tested

#6040 Fixed issue on running app load queries multiple time for the released app
  frontend/src/App/App.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_services/authentication.service.js
Labels: tested

#5970 CI (workflows): bump actions version, fix Node deprecation warning
  .github/workflows/ci.yml
  .github/workflows/cypress.yml
  .github/workflows/packer-build.yml
Labels: run-ci, active-review-app, run-cypress

#6043 Fixes app import on CE when exported from cloud (GDS)
  server/src/services/app_import_export.service.ts
Labels: tested, active-review-app

#6042 Release v2.4.4
  .version
  server/.version
  server/src/services/app_import_export.service.ts
Labels: run-ci

#6034 Release v2.4.5
  .version
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  server/.version
Labels: tested, active-review-app

#6048 [docs] updates in version 2.4.0
  docs/versioned_docs/version-2.3.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.3.0/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/versioned_docs/version-2.3.0/tutorial/manage-users-groups.md
  docs/versioned_docs/version-2.4.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.4.0/contributing-guide/troubleshooting/eslint.md
  docs/versioned_docs/version-2.4.0/data-sources/overview.md
  docs/versioned_docs/version-2.4.0/getting-started.md
  docs/versioned_docs/version-2.4.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.4.0/how-to/use-s3-presigned-url-to-upload-docs.md
  docs/versioned_docs/version-2.4.0/org-management/permissions.md
  docs/versioned_docs/version-2.4.0/tutorial/manage-users-groups.md
  docs/versioned_sidebars/version-1.x.x-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
  docs/yarn.lock
Labels: documentation

#6050 Fixed running subsequent actions in runjs
  .version
  frontend/src/_helpers/appUtils.js
  server/.version
Labels: tested, active-review-app

#6051 Fixed running subsequent actions in runjs (#6050)
  .version
  frontend/src/_helpers/appUtils.js
  server/.version
Labels: run-ci

#6054 Make FE to run on React 17 instead of 18
  frontend/src/_helpers/appUtils.js
  frontend/src/index.jsx
Labels: run-ci, tested, active-review-app

#6055 Added date sorting on table widget
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_styles/custom.scss
Labels: run-ci, tested

#6058 fix :: Line height dropdown
  frontend/src/Editor/Components/DropDown.jsx
Labels: run-ci, tested

#5861 Adding secrets to cypress workflow
  .github/workflows/cypress.yml
Labels: active-review-app, run-cypress

#5881 Fix :: Queryname not updating in header while editing in sidebar and saving
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci, tested, documented

#5883 Anchor tag placed with target="_blank" not opened in new tab in HTML viewer widget
  frontend/src/Editor/Components/Html.jsx
Labels: run-ci, tested, documented

#5954 Added feature to add new rows in the table
  docs/docs/widgets/table.md
  docs/static/img/widgets/table/ui.png
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Components/Table/reducer.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/theme.scss
Labels: feature request, run-ci, tested, active-review-app, documented

#6099 Fix failing cypress specs.
  cypress-tests/cypress.config.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/support/utils/commonWidget.js
Labels: tested, active-review-app, run-cypress

#6019 Fixed logout event issue on editor
  frontend/src/_helpers/appUtils.js
  frontend/src/_services/authentication.service.js
Labels: run-ci, tested, documented

#6109 Modified failing manage users cypress spec
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/manageUsers.js
  cypress-tests/cypress/e2e/authentication/signUp.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageUsers.cy.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageUsers.js
Labels: cypress

#6106 Fixes crashing range slider component
  frontend/src/Editor/Components/RangeSlider.jsx
Labels: run-ci, tested, active-review-app, documented

#6123 Update automation script for export, import and version functionality
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/exportImport.js
  cypress-tests/cypress/e2e/editor/app-version/version.cy.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/version.js
Labels: cypress

#6110 Modified data-cy for manage users page
  frontend/ee/components/UsersPage/UsersFilter.jsx
  frontend/ee/components/UsersPage/UsersTable.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageOrgUsers/FileDropzone.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/Pagination.jsx
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/FolderList/FolderList.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: data-cy, cypress

#6157 Fixed failing specs on v2.5.0
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/support/utils/modal.js
Labels: testcase

#6119 Fixes bug on table date column sort
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: run-ci, tested, documented

#6161 Fix :: Filepicker allowing all types even after providing accepted file types
  frontend/src/Editor/Components/FilePicker.jsx
Labels: tested, documented

#6113 Bugfixes :: Redesign bugs
  frontend/ee/components/UsersPage/UsersFilter.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, documented

#6124 Fix :: Modal firing onOpen event more than once
  frontend/src/Editor/Components/Modal.jsx
Labels: run-ci, tested, documented

#6005 Fixed typo in app builder empty canvas text
  frontend/src/Editor/Container.jsx
  frontend/src/_helpers/createWalkThrough.js
Labels: run-ci, tested, active-review-app, documented

#6172 Fixed and modified manage sso cypress spec
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js
  cypress-tests/cypress/support/utils/manageSSO.js
Labels: cypress

#6173 Added data-cy for manage sso page
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/ManageSSO/ManageSSO.jsx
  frontend/src/_components/OrganizationManager/CustomSelect.jsx
  frontend/src/_ui/Icon/solidIcons/Copy.jsx
  frontend/src/_ui/Icon/solidIcons/Plus.jsx
  frontend/src/_ui/Toggle/index.js
Labels: data-cy, cypress

#6179 [fix] Error when accessing the app preview with slug instead of app id
  server/src/services/users.service.ts
Labels: tested

#6149 [fix] camel paths are converted with underscore while populating the OpenAPI plugin operations field causing internal server error & crashing OpenAPI queries when the user changes the datasource
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  server/src/controllers/global_data_sources.controller.ts
Labels: tested

#6126 Feature: Tjdb for public apps
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_services/tooljetDatabase.service.js
  server/src/controllers/tooljet_db.controller.ts
  server/src/modules/casl/abilities/tooljet-db-ability.factory.ts
  server/src/modules/casl/tooljet-db.guard.ts
  server/src/services/postgrest_proxy.service.ts
Labels: run-ci, tested, active-review-app

#6143 fix:Change cursor to poiner on hover of Global settings toggle option…
  frontend/src/_ui/Toggle/Toggle.scss
Labels: tested, documented

#6129 changed the default cursor to pointer in the page menu option for iss…
  frontend/src/_ui/LeftSidebar/Header.jsx
Labels: tested, documented

#6087 Change the text of CTA for first application
  cypress-tests/cypress/constants/texts/dashboard.js
  docs/docs/getting-started.md
  docs/versioned_docs/version-2.0.0/getting-started.md
  docs/versioned_docs/version-2.1.0/getting-started.md
  docs/versioned_docs/version-2.2.0/getting-started.md
  docs/versioned_docs/version-2.3.0/getting-started.md
  docs/versioned_docs/version-2.4.0/getting-started.md
  frontend/src/HomePage/BlankPage.jsx
Labels: run-ci, tested, suspend-review-app, documented

#6069 Fix: replaced this by page name
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
Labels: run-ci, tested, suspend-review-app, documented

#5696 fixes cursor default to pointer
  frontend/src/Editor/Components/Icon.jsx
  frontend/src/_styles/theme.scss
Labels: tested, documented
