Repository ToolJet/ToolJet, pull requests merged in 2023-02, with the labels that each got.

#5464 [chore] eslint fixes
  frontend/src/Editor/AppVersionsManager/CustomSelect.jsx
  frontend/src/Editor/AppVersionsManager/EditVersionModal.jsx
  frontend/src/Editor/AppVersionsManager/List.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/Toggle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/_components/AppButton.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/OrganizationManager/CustomSelect.jsx
  frontend/src/_components/SortableList/SortableList.jsx
  frontend/src/_services/authentication.service.js
  frontend/src/_ui/Avatar/index.jsx
  frontend/src/_ui/IndeterminateCheckbox/index.jsx
  frontend/src/_ui/Select/styles.js
Labels: run-ci

#5430 [doc] added pages actions
  docs/static/img/actions/page/set-page-var.png
  docs/static/img/actions/page/switch-page.png
  docs/static/img/actions/page/unset-page-var.png
  docs/versioned_docs/version-2.0.0-beta/actions/set-page-var.md
  docs/versioned_docs/version-2.0.0-beta/actions/switch-page.md
  docs/versioned_docs/version-2.0.0-beta/actions/unset-page-var.md
  docs/versioned_docs/version-2.0.0-beta/tutorial/pages.md
  docs/versioned_sidebars/version-2.0.0-beta-sidebars.json
Labels: documentation

#5456 Update dto API completed
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
  server/src/controllers/organizations.controller.ts
  server/src/dto/organization-create.dto.ts
  server/src/dto/organization.dto.ts
Labels: run-ci, tested

#5393 [Feature]: Update Node from 14 to 18
  .github/workflows/ci.yml
  .github/workflows/packer-build.yml
  deploy/ec2/setup_app
  deploy/ec2/setup_machine.sh
  deploy/ec2/tooljet_ubuntu_focal.pkr.hcl
  docker/client.Dockerfile.dev
  docker/plugins.Dockerfile.dev
  docker/preview.Dockerfile
  docker/production.Dockerfile
  docker/server.Dockerfile
  docker/server.Dockerfile.dev
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/Editor/SubContainer.jsx
  package-lock.json
  package.json
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/airtable/package.json
  plugins/packages/amazonses/package.json
  plugins/packages/appwrite/package.json
  plugins/packages/athena/package.json
  plugins/packages/baserow/package.json
  plugins/packages/bigquery/package.json
  plugins/packages/clickhouse/package.json
  plugins/packages/cosmosdb/package.json
  plugins/packages/dynamodb/package.json
  plugins/packages/elasticsearch/package.json
  plugins/packages/firestore/package.json
  plugins/packages/gcs/package.json
  plugins/packages/googlesheets/package.json
  plugins/packages/graphql/package.json
  plugins/packages/mailgun/package.json
  plugins/packages/mariadb/package.json
  plugins/packages/minio/package.json
  plugins/packages/mongodb/package.json
  plugins/packages/mssql/package.json
  plugins/packages/mysql/package.json
  plugins/packages/openapi/package.json
  plugins/packages/postgresql/package.json
  plugins/packages/redis/package.json
  plugins/packages/restapi/package.json
  plugins/packages/s3/package.json
  plugins/packages/sendgrid/package.json
  plugins/packages/slack/package.json
  plugins/packages/smtp/package.json
  plugins/packages/snowflake/package.json
  plugins/packages/stripe/package.json
  plugins/packages/twilio/package.json
  plugins/packages/typesense/package.json
  server/package-lock.json
  server/package.json
Labels: frontend, backend, draft, do not merge, run-ci, suspend-review-app

#5477 [hotfix]: fixes - slack scope
  .version
  frontend/src/_components/Slack.jsx
  plugins/packages/slack/lib/index.ts
  plugins/packages/slack/lib/types.ts
Labels: run-ci

#5479 [ Bug fixed ] : [ Table ] When column name is changes, particular column data becomes empty when downloaded
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: bug, frontend, javascript, run-ci, tested, table, react, active-review-app

#5449 [Bug]: Fixed app crashes when items dropped into container inside listview
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Link.jsx
Labels: bug, javascript, needs testing, editor, react, suspend-review-app

#5511 Add data-cy for sidepanel header
  frontend/src/_ui/LeftSidebar/Header.jsx
Labels: cypress, data-cy

#5513 Add data-cy to fix table regression.
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: cypress, data-cy

#5514 Table automation enhancement
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/table.js
Labels: cypress

#5475 Fix and modify common cypress specs for v2
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/dashboard.js
  cypress-tests/cypress/constants/selectors/manageGroups.js
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/constants/selectors/profile.js
  cypress-tests/cypress/constants/selectors/workspaceVariable.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/dashboard.js
  cypress-tests/cypress/constants/texts/manageGroups.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/constants/texts/manageUsers.js
  cypress-tests/cypress/constants/texts/profile.js
  cypress-tests/cypress/constants/texts/workspacevarText.js
  cypress-tests/cypress/downloads/wolf-app-clone-export-1675848480893.json
  cypress-tests/cypress/e2e/dashboard/dashboard.cy.js
  cypress-tests/cypress/e2e/dashboard/manageGroups.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/userPermissions.cy.js
  cypress-tests/cypress/e2e/dashboard/profile.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO/ssoOnboarding.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/userPermissions.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/dashboard.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: cypress

#4849 feature: folder dto validation
  server/src/controllers/folders.controller.ts
  server/src/dto/create-folder.dto.ts
  server/src/services/folders.service.ts
Labels: run-ci, tested, suspend-review-app

#5529 Add data-cy for self-hosted onboarding
  frontend/src/OnBoardingForm/AdminSetup.jsx
  frontend/src/OnBoardingForm/ContinueButton.jsx
  frontend/src/OnBoardingForm/ContinueButtonSelfHost.jsx
  frontend/src/OnBoardingForm/OnBoardingBubbles.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnBoardingInput.jsx
  frontend/src/OnBoardingForm/OnBoardingRadioInput.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/OnBoardingForm/OnboardingBubblesSH.jsx
  frontend/src/OnBoardingForm/OnboardingPassword.jsx
  frontend/src/SuccessInfoScreen/ForgotPasswordInfoScreen.jsx
  frontend/src/SuccessInfoScreen/LinkExpiredInfoScreen.jsx
  frontend/src/SuccessInfoScreen/PasswordResetinfoScreen.jsx
  frontend/src/SuccessInfoScreen/SetupScreenSelfHost.jsx
  frontend/src/SuccessInfoScreen/SignupInfoScreen.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
Labels: cypress, data-cy

#5525 [Bug] app templates not working
  server/templates/gcs-file-explorer/definition.json
  server/templates/s3-file-explorer/definition.json
  server/templates/whatsapp-and-sms-crm/definition.json
Labels: run-ci, suspend-review-app

#5490 [BUG] Query event mapping to another query breaks on new version create
  server/src/services/apps.service.ts
Labels: run-ci, tested

#5532 [Release] v2.1.3
  .version
  server/.version
Labels: run-ci

#4570 Fixed version name sanitization on editing versions
  server/src/controllers/apps.controller.ts
  server/src/dto/version-edit.dto.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: hacktoberfest-accepted, run-ci, tested

#5545 Add happy path cypress spec for self hosted onboarding
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/selfHost/selfHostSignUp.cy.js
  cypress-tests/cypress/support/utils/selfHostSignUp.js
Labels: cypress

#5550 Added automation for table data download
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/table.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/table.js
Labels: cypress

#5291 [improvement] Renamed the column read_on_dashboard to hide_from_dashboard
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  server/migrations/1673424772525-ChangeReadOnDashboardColumnName.ts
  server/src/entities/app_group_permission.entity.ts
  server/src/helpers/queries.ts
Labels: run-ci, tested, suspend-review-app, improvements

#5520 docs: update heading
  docs/versioned_docs/version-2.0.0-beta/how-to/import-external-lib-py.md
Labels: documentation

#5498 Link corrected for Python doc
  docs/versioned_docs/version-2.0.0-beta/getting-started.md
Labels: documentation

#5494 Update athena.md
  docs/versioned_docs/version-2.0.0-beta/data-sources/athena.md
Labels: documentation

#5567 version name DTO validation fix for version update
  server/src/dto/version-create.dto.ts
  server/src/dto/version-edit.dto.ts
Labels: run-ci, tested

#5563 Added node-xlsx and pdf-parse on cypress.
  cypress-tests/cypress.config.js
  cypress-tests/package-lock.json
  cypress-tests/package.json
Labels: cypress

#5470 Fixed Toggle Button Issue on Table Component
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: run-ci, tested, suspend-review-app, documented

#5442 Fixed row id not changing bug on button click inside ListView
  frontend/src/Editor/Components/Button.jsx
Labels: tested, documented

#5437 Removed on-click event if a widget is disabled
  frontend/src/Editor/Components/Button.jsx
Labels: tested, documented

#5435 Fixed Go to app action on Events
  frontend/src/_helpers/utils.js
Labels: tested, documented

#5566 Added data-cy for signup page elements
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/LinkExpiredInfoScreen.jsx
  frontend/src/SuccessInfoScreen/SetupScreenSelfHost.jsx
  frontend/src/SuccessInfoScreen/SignupInfoScreen.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
Labels: data-cy

#5564 Added cypress test for user signup
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/authentication/signUp.cy.js
  cypress-tests/cypress/fixtures/fake.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/onboarding.js
  cypress-tests/package-lock.json
  cypress-tests/package.json
Labels: cypress

#5577 Hotfix - backfill for runpy quries v1
  server/data-migrations/1667076251897-BackfillDataSources.ts
  server/data-migrations/1676545162064-BackfillRunpyDatasources.ts
Labels: hotfix

#5587 Added data-cy for forgot password page
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/SuccessInfoScreen/ForgotPasswordInfoScreen.jsx
  frontend/src/SuccessInfoScreen/SignupInfoScreen.jsx
Labels: cypress, data-cy

#5560 Added data-cy for sidepanel and multipage icons
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/EditInput.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/_ui/Alert/Alert.jsx
  frontend/src/_ui/LeftSidebar/Button.jsx
Labels: cypress, data-cy

#5517 [Plugins] added connection close on test connection
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mysql/lib/index.ts
  plugins/packages/oracledb/lib/index.ts
Labels: run-ci, tested, suspend-review-app

#5584 Added automation for Multipages.
  cypress-tests/cypress/constants/selectors/multipage.js
  cypress-tests/cypress/constants/texts/multipage.js
  cypress-tests/cypress/e2e/editor/multipage/multipathHappypath.cy.js
  cypress-tests/cypress/support/utils/multipage.js
Labels: cypress

#5585 Fixed Component automation on actions
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/multiselectWidget.js
  cypress-tests/cypress/support/utils/table.js
Labels: suspend-review-app, run-cypress

#5506 [Plugins] AWS support profile instance
  docs/versioned_docs/version-2.0.0/data-sources/amazonses.md
  docs/versioned_docs/version-2.0.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.0.0/data-sources/s3.md
  plugins/packages/amazonses/lib/index.ts
  plugins/packages/amazonses/lib/manifest.json
  plugins/packages/amazonses/lib/operations.json
  plugins/packages/amazonses/lib/types.ts
  plugins/packages/amazonses/package-lock.json
  plugins/packages/amazonses/package.json
  plugins/packages/athena/package-lock.json
  plugins/packages/athena/package.json
  plugins/packages/dynamodb/lib/index.ts
  plugins/packages/dynamodb/lib/manifest.json
  plugins/packages/dynamodb/lib/types.ts
  plugins/packages/s3/lib/index.ts
  plugins/packages/s3/lib/manifest.json
  plugins/packages/s3/package-lock.json
  plugins/packages/s3/package.json
Labels: run-ci, plugins, tested, active-review-app

#5605 Added Missing data-cy for password reset page
  frontend/assets/translations/en.json
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/OnBoardingForm/OnboardingPassword.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/PasswordResetinfoScreen.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
Labels: cypress, data-cy

#5607 Added data-cy to fix DS specs on GitHub actions
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/QueryManager/CustomToggleSwitch.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/HomePage/Header.jsx
  frontend/src/_components/SearchBox.jsx
Labels: cypress, data-cy

#5609 Added cypress spec for password reset functionality
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/authentication/forgotPassword.cy.js
Labels: cypress, active-review-app, run-cypress

#5496 Fix: Show on desktop bug fixed for widgets using subcontainer
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci, tested

#5413 [ Feature request ] : [ Table ] Added feature to highlight a word in the column if matched with searched term
  frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
  frontend/src/Editor/Components/Table/Table.jsx
Labels: feature request, run-ci, tested

#5539 Verticle sidebar color fix, Bugfix for #4829
  frontend/src/Editor/Components/verticalDivider.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested, documented

#5444 Tooljet database : code audit or technical debt review.
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/FilterForm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/OrderForm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SortForm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
Labels: run-ci, tested, active-review-app, documented

#5445 Added option to set the default language for the instance
  frontend/src/index.jsx
  server/src/services/app_config.service.ts
Labels: run-ci, tested, suspend-review-app

#5461 [bug-fix] The public app is redirecting to the login page if the user token expired.
  frontend/src/_services/tooljet.service.js
  server/src/controllers/metadata.controller.ts
  server/src/modules/auth/query-auth.guard.ts
Labels: tested, active-review-app

#5483 Fix:Show popover in calendar in editor mode when clicked outside the editor
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/CalendarPopover.jsx
Labels: run-ci, tested

#5599 fixes - Only Table body should be scrollable and table head should be sticky
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/_styles/theme.scss
Labels: tested, active-review-app

#5597 fixes - Unable to create new column and row after editing table name
  frontend/src/TooljetDatabase/TableListItem/index.jsx
Labels: tested, active-review-app

#5595 Fixes error for setting up default value for on creating a new column (Tooljet database)
  server/src/dto/tooljet-db.dto.ts
Labels: run-ci, tested, active-review-app

#5630 Feature - Support AWS Role to access cross-account resources
  plugins/packages/amazonses/lib/index.ts
  plugins/packages/amazonses/lib/manifest.json
  plugins/packages/amazonses/lib/types.ts
  plugins/packages/dynamodb/lib/index.ts
  plugins/packages/dynamodb/lib/manifest.json
  plugins/packages/s3/lib/index.ts
  plugins/packages/s3/lib/manifest.json
  plugins/packages/s3/lib/types.ts
Labels: feature request

#5592 Improvements - ToolJet database edit row operation
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
Labels: needs testing, run-ci, tested, needs documentation, active-review-app, documented
