Repository ToolJet/ToolJet, pull requests merged in 2023-11, with the labels that each got.

#8037 hotfix: Plugins redirection on subpath
  plugins/packages/common/lib/oauth.ts
  plugins/packages/googlesheets/lib/index.ts
  plugins/packages/slack/lib/index.ts
  plugins/packages/zendesk/lib/index.ts
Labels: tested, active-review-app

#7914 Fixes: #7746 Changed labels to sentence case for NumberInput
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7986 Update README.md
  README.md
Labels: hacktoberfest-accepted

#8057 Accessibility features for Tooljet markdown files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: hacktoberfest-accepted

#8054 fix(readme): Terminate unterminated string literal
  README.md
Labels: hacktoberfest-accepted

#7980 Documentation fix of ClickHouse
  docs/docs/data-sources/clickhouse.md
  docs/versioned_docs/version-2.18.0/data-sources/clickhouse.md
  docs/versioned_docs/version-2.19.0/data-sources/clickhouse.md
Labels: hacktoberfest-accepted

#7583 Fix typo in Container.jsx
  frontend/src/Editor/Container.jsx
Labels: hacktoberfest-accepted

#8007 [improvement] From now on, users will not be able to make the app public or access the shareable URL if the app has not been released
  frontend/src/App/App.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_components/ErrorComponents/ErrorPage.jsx
  frontend/src/_components/ErrorComponents/index.js
  frontend/src/_components/ErrorComponents/static-modal.scss
  frontend/src/_components/ToolTip.jsx
  frontend/src/_helpers/constants.js
  frontend/src/_helpers/handleAppAccess.js
  frontend/src/_helpers/routes.js
  frontend/src/_styles/theme.scss
  server/src/controllers/apps.controller.ts
Labels: run-ci, tested, suspend-review-app, design-approved

#8099 [doc] integrates plugin-image-zoom
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/yarn.lock
Labels: documentation, enhancement

#8104 [doc] testing plugin
  docs/docs/widgets/file-picker.md
  docs/package-lock.json
  docs/versions.json
  docs/yarn.lock
Labels: active-review-docs-app

#8103 UI text fixes
  frontend/src/Editor/Header/InfoOrErrorBox.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Header/index.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: tested, active-review-app

#8048 Fix/add redirection to error pages
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_components/ErrorComponents/ErrorPage.jsx
  frontend/src/_helpers/authorizeWorkspace.js
  frontend/src/_helpers/constants.js
  frontend/src/_helpers/handleAppAccess.js
Labels: run-ci

#8084 [doc]codespaces guide
  docs/docs/contributing-guide/setup/codespaces.md
  docs/docs/setup/ec2.md
  docs/docs/setup/try-tooljet.md
  docs/sidebars.js
  docs/versioned_docs/version-1.x.x/setup/try-tooljet.md
  docs/versioned_docs/version-2.0.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.1.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.10.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.11.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.12.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.13.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.14.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.15.0/contributing-guide/setup/codespaces.md
  docs/versioned_docs/version-2.15.0/setup/ec2.md
  docs/versioned_docs/version-2.15.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.16.0/contributing-guide/setup/codespaces.md
  docs/versioned_docs/version-2.16.0/setup/ec2.md
  docs/versioned_docs/version-2.16.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.17.0/contributing-guide/setup/codespaces.md
  docs/versioned_docs/version-2.17.0/setup/ec2.md
  docs/versioned_docs/version-2.17.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.18.0/contributing-guide/setup/codespaces.md
  docs/versioned_docs/version-2.18.0/setup/ec2.md
  docs/versioned_docs/version-2.18.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.19.0/contributing-guide/setup/codespaces.md
  docs/versioned_docs/version-2.19.0/setup/ec2.md
  docs/versioned_docs/version-2.19.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.2.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.22.0/contributing-guide/setup/codespaces.md
  docs/versioned_docs/version-2.22.0/setup/ec2.md
  docs/versioned_docs/version-2.22.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.3.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.4.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.5.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.6.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.7.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.8.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.9.0/setup/try-tooljet.md
  docs/versioned_docs/version-2.9.4/setup/try-tooljet.md
  docs/versioned_sidebars/version-2.15.0-sidebars.json
  docs/versioned_sidebars/version-2.16.0-sidebars.json
  docs/versioned_sidebars/version-2.17.0-sidebars.json
  docs/versioned_sidebars/version-2.18.0-sidebars.json
  docs/versioned_sidebars/version-2.19.0-sidebars.json
  docs/versioned_sidebars/version-2.22.0-sidebars.json
Labels: documentation

#8047 [hotfix] Redirect old preview URL to new one
  frontend/src/App/App.jsx
  frontend/src/_components/PrivateRoute.jsx
  frontend/src/_helpers/handleAppAccess.js
  frontend/src/_helpers/routes.js
  server/src/controllers/apps.controller.ts
Labels: tested

#8106 Fix default case in handling app editor url
  frontend/src/_helpers/handleAppAccess.js
Labels: tested

#8061 Fixed cypress import failure
  cypress-tests/cypress/e2e/exportImport/import.cy.js
Labels: run-cypress-marketplace

#8108 2.23.0 App Builder automation fixed.
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
Labels: cypress

#8107 Fixed failed test cases for platform release v2.23.0
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/manageGroups.js
  cypress-tests/cypress/e2e/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/support/utils/common.js
Labels: cypress, run-cypress-workspace

#6878 ISSUE#5690 : Create a new Bucket functionality for S3
  marketplace/plugins/s3/lib/index.ts
  marketplace/plugins/s3/lib/operations.json
  marketplace/plugins/s3/lib/query_operations.ts
  marketplace/plugins/s3/lib/types.ts
  plugins/packages/s3/lib/index.ts
  plugins/packages/s3/lib/operations.json
  plugins/packages/s3/lib/operations.ts
  plugins/packages/s3/lib/types.ts
Labels: plugins, active-review-app

#8119 Appdef : appslug released public
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/Editor/Viewer.jsx
  server/src/controllers/apps.controller.v2.ts
Labels: tested

#8122 [appdef] fixes: versioning with cloned page and ghost components
  server/src/controllers/apps.controller.v2.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
Labels: tested

#8126 Added data-cy for apps slug and create app components
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/_components/AppModal.jsx
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
Labels: data-cy, cypress

#8129 Modifed platform cypress test cases
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/e2e/ce/appSlug.cy.js
  cypress-tests/cypress/e2e/ce/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/ce/privateAndPublicApp.cy.js
  cypress-tests/cypress/e2e/ce/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/manageGroups.cy.js
  cypress-tests/cypress/e2e/workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/workspace/profile.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/e2e/workspace/workspaceConstants.cy.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: cypress, run-cypress-workspace

#8130 [refactor]:update labels for components configuration panel
  frontend/assets/translations/en.json
Labels: suspend-review-app, run-cypress-app-builder

#8131 [hotfix] fixes: should have the new color value with fx option
  .version
  frontend/.version
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/utils.js
  server/.version
  server/src/services/components.service.ts
Labels: tested, appbuilder

#8152 Added data-cy for error page component
  frontend/src/_components/ErrorComponents/ErrorPage.jsx
Labels: data-cy, cypress

#7702 Hotfix/slack plugin oauth flow not working
  frontend/src/_components/Slack.jsx
  server/src/services/data_queries.service.ts
  server/src/services/data_sources.service.ts
Labels: run-ci, tested, suspend-review-app

#7663 Fixed Filter button active state issue
  frontend/src/_styles/theme.scss
Labels: bug, tested, suspend-review-app

#7831 Fixed current version app export issue
  frontend/src/HomePage/ExportAppModal.jsx
Labels: bug, tested, suspend-review-app

#6622 feat: Support multipart/form-data body when file like objects are specified in restapi datasource
  docs/docs/data-sources/restapi.md
  docs/docs/tutorial/keyboard-shortcuts.md
  docs/static/img/datasource-reference/rest-api/multipart-form-data.png
  plugins/packages/restapi/lib/index.ts
  plugins/packages/restapi/package-lock.json
  plugins/packages/restapi/package.json
Labels: plugins, suspend-review-app

#7854 Add query validation for TJDB join
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/HomePage/ExportAppModal.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  server/ormconfig.ts
  server/src/controllers/tooljet_db.controller.ts
  server/src/dto/tooljet-db-join.dto.ts
  server/src/filters/all-exceptions-filter.ts
  server/src/filters/tooljetdb-join-exceptions-filter.ts
  server/src/main.ts
  server/src/services/tooljet_db.service.ts
Labels: active-review-app

#8165 Sort event getting fired only when sorting is applied in the table
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci

#8162 Hotfix : Import/export apps with tabs
  .version
  frontend/.version
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_stores/dataQueriesStore.js
  server/.version
  server/src/services/app_import_export.service.ts
Labels: tested, hotfix, appbuilder

#8159 Added cyppress test case for creating and editing workspace
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/dashboard.js
  cypress-tests/cypress/e2e/workspace/errorPage.cy.js
  cypress-tests/cypress/e2e/workspace/workspace.cy.js
Labels: active-review-app, cypress, run-cypress-workspace

#8138 [fix]:change the code for the dynamic document links for data sources
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: suspend-review-app

#8110 [docs] log file
  docs/docs/Enterprise/audit_logs.md
  docs/docs/setup/env-vars.md
  docs/versioned_docs/version-2.23.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.23.0/setup/env-vars.md
Labels: documentation

#8155 [docs] updated instance settings to settings
  docs/docs/Enterprise/superadmin.md
  docs/docs/Enterprise/white-label.md
  docs/docs/dashboard.md
  docs/docs/org-management/licensing.md
  docs/docs/setup/env-vars.md
Labels: documentation

#8180 [doc] minor logfile change
  docs/docs/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.23.0/Enterprise/audit_logs.md
Labels: documentation

#8221 Page change event is getting triggered in the table component
  .version
  frontend/.version
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  server/.version
Labels: bug, run-ci, tested, hotfix
