Repository ToolJet/ToolJet, pull requests merged in 2023-10, with the labels that each got.

#7576 Hotfix: Add default host for tjdb proxy
  server/src/services/postgrest_proxy.service.ts
Labels: run-ci

#7587 Fix app builder automation for 2.19.2
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  frontend/src/_components/CopyToClipboard/CopyToClipboard.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
Labels: cypress

#7625 Displaying total count with totalRecords with respect to serverside pagination in Table
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested

#7627 [appdef-2.0] fixes: event action linking for imported apps
  server/src/services/app_import_export.service.ts
Labels: tested

#7629 [appdef-2] fixes: Toggling display preferences is not saving for components
  server/src/services/components.service.ts
Labels: tested

#7630 Merge main back to develop (v2.19.2)
  .version
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  frontend/.version
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_components/CopyToClipboard/CopyToClipboard.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  server/.version
Labels: run-ci

#7577 [docs] SAML
  docs/docs/user-authentication/sso/saml.md
  docs/sidebars.js
  docs/static/img/sso/saml/auth.png
  docs/static/img/sso/saml/config.png
  docs/static/img/sso/saml/enable.png
  docs/static/img/sso/saml/login.png
  docs/static/img/sso/saml/url.png
  docs/static/img/sso/saml/workspaceset.png
  docs/versioned_docs/version-2.19.0/user-authentication/sso/saml.md
  docs/versioned_sidebars/version-2.19.0-sidebars.json
Labels: documentation

#7632 [appdef-2] fixes: dnd issue for mobile view
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7634 [appdef] - copy associated events for cloned components
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#7636 [appdef-2] : Fixes frontend issues
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  server/src/services/apps.service.ts
Labels: tested

#7637 [appdef-2 ]fixes: Component inspector go blank after switching to different page
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7638 [appdef-2] fixes: general properties of widgets are not getting saved
  frontend/src/_helpers/appUtils.js
  server/migrations/1691006952074-CreateComponentTable.ts
  server/src/entities/component.entity.ts
  server/src/services/components.service.ts
Labels: tested

#7653 [appdef-2] fixes: selecting the components via selecto
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_stores/editorStore.js
Labels: tested

#7656 [appdef-2] fixes: multiple undo-redo actions simultaneously
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7657 [appdef-2] fixes: copy associated events for cloned queries
  frontend/src/_stores/dataQueriesStore.js
Labels: tested

#7701 Fixes not able toggle of Listview pagination toggle
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: tested

#7691 [appdef-2] fixes: dnd fix for widgets dropped inside subcontainer
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/SubContainer.jsx
Labels: tested

#7687 [Appdef-2] copy-paste, cut and clone fix for widgets
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#7688 [appdef-2] Fixes: Component inspector goes bank if selected multiple components via mouse area selection
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7692 [appdef-2] : fixes: Tab children are not getting deleted from currentState on deleting the tab component (parent)
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7695 [appdef-2] fixes: column data generated from restapi does not render correct columns in viewer
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_stores/utils.js
Labels: tested

#7704 [appdef-2] fixes: multiple query confirmations trigger
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/dataQueriesStore.js
Labels: tested

#7705 [appdef-2] fixes:Event handler are running twice for page load
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Viewer.jsx
Labels: tested

#7718 [appdef-2] fixes: container widget is not getting saved on drop
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_stores/utils.js
Labels: tested

#7720 [appdef-2] fixes: Create app version from is empty if we delete another version.
  frontend/src/Editor/AppVersionsManager/CustomSelect.jsx
Labels: tested

#7721 [appdef-2] fixes: on versioned app (switching or creating) version, the componet layout is wrongly updated to the container dnd
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_stores/utils.js
Labels: tested

#7728 [appdef-2] fixes: triggering confirmation box for every query with on load trigger
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/dataQueriesStore.js
Labels: tested

#7725 Fixes canvas background and go to app crashing
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Inspector/ActionConfigurationPanels/GotoApp.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
Labels: tested

#7733 [refactor]:update new quickstart guide link on canvas
  frontend/src/Editor/Container.jsx
Labels: active-review-app

#7735 [appdef-2] fixes: calendar and form widgets
  frontend/src/Editor/Components/Calendar.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#7759 [appdef-2] fixes: rendering of components in viewer for mobile
  frontend/src/Editor/Viewer.jsx
Labels: tested

#7766 [appdef-2] fixes: component validations do not get saved
  frontend/src/_helpers/appUtils.js
  server/data-migrations/1695914619976-MigrateAppsDefinitionSchemaTransition.ts
  server/migrations/1691006952074-CreateComponentTable.ts
  server/src/entities/component.entity.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/components.service.ts
Labels: tested

#7767 [appdef-2] subcontainer dnd height outbound fix
  frontend/src/Editor/SubContainer.jsx
Labels: tested

#7768 [appdef-2] fixes: conditional rendering widget manager inspector
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7770 fixes: goToApp not running from runjs in viewer mode
  frontend/src/_helpers/appUtils.js
Labels: tested

#7761 [appdef-2] fixes: multi-components cloning or copy/paste have same name
  frontend/src/_helpers/appUtils.js
Labels: tested

#7769 Fix disabled page is being displayed on switch page event dropdown
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: tested

#7765 Add new templates and update an existing template
  frontend/assets/images/templates/customer-support-admin-dark.png
  frontend/assets/images/templates/customer-support-admin.png
  frontend/assets/images/templates/customer-ticketing-form-dark.png
  frontend/assets/images/templates/customer-ticketing-form.png
  frontend/assets/images/templates/inventory-management-dark.png
  frontend/assets/images/templates/inventory-management.png
  frontend/assets/images/templates/lead-management-system-dark.png
  frontend/assets/images/templates/lead-management-system.png
  frontend/assets/images/templates/sales-analytics-dashboard-dark.png
  frontend/assets/images/templates/sales-analytics-dashboard.png
  server/templates/customer-support-admin/definition.json
  server/templates/customer-support-admin/manifest.json
  server/templates/customer-ticketing-form/definition.json
  server/templates/customer-ticketing-form/manifest.json
  server/templates/inventory-management/definition.json
  server/templates/inventory-management/manifest.json
  server/templates/lead-management-system/definition.json
  server/templates/lead-management-system/manifest.json
  server/templates/sales-analytics-dashboard/definition.json
  server/templates/sales-analytics-dashboard/manifest.json
  server/templates/supply-chain-management/manifest.json
Labels: active-review-app

#7559 docs: updated translation for few components
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#7548 [refactor]: Update descriptions(tooltips) for range picker, text, image and container components
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#7593 Fix #7524: Updated Component Descriptions for circular progressbar, spinner, statistics and range slider components.
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7529 [refactor]: Update descriptions(tooltips) for custom component, button group, pdf and steps components #7526
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7566 Update descriptions(tooltips)
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7551 changes in S3 data source reference #7542
  docs/docs/data-sources/s3.md
  docs/versioned_docs/version-2.18.0/data-sources/s3.md
  docs/versioned_docs/version-2.19.0/data-sources/s3.md
Labels: hacktoberfest-accepted

#7584 Changed title, description, info in appwrite.md
  docs/docs/data-sources/appwrite.md
  docs/versioned_docs/version-2.18.0/data-sources/appwrite.md
  docs/versioned_docs/version-2.19.0/data-sources/appwrite.md
Labels: hacktoberfest-accepted

#7601 [docs]: changes made in Cloud Firestore data source reference
  docs/docs/data-sources/firestore.md
  docs/versioned_docs/version-2.18.0/data-sources/firestore.md
  docs/versioned_docs/version-2.19.0/data-sources/firestore.md
Labels: hacktoberfest-accepted

#7600 docs : Big query page documentation updated
  docs/docs/data-sources/bigquery.md
  docs/versioned_docs/version-2.18.0/data-sources/bigquery.md
  docs/versioned_docs/version-2.19.0/data-sources/bigquery.md
Labels: hacktoberfest-accepted

#7614 docs: updated cosmosdb reference
  docs/docs/data-sources/cosmosdb.md
  docs/versioned_docs/version-2.18.0/data-sources/cosmosdb.md
  docs/versioned_docs/version-2.19.0/data-sources/cosmosdb.md
Labels: hacktoberfest-accepted

#7610 docs: updated couchdb reference
  docs/docs/data-sources/couchdb.md
  docs/versioned_docs/version-2.18.0/data-sources/couchdb.md
  docs/versioned_docs/version-2.19.0/data-sources/couchdb.md
Labels: hacktoberfest-accepted

#7772 Fix/documentation bug global datasource to data source
  docs/docs/data-sources/dynamodb.md
  docs/versioned_docs/version-2.18.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.19.0/data-sources/dynamodb.md
Labels: hacktoberfest-accepted

#7618 [docs]: updated ElasticSearch data source reference
  docs/docs/data-sources/elasticsearch.md
  docs/versioned_docs/version-2.18.0/data-sources/elasticsearch.md
  docs/versioned_docs/version-2.19.0/data-sources/elasticsearch.md
Labels: hacktoberfest-accepted

#7635 Updated Google Cloud Storage data source reference
  docs/docs/data-sources/gcs.md
  docs/versioned_docs/version-2.18.0/data-sources/gcs.md
  docs/versioned_docs/version-2.19.0/data-sources/gcs.md
Labels: hacktoberfest-accepted

#7684 Updated minio data source reference docs
  docs/docs/data-sources/minio.md
  docs/versioned_docs/version-2.18.0/data-sources/minio.md
  docs/versioned_docs/version-2.19.0/data-sources/minio.md
Labels: hacktoberfest-accepted

#7644 fix: Update the frontmatter of HTML and Rich editor components.
  docs/docs/widgets/html.md
  docs/docs/widgets/rich-text-editor.md
  docs/versioned_docs/version-2.18.0/widgets/html.md
  docs/versioned_docs/version-2.18.0/widgets/rich-text-editor.md
  docs/versioned_docs/version-2.19.0/widgets/html.md
  docs/versioned_docs/version-2.19.0/widgets/rich-text-editor.md
Labels: hacktoberfest-accepted

#7682 docs: Updated MongoDB data source reference
  docs/docs/data-sources/mongodb.md
  docs/versioned_docs/version-2.18.0/data-sources/mongodb.md
  docs/versioned_docs/version-2.19.0/data-sources/mongodb.md
Labels: hacktoberfest-accepted

#7683 Added changes in MS SQL Server data source ref
  docs/docs/data-sources/mssql.md
  docs/versioned_docs/version-2.18.0/data-sources/mssql.md
  docs/versioned_docs/version-2.19.0/data-sources/mssql.md
Labels: hacktoberfest-accepted

#7679 updated notion datasource reference
  docs/docs/data-sources/notion.md
  docs/versioned_docs/version-2.18.0/data-sources/notion.md
  docs/versioned_docs/version-2.19.0/data-sources/notion.md
Labels: hacktoberfest-accepted

#7697 [Docs]: Updated the docs as specified by issue #7654
  docs/docs/data-sources/mysql.md
  docs/versioned_docs/version-2.18.0/data-sources/mysql.md
  docs/versioned_docs/version-2.19.0/data-sources/mysql.md
Labels: hacktoberfest-accepted

#7827 Server side pagination fetching new set of data upon changing page
  .version
  frontend/.version
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  server/.version
Labels: tested

#7808 Fix Kanban widget getting into infinite loop
  frontend/src/Editor/Components/Kanban/Components/Item.jsx
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Components/KanbanBoard/KanbanBoard.jsx
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7821 [appdef] adds support of constants to current state of the ediotr
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
Labels: tested

#7822 [appdef] removes loader added for testing
  frontend/src/AppLoader/AppLoader.jsx
  frontend/src/Editor/Header/index.js
Labels: tested

#7820 [appdef] fixes - dnd container cloning edge cases
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/utils.js
  server/src/services/components.service.ts
Labels: tested

#7863 fixes: Resolving App Version and Timestamp Update Challenges
  server/src/controllers/apps.controller.v2.ts
  server/src/helpers/utils.helper.ts
  server/src/services/components.service.ts
  server/src/services/events_handler.service.ts
  server/src/services/page.service.ts
Labels: tested

#7862 [appdef-2] fixes: triggering confirmation box for button click
  frontend/src/_helpers/appUtils.js
Labels: tested

#7867 [appdef ]fixes: components copied from template app to a new page or app do not render in canvas
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/utils.js
Labels: tested

#7873 [appdef] fixes: Creating page not changing the slug
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7864 [appdef] fixes: on importing a exported app child components are not present in the parent component
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
Labels: tested

#7888 [appdef] api endpoint fixes
  frontend/src/Editor/AppVersionsManager/CreateVersionModal.jsx
  server/src/controllers/apps.controller.v2.ts
Labels: tested

#7812 Fixes CurrentUser & Mode not present in globals in inspector
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_stores/editorStore.js
Labels: tested, suspend-review-app

#7889 Fixes on adding query params in event handler, breaking the app
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Inspector/ActionConfigurationPanels/GotoApp.jsx
  frontend/src/Editor/Inspector/ActionConfigurationPanels/SwitchPage.jsx
Labels: tested

#7858 fixes: fixes on on app load switch page action via run queires
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/editorStore.js
Labels: tested

#7895 [appdef] fixes: event actions mapping for import-export
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/HomePage/ExportAppModal.jsx
  server/src/services/app_import_export.service.ts
Labels: tested

#7859 When pagination is disabled setting page size equal to rows length in table component
  .version
  frontend/.version
  frontend/src/Editor/Components/Table/Table.jsx
  server/.version
Labels: bug, run-ci, tested

#7919 [appdef] fixes: table column data not updated on boxes changes in container
  frontend/src/Editor/Container.jsx
Labels: tested

#7209 New Improved App creation flow
  frontend/src/Editor/Header/EditAppName.jsx
  frontend/src/Editor/Header/InfoOrErrorBox.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/HomePage/Modal.jsx
  frontend/src/HomePage/TemplateLibraryModal/TemplateLibraryModal.jsx
  frontend/src/_components/AppModal.jsx
  frontend/src/_components/index.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/app.service.js
  frontend/src/_services/library-app.service.js
  frontend/src/_styles/theme.scss
  server/src/controllers/app_import_export.controller.ts
  server/src/controllers/apps.controller.ts
  server/src/controllers/library_apps.controller.ts
  server/src/dto/app-clone.dto.ts
  server/src/dto/app-create.dto.ts
  server/src/dto/app-import.dto.ts
  server/src/dto/import-resources.dto.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/import_export_resources.service.ts
  server/src/services/library_app_creation.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/library_apps.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
Labels: run-ci, testing, suspend-review-app

#7905 [appdef] fixes: creating all pages from all versions
  server/src/services/app_import_export.service.ts
Labels: tested

#7900 Fix state not changing in chart
  frontend/src/Editor/Inspector/Components/Chart.jsx
Labels: tested

#7902 Fix url param not being updated on updation of query params in go to app
  frontend/src/Editor/Inspector/ActionConfigurationPanels/GotoApp.jsx
Labels: tested

#7904 [appdef] Pages attributes are missing on versioning or imported app
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
Labels: tested

#7915 [appdef] fixes: deleting children components via selecto
  frontend/src/_helpers/appUtils.js
Labels: tested

#7927 hotfix: tjdb columns of table selected is not listed on drop-down
  .version
  frontend/.version
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  server/.version
Labels: run-ci, tested, active-review-app

#7952 [docs]control component updates
  docs/docs/actions/control-component.md
  docs/versioned_docs/version-2.15.0/actions/control-component.md
  docs/versioned_docs/version-2.16.0/actions/control-component.md
  docs/versioned_docs/version-2.17.0/actions/control-component.md
  docs/versioned_docs/version-2.19.0/actions/control-component.md
Labels: documentation

#7928 [docs]docusauras version update 2.4.0 -> 2.4.3
  docs/package.json
  docs/yarn.lock
Labels: documentation

#7956 Modified cypress test cases for url changes
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress.config.js
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/support/utils/common.js
Labels: cypress, run-cypress-workspace

#7926 [appdef] fixes: component deletion fixes
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: tested

#7930 fixes: cloning components to a new version should also create associted events
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_services/appVersion.service.js
  server/src/controllers/apps.controller.v2.ts
Labels: tested

#7932 [appdef] fixes: creating component general properties and styles for versioning, import/export
  server/data-migrations/1697473340856-MigrateAppsDefinitionSchemaTransition.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/components.service.ts
Labels: tested

#7933 [appdef] - fixes: webpage url on creating new version with multiple pages
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#7969 App Builder failing specs fixed for v2.22.0
  cypress-tests/cypress.config.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
Labels: cypress

#7971 [appdef] fixes: table crash due to columnDeletionHistory saved as an object instead of an array
  frontend/src/_stores/utils.js
Labels: tested

#7975 [appdef] fixes: on creating new version, data_queries should be created
  server/src/services/apps.service.ts
Labels: tested

#7557 [Hacktoberfest]Update descriptions for button,chart and modal components
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#7552 Update descriptions/#7518 checkbox radio button toggle switch textarea
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#7536 Fixes #7520 Refactor/update description dropdown multiselect map
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#7531 [HF23-AB]Update descriptions(tooltips) for timeline, svg image, html viewer and vertical divider components
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7555 [HF23-AB] Updated descriptions(tooltips) for kanban board, color picker and tree select components
  frontend/assets/translations/en.json
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7892 update the document with an requirement and also version will be updated
  docs/docs/data-sources/airtable.md
  docs/versioned_docs/version-2.18.0/data-sources/airtable.md
  docs/versioned_docs/version-2.19.0/data-sources/airtable.md
Labels: hacktoberfest-accepted

#7592 docs-updated
  docs/docs/data-sources/athena.md
  docs/versioned_docs/version-2.18.0/data-sources/athena.md
  docs/versioned_docs/version-2.19.0/data-sources/athena.md
Labels: hacktoberfest-accepted

#7615 Update azureblob.md
  docs/docs/data-sources/azureblob.md
  docs/versioned_docs/version-2.18.0/data-sources/azureblob.md
  docs/versioned_docs/version-2.19.0/data-sources/azureblob.md
Labels: hacktoberfest-accepted

#7612 Update the Baserow Docs
  docs/docs/data-sources/baserow.md
  docs/versioned_docs/version-2.18.0/data-sources/baserow.md
  docs/versioned_docs/version-2.19.0/data-sources/baserow.md
Labels: hacktoberfest-accepted

#7693 Updated docs of oracle
  docs/docs/data-sources/oracledb.md
  docs/versioned_docs/version-2.18.0/data-sources/oracledb.md
  docs/versioned_docs/version-2.19.0/data-sources/oracledb.md
Labels: hacktoberfest-accepted

#7823 fix: Changed widget to component
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: suspend-review-app

#7944 [HF23-AB] Update widgetConfig.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#7860 update: labels changed to sentence case for Button component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7853 change labels to sentence case for Modal Component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7961 Fix: Changed labels to sentence case for Container Component.
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7842 Change labels to sentence case for Text Input Component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7870 fixed labels to sentence case for radio component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7894 fix:Changed the label of text editor component to sentence case
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7837 Change labels to sentence case for Circular Progress Bar component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7868 fix: Change labels to sentence case for Statistics component #7784
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7763 fix/changed-Textarea-label-text
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#8008 [appdef] fixes: slug app link
  frontend/src/App/App.jsx
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/_stores/appDataStore.js
Labels: tested

#8009 [appdef] fixes: on version changed the preview link should also update
  frontend/src/Editor/EditorFunc.jsx
Labels: tested

#8010 [appdef] fixes: on cut and paste events should not cascade
  frontend/src/Editor/EditorFunc.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_services/appVersion.service.js
  frontend/src/_stores/appDataStore.js
  server/src/controllers/apps.controller.v2.ts
  server/src/dto/component.dto.ts
  server/src/services/components.service.ts
Labels: tested

#8012 [appdef] fixes: cloning apps
  frontend/src/Editor/ManageAppUsers.jsx
  server/src/services/app_import_export.service.ts
  server/src/services/import_export_resources.service.ts
Labels: tested

#7999 [docs] ecs and azure container doc updates
  .do/deploy.template.yaml
  docs/docs/setup/azure-container.md
  docs/docs/setup/digitalocean.md
  docs/docs/setup/ec2.md
  docs/docs/setup/ecs.md
  docs/static/img/setup/azure-container/3-a.png
  docs/static/img/setup/azure-container/5a.png
  docs/static/img/setup/ecs/ecs-1.png
  docs/static/img/setup/ecs/ecs-10.png
  docs/static/img/setup/ecs/ecs-11.png
  docs/static/img/setup/ecs/ecs-12.png
  docs/static/img/setup/ecs/ecs-13.png
  docs/static/img/setup/ecs/ecs-14.png
  docs/static/img/setup/ecs/ecs-15.png
  docs/static/img/setup/ecs/ecs-16.png
  docs/static/img/setup/ecs/ecs-17.png
  docs/static/img/setup/ecs/ecs-2.png
  docs/static/img/setup/ecs/ecs-3.png
  docs/static/img/setup/ecs/ecs-4.png
  docs/static/img/setup/ecs/ecs-5.png
  docs/static/img/setup/ecs/ecs-6.png
  docs/static/img/setup/ecs/ecs-8.png
  docs/static/img/setup/ecs/ecs-9.png
  docs/versioned_docs/version-2.15.0/setup/azure-container.md
  docs/versioned_docs/version-2.15.0/setup/digitalocean.md
  docs/versioned_docs/version-2.15.0/setup/ec2.md
  docs/versioned_docs/version-2.15.0/setup/ecs.md
  docs/versioned_docs/version-2.16.0/setup/azure-container.md
  docs/versioned_docs/version-2.16.0/setup/digitalocean.md
  docs/versioned_docs/version-2.16.0/setup/ec2.md
  docs/versioned_docs/version-2.16.0/setup/ecs.md
  docs/versioned_docs/version-2.17.0/setup/azure-container.md
  docs/versioned_docs/version-2.17.0/setup/digitalocean.md
  docs/versioned_docs/version-2.17.0/setup/ec2.md
  docs/versioned_docs/version-2.17.0/setup/ecs.md
  docs/versioned_docs/version-2.18.0/setup/azure-container.md
  docs/versioned_docs/version-2.18.0/setup/digitalocean.md
  docs/versioned_docs/version-2.18.0/setup/ec2.md
  docs/versioned_docs/version-2.18.0/setup/ecs.md
  docs/versioned_docs/version-2.19.0/setup/azure-container.md
  docs/versioned_docs/version-2.19.0/setup/digitalocean.md
  docs/versioned_docs/version-2.19.0/setup/ec2.md
  docs/versioned_docs/version-2.19.0/setup/ecs.md
  docs/versioned_docs/version-2.22.0/setup/azure-container.md
  docs/versioned_docs/version-2.22.0/setup/digitalocean.md
  docs/versioned_docs/version-2.22.0/setup/ec2.md
  docs/versioned_docs/version-2.22.0/setup/ecs.md
Labels: documentation

#8015 Avoided infinite loop in server side sorting in the table component
  .version
  frontend/.version
  frontend/src/Editor/Components/Table/Table.jsx
  server/.version
Labels: bug, run-ci, tested, hotfix

#8031 Fixed app builder automation for app builder.
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/button.js
Labels: cypress

#8026 [appdef] fixes : ghost child components are being created on imported/cloned apps and while migrating
  server/data-migrations/1697473340856-MigrateAppsDefinitionSchemaTransition.ts
  server/src/services/app_import_export.service.ts
Labels: tested

#8036 [appdef] fixes: tabs children are not rendered on duplicating pages
  server/src/services/page.service.ts
Labels: tested

#8038 Adding release label to Trigger all the cypress worflows
  .github/workflows/cypress-appbuilder.yml
  .github/workflows/cypress-marketplace.yml
  .github/workflows/cypress-platform.yml
Labels: tested

#8051 [appdef] fixes: viewer route: keeps on reloading for private apps
  frontend/src/_services/app.service.js
Labels: tested

#7850 [HF23-AB]Enter to Delete | Closes #7711
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: hacktoberfest-accepted, tested

#7978 Change labels to sentence case for Chart Component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7861 Update text component labels to sentence case
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7878 Fix: Changed labels to sentence case for Password Input Component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7942 sentence_casing_for_labels_in_tab_component_added #7743
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7993 feat: convert Color Picker color property label to sentence case
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7991 Change labels to sentence case for Timeline component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7959 Convert into sentence case of timer component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7917 [bug]: update link to circular progress bar in configuration panel
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: suspend-review-app

#8053 Fixed failed platform test cases for app desinition re-design
  cypress-tests/cypress.config.js
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/editor/app-version/version.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/support/utils/version.js
Labels: cypress, run-cypress-workspace

#8066 [hot-fix] Pages `applications` handle issue
  .version
  frontend/.version
  frontend/src/_helpers/authorizeWorkspace.js
  frontend/src/_helpers/routes.js
  frontend/src/_helpers/utils.js
  server/.version
Labels: needs testing, run-ci

#8044 Added data-cy for workspace modal
  frontend/src/_components/OrganizationManager/CreateOrganization.jsx
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
Labels: data-cy, cypress

#7989 Made the required changes in widgetConfig.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7974 Updated the Twitter Logo to New Logo ( X )
  docs/src/css/custom.css
Labels: hacktoberfest-accepted

#7879 fix: fixed labels to sentence case for Rating Component
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7883 Fix: Changed to SentenceCase for DividerComponent
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, suspend-review-app

#7851 [HF23-AB] Fixed/[Icon component] the background color should be of same as the currently active theme of ToolJet
  frontend/src/_styles/theme.scss
Labels: hacktoberfest-accepted, tested, active-review-app
