Repository ToolJet/ToolJet, pull requests merged in 2023-08, with the labels that each got.

#7160 adding changes in getting started docs
  docs/docs/getting-started.md
  docs/package-lock.json
  docs/src/css/custom.css
  docs/static/img/v2-beta/getting_started/howtjworks.webp
  docs/static/img/v2-beta/getting_started/intro.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/addnewrow.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/addproductbutton.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/appbuilder.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/buildingui.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/createnewapplication.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/createnewtable.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/createquery.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/selecttablecustomers.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/tabledata.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/tooljetdb.webp
  docs/static/img/v2-beta/getting_started/quickstart/compressed/tooljetdbeditor.webp
  docs/versioned_docs/version-2.0.0/getting-started.md
  docs/versioned_docs/version-2.1.0/getting-started.md
  docs/versioned_docs/version-2.10.0/getting-started.md
  docs/versioned_docs/version-2.11.0/getting-started.md
  docs/versioned_docs/version-2.2.0/getting-started.md
  docs/versioned_docs/version-2.3.0/getting-started.md
  docs/versioned_docs/version-2.4.0/getting-started.md
  docs/versioned_docs/version-2.5.0/getting-started.md
  docs/versioned_docs/version-2.6.0/getting-started.md
  docs/versioned_docs/version-2.7.0/getting-started.md
  docs/versioned_docs/version-2.8.0/getting-started.md
  docs/versioned_docs/version-2.9.4/getting-started.md
  docs/yarn.lock
Labels: documentation, enhancement, do not merge

#7176 [docs]replaced optimized intro image
  docs/static/img/v2-beta/getting_started/intro.webp
Labels: documentation

#7168 Feature: Mysql socket support
  plugins/packages/mysql/lib/index.ts
  plugins/packages/mysql/lib/manifest.json
  plugins/packages/mysql/lib/types.ts
  server/data-migrations/1690830899563-UpdateMysqlDatasourceForSocketConnection.ts
  server/src/helpers/utils.helper.ts
Labels: run-ci

#7182 [docs] using server side pagination to load large data in chunks
  docs/docs/how-to/serverside-pagination.md
  docs/sidebars.js
  docs/static/img/how-to/server-side/change.gif
  docs/static/img/how-to/server-side/data.png
  docs/static/img/how-to/server-side/event.png
  docs/static/img/how-to/server-side/pagination.png
  docs/versioned_docs/version-2.10.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.11.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.3.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.4.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.5.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.6.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.7.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.8.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.9.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.9.4/how-to/serverside-pagination.md
  docs/versioned_sidebars/version-2.10.0-sidebars.json
  docs/versioned_sidebars/version-2.11.0-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
  docs/versioned_sidebars/version-2.5.0-sidebars.json
  docs/versioned_sidebars/version-2.6.0-sidebars.json
  docs/versioned_sidebars/version-2.7.0-sidebars.json
  docs/versioned_sidebars/version-2.8.0-sidebars.json
  docs/versioned_sidebars/version-2.9.0-sidebars.json
  docs/versioned_sidebars/version-2.9.4-sidebars.json
Labels: documentation

#7185 [docs] updated title in how-to server side pagination
  docs/docs/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.10.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.11.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.3.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.4.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.5.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.6.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.7.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.8.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.9.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.9.4/how-to/serverside-pagination.md
Labels: documentation

#7184 [docs]updated docker deployment setup
  docs/docs/setup/docker.md
  docs/static/img/setup/docker/bash.gif
  docs/versioned_docs/version-1.x.x/setup/docker.md
  docs/versioned_docs/version-2.0.0/setup/docker.md
  docs/versioned_docs/version-2.1.0/setup/docker.md
  docs/versioned_docs/version-2.10.0/setup/docker.md
  docs/versioned_docs/version-2.11.0/setup/docker.md
  docs/versioned_docs/version-2.2.0/setup/docker.md
  docs/versioned_docs/version-2.3.0/setup/docker.md
  docs/versioned_docs/version-2.4.0/setup/docker.md
  docs/versioned_docs/version-2.5.0/setup/docker.md
  docs/versioned_docs/version-2.6.0/setup/docker.md
  docs/versioned_docs/version-2.7.0/setup/docker.md
  docs/versioned_docs/version-2.8.0/setup/docker.md
  docs/versioned_docs/version-2.9.0/setup/docker.md
  docs/versioned_docs/version-2.9.4/setup/docker.md
Labels: documentation

#6915 Fix: Docker-compose file changes to reduce vulnerability with postgres service
  deploy/docker/.env.external.example
  deploy/docker/.env.internal.example
  deploy/docker/docker-compose-db.yaml
  deploy/docker/docker-compose.yaml
  deploy/docker/external.sh
  deploy/docker/internal.sh
Labels: documented

#7197 [improvement] Add mode to the editor inspector
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
Labels: run-ci, tested, suspend-review-app

#7156 [Hotfix] Flashing login page again after SSO login is success
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/Oauth/Authorize.jsx
  frontend/src/_helpers/utils.js
Labels: run-ci, tested, suspend-review-app

#7190 removing copilot from ce
  frontend/src/Editor/QueryManager/Components/Transformation.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
Labels: run-ci, platform

#7177 [hotfix] Private app slug is redirecting to dashboard. Ideally it should redirect to the app if the user has access to the app
  frontend/src/AppLoader/AppLoader.jsx
  frontend/src/Editor/Viewer.jsx
Labels: run-ci, tested, suspend-review-app

#7214 Modified cypress test for new UI changes
  cypress-tests/cypress/e2e/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/e2e/workspace/profile.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: cypress, run-cypress-workspace

#7221 Fixed platform cypress test cases for marketplace 1.2 release
  cypress-tests/cypress/constants/texts/dataSource.js
  cypress-tests/cypress/e2e/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/e2e/workspace/profile.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: run-cypress-workspace

#7155 [hotfix] Invitation URLs and SSO redirection URLs are not subpath compatible
  frontend/ee/components/LoginPage/GoogleSSOLoginButton.jsx
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/Google.jsx
  server/ee/services/oauth/oauth.service.ts
  server/src/helpers/utils.helper.ts
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/organizations.service.ts
Labels: run-ci, tested

#7067 Bugfix :: Validation errors should only be shown once the user has made a change
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
Labels: run-ci, tested, documented, appbuilder

#7229 [docs]fix failing deployment of v2.12
  docs/versioned_docs/version-2.11.0/widgets/pdf.md
Labels: documentation

#7223 Fix automation for query manager revamp.
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/multipage.js
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/queries.js
  cypress-tests/cypress/support/utils/table.js
  frontend/src/Editor/Inspector/ActionConfigurationPanels/RunjsParamters.jsx
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterDetails.jsx
  frontend/src/Editor/QueryPanel/FilterandSortPopup.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
Labels: data-cy, cypress, run-cypress-app-builder

#7199 [docs] Workspace constants
  docs/docs/org-management/workspaces/workspace-variables.md
  docs/docs/org-management/workspaces/workspace_constants.md
  docs/docs/org-management/workspaces/workspace_overview.md
  docs/sidebars.js
  docs/static/img/workspace-const/createconstant.gif
  docs/static/img/workspace-const/editdelete.png
  docs/static/img/workspace-const/globaldatasource.png
  docs/static/img/workspace-const/inspector.png
  docs/static/img/workspace-const/querypanel.png
  docs/versioned_docs/version-2.10.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.11.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.12.0/org-management/workspaces/workspace-variables.md
  docs/versioned_docs/version-2.12.0/org-management/workspaces/workspace_constants.md
  docs/versioned_docs/version-2.12.0/org-management/workspaces/workspace_overview.md
  docs/versioned_docs/version-2.4.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.5.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.6.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.7.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.8.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.9.0/tutorial/workspace_overview.md
  docs/versioned_docs/version-2.9.4/tutorial/workspace_overview.md
  docs/versioned_sidebars/version-2.12.0-sidebars.json
Labels: documentation

#7203 [docs]query panel revamp
  docs/docs/app-builder/query-panel.md
  docs/static/img/v2-beta/app-builder/querypanel/newui2/add.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/add.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/addquery.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/delete.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/duplicate.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/editor.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/events.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/params.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/preview.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/querymanager.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/querypanel.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/rename.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/renameeditor.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/run.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/search.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/settings.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/sortfilter.gif
  docs/static/img/v2-beta/app-builder/querypanel/newui2/switch.png
  docs/static/img/v2-beta/app-builder/querypanel/newui2/transform.gif
  docs/versioned_docs/version-2.0.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.1.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.10.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.11.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.12.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.2.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.3.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.4.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.5.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.6.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.7.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.8.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.9.0/app-builder/query-panel.md
  docs/versioned_docs/version-2.9.4/app-builder/query-panel.md
Labels: documentation

#7009 web-dev-kushal/issue: #6760
  frontend/src/HomePage/Folders.jsx
Labels: run-ci, tested

#7146 fixes issue #7096 for toggle switches activating in the entire line
  frontend/src/_styles/theme.scss
Labels: tested

#6959 changed placeholder to be consistent with labels
  frontend/assets/translations/en.json
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
Labels: tested

#6966 fixed dark mode inconsistency in query formation dialog box
  frontend/src/Editor/Viewer.jsx
Labels: run-ci, tested

#7166 Refactor/6945 modify tooljet database text
  frontend/src/Editor/QueryManager/constants.js
Labels: run-ci, tested

#6962 Query Panel Fix
  frontend/src/Editor/QueryManager/Components/EmptyGlobalDataSources.jsx
Labels: run-ci, tested

#6967 Add Enter Key Functionality to Execute handleSend on Button Press
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci, tested

#7098 refactor: updation of the text Datasource 101 to Datasources
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
Labels: run-ci, tested

#6753 Allow multi-line editing of Text column in Table component
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#7243 [docs]switch page with params
  docs/docs/actions/switch-page.md
  docs/versioned_docs/version-2.10.0/actions/switch-page.md
  docs/versioned_docs/version-2.11.0/actions/switch-page.md
  docs/versioned_docs/version-2.12.0/actions/switch-page.md
  docs/versioned_docs/version-2.13.0/actions/switch-page.md
  docs/versioned_docs/version-2.3.0/actions/switch-page.md
  docs/versioned_docs/version-2.4.0/actions/switch-page.md
  docs/versioned_docs/version-2.5.0/actions/switch-page.md
  docs/versioned_docs/version-2.6.0/actions/switch-page.md
  docs/versioned_docs/version-2.7.0/actions/switch-page.md
  docs/versioned_docs/version-2.8.0/actions/switch-page.md
  docs/versioned_docs/version-2.9.0/actions/switch-page.md
  docs/versioned_docs/version-2.9.4/actions/switch-page.md
Labels: documentation

#7035 bug:fixed / PasswordInput Component Not Adapting to Dark Mode
  frontend/src/Editor/Components/PasswordInput.jsx
Labels: tested

#7251 Added data-cy for workspace constants elements
  frontend/src/ManageOrgConstants/ConstantForm.jsx
  frontend/src/ManageOrgConstants/ConstantTable.jsx
  frontend/src/ManageOrgConstants/EmptyState.jsx
  frontend/src/ManageOrgConstants/ManageOrgConstants.jsx
Labels: run-ci, data-cy, cypress

#7246 Hotfix: Support MySQL caching sha auth mode
  plugins/package-lock.json
  plugins/packages/mysql/lib/index.ts
  plugins/packages/mysql/package-lock.json
  plugins/packages/mysql/package.json
Labels: run-ci, tested, active-review-app

#7189 Fix :: Migration improvement listview component
  server/data-migrations/1688977149516-ListviewDefaultMode.ts
Labels: appbuilder

#7254 Added cypress test case for workspace constants
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/workspaceConstants.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/workspaceConstants.js
  cypress-tests/cypress/e2e/workspace/workspaceConstants.cy.js
Labels: cypress

#7262 Lint fix: platform 3.0 - updates lock file (removes unwanted deps)
  frontend/src/ToolJetUI/DateRangepicker/index.jsx
  package-lock.json
  package.json
Labels: run-ci

#7270 Fixed failed test cases for platform/v3.0 release
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/e2e/workspace/workspaceConstants.cy.js
  frontend/src/ManageOrgConstants/ConstantForm.jsx
Labels: cypress, run-cypress-workspace

#7237 Added data cy for datasource revamp
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/GlobalDatasources/SegregatedList/index.js
  frontend/src/_components/ConfirmDialog.jsx
Labels: data-cy, cypress

#7271 bugfix - Fixes add constants support to auth headers
  frontend/src/ManageOrgConstants/ConstantForm.jsx
  frontend/src/ManageOrgConstants/EmptyState.jsx
  frontend/src/ManageOrgConstants/ManageOrgConstants.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/Zendesk.jsx
  frontend/src/_ui/HttpHeaders/SourceEditor.jsx
  frontend/src/_ui/HttpHeaders/index.js
  frontend/src/_ui/Input/index.js
  frontend/src/_ui/OAuth/Authentication.jsx
  frontend/src/_ui/OAuth/index.js
  frontend/src/_ui/OpenAPI/Oauth.jsx
  frontend/src/_ui/OpenAPI/index.js
Labels: run-ci, tested, active-review-app

#7274 Platform v3 appbuilder automation fixes.
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
Labels: cypress, run-cypress-app-builder

#7277 [docs]how-to: delete multiple rows in table
  docs/docs/how-to/delete-multiple-rows-table.md
  docs/sidebars.js
  docs/static/img/how-to/delete-rows/bulkselection.png
  docs/static/img/how-to/delete-rows/button.png
  docs/static/img/how-to/delete-rows/delete.png
  docs/static/img/how-to/delete-rows/eventdelete.png
  docs/static/img/how-to/delete-rows/eventrunjs.png
  docs/static/img/how-to/delete-rows/getRecords.png
  docs/static/img/how-to/delete-rows/querydata.png
  docs/static/img/how-to/delete-rows/runjs.png
  docs/static/img/how-to/delete-rows/runjs1.png
  docs/versioned_docs/version-2.10.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.11.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.12.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.13.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.3.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.4.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.5.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.6.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.7.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.8.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.9.0/how-to/delete-multiple-rows-table.md
  docs/versioned_docs/version-2.9.4/how-to/delete-multiple-rows-table.md
  docs/versioned_sidebars/version-2.10.0-sidebars.json
  docs/versioned_sidebars/version-2.11.0-sidebars.json
  docs/versioned_sidebars/version-2.12.0-sidebars.json
  docs/versioned_sidebars/version-2.13.0-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
  docs/versioned_sidebars/version-2.5.0-sidebars.json
  docs/versioned_sidebars/version-2.6.0-sidebars.json
  docs/versioned_sidebars/version-2.7.0-sidebars.json
  docs/versioned_sidebars/version-2.8.0-sidebars.json
  docs/versioned_sidebars/version-2.9.0-sidebars.json
  docs/versioned_sidebars/version-2.9.4-sidebars.json
Labels: documentation

#7285 Added cypress test case for resolving workspace constants on query and components
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/workspaceConstants.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/workspace/workspaceConstants.cy.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/workspaceConstants.js
Labels: cypress, run-cypress-workspace

#7259 Import app, Create app from template and Clone app flow
  frontend/src/Editor/Header/EditAppName.jsx
  frontend/src/Editor/Header/InfoOrErrorBox.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/HomePage/Modal.jsx
  frontend/src/HomePage/TemplateLibraryModal/TemplateLibraryModal.jsx
  frontend/src/_components/AppModal.jsx
  frontend/src/_components/CreateApp.jsx
  frontend/src/_components/RenameApp.jsx
  frontend/src/_components/index.js
  frontend/src/_services/app.service.js
  frontend/src/_services/library-app.service.js
  frontend/src/_styles/theme.scss
  server/src/controllers/app_import_export.controller.ts
  server/src/controllers/apps.controller.ts
  server/src/controllers/library_apps.controller.ts
  server/src/dto/app-clone.dto.ts
  server/src/dto/app-import.dto.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/library_app_creation.service.ts
  server/test/services/app_import_export.service.spec.ts
Labels: run-ci, suspend-review-app

#7007 Workspace crashing on plugins load
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: needs testing, plugins, suspend-review-app

#7150 Feature/restapi ssl options
  frontend/package-lock.json
  package-lock.json
  plugins/packages/restapi/lib/index.ts
  plugins/packages/restapi/lib/manifest.json
  server/package-lock.json
Labels: run-ci, tested, suspend-review-app

#7188 Global Datasource UI flow changes
  cypress-tests/cypress/constants/texts/dataSource.js
  cypress-tests/cypress/constants/texts/postgreSql.js
  frontend/assets/translations/en.json
  frontend/src/App/App.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/DataSourceManager/SourceComponents/index.js
  frontend/src/Editor/DataSourceManager/TestConnection.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/QueryManager/Components/AddGlobalDataSourceButton.jsx
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/GlobalDatasources/CreateDataSource/index.jsx
  frontend/src/GlobalDatasources/CreateDataSourceModal/index.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/LIstItem/index.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/GlobalDatasources/SegregatedList/index.js
  frontend/src/GlobalDatasources/Sidebar/index.jsx
  frontend/src/GlobalDatasources/index.jsx
  frontend/src/_components/ConfirmDialog.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/Profile.jsx
  frontend/src/_helpers/routes.js
  frontend/src/_helpers/utils.js
  frontend/src/_hooks/useGlobalDatasourceUnsavedChanges.js
  frontend/src/_stores/dataSourcesStore.js
  frontend/src/_styles/components.scss
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Card/Card.jsx
  frontend/src/_ui/Header/index.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: run-ci, suspend-review-app, platform

#7070 Fix ::Number input component shows with decimal values instead of the given when applying min and max value
  frontend/src/Editor/Components/NumberInput.jsx
Labels: run-ci, tested, suspend-review-app, documented, appbuilder, product approved

#7343 Added polygon path property to map component
  .version
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  server/.version
Labels: run-ci, tested, active-review-app

#7106 Added horizontal alignment property for each columns in the table to set the horizontal alignment individually
  frontend/assets/translations/en.json
  frontend/src/Editor/Components/Table/Link.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleProperties.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/_styles/custom.scss
  frontend/src/_styles/theme.scss
Labels: feature request, run-ci, tested, suspend-review-app, documented, run-cypress-app-builder

#7247 reword datasource to data source
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/Editor/QueryPanel/FilterandSortPopup.jsx
Labels: run-ci, tested

#7231 [improvement] Improve Code Hinter Performance
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: tested, documented, appbuilder

#7065 Bugfix :: Clicking on custom validation field and clicking outside will set isValid to false
  frontend/src/_helpers/utils.js
Labels: run-ci, tested, documented, appbuilder

#7015 Prevent app re-renders on hovering widgets in canvas
  docs/docs/setup/env-vars.md
  docs/versioned_docs/version-2.8.0/setup/env-vars.md
  docs/versioned_docs/version-2.9.0/actions/generate-file.md
  docs/versioned_docs/version-2.9.0/setup/env-vars.md
  docs/versioned_docs/version-2.9.4/actions/generate-file.md
  docs/versioned_docs/version-2.9.4/setup/env-vars.md
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/editorStore.js
Labels: run-ci, tested

#7276 fix: fallback message added if componentName not passed into CodeHinter
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
Labels: run-ci, tested

#7318 Fixed minor ui issues in query manager
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#7359 fixed checkbox and toogle color
  frontend/src/_styles/theme.scss
Labels: bug, tested

#7365 Hotfix: MySQL ssl connections
  .version
  plugins/packages/mysql/lib/index.ts
  plugins/packages/mysql/package-lock.json
  plugins/packages/mysql/package.json
  server/.version
Labels: active-review-app
