Repository ToolJet/ToolJet, pull requests merged in 2023-06, with the labels that each got.

#6470 [fix] Incorrect edit informations is displayed on app card
  frontend/src/HomePage/AppCard.jsx
Labels: tested

#6299 Workspace name sanitisation
  frontend/src/_components/OrganizationManager/CreateOrganization.jsx
  frontend/src/_components/OrganizationManager/CustomSelect.jsx
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
  frontend/src/_components/OrganizationManager/List.jsx
  frontend/src/_helpers/handle-response.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/theme.scss
  server/ee/services/oauth/oauth.service.ts
  server/migrations/1683136077244-AddUniqueConstraintToWorkspaceName.ts
  server/src/dto/organization.dto.ts
  server/src/entities/organization.entity.ts
  server/src/helpers/db_constraints.constants.ts
  server/src/helpers/utils.helper.ts
  server/src/services/auth.service.ts
  server/src/services/organizations.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/organizations.e2e-spec.ts
  server/test/test.helper.ts
Labels: run-ci, tested, suspend-review-app, documented

#6558 [Fix] typo in inspector
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
Labels: needs testing, run-ci, active-review-app

#6586 fix: Global datasource searchbar and page rename input-box text visibility in dark mode
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/theme.scss
Labels: tested, active-review-app

#6629 templates revamp
  frontend/assets/images/templates/customer-dashboard-dark.png
  frontend/assets/images/templates/customer-dashboard.png
  frontend/assets/images/templates/job-application-tracker-dark.png
  frontend/assets/images/templates/kpi-management-dashboard-dark.png
  frontend/assets/images/templates/kpi-management-dashboard.png
  frontend/assets/images/templates/store-catalogue-management-dashboard-dark.png
  frontend/assets/images/templates/store-catalogue-management-dashboard.png
  server/templates/customer-dashboard/definition.json
  server/templates/job-application-tracker/definition.json
  server/templates/kpi-management-dashboard/definition.json
  server/templates/store-catalogue-management-dashboard/definition.json
Labels: active-review-app

#6642 Fixed auto generated workspace name issue
  server/ee/services/oauth/oauth.service.ts
  server/src/helpers/utils.helper.ts
  server/src/services/auth.service.ts
  server/src/services/organizations.service.ts
  server/test/controllers/app.e2e-spec.ts
Labels: run-ci, tested, active-review-app

#6279 Query Manager Refactor
  frontend/src/CopilotSettings/CopilotSetting.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/QueryManager/Components/AddGlobalDataSourceButton.jsx
  frontend/src/Editor/QueryManager/Components/ChangeDataSource.jsx
  frontend/src/Editor/QueryManager/Components/CustomToggleSwitch.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceLister.jsx
  frontend/src/Editor/QueryManager/Components/EmptyGlobalDataSources.jsx
  frontend/src/Editor/QueryManager/Components/Preview.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/Components/Transformation.jsx
  frontend/src/Editor/QueryManager/Icons/BreadcrumbsIcon.jsx
  frontend/src/Editor/QueryManager/Icons/CreateIcon.jsx
  frontend/src/Editor/QueryManager/Icons/PreviewIcon.jsx
  frontend/src/Editor/QueryManager/Icons/RenameIcon.jsx
  frontend/src/Editor/QueryManager/Icons/RunIcon.jsx
  frontend/src/Editor/QueryManager/Icons/ToggleQueryEditorIcon.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/GroupHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/constants.js
  frontend/src/Editor/QueryManager/index.js
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/dataSourcesStore.js
  frontend/src/_stores/queryPanelStore.js
  frontend/src/_stores/utils.js
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, suspend-review-app, documented

#6423 [enhancement] Sanitising app name while creating or editing an app
  frontend/assets/translations/en.json
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/EditAppName.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/HomePage/HomePage.jsx
  server/data-migrations/1684157120658-AddUniqueConstraintToAppName.ts
  server/src/dto/app-update.dto.ts
  server/src/helpers/db_constraints.constants.ts
  server/src/helpers/utils.helper.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/library_apps.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
Labels: run-ci, tested, suspend-review-app, documented

#6420 fixes: on bulk-updating users with csv, the data is not reflected
  frontend/src/ManageOrgUsers/FileDropzone.jsx
  server/src/services/organizations.service.ts
Labels: run-ci, tested, active-review-app, platform

#6396 Sanitising workspace folder name while creating or editing a folder
  frontend/assets/translations/de.json
  frontend/assets/translations/en.json
  frontend/assets/translations/es.json
  frontend/assets/translations/fr.json
  frontend/assets/translations/id.json
  frontend/assets/translations/it.json
  frontend/assets/translations/ru.json
  frontend/assets/translations/uk.json
  frontend/src/HomePage/Folders.jsx
  frontend/src/_styles/theme.scss
  server/migrations/1684145489093-AddUniqueConstraintToFolderName.ts
  server/src/dto/create-folder.dto.ts
  server/src/entities/folder.entity.ts
  server/src/helpers/db_constraints.constants.ts
  server/src/helpers/utils.helper.ts
  server/src/services/folders.service.ts
  server/test/controllers/folders.e2e-spec.ts
  server/test/services/folder_apps.service.spec.ts
Labels: run-ci, tested, suspend-review-app, documented

#6670 testing cypress workflow
  .github/workflows/cypress.yml
  .github/workflows/render-preview-deploy-pro.yml
  .github/workflows/render-preview-deploy.yml
Labels: active-review-app

#6672 Resolved latest lint issue
  server/src/helpers/utils.helper.ts
Labels: run-ci, active-review-app

#6436 Row selection revamp
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/actions.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: feature request, run-ci, tested, documented, run-cypress, suspend-review-cypress-app

#6325 Added feature to toggle the visibility of columns programmatically
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
Labels: feature request, run-ci, tested, suspend-review-app, documented

#6301 Detach modal button height property from modal height
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, suspend-review-app, documented

#6393 [fix] Deprecated css code errors
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#6682 [docs] updated `ssoUserInfo` in openid
  docs/docs/user-authentication/sso/openid/setup.md
  docs/static/img/sso/openid/ssouserinfo.png
  docs/versioned_docs/version-2.6.0/user-authentication/sso/openid/setup.md
Labels: documentation

#6287 Page clone feature
  frontend/assets/images/icons/clone.svg
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
Labels: run-ci, tested, documented

#6681 [docs] ToolJet CLI v0.0.14
  docs/docs/contributing-guide/marketplace/creating-a-plugin.md
  docs/docs/contributing-guide/marketplace/marketplace-setup.md
  docs/docs/tooljetcli.md
  docs/sidebars.js
  docs/static/img/tooljet-cli/create.gif
  docs/static/img/tooljet-cli/delete.gif
  docs/static/img/tooljet-cli/info.png
  docs/static/img/tooljet-cli/install.png
  docs/static/img/tooljet-cli/version.png
  docs/versioned_docs/version-2.3.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.4.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.5.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.6.0/contributing-guide/marketplace/marketplace-setup.md
Labels: documentation

#6703 [docs] mariadb revamp
  docs/docs/data-sources/mariadb.md
  docs/static/img/datasource-reference/mariadb/connections.png
  docs/static/img/datasource-reference/mariadb/deleteuser.png
  docs/static/img/datasource-reference/mariadb/gdsmaria.gif
  docs/static/img/datasource-reference/mariadb/insertuser.png
  docs/static/img/datasource-reference/mariadb/insertusers.png
  docs/static/img/datasource-reference/mariadb/querycreate.png
  docs/static/img/datasource-reference/mariadb/readall.png
  docs/static/img/datasource-reference/mariadb/readcolumn.png
  docs/static/img/datasource-reference/mariadb/readfilter.png
  docs/static/img/datasource-reference/mariadb/updateuser.png
  docs/versioned_docs/version-2.3.0/data-sources/mariadb.md
  docs/versioned_docs/version-2.4.0/data-sources/mariadb.md
  docs/versioned_docs/version-2.5.0/data-sources/mariadb.md
  docs/versioned_docs/version-2.6.0/data-sources/mariadb.md
Labels: documentation

#6392 Feature :: Dropdown widget enhancement
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested, suspend-review-app, documented, appbuilder, run-cypress-app-builder, suspend-review-cypress-app

#6702 fix: retain query param on redirection to home page from base url
  frontend/src/Editor/Viewer.jsx
Labels: tested, documented

#6659 Improving user experience of left side drawer in app builder
  frontend/src/Editor/CustomDragLayer.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarItem.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/_hooks/useWindowResize.js
  frontend/src/_styles/custom.scss
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Popover/index.jsx
Labels: tested, suspend-review-app, documented

#6711 Modal crashing while loading state is turned on
  frontend/src/Editor/Components/Modal.jsx
Labels: run-ci, tested, documented, appbuilder, run-cypress-app-builder, active-review-cypress-app

#6713 Fix :: Component specific actions (CSA) not executing
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, documented, appbuilder, run-cypress-app-builder, active-review-cypress-app

#6675 fix: Rename widget to component
  frontend/src/Editor/Inspector/Components/Chart.jsx
  frontend/src/Editor/Inspector/Components/CustomComponent.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/_helpers/createWalkThrough.js
Labels: run-ci, tested, active-review-app

#6699 fix: Added onKeyDown function for input field
  frontend/src/_components/OrganizationManager/CreateOrganization.jsx
Labels: run-ci, tested, active-review-app

#6620 removed event manager text
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci, tested, active-review-app

#6474 cursor pointer added fixes #6121
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, active-review-app

#6722 fix: public app which from non-access workspace redirecting to the login page
  server/src/controllers/app.controller.ts
  server/src/services/users.service.ts
Labels: run-ci, tested, suspend-review-app

#6663 Added data-cy for global settings and release button
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
Labels: data-cy

#6651 Added data-cy for codehinder popup
  frontend/src/_components/Portal/Portal.jsx
  frontend/src/_hooks/use-portal.jsx
Labels: data-cy

#6736 [docs] dynamodb revamp
  docs/docs/data-sources/dynamodb.md
  docs/static/img/datasource-reference/dynamodb/deleteitem.png
  docs/static/img/datasource-reference/dynamodb/dynamogds.gif
  docs/static/img/datasource-reference/dynamodb/getitem.png
  docs/static/img/datasource-reference/dynamodb/iam.png
  docs/static/img/datasource-reference/dynamodb/listtables.png
  docs/static/img/datasource-reference/dynamodb/querytable.png
  docs/static/img/datasource-reference/dynamodb/scantable.png
  docs/versioned_docs/version-2.0.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.1.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.2.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.3.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.4.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.5.0/data-sources/dynamodb.md
  docs/versioned_docs/version-2.6.0/data-sources/dynamodb.md
Labels: documentation

#6715 [docs] audit logs update
  docs/docs/Enterprise/audit_logs.md
  docs/static/img/enterprise/audit_logs/filtersnew.png
  docs/static/img/enterprise/audit_logs/logsnew copy.png
  docs/static/img/enterprise/audit_logs/logsnew.png
  docs/versioned_docs/version-2.6.0/Enterprise/audit_logs.md
Labels: documentation

#6239 Fixed and Modified the popup UI
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/Viewer/Confirm.jsx
Labels: run-ci, tested, active-review-app

#6268 Bugfix - handles plugins to move from gds to lds when importing app to different workspaces
  frontend/src/Editor/Editor.jsx
  server/src/services/app_import_export.service.ts
Labels: run-ci, plugins, tested, documented

#6454 Bugfix - source options are lost on save in client
  plugins/packages/gcs/lib/manifest.json
  plugins/packages/twilio/lib/index.ts
  plugins/packages/twilio/lib/manifest.json
  plugins/packages/twilio/lib/operations.json
  plugins/packages/twilio/lib/types.ts
  plugins/packages/typesense/lib/manifest.json
Labels: run-ci, tested, suspend-review-app, platform

#6733 Upgraded snowflake sdk
  plugins/package-lock.json
  plugins/packages/snowflake/package-lock.json
  plugins/packages/snowflake/package.json
Labels: run-ci, tested, active-review-app

#6752 Modified cypress test to verify the visibility of the public for the same instance user
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/onboarding.js
Labels: cypress

#6745 Fix failing version cypress spec
  cypress-tests/cypress/constants/selectors/version.js
  cypress-tests/cypress/constants/texts/version.js
  cypress-tests/cypress/support/utils/version.js
Labels: cypress

#6671 Added cypress test for bulk user upload
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/e2e/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/fixtures/bulkUser/500_invite_users - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/empty_first_and_last_name - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/invalid_group_name - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/invite_users - Sheet1 .csv
  cypress-tests/cypress/fixtures/bulkUser/multiple_groups - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/non_existing_group -Sheet1 .csv
  cypress-tests/cypress/fixtures/bulkUser/same_email - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/without_email - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/without_firstname - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/without_group - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/without_lastname - Sheet1.csv
  cypress-tests/cypress/fixtures/bulkUser/without_name - Sheet1.csv
  cypress-tests/cypress/support/utils/manageUsers.js
  frontend/src/ManageOrgUsers/FileDropzone.jsx
Labels: suspend-review-app, data-cy, cypress, run-cypress-workspace

#6766 hot fix: pr cypress app
  .github/workflows/render-preview-deploy-pro.yml
Labels: active-review-cypress-app

#6761 [docs] copilot update
  docs/docs/copilot.md
  docs/versioned_docs/version-2.7.0/copilot.md
Labels: documentation

#6763 Query switching with the same type not working
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
Labels: run-ci, tested

#6774 Bugfix :: Dropdown widget theme during disabled state
  frontend/src/Editor/Components/DropDown.jsx
Labels: run-ci, tested

#6778 Database drawer is not opening from the left sidebar
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
Labels: bug, run-ci, tested

#6758 Made switch page action to execute in release 2.7.0
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: bug, run-ci, tested, suspend-review-app

#6781 Fixed workspace cypress v2.7.0
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
Labels: run-cypress-workspace, active-review-cypress-app

#6788 onCellValueChanged event is fired upon change in the cell value in table
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested

#6783 Csa for deselect row is not working when bulk selection is toggled on
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested

#6792 App builder cypress fix for 2.7.0
  cypress-tests/cypress/constants/selectors/multipage.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/exportImport.js
Labels: cypress, run-cypress-app-builder, active-review-cypress-app

#6796 Fixed cypress app builder v2.7.0
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/commands.js
Labels: cypress, run-cypress-app-builder, active-review-cypress-app

#6798 fix: disable hiding home page
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/Viewer.jsx
Labels: tested

#6773 updated: how-to use to_py
  docs/docs/how-to/use-to-py.md
  docs/static/img/how-to/to_py/topy.gif
  docs/versioned_docs/version-2.0.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.1.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.2.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.3.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.4.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.5.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.6.0/how-to/use-to-py.md
Labels: documentation

#6836 [docs] openapi revamp
  docs/docs/data-sources/openapi.md
  docs/static/img/datasource-reference/openapi/openapiconnect.gif
  docs/static/img/datasource-reference/openapi/query.png
  docs/versioned_docs/version-2.3.0/data-sources/openapi.md
  docs/versioned_docs/version-2.4.0/data-sources/openapi.md
  docs/versioned_docs/version-2.5.0/data-sources/openapi.md
  docs/versioned_docs/version-2.6.0/data-sources/openapi.md
  docs/versioned_docs/version-2.7.0/data-sources/openapi.md
Labels: documentation

#6697 [docs]setup on azure container apps
  docs/docs/setup/azure-container.md
  docs/sidebars.js
  docs/src/components/DocsCard/DocsCard.jsx
  docs/static/img/setup/azure-container/step1.png
  docs/static/img/setup/azure-container/step2.png
  docs/static/img/setup/azure-container/step3.png
  docs/static/img/setup/azure-container/step3a.png
  docs/static/img/setup/azure-container/step4.png
  docs/static/img/setup/azure-container/step5.png
  docs/static/img/setup/azure-container/step6.png
  docs/static/img/setup/icons/azure-container.svg
  docs/versioned_docs/version-1.x.x/setup/azure-container.md
  docs/versioned_docs/version-2.0.0/setup/azure-container.md
  docs/versioned_docs/version-2.1.0/setup/azure-container.md
  docs/versioned_docs/version-2.2.0/setup/azure-container.md
  docs/versioned_docs/version-2.3.0/setup/azure-container.md
  docs/versioned_docs/version-2.4.0/setup/azure-container.md
  docs/versioned_docs/version-2.5.0/setup/azure-container.md
  docs/versioned_docs/version-2.6.0/setup/azure-container.md
  docs/versioned_docs/version-2.7.0/setup/azure-container.md
  docs/versioned_sidebars/version-1.x.x-sidebars.json
  docs/versioned_sidebars/version-2.0.0-sidebars.json
  docs/versioned_sidebars/version-2.1.0-sidebars.json
  docs/versioned_sidebars/version-2.2.0-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
  docs/versioned_sidebars/version-2.5.0-sidebars.json
  docs/versioned_sidebars/version-2.6.0-sidebars.json
  docs/versioned_sidebars/version-2.7.0-sidebars.json
Labels: documentation

#6846 [docs] contributing guide/setup/windows
  docs/docs/contributing-guide/setup/windows.md
  docs/sidebars.js
  docs/static/img/contributing-guide/windows/wsl2.png
  docs/versioned_docs/version-1.x.x/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.2.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.3.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.4.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.5.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.6.0/contributing-guide/setup/windows.md
  docs/versioned_docs/version-2.7.0/contributing-guide/setup/windows.md
  docs/versioned_sidebars/version-1.x.x-sidebars.json
  docs/versioned_sidebars/version-2.0.0-sidebars.json
  docs/versioned_sidebars/version-2.1.0-sidebars.json
  docs/versioned_sidebars/version-2.2.0-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
  docs/versioned_sidebars/version-2.5.0-sidebars.json
  docs/versioned_sidebars/version-2.6.0-sidebars.json
  docs/versioned_sidebars/version-2.7.0-sidebars.json
Labels: documentation

#6847 [docs] setup/helm
  docs/docs/setup/helm.md
  docs/sidebars.js
  docs/src/components/DocsCard/DocsCard.jsx
  docs/static/img/setup/icons/helm.svg
  docs/versioned_docs/version-1.x.x/setup/helm.md
  docs/versioned_docs/version-2.0.0/setup/helm.md
  docs/versioned_docs/version-2.1.0/setup/helm.md
  docs/versioned_docs/version-2.2.0/setup/helm.md
  docs/versioned_docs/version-2.3.0/setup/helm.md
  docs/versioned_docs/version-2.4.0/setup/helm.md
  docs/versioned_docs/version-2.5.0/setup/helm.md
  docs/versioned_docs/version-2.6.0/setup/helm.md
  docs/versioned_docs/version-2.7.0/setup/helm.md
  docs/versioned_sidebars/version-1.x.x-sidebars.json
  docs/versioned_sidebars/version-2.0.0-sidebars.json
  docs/versioned_sidebars/version-2.1.0-sidebars.json
  docs/versioned_sidebars/version-2.2.0-sidebars.json
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
  docs/versioned_sidebars/version-2.5.0-sidebars.json
  docs/versioned_sidebars/version-2.6.0-sidebars.json
  docs/versioned_sidebars/version-2.7.0-sidebars.json
Labels: documentation

#6815 [docs]harperdb plugin
  docs/docs/marketplace/plugins/harperdb.md
  docs/sidebars.js
  docs/static/img/marketplace/plugins/harperdb/creds.png
  docs/static/img/marketplace/plugins/harperdb/delete.png
  docs/static/img/marketplace/plugins/harperdb/harperconnect.gif
  docs/static/img/marketplace/plugins/harperdb/insert.png
  docs/static/img/marketplace/plugins/harperdb/query.png
  docs/static/img/marketplace/plugins/harperdb/select.png
  docs/static/img/marketplace/plugins/harperdb/update.png
Labels: documentation

#6755 improvement - check for Conflicting Group Memberships in Bulk uploading users from csv
  server/src/services/organizations.service.ts
Labels: run-ci, tested, suspend-review-app, platform

#6857 [docs] revamped gsheet
  docs/docs/data-sources/google.sheets.md
  docs/static/img/datasource-reference/google-sheets/del.png
  docs/static/img/datasource-reference/google-sheets/infoo.png
  docs/static/img/datasource-reference/google-sheets/operations.png
  docs/static/img/datasource-reference/google-sheets/sheetconnect.gif
  docs/static/img/datasource-reference/google-sheets/upd.png
  docs/versioned_docs/version-2.3.0/data-sources/google.sheets.md
  docs/versioned_docs/version-2.4.0/data-sources/google.sheets.md
  docs/versioned_docs/version-2.5.0/data-sources/google.sheets.md
  docs/versioned_docs/version-2.6.0/data-sources/google.sheets.md
  docs/versioned_docs/version-2.7.0/data-sources/google.sheets.md
  docs/versioned_docs/version-2.8.0/data-sources/google.sheets.md
Labels: documentation

#6858 [docs] fix harperdb
  docs/docs/marketplace/plugins/harperdb.md
  docs/versioned_docs/version-2.8.0/marketplace/plugins/harperdb.md
Labels: documentation

#6795 Feature/harperdb plugin no sql
  marketplace/plugins/harperdb/lib/index.ts
  marketplace/plugins/harperdb/lib/operations.json
  marketplace/plugins/harperdb/lib/types.ts
Labels: run-ci, suspend-review-app

#6708 Updated automation script for table with new features
  cypress-tests/cypress/constants/selectors/table.js
  cypress-tests/cypress/constants/texts/table.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/inspector.js
  cypress-tests/cypress/support/utils/table.js
Labels: cypress

#6868 [docs] Run only if option
  docs/docs/widgets/overview.md
  docs/static/img/widgets/overview/admin.png
  docs/static/img/widgets/overview/isvalid.png
Labels: documentation

#6805 Fix for nested widget issue on cloned pages
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
Labels: run-ci, tested, documented

#6540 Fix :: Redirection to homepage of link widget when target is none and switch page event is attached
  frontend/src/Editor/Components/Link.jsx
Labels: tested, documented, appbuilder

#6555 feat: update preview page url as well when user edits page handle
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
Labels: tested, suspend-review-app, documented

#6559 fix: added duplicate check for page name and handle
  frontend/src/Editor/Editor.jsx
Labels: tested, suspend-review-app, documented

#6618 Bug fixed : export with two identical column titles fills data in wrong column
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested, documented, run-cypress-app-builder, suspend-review-cypress-app

#6729 bug fixed : changeSet getting updated without changing the value in the table
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: bug, tested, documented

#6718 Showing page "1 of 1 " instead of "1 of 0" when no data is available in the table for client side pagination
  frontend/src/Editor/Components/Table/Pagination.jsx
Labels: bug, run-ci, tested, documented

#6705 Codehinter portal is not getting closed after clicking inside it for go to app action
  frontend/src/Editor/Inspector/ActionConfigurationPanels/GotoApp.jsx
  frontend/src/_components/Portal/Portal.jsx
Labels: bug, run-ci, tested, documented

#6391 feat: conditional execution of even handler functions
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, active-review-app, documented

#6802 Bugfix :: Box shadow is getting applied to the surrounding box
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/BoundedBox/BoundedBox.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/ButtonGroup.jsx
  frontend/src/Editor/Components/Calendar.jsx
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/Checkbox.jsx
  frontend/src/Editor/Components/CirularProgressbar.jsx
  frontend/src/Editor/Components/CodeEditor.jsx
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/DaterangePicker.jsx
  frontend/src/Editor/Components/Divider.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/Form.jsx
  frontend/src/Editor/Components/Html.jsx
  frontend/src/Editor/Components/IFrame.jsx
  frontend/src/Editor/Components/Icon.jsx
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/Components/Kanban/Kanban.jsx
  frontend/src/Editor/Components/Link.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PDF.jsx
  frontend/src/Editor/Components/Pagination.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/QrScanner/QrScanner.jsx
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Components/RangeSlider.jsx
  frontend/src/Editor/Components/RichTextEditor.jsx
  frontend/src/Editor/Components/Spinner.jsx
  frontend/src/Editor/Components/StarRating/index.js
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/Steps.jsx
  frontend/src/Editor/Components/SvgImage.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/Tags.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/Timeline.jsx
  frontend/src/Editor/Components/Timer.jsx
  frontend/src/Editor/Components/Toggle.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/Components/verticalDivider.jsx
Labels: tested, documented

#6814 Bugfix :: Homepage appcard button having uneven margin
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app, documented

#6593 Move Editor's version manager regarding states to zustand store
  frontend/src/Editor/AppVersionsManager/CreateVersionModal.jsx
  frontend/src/Editor/AppVersionsManager/List.jsx
  frontend/src/Editor/AppVersionsManager/ReleasedVersionError.jsx
  frontend/src/Editor/CommentNotifications/index.jsx
  frontend/src/Editor/Comments.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/RealtimeCursors.jsx
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager.jsx
  frontend/src/_components/SortableList/SortableList.jsx
  frontend/src/_components/SortableList/index.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/appVersionStore.js
  frontend/src/_stores/dataQueriesStore.js
Labels: tested, documented, run-cypress-app-builder, active-review-cypress-app

#6879 [docs] plotly bar mode
  docs/docs/widgets/chart.md
  docs/static/img/widgets/chart/barmodes.png
Labels: documentation

#6286 Added bar type option to chart widget
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Inspector/Components/Chart.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: tested, suspend-review-app, documented, appbuilder

#6886 Hotfix - passes correct state to preview query
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, hotfix, appbuilder

#6820 [ hotfix ] Bug fixed, not able to edit column type text when action button is present in the row in the table component
  .version
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/actions.jsx
  frontend/src/_styles/theme.scss
  server/.version
Labels: bug, run-ci, tested, hotfix
