Repository ToolJet/ToolJet, pull requests merged in 2023-12, with the labels that each got.

#8237 [docs]revamp how-to: bulk update multiple rows
  docs/docs/how-to/bulk-update-multiple-rows-in-table.md
  docs/static/img/how-to/bulk-update-multiple/new/data.png
  docs/static/img/how-to/bulk-update-multiple/new/editable.png
  docs/static/img/how-to/bulk-update-multiple/new/populate.png
  docs/static/img/how-to/bulk-update-multiple/new/querysuccess.png
  docs/static/img/how-to/bulk-update-multiple/new/rowselect.png
  docs/static/img/how-to/bulk-update-multiple/new/runjs1.png
  docs/static/img/how-to/bulk-update-multiple/new/savechanges.png
  docs/static/img/how-to/bulk-update-multiple/new/update.png
  docs/versioned_docs/version-2.16.0/how-to/bulk-update-multiple-rows-in-table.md
  docs/versioned_docs/version-2.17.0/how-to/bulk-update-multiple-rows-in-table.md
  docs/versioned_docs/version-2.18.0/how-to/bulk-update-multiple-rows-in-table.md
  docs/versioned_docs/version-2.19.0/how-to/bulk-update-multiple-rows-in-table.md
  docs/versioned_docs/version-2.22.0/how-to/bulk-update-multiple-rows-in-table.md
  docs/versioned_docs/version-2.23.0/how-to/bulk-update-multiple-rows-in-table.md
Labels: documentation

#8238 Code coverage test PR
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/editor/data-source/azureBlobStorageHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/clickHouseHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/cosmosDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/couchDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/influxDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mariaDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/oracleDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/postgresHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/rethinkDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sapHanaHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sqlServerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/regressionSuite/appBuilder/queryPanel/queryEditorRegression.cy.js
Labels: do not merge, check-coverage

#8247 [hotfix] Public app is not loading on subpath deployment.
  frontend/src/_helpers/routes.js
Labels: tested

#8257 Marketplace 1.5 automation fix for Appbuilder
  cypress-tests/cypress/constants/texts/button.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/datePicker.js
  cypress-tests/cypress/constants/texts/multiselect.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
Labels: cypress, run-cypress-app-builder

#8258 [hotfix ]fix: event mapping query race condition
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
Labels: tested, run-cypress

#7412 [Refactor]7380 - Improve performance by preventing states used as prop when not necessary
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/EditorKeyHooks.jsx
  frontend/src/Editor/EditorSelecto.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/RightSidebarTabManager.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetBox.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_helpers/websocketConnection.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/currentStateStore.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/editorStore.js
Labels: run-ci, tested, suspend-review-app, run-cypress, run-cypress-app-builder

#7304 Bug Fix : query panel search box component close icon
  frontend/src/_components/SearchBox.jsx
Labels: bug, tested

#7462 Show type error message in codehinter preview if any
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/component-properties-validation.js
Labels: feature request, run-ci, tested

#7439 Discard add new row csa , discards newly added rows from current state
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested, Table component

#7505 Feature :: Controlling form children through CSA
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, appbuilder

#7516 Show listItem in suggestions and interpret it in event handler codehinter previews
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/_components/SearchBox.jsx
Labels: run-ci, tested, appbuilder

#7856 Made column header positioning consistent while dragging the header to change its order in table
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested

#8033 Discarding the searched term when clicked on cross icon in search box element in the table
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
Labels: run-ci, tested, documented, Table component

#7395 Fixed page options clicks issue
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/RenameInput.jsx
  frontend/src/_ui/LeftSidebar/Button.jsx
Labels: bug, run-ci, tested, suspend-review-app

#7381 fixed query failed empty toast issue
  frontend/src/_helpers/appUtils.js
Labels: bug, run-ci, tested

#7437 Fixed empty error logs on debugger
  frontend/src/Editor/LeftSidebar/SidebarDebugger/Logs.jsx
Labels: bug, run-ci, tested

#7451 Fixed undo app name issue
  frontend/src/Editor/Header/EditAppName.jsx
Labels: bug, run-ci, tested

#7442 Query preview is updating whenever a query is run
  frontend/src/Editor/QueryManager/Components/Preview.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/_helpers/appUtils.js
Labels: feature request, run-ci, tested

#8081 Bugfix :: Listview pagination not showing correct pagination details
  frontend/src/Editor/Components/Listview.jsx
Labels: run-ci, tested, appbuilder

#8001 Horizontal alignment getting applied properly for string, number , text and badge column type in the table
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: bug, run-ci, tested, Table component

#7415 Fixed Number Input Field Issue.
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/Text.jsx
Labels: bug, tested

#8167 Selected row [Table] in the current state is persisting upon change in the theme
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, needs testing, run-ci

#8153 Bugfix :: Resolving Issue with comments not displaying during walkthrough
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger/Logs.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/RenameInput.jsx
  frontend/src/Editor/WidgetManager.jsx
  frontend/src/_helpers/createWalkThrough.js
Labels: run-ci, tested, appbuilder

#8286 App Builder automation fixed for appbuilder-1.4
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
Labels: cypress

#8283 Bugfixes:: Form child csa and form listing twice in inspector
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: tested

#8289 [docs] change related to accessibility of released apps
  docs/docs/actions/go-to-app.md
  docs/docs/app-builder/share.md
  docs/docs/app-builder/toolbar.md
  docs/static/img/actions/gotoapp/gotoapp3.png
  docs/versioned_docs/version-2.22.0/actions/go-to-app.md
  docs/versioned_docs/version-2.22.0/app-builder/share.md
  docs/versioned_docs/version-2.22.0/app-builder/toolbar.md
  docs/versioned_docs/version-2.23.0/actions/go-to-app.md
  docs/versioned_docs/version-2.23.0/app-builder/share.md
  docs/versioned_docs/version-2.23.0/app-builder/toolbar.md
Labels: documentation

#8132 Enhancement :: Password input updated according to new design
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: suspend-review-app, appbuilder

#8296 [docs] minor changes in v2.25
  docs/versioned_docs/version-2.25.0/actions/go-to-app.md
  docs/versioned_docs/version-2.25.0/app-builder/share.md
  docs/versioned_docs/version-2.25.0/app-builder/toolbar.md
Labels: documentation

#8292 Fixes: versioning is not working when queries in an app version has only GDS queries
  server/src/services/apps.service.ts
Labels: tested

#8294 Appbuilder 1.4 automation fixedfor form
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/support/utils/basicComponents.js
Labels: cypress

#8301 AppBuilder-1.4 automation fixed for drag component
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
Labels: cypress

#8302 Table column popover is not hiding behind query panel
  frontend/src/_styles/theme.scss
Labels: bug, tested

#8279 Filtering out null and undefined values from array fed to table as data
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, hotfix, Table component

#8309 [Hotfix] Table component column generations issues
  frontend/src/_helpers/appUtils.js
  server/src/services/components.service.ts
Labels: run-ci, tested, hotfix, appbuilder

#8290 Fixed failing cypress test cases on action
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/ce/appSlug.cy.js
  cypress-tests/cypress/e2e/ce/privateAndPublicApp.cy.js
  cypress-tests/cypress/e2e/ce/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/workspace/workspace.cy.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: do not merge, cypress, run-cypress-workspace

#8295 bugfix: airtable plugin support for personal access token
  plugins/packages/airtable/lib/index.ts
  plugins/packages/airtable/lib/manifest.json
  plugins/packages/airtable/lib/types.ts
Labels: do not merge, needs testing, run-ci, plugins, active-review-app

#8320 Fix edApp Builder automation for v2.26.1
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/support/utils/basicComponents.js
Labels: cypress

#8322 Merge main back to develop (v2.26.1)
  .version
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/ce/appSlug.cy.js
  cypress-tests/cypress/e2e/ce/privateAndPublicApp.cy.js
  cypress-tests/cypress/e2e/ce/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/e2e/workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/workspace/workspace.cy.js
  cypress-tests/cypress/support/utils/basicComponents.js
  cypress-tests/cypress/support/utils/userPermissions.js
  frontend/.version
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_helpers/appUtils.js
  server/.version
  server/src/services/components.service.ts
Labels: run-ci

#8128 [Imp] Auto-removing query params from redirect urls (While login to the application)
  frontend/src/Editor/Editor.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/_components/PrivateRoute.jsx
  frontend/src/_helpers/routes.js
  frontend/src/_services/authentication.service.js
Labels: tested, suspend-review-app

#8133 [fix] Rendering all apps inside a folder after the app rename.
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_ui/Breadcrumbs/index.jsx
Labels: tested

#8299 [fix] Sometimes the workspace modal CTA is in disabled state even if the values are correct
  frontend/src/_components/OrganizationManager/CreateOrganization.jsx
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
Labels: tested

#8235 Fix MariaDB connection issues
  frontend/src/GlobalDatasources/index.jsx
  frontend/src/_components/DynamicForm.jsx
  plugins/packages/mariadb/lib/index.ts
Labels: tested, suspend-review-app

#8171 Save button on Datasource changes not enabled
  frontend/src/_ui/HttpHeaders/index.js
Labels: tested

#8223 Constants resolution of encrypted fields on saved global datasources
  server/src/services/data_sources.service.ts
Labels: tested

#8305 [fix] `Websocket unavailable` issue when the user tries to release the version before the connection is established
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/_hooks/use-socket-open.jsx
Labels: tested

#8274 Revamp Global Data sources
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/SegregatedList/index.js
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/EncyrptedFieldWrapper.jsx
  frontend/src/_components/Zendesk.jsx
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/EyeClosed.jsx
  frontend/src/_ui/Input/index.js
  frontend/src/_ui/OAuth/Authentication.jsx
  frontend/src/_ui/OAuth/index.js
  plugins/packages/n8n/lib/manifest.json
  plugins/packages/zendesk/lib/manifest.json
Labels: tested, suspend-review-app, design-approved

#8169 Fix for handling 'go to app' event for previously added unreleased apps and new apps
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/_components/ErrorComponents/ErrorPage.jsx
  frontend/src/_helpers/constants.js
  frontend/src/_helpers/handleAppAccess.js
  server/src/controllers/apps.controller.ts
Labels: tested

#8351 [hotfix] The private app is not redirected to the login page when the user doesn't have any valid session
  frontend/src/Editor/Viewer.jsx
Labels: tested, run-cypress-workspace

#8354 [Hotfix] cloning/duplicating component from widget inspector header actions menu
  .version
  frontend/.version
  frontend/src/Editor/Editor.jsx
  server/.version
Labels: tested, hotfix, appbuilder

#8358 [docs] updates in gitsync doc
  docs/docs/gitsync.md
  docs/static/img/gitsync/connect.png
  docs/static/img/gitsync/deleteconfig.png
  docs/static/img/gitsync/git2.png
  docs/static/img/gitsync/git5.png
  docs/static/img/gitsync/gitsync.png
  docs/static/img/gitsync/modalgit.png
  docs/versioned_docs/version-2.24.0/gitsync.md
  docs/versioned_docs/version-2.25.0/gitsync.md
Labels: documentation

#8323 [docs] added how-to: use events on chart
  docs/docs/how-to/use-events-on-chart.md
  docs/docs/widgets/chart.md
  docs/sidebars.js
  docs/static/img/how-to/events-chart/plotly-chart.png
  docs/versioned_docs/version-2.23.0/how-to/use-events-on-chart.md
  docs/versioned_docs/version-2.23.0/widgets/chart.md
  docs/versioned_docs/version-2.24.0/how-to/use-events-on-chart.md
  docs/versioned_docs/version-2.24.0/widgets/chart.md
  docs/versioned_docs/version-2.25.0/how-to/use-events-on-chart.md
  docs/versioned_docs/version-2.25.0/widgets/chart.md
  docs/versioned_sidebars/version-2.23.0-sidebars.json
  docs/versioned_sidebars/version-2.24.0-sidebars.json
  docs/versioned_sidebars/version-2.25.0-sidebars.json
Labels: documentation

#8226 [chore] Node-module vulnerabilities
  .github/workflows/ci.yml
  .github/workflows/cypress-appbuilder.yml
  .github/workflows/cypress-platform.yml
  .nvmrc
  cli/package-lock.json
  cypress-tests/package-lock.json
  deploy/ec2/setup_machine.sh
  docker/client.Dockerfile.dev
  docker/plugins.Dockerfile.dev
  docker/preview.Dockerfile
  docker/production.Dockerfile
  docker/server.Dockerfile
  docker/server.Dockerfile.dev
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/_components/PrivateRoute.jsx
  marketplace/package-lock.json
  marketplace/package.json
  package-lock.json
  package.json
  plugins/package-lock.json
  plugins/package.json
  plugins/packages/bigquery/package-lock.json
  plugins/packages/bigquery/package.json
  plugins/packages/firestore/package-lock.json
  plugins/packages/firestore/package.json
  plugins/packages/grpc/package-lock.json
  plugins/packages/grpc/package.json
  plugins/packages/minio/lib/index.ts
  plugins/packages/minio/lib/operations.ts
  plugins/packages/minio/package-lock.json
  plugins/packages/minio/package.json
  plugins/packages/snowflake/package-lock.json
  plugins/packages/snowflake/package.json
  plugins/packages/twilio/package-lock.json
  plugins/packages/twilio/package.json
  server/package-lock.json
  server/package.json
  server/src/events/events.gateway.ts
  server/test/controllers/oauth/oauth-git-instance.e2e-spec.ts
  server/test/controllers/oauth/oauth-git.e2e-spec.ts
  server/test/controllers/tooljet_db.e2e-spec.ts
Labels: do not merge, run-ci, suspend-review-app, documented, run-cypress, run-cypress-app-builder

#8265 aws-lambda plugin
  marketplace/package-lock.json
  marketplace/plugins/aws-lambda/.gitignore
  marketplace/plugins/aws-lambda/README.md
  marketplace/plugins/aws-lambda/__tests__/index.js
  marketplace/plugins/aws-lambda/lib/icon.svg
  marketplace/plugins/aws-lambda/lib/index.ts
  marketplace/plugins/aws-lambda/lib/manifest.json
  marketplace/plugins/aws-lambda/lib/operations.json
  marketplace/plugins/aws-lambda/lib/types.ts
  marketplace/plugins/aws-lambda/package.json
  marketplace/plugins/aws-lambda/tsconfig.json
  server/src/assets/marketplace/plugins.json
Labels: tested, suspend-review-app

#8377 Fixes UI and test connection issues
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/HttpHeaders/QueryEditor.jsx
  frontend/src/_ui/HttpHeaders/SourceEditor.jsx
  frontend/src/_ui/HttpHeaders/index.js
  frontend/src/_ui/Layout/index.jsx
  plugins/packages/influxdb/lib/manifest.json
  plugins/packages/mongodb/lib/manifest.json
Labels: active-review-app

#8411 [docs] added paid label on gitsync
  docs/docs/gitsync.md
  docs/versioned_docs/version-2.24.0/gitsync.md
  docs/versioned_docs/version-2.25.0/gitsync.md
Labels: documentation

#7981 Update README.md and added Keyword "DigitalOcean" for oneClickDeployment statement before its link
  README.md
Labels: hacktoberfest-accepted

#8095 Update file-picker.md - Add filetype example
  docs/versioned_docs/version-2.22.0/widgets/file-picker.md
Labels: documentation

#8035 Updated TreeSelect Component in widgetConfig.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted

#7476 Added automation for link column type
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
Labels: cypress

#8416 new datatype dropdown design implemented for ToolJet Database
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Icons/Biginteger.svg
  frontend/src/TooljetDatabase/Icons/DeleteIconNew.svg
  frontend/src/TooljetDatabase/Icons/Float.svg
  frontend/src/TooljetDatabase/Icons/Integer.svg
  frontend/src/TooljetDatabase/Icons/Text.svg
  frontend/src/TooljetDatabase/Icons/Tick.svg
  frontend/src/TooljetDatabase/Icons/Toggle.svg
  frontend/src/TooljetDatabase/constants.js
  frontend/src/_styles/theme.scss
Labels: active-review-app

#8424 [docs] added missing label on gitsync 2.27
  docs/versioned_docs/version-2.27.0/gitsync.md
Labels: documentation

#8234 Added code coverage for cypress
  .github/workflows/code-coverage.yml
  cypress-tests/.gitignore
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/ce/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/editor/data-source/azureBlobStorageHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/clickHouseHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/cosmosDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/couchDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/influxDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mariaDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/oracleDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/postgresHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/rethinkDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sapHanaHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sqlServerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/regressionSuite/appBuilder/queryPanel/queryEditorRegression.cy.js
  cypress-tests/cypress/fixtures/fake.js
  cypress-tests/cypress/plugins/index.js
  cypress-tests/cypress/support/e2e.js
  cypress-tests/package-lock.json
  cypress-tests/package.json
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
Labels: cypress

#8395 [hotfix] CE fixes
  .version
  frontend/.version
  frontend/src/Editor/Context/EditorContextWrapper.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Viewer.jsx
  plugins/packages/common/lib/utils.helper.ts
  plugins/packages/graphql/lib/index.ts
  plugins/packages/restapi/lib/index.ts
  server/.version
  server/data-migrations/1697473340856-MigrateAppsDefinitionSchemaTransition.ts
  server/migrations/1691007037021-CreateLayoutTable.ts
  server/src/services/app_import_export.service.ts
Labels: hotfix, run-cypress

#8387 Feature/tjdb null contraint support
  server/src/controllers/tooljet_db.controller.ts
  server/src/dto/tooljet-db.dto.ts
  server/src/modules/casl/abilities/tooljet-db-ability.factory.ts
  server/src/services/tooljet_db.service.ts
Labels: run-ci

#8426 [hot-fix] Edit Workspace CTA isn't working.
  frontend/src/_components/OrganizationManager/EditOrganization.jsx
Labels: tested, active-review-app

#7562 Fixed Page name to be restricted to less than 50 characters
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
Labels: tested
