Repository ToolJet/ToolJet, pull requests merged in 2023-09, with the labels that each got.

#7142 Feature :: Exposing CSA for child widgets of form and listview
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/BoundedBox/RenderEditor.jsx
  frontend/src/Editor/Components/BoundedBox/RenderHighlight.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/ButtonGroup.jsx
  frontend/src/Editor/Components/Checkbox.jsx
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Icon.jsx
  frontend/src/Editor/Components/Kanban/Components/Item.jsx
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Components/KanbanBoard/Board.jsx
  frontend/src/Editor/Components/KanbanBoard/Card.jsx
  frontend/src/Editor/Components/Link.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Components/Steps.jsx
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_ui/JSONTreeViewer/JSONNodeValue.jsx
Labels: run-ci, tested, suspend-review-app, documented, appbuilder, run-cypress-app-builder, product approved

#7210 #6974 - Add support to disable page
  frontend/assets/images/icons/editor/left-sidebar/file-accept.svg
  frontend/assets/images/icons/editor/left-sidebar/file-remove.svg
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger/Logs.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/colors.scss
  frontend/src/_ui/Icon/solidIcons/FIleRemove.jsx
Labels: run-ci, tested, documented, appbuilder, product approved

#6573 Feature/4964 multi select component events
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested, suspend-review-app, documented

#7143 Setup sentry logging as per version and upload its source map
  frontend/.version
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.jsx
  frontend/webpack.config.js
  package.json
  server/src/main.ts
  update-version.js
Labels: run-ci, tested, suspend-review-app, documented

#7178 Table redsign
  cypress-tests/cypress/constants/selectors/table.js
  frontend/assets/images/avatar.png
  frontend/assets/images/icons/eye1.svg
  frontend/assets/images/icons/filedownload.svg
  frontend/assets/images/icons/plus.svg
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Components/Table/IndeterminateCheckbox.jsx
  frontend/src/Editor/Components/Table/OverlayTriggerComponent.jsx
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_styles/theme.scss
  frontend/src/_styles/typography.scss
  frontend/src/_ui/AppButton/AppButton.scss
  frontend/src/_ui/Icon/solidIcons/Check.jsx
  frontend/src/_ui/Icon/solidIcons/CheveronLeftDouble.jsx
  frontend/src/_ui/Icon/solidIcons/CheveronRightDouble.jsx
  frontend/src/_ui/Icon/solidIcons/Cross.jsx
  frontend/src/_ui/Icon/solidIcons/Dot.jsx
  frontend/src/_ui/Icon/solidIcons/Editable.jsx
  frontend/src/_ui/Icon/solidIcons/Save.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/data-migrations/1692973078520-CellSizeRegularCondensed.ts
  server/data-migrations/1692974311591-TableRowCellStyle.ts
Labels: feature request, run-ci, tested, suspend-review-app, documented, run-cypress-app-builder, Table component

#7368 Modified data source cypress spec with GDS UI changes
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/editor/data-source/azureBlobStorageHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/clickHouseHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/cosmosDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/couchDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/influxDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mariaDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/oracleDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/postgresHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/rethinkDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sqlServerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.skip.js
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/postgreSql.js
Labels: suspend-review-cypress-app, run-cypress-marketplace

#7371 Automation fixed for table redesign phase-1.
  cypress-tests/cypress/constants/selectors/table.js
  cypress-tests/cypress/constants/texts/table.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  frontend/src/Editor/Components/Table/Filter.jsx
Labels: cypress

#7379 Bugfix : Button styles fixes
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/AppButton/AppButton.scss
Labels: appbuilder

#7384 feat: Minor UX changes on querymanager for button states
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
Labels: tested

#7310 [docs] components revamp
  docs/docs/widgets/bounded-box.md
  docs/docs/widgets/button-group.md
  docs/docs/widgets/button.md
  docs/static/img/widgets/bounded-box/event1.png
  docs/static/img/widgets/bounded-box/layout1.png
  docs/static/img/widgets/bounded-box/tooltip1.png
  docs/static/img/widgets/button-group/buttongroup1.png
  docs/static/img/widgets/button-group/grouptooltip.png
  docs/static/img/widgets/button/buttontooltip.png
Labels: documentation

#7387 Avoid box shadow on the selector type column header, when clicked on the input checkbox in the table component
  frontend/src/Editor/Components/Table/IndeterminateCheckbox.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/table-component.scss
  frontend/src/_ui/AppButton/AppButton.scss
Labels: tested

#7305 [docs]:update component docs
  docs/docs/widgets/bounded-box.md
  docs/docs/widgets/button-group.md
  docs/docs/widgets/button.md
  docs/docs/widgets/form.md
  docs/docs/widgets/number-input.md
  docs/docs/widgets/password-input.md
  docs/docs/widgets/text.md
  docs/docs/widgets/textarea.md
  docs/static/img/widgets/bounded-box/event1.png
  docs/static/img/widgets/bounded-box/layout1.png
  docs/static/img/widgets/bounded-box/tooltip1.png
  docs/static/img/widgets/button-group/buttongroup1.png
  docs/static/img/widgets/button-group/grouptooltip.png
  docs/static/img/widgets/button/buttontooltip.png
  docs/static/img/widgets/form/box-shadow.png
  docs/static/img/widgets/form/form-preview.png
  docs/static/img/widgets/form/formnew.png
  docs/static/img/widgets/form/tooltip.png
  docs/static/img/widgets/number-input/tooltip.png
  docs/static/img/widgets/text/box-shadow.png
  docs/static/img/widgets/text/tooltip.png
  docs/static/img/widgets/textarea/box-shadow.png
  docs/static/img/widgets/textarea/tooltip.png
  docs/versioned_docs/version-2.16.0/widgets/form.md
Labels: documentation

#7391 Bug fixed - Datepicker dates are not aligned properly
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/table-component.scss
Labels: tested

#7389 fixed filled icons color issue
  frontend/src/Editor/Components/Icon.jsx
Labels: bug, run-ci, tested

#7397 Hotfix: marketplace fixes
  .version
  plugins/packages/snowflake/lib/manifest.json
  server/.version
  server/src/services/app_import_export.service.ts
Labels: tested, active-review-app

#7373 Bugfix :: Textinput getting reset on type
  frontend/src/Editor/Components/TextInput.jsx
Labels: tested, appbuilder

#7393 feat: update viwer mode bg and screen alignmanet
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/FolderList/FolderList.scss
Labels: tested, active-review-app

#7378 Bugfix :: Canvas color not switching in older apps while theme switching , along with some bugfixes and design changes
  frontend/assets/translations/en.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Inspector/Components/Table/NoListItem.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/ManageEventButton.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/ToolJetUI/Buttons/AddNewButton/AddNewButton.jsx
  frontend/src/ToolJetUI/Buttons/AddNewButton/addNewButton.scss
  frontend/src/ToolJetUI/List/List.jsx
  frontend/src/ToolJetUI/SwitchGroup/toggleGroup.scss
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/AppButton/AppButton.jsx
Labels: run-ci, tested, suspend-review-app, appbuilder

#7398 Show bulk selector button not visible in the table inspector
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/_styles/table-component.scss
Labels: tested

#7388 Automation fixed for appbuilder-1.3
  cypress-tests/cypress.config.js
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/dataSource.js
  cypress-tests/cypress/constants/selectors/multipage.js
  cypress-tests/cypress/constants/selectors/postgreSql.js
  cypress-tests/cypress/constants/selectors/table.js
  cypress-tests/cypress/constants/texts/button.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/dataSource.js
  cypress-tests/cypress/constants/texts/datePicker.js
  cypress-tests/cypress/constants/texts/listview.js
  cypress-tests/cypress/constants/texts/multipage.js
  cypress-tests/cypress/constants/texts/multiselect.js
  cypress-tests/cypress/constants/texts/numberInput.js
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/constants/texts/table.js
  cypress-tests/cypress/constants/texts/textInput.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/e2e/editor/widget/datePickerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/multiselectHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/modal.js
  cypress-tests/cypress/support/utils/multipage.js
  cypress-tests/cypress/support/utils/table.js
  frontend/src/Editor/Inspector/Components/Table/NoListItem.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/_ui/Icon/solidIcons/EyeDisable.jsx
  frontend/src/_ui/Icon/solidIcons/Home.jsx
  frontend/src/_ui/LeftSidebar/Header.jsx
Labels: cypress, run-cypress-app-builder

#7419 Fixed failure cypress specs
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/selectors/exportImport.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/support/utils/postgreSql.js
Labels: run-cypress-app-builder

#7423 Appbuilder-1.3 cypress minor fixes.
  cypress-tests/cypress.config.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
Labels: cypress

#7426 Fixed platform cypress test cases
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/dataSource.js
  cypress-tests/cypress/e2e/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
  cypress-tests/cypress/e2e/workspace/workspaceConstants.cy.js
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/postgreSql.js
  frontend/src/Editor/ManageAppUsers.jsx
Labels: data-cy, cypress, run-cypress-workspace

#7410 Bugfix :: Base color theme change for app
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/Elements/BoxShadow.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_styles/theme.scss
  frontend/src/_styles/widgets/multi-select.scss
  frontend/src/_ui/AppButton/AppButton.scss
Labels: run-ci, tested, active-review-app, appbuilder, run-cypress-app-builder

#7411 Bugfix :: Data exposing for custom json schema form widget
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Form/FormUtils.js
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci, tested, appbuilder

#7428 Fix flaky tableRegression
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/inspector.js
  cypress-tests/cypress/support/utils/table.js
Labels: cypress

#7420 Fix #7417 Updated plugin descriptions on the Marketplace page
  server/src/assets/marketplace/plugins.json
Labels: active-review-app

#7441 Hotfix :: Dynamic canvas background
  .version
  frontend/.version
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/_ui/FolderList/FolderList.scss
  server/.version
Labels: tested

#7445 [docs]updated props of link column type
  docs/docs/widgets/table.md
  docs/static/img/widgets/table/linkupd.png
  docs/versioned_docs/version-2.11.0/widgets/table.md
  docs/versioned_docs/version-2.12.0/widgets/table.md
  docs/versioned_docs/version-2.13.0/widgets/table.md
  docs/versioned_docs/version-2.14.0/widgets/table.md
  docs/versioned_docs/version-2.15.0/widgets/table.md
  docs/versioned_docs/version-2.16.0/widgets/table.md
  docs/versioned_docs/version-2.17.0/widgets/table.md
Labels: documentation

#7447 [docs] revoved comments from schema and added tables and example
  docs/docs/widgets/form.md
  docs/static/img/widgets/form/customform.png
  docs/versioned_docs/version-2.15.0/widgets/form.md
  docs/versioned_docs/version-2.16.0/widgets/form.md
  docs/versioned_docs/version-2.17.0/widgets/form.md
Labels: documentation

#7452 Fix:: Leftsidebar popovers positioning in mozilla
  frontend/src/_styles/popover.scss
  frontend/src/_styles/queryManager.scss
Labels: run-ci, tested

#7450 Make events draggable in inspector
  .version
  frontend/.version
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/ManageEventButton.jsx
  server/.version
Labels: run-ci, tested

#7460 Add data-cy for query manager regression and smoke.
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/Editor/QueryPanel/FilterandSortPopup.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
Labels: data-cy

#7464 Fix query panel not returning falsey values on clicking preview
  .version
  frontend/.version
  frontend/src/Editor/QueryManager/Components/Preview.jsx
  frontend/src/_stores/queryPanelStore.js
  server/.version
Labels: run-ci, tested

#7458 Feature: Add support for bigint in TJDB
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/constants.js
  server/src/dto/tooljet-db.dto.ts
Labels: database

#7469 Hotfix: Import events linkage
  .version
  frontend/.version
  server/.version
  server/src/services/app_import_export.service.ts
Labels: active-review-app

#7477 Fix: unit tests for app import
  server/test/services/app_import_export.service.spec.ts
Labels: run-ci

#7481 [Hotfix]: Clear interval on switching to dashboard
  .version
  frontend/.version
  frontend/assets/images/icons/trash.svg
  frontend/src/App/App.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/_components/CopyToClipboard/CopyToClipboard.jsx
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  server/.version
Labels: run-ci, tested

#7474 Bugfix/tooljetdb join operations
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/Confirm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSort.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinTable.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/_helpers/appUtils.js
  server/src/services/tooljet_db.service.ts
Labels: run-ci, active-review-app

#7207 Added unique key constrain to organization users table
  server/data-migrations/1693288308041-organizationUsersRemoveDuplicates.ts
  server/data-migrations/1693309526388-addUniqueKeyConstrainForOrganizationUsers.ts
  server/src/entities/organization_user.entity.ts
  server/src/helpers/db_constraints.constants.ts
  server/test/controllers/onboarding/form-auth.e2e-spec.ts
  server/test/controllers/onboarding/git-sso-auth.e2e-spec.ts
  server/test/controllers/onboarding/google-sso-auth.e2e-spec.ts
Labels: run-ci

#7479 Added automation for Component movement verification.
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
Labels: cypress

#7468 [docs]updated restapi with bearer auth
  docs/docs/data-sources/restapi.md
  docs/docs/how-to/oauth2-authorization.md
  docs/sidebars.js
  docs/static/img/datasource-reference/rest-api/bearersuccess.png
  docs/static/img/datasource-reference/rest-api/cacert.png
  docs/static/img/datasource-reference/rest-api/clientcert.png
  docs/static/img/datasource-reference/rest-api/none.png
  docs/versioned_docs/version-2.17.0/data-sources/restapi.md
  docs/versioned_docs/version-2.17.0/how-to/oauth2-authorization.md
  docs/versioned_sidebars/version-2.17.0-sidebars.json
Labels: documentation

#7494 fix:error handling by status code
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSort.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinTable.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/_helpers/appUtils.js
Labels: run-ci, active-review-app

#7455 Adding redis as a default deployment
  .github/workflows/packer-build.yml
  .github/workflows/tooljet-release-docker-image-build.yml
  deploy/ec2/variables.pkr.hcl
Labels: do not merge, tested

#7503 Chore: Plugin deletion confirmation
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/_components/ConfirmDialog.jsx
Labels: run-ci, tested, active-review-app

#7506 Bug/installed plugins cardsize different
  frontend/package-lock.json
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/MarketplacePage/MarketplaceCard.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, active-review-app

#7483 tjdb dropdown menu flickering issue
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, active-review-app

#7323 creating folder dialog box on pressing Enter/return key (#7021)
  frontend/src/HomePage/Folders.jsx
Labels: run-ci

#7256 fixed-send-button-being-active-without-input
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: run-ci

#7239 fixed toast for multiple components selection
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested

#7263 Feature/tooljetdb join operations
  frontend/jsconfig.json
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/Confirm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSort.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinTable.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/util.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_styles/queryManager.scss
  frontend/src/_ui/Icon/solidIcons/FullOuterJoin.jsx
  frontend/src/_ui/Icon/solidIcons/Information.jsx
  frontend/src/_ui/Icon/solidIcons/InnerJoinIcon.jsx
  frontend/src/_ui/Icon/solidIcons/LeftOuterJoinIcon.jsx
  frontend/src/_ui/Icon/solidIcons/Remove.jsx
  frontend/src/_ui/Icon/solidIcons/RightOuterJoin.jsx
  frontend/src/_ui/Icon/solidIcons/Tick.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/src/controllers/tooljet_db.controller.ts
  server/src/modules/casl/abilities/tooljet-db-ability.factory.ts
  server/src/modules/import_export_resources/import_export_resources.module.ts
  server/src/services/postgrest_proxy.service.ts
  server/src/services/tooljet_db.service.ts
Labels: run-ci, tested, active-review-app, database

#7421 Feature: Bulk csv upload for TJDB
  cypress-tests/cypress/support/utils/database.js
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/FileDropzone.jsx
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/ExportSchema/ExportSchema.jsx
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
  frontend/src/_helpers/http-client.js
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/AppButton/AppButton.scss
  frontend/src/_ui/Drawer/index.jsx
  frontend/src/_ui/Icon/solidIcons/ReloadError.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/src/controllers/tooljet_db.controller.ts
  server/src/modules/casl/abilities/tooljet-db-ability.factory.ts
  server/src/modules/tooljet_db/tooljet_db.module.ts
  server/src/services/postgrest_proxy.service.ts
  server/src/services/tooljet_db.service.ts
  server/src/services/tooljet_db_bulk_upload.service.ts
Labels: run-ci, tested, active-review-app, documented, database

#7198 changed the mongodb-slate-blue logo to mongodb-forest-green logo
  plugins/packages/mongodb/lib/icon.svg
Labels: run-ci, tested, suspend-review-app

#7005 Fix [Dark Mode] UI inconsistency user selects autofill values
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#7292 renamed/ issue #7227:Updated the text on the File picker component.
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested

#7539 Hotfix :: Components not showing up in dropdown for csa using page event handler
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci, tested

#7512 Release: Marketplace 1.4
  .version
  cypress-tests/cypress/support/utils/database.js
  frontend/.version
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/Confirm.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSort.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinTable.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/util.js
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/MarketplacePage/MarketplaceCard.jsx
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/FileDropzone.jsx
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/ExportSchema/ExportSchema.jsx
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/TooljetDatabase/constants.js
  frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
  frontend/src/_components/ConfirmDialog.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/http-client.js
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/AppButton/AppButton.scss
  frontend/src/_ui/Drawer/index.jsx
  frontend/src/_ui/Icon/solidIcons/FullOuterJoin.jsx
  frontend/src/_ui/Icon/solidIcons/Information.jsx
  frontend/src/_ui/Icon/solidIcons/InnerJoinIcon.jsx
  frontend/src/_ui/Icon/solidIcons/LeftOuterJoinIcon.jsx
  frontend/src/_ui/Icon/solidIcons/ReloadError.jsx
  frontend/src/_ui/Icon/solidIcons/Remove.jsx
  frontend/src/_ui/Icon/solidIcons/RightOuterJoin.jsx
  frontend/src/_ui/Icon/solidIcons/Tick.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/.version
  server/src/controllers/tooljet_db.controller.ts
  server/src/dto/tooljet-db.dto.ts
  server/src/modules/casl/abilities/tooljet-db-ability.factory.ts
  server/src/modules/import_export_resources/import_export_resources.module.ts
  server/src/modules/tooljet_db/tooljet_db.module.ts
  server/src/services/postgrest_proxy.service.ts
  server/src/services/tooljet_db.service.ts
  server/src/services/tooljet_db_bulk_upload.service.ts
Labels: run-ci, active-review-app, documented, marketplace, run-cypress-app-builder, active-review-cypress-app, run-cypress-workspace, run-cypress-marketplace
