Repository ToolJet/ToolJet, pull requests merged in 2023-01, with the labels that each got.

#5126 Bugfix :: name change from `work email` to `Email` in onboarding
  cypress-tests/cypress/constants/texts/common.js
  frontend/assets/translations/en.json
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/OnBoardingForm/AdminSetup.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
Labels: enhancement, frontend

#5057 [ Bug fixed ] : input field width is not fixed
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/_styles/queryManager.scss
Labels: bug, frontend, javascript, run-ci, ui, react, suspend-review-app

#5107 [multipage]redirects to homepage if page is invalid
  frontend/src/Editor/Viewer.jsx
Labels: bug, multipages

#5095 [ Bug fixed ]: Should be workspace instead of organization
  frontend/assets/translations/en.json
  frontend/src/App/App.jsx
  frontend/src/_components/OrganizationManager/CustomSelect.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: bug, frontend, javascript, needs testing, run-ci, react

#5118 [ Bug fixed ] : Edit version pop-up is not getting closed after clicking on x button
  frontend/src/Editor/AppVersionsManager/EditVersionModal.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_helpers/appUtils.js
  server/src/app.module.ts
Labels: bug, frontend, javascript, run-ci, editor, react

#5145 [ Bug fix ]: Dark theme bugs
  frontend/src/Editor/CommentNotifications/index.jsx
  frontend/src/Editor/Header/HeaderActions.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/Profile.jsx
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Popover/index.jsx
Labels: bug, frontend, javascript, run-ci, ui, react

#5115 [Bug fixed ] : restAPI is getting created everytime on query panel after adding any data source or deleting a data source
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: bug, frontend, javascript, run-ci, react

#5098 [ Bug fixed ] : UI is not consistent when query name is large in query panel header
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_styles/queryManager.scss
Labels: bug, frontend, javascript, run-ci, ui, editor, react

#5158 [ bug fixed ] : dark theme issues in ManageGroupPermissionResources component
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
Labels: frontend, javascript, run-ci, ui, react

#5128 [ Bug fixed ] : select custom component styles not getting applied in query manager
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Inspector/ActionConfigurationPanels/GotoApp.jsx
  frontend/src/Editor/Inspector/ActionConfigurationPanels/SwitchPage.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/Select/SelectComponent.jsx
Labels: bug, frontend, javascript, needs discussion, run-ci, ui, react, active-review-app

#5169 [Bugfix] check if default value is an empty string
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
Labels: bug

#5170 [Bugfix] unable to create a rest api dataquery on v2-beta,
  frontend/src/_services/dataquery.service.js
Labels: bug

#5163 Bugfix :: single workspace breaking on clicking signup option
  frontend/src/SignupPage/SignupPage.jsx
Labels: bug, frontend, react

#5164 [ Bug fix ] : dark theme fixes
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarItem.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/NotificationCenter/index.jsx
  frontend/src/_components/Profile.jsx
  frontend/src/_styles/onboarding.scss
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  frontend/src/_ui/Layout/index.jsx
  frontend/src/_ui/LeftSidebar/Header.jsx
  frontend/src/_ui/Search/Search.jsx
Labels: frontend, javascript, run-ci, ui, react

#5096 [ Bug fixed ] : It should be Query Parametres instead of Query parameters
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabParams.jsx
Labels: bug, good first issue, frontend, javascript, run-ci, react

#5011 [ Bug fixed ] : [Multi-Select widget ] app freezes when we use control component action to control the same multi-select
  frontend/src/Editor/Components/Multiselect.jsx
Labels: frontend, javascript, run-ci, widget, tested, react, suspend-review-app

#5172 Homepage and editor design fixes
  frontend/assets/images/rocket.svg
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Icons/logo.svg
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarItem.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Layout/index.jsx
  frontend/webpack.config.js
Labels: active-review-app

#5180 fix: add pin and unpin button for left sidebar item
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/_ui/Popover/index.jsx
Labels: active-review-app

#5182 Table dashboard improvements
  frontend/src/App/App.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: enhancement, active-review-app, internal-storage

#5187 V2 minor UI fixes
  frontend/src/Editor/Viewer/Header.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/_components/OrganizationManager/CustomSelect.jsx
  frontend/src/_ui/Select/styles.js
Labels: enhancement

#5196 [ Bug fix ] : made left sidebar icon consistent with the dark theme
  frontend/src/_styles/left-sidebar.scss
Labels: frontend, javascript, run-ci, ui, react

#5197 v2-improvement: select the first group by default and render the selected on by default
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_styles/theme.scss
Labels: enhancement, active-review-app

#5188 V2 tables dashboard improvements
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_styles/components.scss
  frontend/src/_ui/Select/SelectComponent.jsx
Labels: enhancement, internal-storage

#5207 [bug-fix] Preview app doesn't redirect to the login page if the user doesn't have permission.
  frontend/src/_services/authentication.service.js
Labels: run-ci, active-review-app

#5208 [bug-fix] View or hide Menu based on privileges
  frontend/src/OrganizationSettingsPage/index.jsx
Labels: run-ci, active-review-app

#5195 [ Bug fixed ] : Popover content in left sidebar is not scrollable
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/QueryPanel.jsx
  frontend/src/_styles/popover.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Popover/index.jsx
Labels: frontend, javascript, run-ci, ui, react

#5215 [ Bug fixed ] : tooltip was not displaying for the left sidebar icons
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarComment.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarItem.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
Labels: frontend, javascript, run-ci, react

#5218 Fixes app crash for toggling fx button in global settings
  frontend/src/Editor/Editor.jsx
Labels: bug

#5203 Bugfix :: Fixing scroll in dashboard and databases
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/TooljetDatabase/Sidebar/index.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_styles/theme.scss
Labels: active-review-app

#5232 Bugfix :: Remove autocompletion and rendered logo as svg
  frontend/assets/images/Logomark.svg
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnBoardingInput.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/OnBoardingForm/OnboardingPassword.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/SetupScreenSelfHost.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
  frontend/src/_components/OnboardingNavbar.jsx
Labels: active-review-app

#5241 Bugfix :: Login button's disabled state is removed
  frontend/src/LoginPage/LoginPage.jsx
Labels: active-review-app

#5239 [ Bug fixed ] : dark theme bug fixes
  frontend/src/Editor/Comment/CommentActions.jsx
  frontend/src/Editor/CommentNotifications/Content.jsx
  frontend/src/Editor/CommentNotifications/index.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/RealtimeAvatars.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_components/ConfirmDialog.jsx
  frontend/src/_components/NotificationCenter/Notification.jsx
  frontend/src/_components/NotificationCenter/index.jsx
  frontend/src/_styles/editor/comment-notifications.scss
  frontend/src/_styles/editor/comments.scss
Labels: bug, frontend, javascript, ui, react

#5236 Bugfix :: TooljetDB query manager fields scroll issue
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  frontend/src/_styles/theme.scss
Labels: do not merge, active-review-app

#5247 Multipage: component and current state is persisted for duplicate pages
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
Labels: bug, tested, active-review-app, multipages

#5250 fixes: runpy queries from v1 is not created in v2
  server/src/services/app_import_export.service.ts
Labels: bug, tested, active-review-app

#5256 [bug-fix] Workspace name isn't visible in single workspace
  frontend/src/_ui/Header/index.jsx
Labels: active-review-app

#5245 [Table widget] Boolean value is not coerce to string for default and string non-editable column
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: bug, widget

#5261 [ Bug fixed ] : Table popover is not consistent with the dark theme in the dashboard
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/_styles/theme.scss
Labels: bug, frontend, javascript, ui, react

#5246 Bugfix :: Popover gets removed when cursor goes to canvas
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
Labels: do not merge, tested, active-review-app

#5262 Fix :: Navbar background issue
  frontend/src/_components/OnboardingNavbar.jsx
  frontend/src/_styles/onboarding.scss
Labels: do not merge, active-review-app

#5251 [V2-Beta] add validation to overcome sql injection
  server/src/controllers/tooljet_db.controller.ts
  server/src/dto/tooljet-db.dto.ts
Labels: active-review-app

#5221 Fix: v2-beta test cases
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/test/controllers/app.e2e-spec.ts
  server/test/controllers/app_users.e2e-spec.ts
  server/test/controllers/apps.e2e-spec.ts
  server/test/controllers/data_queries.e2e-spec.ts
  server/test/controllers/data_sources.e2e-spec.ts
  server/test/controllers/tooljet_db.e2e-spec.ts
  server/test/services/app_import_export.service.spec.ts
  server/test/test.helper.ts
Labels: run-ci

#5205 Bugfix :: Onboarded data saved to telemetry
  frontend/src/_services/authentication.service.js
  server/src/controllers/metadata.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/organizations/organizations.module.ts
  server/src/services/auth.service.ts
  server/src/services/metadata.service.ts
Labels: do not merge, run-ci, active-review-app, suspend-review-app

#5260 [multipages] disable: duplicate page
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/SettingsModal.jsx
  frontend/src/Editor/Viewer.jsx
Labels: tested, active-review-app

#5263 fix: pick organization id from param for internal storage
  server/src/controllers/tooljet_db.controller.ts
  server/src/services/postgrest_proxy.service.ts
  server/src/services/tooljet_db.service.ts
Labels: active-review-app

#5230 fix: app card height while no edit access for user
  frontend/src/HomePage/AppCard.jsx
  frontend/src/_styles/theme.scss
Labels: suspend-review-app

#5266 [ Bug fixes ] : Dark theme bugs 5
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/_styles/onboarding.scss
  frontend/src/_styles/theme.scss
Labels: bug, frontend, javascript, run-ci, react

#5264 fire error toast as per error response
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/_helpers/appUtils.js
Labels: active-review-app

#5248 [ Bug fixed ] : ToolJet logo dark theme
  frontend/assets/images/Logomark-dark-mode.svg
  frontend/src/App/App.jsx
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/LoginPage/LoginPage.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/SetupScreenSelfHost.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
  frontend/src/_components/OnboardingNavbar.jsx
Labels: bug, frontend, javascript, ui, react, active-review-app

#5271 Revert "Bugfix :: Popover gets removed when cursor goes to canvas (#5…
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
Labels: active-review-app

#5304 Fix :: Users not able to complete signup process in firefox
  frontend/src/OnBoardingForm/ContinueButton.jsx
  frontend/src/OnBoardingForm/ContinueButtonSelfHost.jsx
Labels: tested, active-review-app

#5314 Add and modify data-cy acording to v2 changes. (to fix cypress tests)
  frontend/src/Editor/Header/HeaderActions.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarItem.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: cypress

#5310 Fix ::Removed max length in inputs , added it only for worspace and company name
  frontend/src/OnBoardingForm/OnBoardingInput.jsx
  frontend/src/_styles/onboarding.scss
Labels: tested, active-review-app

#5335 [ Bug fixed ] : datepicker UI in table widget column is broken
  frontend/src/_styles/custom.scss
  frontend/src/_styles/theme.scss
Labels: frontend, javascript, run-ci, ui, react

#5127 Enhance GraphQL plugin to be able to send custom headers
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/HttpHeaders/QueryEditor.jsx
  frontend/src/_ui/HttpHeaders/SourceEditor.jsx
  frontend/src/_ui/HttpHeaders/index.js
  plugins/packages/graphql/__tests__/graphql.test.js
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/lib/manifest.json
  plugins/packages/graphql/lib/operations.json
  plugins/packages/graphql/lib/types.ts
Labels: run-ci, tested, suspend-review-app

#5071 Added automation for AWS S3 and MySQL connection.
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/awss3.js
  cypress-tests/cypress/constants/texts/awss3.js
  cypress-tests/cypress/constants/texts/mysql.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/postgreSql.js
Labels: cypress

#5317 Fix failing components verification specs
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/datePickerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/multiselectHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/commonWidget.js
Labels: cypress

#5091 Added automation for datasource connection.
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/texts/bigquery.js
  cypress-tests/cypress/constants/texts/firestore.js
  cypress-tests/cypress/constants/texts/mongoDb.js
  cypress-tests/cypress/constants/texts/redis.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
Labels: cypress

#5349 Add automation for smtp, dynamoDB, Elastic-search connections.
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/postgreSql.js
  cypress-tests/cypress/constants/texts/dynamodb.js
  cypress-tests/cypress/constants/texts/elasticsearch.js
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
Labels: cypress

#5345 Modified cypress login spec V2
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/login.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/login.js
  cypress-tests/cypress/e2e/authentication/login.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/dashboard.js
  cypress-tests/cypress/support/utils/login.js
  cypress-tests/cypress/support/utils/manageSSO.js
Labels: cypress

#5350 Fix :: Form submission error in Firefox browser
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
Labels: active-review-app

#5347 [Bug] Variables in Graphql plugin not working
  plugins/packages/graphql/lib/index.ts
  plugins/packages/graphql/lib/types.ts
Labels: bug, plugins, tested, active-review-app

#5366 Add cypress.env.example
  cypress-tests/.gitignore
  cypress-tests/cypress.config.js
  cypress-tests/cypress.env.example
  cypress-tests/cypress/jsconfig.json
Labels: cypress

#5338 [bug-fix] Public app is redirecting to login page [Subpath]
  frontend/src/_services/authentication.service.js
  server/src/modules/auth/query-auth.guard.ts
Labels: tested, suspend-review-app

#5342 [Bugfix] app crashes when delete op is ran for tj db query
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/_helpers/appUtils.js
Labels: bug, needs testing, suspend-review-app, internal-storage

#4938 chore: add backend version name length validation
  server/src/dto/version-create.dto.ts
  server/src/services/apps.service.ts
Labels: run-ci, tested, suspend-review-app

#4671 Bug: Added workspace title length validation while editing
  frontend/src/_components/Organization.jsx
  server/src/controllers/organizations.controller.ts
  server/test/controllers/organizations.e2e-spec.ts
Labels: hacktoberfest-accepted, run-ci, tested, suspend-review-app

#5025 File picker issues on CSV parsing
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
Labels: tested, suspend-review-app

#5364 [Fix] :: URL for manage users on Editor page
  frontend/src/Editor/ManageAppUsers.jsx
Labels: tested, suspend-review-app

#5409 Added spec to verify common components operations
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/basicComponents.js
  cypress-tests/cypress/support/utils/commonWidget.js
Labels: cypress

#5411 Add data-cy for Modal, Kanban, QR Scanner and Map
  frontend/src/Editor/Components/KanbanBoard/KanbanBoard.jsx
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Components/QrScanner/QrScanner.jsx
Labels: cypress, data-cy

#5385 Added data-cy for all the components.
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/ButtonGroup.jsx
  frontend/src/Editor/Components/Calendar.jsx
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/Checkbox.jsx
  frontend/src/Editor/Components/CirularProgressbar.jsx
  frontend/src/Editor/Components/CodeEditor.jsx
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/DaterangePicker.jsx
  frontend/src/Editor/Components/Divider.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/Form.jsx
  frontend/src/Editor/Components/Html.jsx
  frontend/src/Editor/Components/IFrame.jsx
  frontend/src/Editor/Components/Icon.jsx
  frontend/src/Editor/Components/Image.jsx
  frontend/src/Editor/Components/Link.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PDF.jsx
  frontend/src/Editor/Components/Pagination.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Components/RangeSlider.jsx
  frontend/src/Editor/Components/RichTextEditor.jsx
  frontend/src/Editor/Components/Spinner.jsx
  frontend/src/Editor/Components/StarRating/index.js
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/Steps.jsx
  frontend/src/Editor/Components/SvgImage.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/Tags.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/Timeline.jsx
  frontend/src/Editor/Components/Timer.jsx
  frontend/src/Editor/Components/Toggle.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/Components/verticalDivider.jsx
Labels: cypress, data-cy

#5320 [ Feature added ] : [Table widget ] adding CSA to deselect the row
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: good first issue, frontend, feature request, javascript, run-ci, tested, table, react, suspend-review-app

#5123 fix: able to delete the only version
  server/src/controllers/apps.controller.ts
Labels: run-ci, tested, suspend-review-app

#5359 [Fix] :: Editor crash while adding REST api datasrouce
  frontend/src/_components/DynamicForm.jsx
Labels: tested, suspend-review-app

#5421 [bug-fix] OpenAPI query fields doesn't show saved values
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
Labels: run-ci, tested, suspend-review-app

#5281 fixes app crash for adding and then removing ds
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/Googlesheets.jsx
  frontend/src/_components/Slack.jsx
  frontend/src/_components/Zendesk.jsx
Labels: bug, tested, suspend-review-app

#5372 [Bugfix] Tooljet database queries: the button's clickable area should fit the content of the element
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  frontend/src/_styles/queryManager.scss
Labels: tested, suspend-review-app, internal-storage, query-manager

#5425 [Bug] Not able to save sso configurations
  server/data-migration-config.ts
  server/ormconfig.ts
  server/src/controllers/organizations.controller.ts
Labels: run-ci, tested, suspend-review-app

#5383 [Fix] :: Check for subpaths in openapi
  server/src/controllers/data_sources.controller.ts
Labels: run-ci, tested, suspend-review-app

#5416 Fix :: Scrolling issue through whole dashboard
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/ManageSSO/ManageSSO.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_styles/theme.scss
Labels: bug, frontend, tested, ui, active-review-app

#5420 Feature: Show scrollbars in released and preview pages
  frontend/src/_styles/theme.scss
Labels: frontend, feature request, tested, ui, suspend-review-app, improvements

#5395 [ Bug fixed ] : [ Table ] wrong timezone entries for date picker
  frontend/src/Editor/Inspector/Components/Table.jsx
Labels: bug, javascript, run-ci, tested, table, react, suspend-review-app

#5394 Update star-rating.md
  docs/versioned_docs/version-2.0.0-beta/widgets/star-rating.md
  docs/versioned_sidebars/version-2.0.0-beta-sidebars.json
Labels: tested

#5368 [ Bug fixed ] - [ Table widget ] showing blank spaces for undefined and null values in the respective cells
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: bug, javascript, run-ci, tested, suspend-review-app

#5325 all: fix spelling
  docs/versioned_docs/version-2.0.0-beta/app-builder/canvas.md
  docs/versioned_docs/version-2.0.0-beta/app-builder/overview.md
  docs/versioned_docs/version-2.0.0-beta/app-builder/query-panel.md
  docs/versioned_docs/version-2.0.0-beta/app-builder/toolbar.md
  docs/versioned_docs/version-2.0.0-beta/getting-started.md
  docs/versioned_docs/version-2.0.0-beta/how-to/use-form-component.md
  docs/versioned_docs/version-2.0.0-beta/setup/google-cloud-run.md
  docs/versioned_docs/version-2.0.0-beta/tutorial/pages.md
  docs/versioned_docs/version-2.0.0-beta/widgets/overview.md
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/_styles/onboarding.scss
  frontend/src/_ui/Select/SelectComponent.jsx
Labels: tested

#5235 fix: rename User -> Username in SMTP datasource modal
  plugins/packages/smtp/lib/manifest.json
Labels: tested

#4558 Added border color option to Password Input widget
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: hacktoberfest-accepted, run-ci, tested

#5358 [improvement] validation error message for columns includes the column name
  server/src/dto/tooljet-db.dto.ts
Labels: tested, active-review-app, internal-storage, improvements

#5378 4810 - add a list messages operation to the Slack plugin
  docs/docs/data-sources/slack.md
  docs/static/img/datasource-reference/slack/listmessages.png
  frontend/src/_components/Slack.jsx
  plugins/packages/slack/lib/index.ts
  plugins/packages/slack/lib/operations.json
  plugins/packages/slack/lib/types.ts
Labels: plugins

#5451 [Fix-Test cases] App version delete test cases fix
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci
