Repository ToolJet/ToolJet, pull requests merged in 2023-05, with the labels that each got.

#6134 Modified database cypress spec failure
  cypress-tests/cypress/support/utils/database.js
  frontend/src/TooljetDatabase/Forms/FilterForm.jsx
  frontend/src/TooljetDatabase/Forms/SortForm.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: cypress

#6212 Added and modified data-cy for dashboard
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ResetPassword/ResetPasswordPage.jsx
  frontend/src/_components/OrganizationManager/List.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/bulkIcons/Apps.jsx
  frontend/src/_ui/Icon/bulkIcons/Archive.jsx
  frontend/src/_ui/Icon/bulkIcons/Calender.jsx
  frontend/src/_ui/Icon/bulkIcons/DragHandle.jsx
  frontend/src/_ui/Icon/bulkIcons/FloppyDisk.jsx
  frontend/src/_ui/Icon/bulkIcons/FolderUpload.jsx
  frontend/src/_ui/Icon/bulkIcons/Globe.jsx
  frontend/src/_ui/Icon/bulkIcons/Grid.jsx
  frontend/src/_ui/Icon/bulkIcons/Home.jsx
  frontend/src/_ui/Icon/bulkIcons/Layers.jsx
  frontend/src/_ui/Icon/bulkIcons/MenuHome.jsx
  frontend/src/_ui/Icon/bulkIcons/SentFast.jsx
  frontend/src/_ui/Icon/bulkIcons/Server.jsx
  frontend/src/_ui/Icon/bulkIcons/Share.jsx
  frontend/src/_ui/Icon/bulkIcons/Shield.jsx
  frontend/src/_ui/Icon/bulkIcons/Sun.jsx
  frontend/src/_ui/Icon/bulkIcons/Table.jsx
  frontend/src/_ui/Icon/solidIcons/EditRectangle.jsx
  frontend/src/_ui/Icon/solidIcons/Notification.jsx
  frontend/src/_ui/Layout/index.jsx
Labels: data-cy, cypress

#6211 GRPC Datasource
  docs/docs/data-sources/grpc.md
  frontend/package-lock.json
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/GRPC.jsx
  frontend/src/Editor/QueryManager/QueryEditors/index.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_ui/Card/Card.jsx
  frontend/src/_ui/OAuth/GrpcAuthentication.jsx
  frontend/src/_ui/OAuth/index.js
  plugins/package.json
  plugins/packages/grpc/.gitignore
  plugins/packages/grpc/README.md
  plugins/packages/grpc/__tests__/index.js
  plugins/packages/grpc/lib/icon.svg
  plugins/packages/grpc/lib/index.ts
  plugins/packages/grpc/lib/manifest.json
  plugins/packages/grpc/lib/operations.json
  plugins/packages/grpc/lib/types.ts
  plugins/packages/grpc/package-lock.json
  plugins/packages/grpc/package.json
  plugins/packages/grpc/tsconfig.json
  server/package-lock.json
  server/package.json
  server/src/controllers/global_data_sources.controller.ts
  server/src/helpers/utils.helper.ts
Labels: run-ci, plugins

#6190 fixes: app crash for adding a new gds from marketplace
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  server/src/controllers/global_data_sources.controller.ts
Labels: bug, run-ci, tested, active-review-app

#6213 Fixed Editor cypress v2.5.0
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/multipage.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/basicComponents.js
  cypress-tests/cypress/support/utils/table.js
  cypress-tests/cypress/support/utils/version.js
Labels: testcase, active-review-app, run-cypress

#5916 [fixes] Deleting the current version shows empty selected value - Delete icon is visible for released version menu item
  frontend/src/Editor/AppVersionsManager/List.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/index.js
Labels: tested

#6137 Fix :: Repeated toast bug after adding new row and opening a drawer in TJDB
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
Labels: needs testing, run-ci, active-review-app

#6230 Release/v2.5.0
  .version
  plugins/package-lock.json
  server/.version
Labels: run-ci

#6003 Bugfix - Custom props are not available in breadcrumbs for certain routes (tooljet-database)
  frontend/src/ManageOrgUsers/FileDropzone.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/_components/MultiSelectUser.jsx
  frontend/src/_ui/Breadcrumbs/index.jsx
Labels: run-ci, tested, active-review-app, documented

#6072 Feature/Plugin - AWS Textract Plugin
  frontend/src/MarketplacePage/index.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/CheckBox/CheckBox.jsx
  frontend/src/_ui/CheckBox/index.js
  marketplace/.eslintrc
  marketplace/package-lock.json
  marketplace/plugins/textract/.gitignore
  marketplace/plugins/textract/README.md
  marketplace/plugins/textract/__tests__/index.js
  marketplace/plugins/textract/lib/icon.svg
  marketplace/plugins/textract/lib/index.ts
  marketplace/plugins/textract/lib/manifest.json
  marketplace/plugins/textract/lib/operations.json
  marketplace/plugins/textract/lib/query_operations.ts
  marketplace/plugins/textract/lib/types.ts
  marketplace/plugins/textract/package.json
  marketplace/plugins/textract/tsconfig.json
  server/src/assets/marketplace/plugins.json
Labels: run-ci, plugins, tested, active-review-app

#6241 Added data-cy for manage groups page
  frontend/src/HomePage/FolderMenu.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_ui/Icon/bulkIcons/Trash.jsx
  frontend/src/_ui/Icon/solidIcons/Information.jsx
Labels: data-cy, cypress

#6178 Plugins JSON validation to prevent saving invalid data to database
  server/src/services/plugins.service.ts
Labels: marketplace

#6242 [docs]grpc datasource
  docs/docs/data-sources/grpc.md
  docs/sidebars.js
  docs/static/img/datasource-reference/grpc/connection.png
  docs/static/img/datasource-reference/grpc/grpcgds.png
  docs/static/img/datasource-reference/grpc/proto1.png
  docs/static/img/datasource-reference/grpc/proto2.png
  docs/static/img/datasource-reference/grpc/query.png
Labels: documentation

#6057 [docs] new marketplace docs
  docs/docs/contributing-guide/marketplace/creating-a-plugin.md
  docs/docs/contributing-guide/marketplace/marketplace-setup.md
  docs/docs/contributing-guide/setup/docker.md
  docs/docs/contributing-guide/setup/macos.md
  docs/docs/contributing-guide/setup/ubuntu.md
  docs/docs/contributing-guide/tutorials/creating-a-plugin.md
  docs/docs/marketplace.md
  docs/docs/marketplace/marketplace_overview.md
  docs/docs/marketplace/plugins/github.md
  docs/docs/marketplace/plugins/openai.md
  docs/docs/marketplace/plugins/plivo.md
  docs/docs/setup/env-vars.md
  docs/sidebars.js
  docs/static/img/marketplace/overview/allplugins.png
  docs/static/img/marketplace/overview/gdsplugin.png
  docs/static/img/marketplace/overview/icon.png
  docs/static/img/marketplace/overview/marketplace.png
  docs/static/img/marketplace/overview/query.png
  docs/static/img/marketplace/overview/remove.png
  docs/static/img/marketplace/plugins/github/connection.png
  docs/static/img/marketplace/plugins/github/getissues.png
  docs/static/img/marketplace/plugins/github/getpr.png
  docs/static/img/marketplace/plugins/github/getrepo.png
  docs/static/img/marketplace/plugins/github/getuserinfo.png
  docs/static/img/marketplace/plugins/github/githubadd.gif
  docs/static/img/marketplace/plugins/github/list.png
  docs/static/img/marketplace/plugins/openai/chat.png
  docs/static/img/marketplace/plugins/openai/completions.png
  docs/static/img/marketplace/plugins/openai/connection.png
  docs/static/img/marketplace/plugins/openai/list.png
  docs/static/img/marketplace/plugins/openai/openaiadd.gif
  docs/static/img/marketplace/plugins/plivo/connection.png
  docs/static/img/marketplace/plugins/plivo/plivoadd.gif
  docs/static/img/marketplace/plugins/plivo/sendsms.png
  docs/versioned_docs/version-2.3.0/contributing-guide/marketplace/creating-a-plugin.md
  docs/versioned_docs/version-2.3.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.3.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.3.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.3.0/contributing-guide/setup/ubuntu.md
  docs/versioned_docs/version-2.3.0/contributing-guide/tutorials/creating-a-plugin.md
  docs/versioned_docs/version-2.3.0/marketplace.md
  docs/versioned_docs/version-2.3.0/marketplace/marketplace_overview.md
  docs/versioned_docs/version-2.3.0/marketplace/plugins/github.md
  docs/versioned_docs/version-2.3.0/marketplace/plugins/openai.md
  docs/versioned_docs/version-2.3.0/marketplace/plugins/plivo.md
  docs/versioned_docs/version-2.3.0/setup/env-vars.md
  docs/versioned_docs/version-2.4.0/contributing-guide/marketplace/creating-a-plugin.md
  docs/versioned_docs/version-2.4.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.4.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.4.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.4.0/contributing-guide/setup/ubuntu.md
  docs/versioned_docs/version-2.4.0/contributing-guide/tutorials/creating-a-plugin.md
  docs/versioned_docs/version-2.4.0/marketplace.md
  docs/versioned_docs/version-2.4.0/marketplace/marketplace_overview.md
  docs/versioned_docs/version-2.4.0/marketplace/plugins/github.md
  docs/versioned_docs/version-2.4.0/marketplace/plugins/openai.md
  docs/versioned_docs/version-2.4.0/marketplace/plugins/plivo.md
  docs/versioned_docs/version-2.4.0/setup/env-vars.md
  docs/versioned_sidebars/version-2.3.0-sidebars.json
  docs/versioned_sidebars/version-2.4.0-sidebars.json
Labels: documentation

#6227 Added hash to the filenames in webpack
  frontend/webpack.config.js
Labels: run-ci, tested, documented

#6245 Fixed failing profile cypress spec
  .github/workflows/cypress.yml
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/dashboard.js
  cypress-tests/cypress/constants/selectors/manageSSO.js
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/constants/selectors/profile.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/dashboard.js
  cypress-tests/cypress/constants/texts/manageGroups.js
  cypress-tests/cypress/constants/texts/manageSSO.js
  cypress-tests/cypress/constants/texts/manageUsers.js
  cypress-tests/cypress/constants/texts/profile.js
  cypress-tests/cypress/constants/texts/workspacevarText.js
  cypress-tests/cypress/e2e/authentication/forgotPassword.cy.js
  cypress-tests/cypress/e2e/authentication/signUp.cy.js
  cypress-tests/cypress/e2e/dashboard/multi-workspace/userPermissions.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO/ssoOnboarding.cy.js
  cypress-tests/cypress/e2e/dashboard/single-workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/selfHost/selfHostSignUp.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/manageGroups.cy.js
  cypress-tests/cypress/e2e/workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/workspace/profile.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/dashboard.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/manageSSO.js
  cypress-tests/cypress/support/utils/manageUsers.js
  frontend/src/_ui/Header/index.jsx
Labels: active-review-app, data-cy, run-cypress, cypress

#6136 Fix :: Event manager popup closes on select of event
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: run-ci, tested, documented

#6135 Feat :: Exposed selected label in dropdown widget
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: enhancement, run-ci, tested, active-review-app, documented

#6311 [docs] updated dropdown exposed var
  docs/docs/widgets/dropdown.md
  docs/versioned_docs/version-2.5.0/widgets/dropdown.md
Labels: documentation

#6127 Fix :: Default value displayed in the preview for Number Input is incorrect for the first time
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested, active-review-app, documented

#6036 Fix :: View remains in same position during page switch in multi page apps
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
Labels: run-ci, tested, documented

#6025 Bugfix :: Dropdown and multiselect broken in table widget
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: run-ci, tested, suspend-review-app, documented

#6277 Fix for REST API plugin: Convert to Base64 if response type image
  plugins/packages/restapi/lib/index.ts
Labels: tested, active-review-app, documented

#6262 Hotfix :: App breaking during version switch
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-ci, tested

#6231 Hotfix :: Removing ellipsis on text overflow in legend labels in chart widget
  frontend/src/Editor/Components/Chart.jsx
Labels: run-ci, tested

#6038 Fix :: Additional button is getting added in Button Group component by changing value in labels
  frontend/src/Editor/Components/ButtonGroup.jsx
Labels: run-ci, tested, active-review-app, documented

#6332 Fixes the lint ci failing from plugins
  server/src/services/plugins.service.ts
Labels: run-ci, plugins

#5784 Upon saving the edited changes in the table, it is not mutating query object
  frontend/src/Editor/Components/Table/Table.jsx
Labels: bug, run-ci, tested, documented

#5980 Introduced global state management
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeBuilder.jsx
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/SettingsModal.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/index.js
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/dataSourcesStore.js
  frontend/src/_stores/queryPanelStore.js
  frontend/src/_stores/utils.js
Labels: run-ci, tested, documented

#6247 Fixed Color Difference In Toggling Icons
  frontend/src/Editor/Header/HeaderActions.jsx
Labels: run-ci, tested, active-review-app, documented

#6128 bug-fix: 🐛 - handle when a filter exist for equal & null
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/util.js
Labels: tested, documented

#6083 BugFix: Show correct message on row edit
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
Labels: tested, active-review-app, documented

#6345 Add data-cy for events input fields
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: data-cy

#6092 Adds an entry point to Global datasource page from Query Manager
  frontend/assets/images/icons/info.svg
  frontend/src/Editor/Icons/tooljetdb.svg
  frontend/src/Editor/QueryManager/AddGlobalDataSourceButton.jsx
  frontend/src/Editor/QueryManager/DataSourceLister.jsx
  frontend/src/Editor/QueryManager/EmptyGlobalDataSources.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/GlobalDatasources/index.jsx
  frontend/src/_styles/queryManager.scss
Labels: run-ci, tested, active-review-app, documented

#5947 App version creation flow enhancement - New released version warning popup - Current version issues
  frontend/src/Editor/AppVersionsManager/CreateVersionModal.jsx
  frontend/src/Editor/AppVersionsManager/CustomSelect.jsx
  frontend/src/Editor/AppVersionsManager/EditVersionModal.jsx
  frontend/src/Editor/AppVersionsManager/List.jsx
  frontend/src/Editor/AppVersionsManager/ReleasedVersionError.jsx
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/GlobalSettings.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/PageHandler.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/DataSourceLister.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager.jsx
  frontend/src/_components/SortableList/SortableList.jsx
  frontend/src/_components/SortableList/index.js
  frontend/src/_services/appVersion.service.js
  frontend/src/_styles/theme.scss
  server/src/dto/version-edit.dto.ts
  server/src/services/apps.service.ts
  server/test/controllers/apps.e2e-spec.ts
Labels: run-ci, tested, active-review-app, documented

#6074 Feature - ToolJet Copilot 🚀
  frontend/assets/images/icons/copilot.svg
  frontend/assets/images/icons/flash.svg
  frontend/assets/images/icons/padlock2.svg
  frontend/assets/images/icons/portal-close.svg
  frontend/assets/images/icons/portal-open.svg
  frontend/src/CopilotSettings/ApiKeyContainer.jsx
  frontend/src/CopilotSettings/CopilotSetting.jsx
  frontend/src/CopilotSettings/index.js
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/QueryManager/Transformation.jsx
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/Portal/Portal.jsx
  frontend/src/_hooks/use-portal.jsx
  frontend/src/_services/copilot.service.js
  frontend/src/_services/index.js
  frontend/src/_styles/components.scss
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/LeftSidebar/Button.jsx
  server/package-lock.json
  server/src/app.module.ts
  server/src/controllers/copilot.controller.ts
  server/src/dto/copilot.dto.ts
  server/src/modules/copilot/copilot.module.ts
  server/src/services/copilot.service.ts
Labels: run-ci, tested, active-review-app, documented

#6361 Added data-cy for global datasource manager page
  frontend/src/GlobalDatasources/CreateDataSourceModal/index.jsx
  frontend/src/GlobalDatasources/LIstItem/index.jsx
Labels: data-cy, cypress

#6371 Fixed datasource connection cypress test cases
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress.config.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/postgreSql.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/clickHouseHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/cosmosDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/couchDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/influxDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mariaDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/oracleDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/postgresHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/rethinkDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sapHanaHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sqlServerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.js
  cypress-tests/cypress/screenshots/.gitignore
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/postgreSql.js
  frontend/package-lock.json
  package-lock.json
  plugins/package-lock.json
Labels: active-review-app, run-cypress, cypress

#5343 Fixed default text widget bg color
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: run-ci, tested, documented

#6351 [docs] v2.5.1
  docs/docs/data-sources/overview.md
  docs/docs/tutorial/versioning-and-release.md
  docs/static/img/datasource-reference/newui/overview/defaultds.png
  docs/static/img/datasource-reference/newui/overview/newquery1.png
  docs/static/img/datasource-reference/newui/overview/qpanel.png
  docs/static/img/tutorial/versioning-and-release/deletev.png
  docs/static/img/tutorial/versioning-and-release/editv.png
  docs/static/img/tutorial/versioning-and-release/newpopup.png
  docs/static/img/tutorial/versioning-and-release/releasefreeze.png
  docs/static/img/tutorial/versioning-and-release/releasev25.png
  docs/static/img/tutorial/versioning-and-release/releasev2_5.png
  docs/versioned_docs/version-2.5.0/data-sources/overview.md
  docs/versioned_docs/version-2.5.0/tutorial/versioning-and-release.md
Labels: documentation

#6349 [docs] removed: docker-local
  docs/docs/setup/docker-local.md
  docs/versioned_docs/version-1.x.x/setup/docker-local.md
  docs/versioned_docs/version-2.0.0/setup/docker-local.md
  docs/versioned_docs/version-2.1.0/setup/docker-local.md
  docs/versioned_docs/version-2.2.0/setup/docker-local.md
  docs/versioned_docs/version-2.3.0/setup/docker-local.md
  docs/versioned_docs/version-2.4.0/setup/docker-local.md
  docs/versioned_docs/version-2.5.0/setup/docker-local.md
Labels: documentation

#6382 Added data-cy for the event handler input field to fix inspector automation
  frontend/src/Editor/Inspector/ActionConfigurationPanels/SwitchPage.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: data-cy

#6380 Added automation for inspector.
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/support/utils/inspector.js
Labels: testcase

#6377 Modified version and database cypress spec failure
  cypress-tests/cypress/constants/texts/database.js
  cypress-tests/cypress/constants/texts/version.js
  cypress-tests/cypress/e2e/editor/app-version/version.cy.js
  cypress-tests/cypress/support/utils/database.js
  cypress-tests/cypress/support/utils/version.js
Labels: cypress

#6182 feat: Add is operator in tooljet db query manager
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/operations.js
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/util.js
  frontend/src/TooljetDatabase/constants.js
  frontend/src/_helpers/postgrestQueryBuilder.js
Labels: run-ci, tested, active-review-app

#6430 Fixed cypress for v2.6.0
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/constants/texts/database.js
  cypress-tests/cypress/constants/texts/version.js
  cypress-tests/cypress/e2e/editor/app-version/version.cy.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/support/utils/database.js
  cypress-tests/cypress/support/utils/inspector.js
  cypress-tests/cypress/support/utils/version.js
  frontend/src/Editor/Inspector/ActionConfigurationPanels/SwitchPage.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: active-review-app

#6310 [docs]copilot
  docs/docs/copilot.md
  docs/sidebars.js
  docs/static/img/copilot/copilot1.gif
  docs/static/img/copilot/enable.png
  docs/static/img/copilot/query.png
  docs/versioned_docs/version-2.5.0/copilot.md
  docs/versioned_sidebars/version-2.5.0-sidebars.json
Labels: documentation

#6441 [docs] removed copilot from v2.5
  docs/versioned_docs/version-2.5.0/copilot.md
  docs/versioned_sidebars/version-2.5.0-sidebars.json
Labels: documentation

#6459 Added cypress test for share app functionality
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/workspace/shareApp.cy.js
Labels: cypress

#6438 Fix for failing specs on release branch
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/e2e/editor/app-version/version.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/textHappyPath.cy.js
  cypress-tests/cypress/support/utils/commonWidget.js
  frontend/src/_ui/LeftSidebar/Button.jsx
Labels: active-review-app, run-cypress

#6446 fixes: backdrop when alert modal is active for creating new workspace
  frontend/src/_ui/AlertDialog/index.jsx
Labels: tested

#6462 Fixed bug on running query after renaming it
  frontend/src/Editor/Editor.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#6494 Modified datasource cypress spec
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/clickHouseHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/cosmosDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/couchDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/influxDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/postgresHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sqlServerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.js
  cypress-tests/cypress/support/utils/dataSource.js
Labels: cypress

#6416 Enable Marketplace Feature in Review App Deployment Workflow
  .github/workflows/render-preview-deploy.yml
Labels: deployment

#6510 Hot fixed : app is crashing upon clicking on codehinter icon in isEditable field in table column
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx
Labels: bug, tested, hotfix

#6298 Fix : Global settings color popover not closing on outside click
  frontend/src/Editor/Header/GlobalSettings.jsx
Labels: run-ci, tested, active-review-app, documented

#6282 Fix :: No events are running after an empty control component action
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, documented

#6563 Fixes app crash while deleting query created from gds
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: tested

#6568 Fixes draft query rename issue
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryPanel/QueryCard.jsx
Labels: tested

#6101 Fixes the background colour popover broken UI
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/_styles/popover.scss
Labels: run-ci, tested, active-review-app

#6356 Fixed vertical alignment issue for cells in the table component whose column type are action, multiselect,datepicker
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/theme.scss
Labels: bug, run-ci, tested, documented

#6132 Added feature to download table data using component specific actions
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, active-review-app, documented

#6253 fix: display home page if user navigates to hidden page in preview mode
  frontend/src/Editor/Viewer.jsx
Labels: run-ci, tested, active-review-app, documented

#6536 Added automation for runjs
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/inspector.js
  cypress-tests/cypress/support/utils/queries.js
Labels: testcase, active-review-app, run-cypress

#6591 Added data-cy for and runJS for runPy input fields
  frontend/src/Editor/QueryManager/QueryEditors/Runjs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runpy.jsx
Labels: data-cy

#6590 Added automation for runPy
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
Labels: cypress

#6414 [chore] Disable/removing AWS S3 plugin from marketplace
  server/src/assets/marketplace/plugins.json
Labels: active-review-app, marketplace

#6584 Chore: Update snowflake-sdk
  plugins/packages/snowflake/package-lock.json
  plugins/packages/snowflake/package.json
Labels: tested, active-review-app

#6422 improvement - Confirm dialog box after pressing the release app button
  frontend/src/Editor/ReleaseVersionButton.jsx
  frontend/src/_components/ConfirmDialog.jsx
Labels: run-ci, tested, active-review-app, documented, platform

#6472 [Fix] Can't set JSON body of OpenAPI Query
  frontend/src/Editor/QueryManager/QueryEditors/Openapi.jsx
Labels: tested, active-review-app

#6616 fix: Run-ci workflow
  plugins/package-lock.json
Labels: run-ci

#6592 Added app builder specific test run
  .github/workflows/cypress.yml
  cypress-tests/cypress-app-builder.config.js
  cypress-tests/cypress-workspace.config.js
Labels: active-review-app, run-cypress-app-builder
