Repository ToolJet/ToolJet, pull requests merged in 2023-03, with the labels that each got.

#5649 bug fixed, bounded box widget is breaking when default array in the label feild has wrong enteries
  frontend/src/Editor/Components/BoundedBox/BoundedBox.jsx
  frontend/src/Editor/Components/BoundedBox/RenderEditor.jsx
  frontend/src/Editor/Components/BoundedBox/RenderHighlight.jsx
Labels: bug

#5656 bug fixed, app is getting crashed upon clicking columns in the table inspector for the widget inside listview
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_helpers/utils.js
Labels: bug, run-ci

#5455 Add data-cy for database functionality
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateTableDrawer/index.jsx
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/FilterForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/SortForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Search/index.jsx
  frontend/src/TooljetDatabase/Sidebar/index.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/TableList/index.jsx
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  frontend/src/_ui/Pagination/index.jsx
Labels: data-cy

#5685 Marketplace new plugin GitHub
  marketplace/package-lock.json
  marketplace/plugins/github/.gitignore
  marketplace/plugins/github/README.md
  marketplace/plugins/github/__tests__/index.js
  marketplace/plugins/github/lib/icon.svg
  marketplace/plugins/github/lib/index.ts
  marketplace/plugins/github/lib/manifest.json
  marketplace/plugins/github/lib/operations.json
  marketplace/plugins/github/lib/query_operations.ts
  marketplace/plugins/github/lib/types.ts
  marketplace/plugins/github/package.json
  marketplace/plugins/github/tsconfig.json
  server/src/assets/marketplace/plugins.json
Labels: plugins, marketplace

#5710 Add automation for mysql queries
  cypress-tests/cypress/constants/selectors/postgreSql.js
  cypress-tests/cypress/constants/texts/mysql.js
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/support/e2e.js
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/postgreSql.js
  cypress-tests/package-lock.json
  cypress-tests/package.json
Labels: testcase

#5641 Added automation for table filter
  cypress-tests/cypress-run.config.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/table.js
Labels: active-review-app, run-cypress

#5699 Fixes widget alignment issue inside container
  frontend/src/Editor/SubContainer.jsx
Labels: run-ci, tested, active-review-app

#5727 Hotfix - mongodb connection error on passing unescaped characters
  plugins/packages/mongodb/lib/index.ts
Labels: tested, active-review-app

#5738 fixed CI workflow
  .github/workflows/ci.yml
  plugins/package-lock.json
Labels: run-ci

#5299 Fixes button-group label visibility
  frontend/src/Editor/Components/ButtonGroup.jsx
Labels: tested, active-review-app

#5658 Replacing react-google-login library
  frontend/ee/components/LoginPage/GoogleSSOLoginButton.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Oauth/Configs/Config.json
Labels: tested

#5743 fixed broken deployment docs link
  README.md
Labels: documentation

#5741 [docs] updated node and npm versions in v2 docs
  docs/docs/contributing-guide/setup/architecture.md
  docs/docs/contributing-guide/setup/docker.md
  docs/docs/contributing-guide/setup/macos.md
  docs/docs/contributing-guide/setup/ubuntu.md
  docs/docs/contributing-guide/troubleshooting/eslint.md
  docs/docs/setup/kubernetes-aks.md
  docs/docs/setup/kubernetes-gke.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/architecture.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/ubuntu.md
  docs/versioned_docs/version-2.0.0/contributing-guide/troubleshooting/eslint.md
  docs/versioned_docs/version-2.0.0/setup/kubernetes-aks.md
  docs/versioned_docs/version-2.0.0/setup/kubernetes-gke.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/architecture.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/docker.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/ubuntu.md
  docs/versioned_docs/version-2.1.0/contributing-guide/troubleshooting/eslint.md
  docs/versioned_docs/version-2.1.0/setup/kubernetes-aks.md
  docs/versioned_docs/version-2.1.0/setup/kubernetes-gke.md
Labels: documentation

#5740 [how-to] build a new plugin for marketplace
  docs/docs/how-to/build-plugin-for-marketplace.md
  docs/sidebars.js
  docs/versioned_docs/version-2.0.0/how-to/build-plugin-for-marketplace.md
  docs/versioned_docs/version-2.1.0/how-to/build-plugin-for-marketplace.md
  docs/versioned_sidebars/version-2.0.0-sidebars.json
  docs/versioned_sidebars/version-2.1.0-sidebars.json
Labels: documentation

#5683 [fix] exported app from cloud is failing while running RestAPI Oauth
  server/src/services/data_sources.service.ts
Labels: tested

#5702 Add data-cy for App version functionality
  frontend/src/Editor/AppVersionsManager/CreateVersionModal.jsx
  frontend/src/Editor/AppVersionsManager/EditVersionModal.jsx
Labels: data-cy

#5352 fix: Fixed multiselect component label update
  frontend/src/Editor/Components/Multiselect.jsx
Labels: tested

#5765 Radio button widget throws error in debugger when value inside values (array) property is not boolean data type
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: bug, run-ci, tested, documented

#5760 Columns multiple badge and badges dropdown should have proper width in table component
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_styles/theme.scss
Labels: bug, run-ci, tested, documented

#5810 Added automation for mongoDB queries
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/support/commands.js
  cypress-tests/cypress/support/utils/dataSource.js
  cypress-tests/cypress/support/utils/mongoDB.js
Labels: testcase

#5650 bug fixed changed danger alert type's name to error
  docs/docs/actions/show-alert.md
  docs/docs/how-to/run-action-from-runjs.md
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: bug, tested, active-review-app, documented

#5827 Added data-cy for query preview container and undo&redo icons
  frontend/src/Editor/Header/HeaderActions.jsx
  frontend/src/Editor/QueryManager/Preview.jsx
Labels: data-cy

#5380 Kanban Widget 2.0
  docs/docs/actions/close-modal.md
  docs/docs/actions/control-component.md
  docs/docs/actions/copy-to-clipboard.md
  docs/docs/actions/generate-file.md
  docs/docs/actions/go-to-app.md
  docs/docs/actions/logout.md
  docs/docs/actions/open-webpage.md
  docs/docs/actions/run-query.md
  docs/docs/actions/set-localstorage.md
  docs/docs/actions/set-page-var.md
  docs/docs/actions/set-table-page.md
  docs/docs/actions/set-variable.md
  docs/docs/actions/show-alert.md
  docs/docs/actions/show-modal.md
  docs/docs/actions/switch-page.md
  docs/docs/actions/unset-page-var.md
  docs/docs/actions/unset-variable.md
  docs/docs/widgets/kanban-board.md
  docs/static/img/actions/closemodal/closemodal2.png
  docs/static/img/actions/copytoclipboard/copy2.png
  docs/static/img/actions/gotoapp/gotoapp2.png
  docs/static/img/actions/localstorage/debounce.png
  docs/static/img/actions/logout/logout2.png
  docs/static/img/actions/open-webpage/open2.png
  docs/static/img/actions/page/setpagevar2.png
  docs/static/img/actions/page/switchpage2.png
  docs/static/img/actions/page/unsetpagevar2.png
  docs/static/img/actions/run-query/run-query2.png
  docs/static/img/actions/settablepage/page2.png
  docs/static/img/actions/setvar/setvar2.png
  docs/static/img/actions/show-alert/alert2.png
  docs/static/img/actions/showmodal/showmodal2.png
  docs/static/img/actions/unsetvar/unsetvar2.png
  docs/static/img/widgets/kanban/kanban2/events.png
  docs/static/img/widgets/kanban/kanban2/exposedvar.png
  docs/static/img/widgets/kanban/kanban2/kanban2.png
  docs/static/img/widgets/kanban/kanban2/layout.png
  docs/static/img/widgets/kanban/kanban2/props.png
  docs/static/img/widgets/kanban/kanban2/styles.png
  docs/static/img/widgets/kanban/kanban2/tooltip.png
  frontend/assets/images/icons/widgets/kanban.svg
  frontend/assets/translations/en.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Kanban/Components/Container.jsx
  frontend/src/Editor/Components/Kanban/Components/Handle.jsx
  frontend/src/Editor/Components/Kanban/Components/Item.jsx
  frontend/src/Editor/Components/Kanban/Components/Modal.jsx
  frontend/src/Editor/Components/Kanban/Components/Trash.jsx
  frontend/src/Editor/Components/Kanban/Kanban.jsx
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Components/Kanban/helpers/multipleContainersKeyboardCoordinates.js
  frontend/src/Editor/Components/Kanban/helpers/utils.js
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/widgets/kanban.scss
Labels: run-ci, tested, active-review-app, documented

#5777 Enhancements to the process of developing a Marketplace plugin
  cli/src/commands/plugin/create.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/MarketplacePage/MarketplacePlugins.jsx
  frontend/src/MarketplacePage/index.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_services/plugins.service.js
  frontend/webpack.config.js
  marketplace/_templates/plugin/new/docs.ejs.t
  marketplace/_templates/plugin/new/packagejson.ejs.t
  marketplace/lerna.json
  marketplace/package.json
  marketplace/plugins/github/lib/index.ts
  marketplace/plugins/github/package.json
  marketplace/plugins/plivo/package.json
  marketplace/plugins/s3/package.json
  server/src/controllers/plugins.controller.ts
  server/src/helpers/plugins.helper.ts
  server/src/services/plugins.service.ts
Labels: enhancement, run-ci, plugins, tested

#5822 Add data-cy for edit row functionality
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
Labels: data-cy

#5830 [Fix] Global datasources & Environment Id issue
  server/src/services/data_sources.service.ts
Labels: tested

#5832 Fixed modal closing and widget selection issue inside modal
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
Labels: run-ci, active-review-app

#5759 Tree component is not reflecting data correctly
  frontend/src/Editor/Components/ButtonGroup.jsx
  frontend/src/Editor/Components/Steps.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/_helpers/utils.js
Labels: bug, on hold, run-ci, tested, active-review-app, documented

#5767 Added feature to programatically enable/disable, the make editable field in the tables column
  docs/docs/widgets/table.md
  docs/static/img/widgets/table/columns2.png
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/_styles/editor/react-select-search.scss
Labels: feature request, run-ci, tested, active-review-app, documented

#5824 Fix for entrypoint.sh file to take default port value 5432 in database_url
  .env.example
  docs/docs/setup/env-vars.md
  docs/versioned_docs/version-2.2.0/setup/env-vars.md
  server/entrypoint.sh
  server/scripts/database-config-utils.ts
Labels: active-review-app

#5806 Exposed display_values to the exposed variables as optionLabels for dropdown component
  docs/docs/widgets/dropdown.md
  docs/static/img/widgets/dropdown/variables.png
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: feature request, run-ci, tested, active-review-app, documented

#5792 Added dynamic column support in table widget
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/autogenerateColumns.js
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: needs testing, run-ci

#5866 Fix: The error messages isn't showing while login with SSO
  frontend/src/Oauth/Authorize.jsx
Labels: tested, active-review-app

#5857 Fixes for integration issues
  frontend/src/App/App.jsx
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested, active-review-app

#5875 [docs] added plotly chart examples
  docs/docs/widgets/chart.md
  docs/static/img/widgets/chart/plotly/area.png
  docs/static/img/widgets/chart/plotly/bar.png
  docs/static/img/widgets/chart/plotly/bar2.png
  docs/static/img/widgets/chart/plotly/chart1.png
  docs/static/img/widgets/chart/plotly/chart2.png
  docs/static/img/widgets/chart/plotly/line.png
  docs/versioned_docs/version-1.x.x/widgets/chart.md
  docs/versioned_docs/version-2.0.0/widgets/chart.md
  docs/versioned_docs/version-2.1.0/widgets/chart.md
  docs/versioned_docs/version-2.2.0/widgets/chart.md
Labels: documentation

#5879 Fix :: Bug in phone number input during enter key press
  frontend/src/OnBoardingForm/ContinueButton.jsx
  frontend/src/OnBoardingForm/ContinueButtonSelfHost.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
Labels: tested

#5871 Refactoring for Global Datasources Modal and UI
  frontend/assets/images/icons/back.svg
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/GlobalDatasources/CreateDataSourceModal/index.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/left-sidebar.scss
Labels: tested

#5880 [docs] updated ubuntu contributing guides and disable action button
  docs/docs/contributing-guide/setup/ubuntu.md
  docs/docs/widgets/table.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/ubuntu.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/ubuntu.md
  docs/versioned_docs/version-2.2.0/contributing-guide/setup/ubuntu.md
Labels: documentation

#5892 Fix for query event mapping to other query breaks on new version create
  server/src/services/apps.service.ts
Labels: tested, active-review-app

#5882 fix - App version Issues
  frontend/src/Editor/AppVersionsManager/CreateVersionModal.jsx
  frontend/src/Editor/Editor.jsx
Labels: active-review-app
