Repository ToolJet/ToolJet, pull requests merged in 2024-04, with the labels that each got.

#9237 [:docs] change includeCurrentVersion flag to false
  docs/docusaurus.config.js
Labels: active-review-docs-app

#9145 Feature Pocketbase datasource plugin implementation
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/MultiConditions.jsx
  marketplace/plugins/pocketbase/.gitignore
  marketplace/plugins/pocketbase/README.md
  marketplace/plugins/pocketbase/__tests__/index.js
  marketplace/plugins/pocketbase/lib/icon.svg
  marketplace/plugins/pocketbase/lib/index.ts
  marketplace/plugins/pocketbase/lib/manifest.json
  marketplace/plugins/pocketbase/lib/operations.json
  marketplace/plugins/pocketbase/lib/types.ts
  marketplace/plugins/pocketbase/package.json
  marketplace/plugins/pocketbase/tsconfig.json
  server/src/assets/marketplace/plugins.json
Labels: plugins, suspend-review-app, deploy-marketplace-plugin

#9054 Add routing for workspace settings subtabs
  frontend/src/App/App.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Header/index.jsx
Labels: tested

#9223 Revamp: user journey emails
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/mails/assets/github.png
  server/src/mails/assets/linkedin.png
  server/src/mails/assets/rocket.png
  server/src/mails/assets/twitter.png
  server/src/mails/assets/youtube.png
  server/src/mails/base/base_template.hbs
  server/src/mails/base/partials/body.hbs
  server/src/mails/base/partials/footer.hbs
  server/src/mails/base/partials/header.hbs
  server/src/mails/invite_user.hbs
  server/src/mails/reset_password.hbs
  server/src/mails/setup_account.hbs
  server/src/services/auth.service.ts
  server/src/services/email.service.ts
  server/src/services/organization_users.service.ts
Labels: tested

#9102 Updated displayName for button
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: needs testing

#9255 Fix: typo in password reset email
  server/package-lock.json
  server/package.json
  server/src/mails/reset_password.hbs
Labels: tested

#9251 Fix: darkmode and constants routing
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/_components/OrganizationLogin/Configuration.scss
Labels: tested

#9264 Fix: app export modal api failure
  frontend/src/HomePage/ExportAppModal.jsx
  frontend/src/_components/OrganizationLogin/Configuration.scss
  server/src/controllers/apps.controller.ts
Labels: tested, run-cypress-workspace, run-cypress-marketplace

#9233 Fix marketplace workflow remote branch issue
  .github/workflows/maketplace-plugins-deploy.yml
Labels: deploy-marketplace-plugin

#9122 feat: Deprecate few column types in table
  frontend/package-lock.json
  frontend/src/Editor/CodeBuilder/Elements/Select.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/DeprecatedColumnTypeMsg.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/PropertiesTabElements.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/ToolJetUI/List/List.jsx
  frontend/src/ToolJetUI/List/list.scss
  frontend/src/_styles/theme.scss
Labels: needs testing, suspend-review-app

#9268 Adding check for detecting remote branch in marketplace plugin workflow
  .github/workflows/maketplace-plugins-deploy.yml
Labels: deploy-marketplace-plugin

#9025 feat :Table link column
  frontend/src/Editor/Components/Table/Link.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/PropertiesTabElements.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/StylesTabElements.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleProperties.jsx
  frontend/src/_styles/table-component.scss
Labels: needs testing, appbuilder

#9272 hotfix : Not able to view full text while using vertical alignment in text component
  frontend/src/Editor/Components/Text.jsx
Labels: tested

#9289 hotfix: Fix text component and map component issues (v2.34.2)
  .version
  frontend/.version
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/Components/Text.jsx
  server/.version
Labels: run-cypress

#9213 Feature supabase plugin integration
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/MultiConditions.jsx
  marketplace/plugins/supabase/.gitignore
  marketplace/plugins/supabase/README.md
  marketplace/plugins/supabase/__tests__/index.js
  marketplace/plugins/supabase/lib/icon.svg
  marketplace/plugins/supabase/lib/index.ts
  marketplace/plugins/supabase/lib/manifest.json
  marketplace/plugins/supabase/lib/operations.json
  marketplace/plugins/supabase/lib/types.ts
  marketplace/plugins/supabase/package.json
  marketplace/plugins/supabase/tsconfig.json
  server/src/assets/marketplace/plugins.json
Labels: plugins, active-review-app

#9216 [wip] appbuilder - performance
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/BoxUI.jsx
  frontend/src/Editor/CodeBuilder/CodeBuilder.jsx
  frontend/src/Editor/CodeBuilder/Elements/BoxShadow.jsx
  frontend/src/Editor/CodeEditor/utils.js
  frontend/src/Editor/Comment/index.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Container.jsx
  frontend/src/Editor/Components/FilePicker.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Map/Map.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/ControlledComponentToRender.jsx
  frontend/src/Editor/CustomDragLayer.jsx
  frontend/src/Editor/DragContainer.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/EditorSelecto.jsx
  frontend/src/Editor/GhostWidget.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Inspector/Components/Chart.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/ItemTypes.js
  frontend/src/Editor/LeftSidebar/SidebarDebugger/useDebugger.js
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/Middlewares/HydrateWithResolveReferences.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/SubCustomDragLayer.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/editorConstants.js
  frontend/src/Editor/gridUtils.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_helpers/utils.js
  frontend/src/_hoc/withProfiler.jsx
  frontend/src/_hooks/useRenderCount.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/currentStateStore.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/editorStore.js
  frontend/src/_stores/gridStore.js
  frontend/src/_stores/queryPanelStore.js
  frontend/src/_stores/resolverStore.js
  frontend/src/_stores/utils.js
  frontend/src/index.jsx
  frontend/src/wdyr.js
  server/src/helpers/import_export.helpers.ts
  server/src/services/app_import_export.service.ts
Labels: appbuilder, wip

#9304 [:docs] add pocketbase
  docs/docs/marketplace/marketplace_overview.md
  docs/docs/marketplace/plugins/pocketbase.md
  docs/sidebars.js
  docs/static/img/marketplace/plugins/pocketbase/add_query.gif
  docs/static/img/marketplace/plugins/pocketbase/add_record.png
  docs/static/img/marketplace/plugins/pocketbase/delete_record.png
  docs/static/img/marketplace/plugins/pocketbase/get_record.png
  docs/static/img/marketplace/plugins/pocketbase/list_records.png
  docs/static/img/marketplace/plugins/pocketbase/pocketbase_install.png
  docs/static/img/marketplace/plugins/pocketbase/update_record.png
Labels: active-review-docs-app

#9294 updated the runjs guide along with the formating
  docs/docs/how-to/run-action-from-runjs.md
  docs/static/img/how-to/run-actions-from-runjs/runquery-v3.png
  docs/versioned_docs/version-2.29.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.30.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.33.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.34.0/how-to/run-action-from-runjs.md
Labels: active-review-docs-app

#9215 [:docs] Update licensing documentation
  docs/docs/org-management/licensing/cloud.md
  docs/docs/org-management/licensing/self-hosted.md
  docs/sidebars.js
  docs/static/img/licensing/dashboard-free-trial.png
  docs/static/img/licensing/upgrade-business-plan.gif
  docs/static/img/licensing/upgrade-subscription.png
Labels: suspend-review-docs-app

#9287 [Docs]: Supabase plugin
  docs/docs/marketplace/marketplace_overview.md
  docs/docs/marketplace/plugins/supabase.md
  docs/sidebars.js
  docs/static/img/marketplace/plugins/supabase/add_query.gif
  docs/static/img/marketplace/plugins/supabase/api_settings.png
  docs/static/img/marketplace/plugins/supabase/count_rows.png
  docs/static/img/marketplace/plugins/supabase/create_rows.png
  docs/static/img/marketplace/plugins/supabase/delete_rows.png
  docs/static/img/marketplace/plugins/supabase/get_rows.png
  docs/static/img/marketplace/plugins/supabase/supabase_install.png
  docs/static/img/marketplace/plugins/supabase/update_rows.png
Labels: active-review-docs-app

#9333 Codehinter fixes main 2.0
  frontend/src/Editor/CodeEditor/styles.scss
  frontend/src/Editor/CodeEditor/utils.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: tested

#9311 Fix: Dark mode inconsistencies in TJDB dashboard
  frontend/src/TooljetDatabase/Icons/warning-dark.svg
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/AppButton/AppButton.jsx
  frontend/src/_ui/AppButton/AppButton.scss
  frontend/src/_ui/Header/index.jsx
Labels: active-review-app

#8608 Fix: #7059 Exposing page's data on runPy
  frontend/src/_helpers/appUtils.js
Labels: needs testing

#9352 fixes: GraphQL and RestAPI headers & expose page in runpy
  .version
  frontend/.version
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_helpers/appUtils.js
  server/.version
  server/src/services/data_queries.service.ts
Labels: tested, run-cypress

#9341 Feature: Preselect Default Values in Create New Row Form on TJDB Dashboard (Issue: #9332)
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
Labels: active-review-app, database

#9382 Fix for alignment for CTA buttons on blank page
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/HomePage/BlankPage.jsx
Labels: run-ci, tested

#9370 changed translations file and edited HomePage
  frontend/assets/translations/en.json
  frontend/src/HomePage/HomePage.jsx
Labels: run-ci, tested

#9365 changed z-index value
  frontend/src/_styles/theme.scss
Labels: run-ci, tested

#9396 Modified dashboard cypress test case.
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/workspace/dashboard.cy.js
Labels: cypress

#9402 Release platform v14.8 (v2.35.3)
  .version
  frontend/.version
  server/.version
  server/src/services/app_import_export.service.ts
Labels: run-ci, run-cypress

#9423 Migration: set default demo data for older data
  server/data-migrations/1711528858371-MoveTableVisibilityDisabledToStyles.ts
Labels: tested

#9428 [docs]: fix bash snippet
  docs/docs/contributing-guide/setup/macos.md
  docs/versioned_docs/version-1.x.x/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.0.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.1.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.10.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.11.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.12.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.13.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.14.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.15.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.16.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.17.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.18.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.19.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.2.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.22.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.23.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.24.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.25.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.27.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.29.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.3.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.30.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.33.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.34.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.35.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.4.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.5.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.6.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.7.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.8.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.9.0/contributing-guide/setup/macos.md
  docs/versioned_docs/version-2.9.4/contributing-guide/setup/macos.md
Labels: active-review-docs-app

#9429 Fix : Wrapping the content of selected options of multiselect column type
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/table-component.scss
Labels: run-ci, tested, Table component

#9322 Release: platform v14.7 (v2.35.1)
  .version
  cypress-tests/cypress/constants/texts/exportImport.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/workspace/dashboard.cy.js
  frontend/.version
  frontend/assets/translations/en.json
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_styles/theme.scss
  server/.version
  server/src/app.module.ts
  server/src/controllers/apps.controller.ts
  server/src/controllers/import_export_resources.controller.ts
  server/src/modules/casl/abilities/apps-ability.factory.ts
Labels: run-ci, run-cypress

#9431 Fix : String column types bug fixes
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/table-component.scss
Labels: run-ci, Table component

#9425 fix : Remove height and width from table image column / backward compatibility
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/StylesTabElements.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: active-review-app

#9160 feat: added support for annotation in plotly charts
  frontend/src/Editor/Components/Chart.jsx
Labels: tested, suspend-review-app

#9371 [docs]: Update the formatting of server side pagination section
  docs/docs/how-to/serverside-pagination.md
  docs/static/img/how-to/server-side/change-v2.gif
  docs/static/img/how-to/server-side/data-v2.png
  docs/static/img/how-to/server-side/event-v2.png
  docs/static/img/how-to/server-side/pagination-v2.png
  docs/versioned_docs/version-2.30.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.33.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.34.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.35.0/how-to/serverside-pagination.md
Labels: suspend-review-docs-app

#9091 feat: Add light/dark/auto mode theme setting at application level
  frontend/assets/translations/en.json
  frontend/src/App/App.jsx
  frontend/src/Editor/AppVersionsManager/AppVersionsManager.jsx
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Header/AppModeToggle.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Header/HeaderActions.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/Viewer/DesktopHeader.jsx
  frontend/src/Editor/Viewer/MobileHeader.jsx
  frontend/src/Editor/Viewer/MobileNavigationMenu.jsx
  frontend/src/Editor/Viewer/PreviewSettings.jsx
  frontend/src/_components/DarkModeToggle.jsx
  frontend/src/_hooks/useAppDarkMode.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/editorStore.js
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/JSONTreeViewer/JSONNodeValue.jsx
  frontend/src/_ui/Select/SelectComponent.jsx
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
Labels: tested, suspend-review-app

#8388 fix :: Event triggering onclose of modal gets triggered on each refresh
  frontend/src/Editor/Components/Modal.jsx
Labels: tested

#8935 feat: Adding new color swatches and update new components with color variable
  frontend/src/Editor/CodeBuilder/Elements/BoxShadow.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/Eye1.jsx
  frontend/src/_ui/Icon/solidIcons/EyeDisable.jsx
  frontend/src/_ui/Icon/solidIcons/TriangleDownCenter.jsx
  frontend/src/_ui/Icon/solidIcons/TriangleUpCenter.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  frontend/src/_ui/Icon/solidIcons/new-export-1682542240466.json
  frontend/src/_ui/Label.jsx
Labels: tested, suspend-review-app, appbuilder

#8798 fix: fixed icon image of queries in sidebar inspector
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
Labels: bug, tested, appbuilder

#9026 [improvement] Component layout table : Add updatedAt column
  server/migrations/1709794417386-AddUpdatedAtColumnToLayouts.ts
  server/src/entities/layout.entity.ts
  server/src/services/components.service.ts
Labels: enhancement, needs testing, suspend-review-app, appbuilder

#8855 fix: Fixed inconsistent behaviour of check box inside ListView
  frontend/src/Editor/Components/Listview.jsx
Labels: tested

#9023 feat : Updating commonly used components
  frontend/src/Editor/WidgetManager.jsx
Labels: tested, suspend-review-app

#8819 fix: Update scroll bar styling for components
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app

#8885 feat: Updating the format of the name of exported file in table component
  frontend/src/Editor/Components/Table/Table.jsx
Labels: tested, suspend-review-app, documented

#8782 fix: Removed extra border from black ghost button
  frontend/src/_ui/AppButton/AppButton.scss
Labels: tested, suspend-review-app

#9354 [docs]: add invoice history
  docs/docs/org-management/licensing/cloud.md
  docs/static/img/licensing/invoice-history.gif
  docs/versioned_docs/version-2.35.0/org-management/licensing/cloud.md
Labels: suspend-review-docs-app

#9440 Fix : arrow indicators vertical alignment in number column
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/_styles/table-component.scss
Labels: run-ci, tested, Table component

#9437 fix : Link column ui bugs , console error fix when hovering table
  frontend/src/Editor/Components/Table/String.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/PropertiesTabElements.jsx
  frontend/src/_ui/Icon/solidIcons/AlignCenter.jsx
  frontend/src/_ui/Icon/solidIcons/AlignLeft.jsx
  frontend/src/_ui/Icon/solidIcons/AlignRight.jsx
Labels: tested

#9406 fix: number input overlap with increment/decrement button
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: tested

#9441 Number input arrow bug
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: tested

#9024 fix :Pagination component overflowing out of box
  frontend/src/Editor/Components/Pagination.jsx
Labels: tested, suspend-review-app, appbuilder

#8904 Updated column background styles on resize of components
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/table-component.scss
Labels: tested

#9053 feat: Add "Mark all columns as editable" toggle in Table
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleProperties.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/ToolJetUI/List/List.jsx
Labels: tested, suspend-review-app, documented

#9451 [docs]: update the formatting of Import External Libraries using RunJS
  docs/docs/how-to/import-external-lib-js.md
  docs/static/img/how-to/import-js/create-new-query-v2.png
  docs/static/img/how-to/import-js/flatten-js-v2.png
  docs/static/img/how-to/import-js/import-successful-v2.png
  docs/static/img/how-to/import-js/math-js-v2.png
  docs/versioned_docs/version-2.30.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.33.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.34.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.35.0/how-to/import-external-lib-js.md
Labels: active-review-docs-app

#9392 [docs]: Update the formatting of the use-events-on-charts section
  docs/docs/how-to/use-events-on-chart.md
  docs/static/img/how-to/events-chart/plotly-chart-v2.png
  docs/versioned_docs/version-2.30.0/how-to/use-events-on-chart.md
  docs/versioned_docs/version-2.33.0/how-to/use-events-on-chart.md
  docs/versioned_docs/version-2.34.0/how-to/use-events-on-chart.md
  docs/versioned_docs/version-2.35.0/how-to/use-events-on-chart.md
Labels: suspend-review-docs-app

#9465 Bug fixes from appbuilder-1.6
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Components/Table/String.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/Text.jsx
  frontend/src/Editor/Inspector/Components/Table/SelectOptionsList/OptionsList.jsx
  frontend/src/_styles/table-component.scss
Labels: run-ci

#9454 fix : Default table UI
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: active-review-app

#9456 App builder 1.6 integration bug fixes
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/CustomDropdown.jsx
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Components/Table/Datepicker.jsx
  frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
  frontend/src/Editor/Components/Table/String.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/Text.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Components/Table/datepicker.scss
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/DatepickerProperties.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/StylesTabElements.jsx
  frontend/src/Editor/Inspector/Components/Table/SelectOptionsList/OptionsList.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Viewer/viewer.scss
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/editor/react-select-search.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_ui/Accordion/AccordionItem.js
Labels: active-review-app, run-cypress

#9471 Fix string text table column type not pasting in plain-text
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/String.jsx
  frontend/src/Editor/Components/Table/Text.jsx
Labels: tested

#9477 Fix : Boolean column type was not auto generated
  frontend/src/Editor/Components/Table/columns/autogenerateColumns.js
Labels: bug, run-ci, Table component

#9020 fix: The dashboard needs a refresh to get the add folder icon(+) back once the search icon is clicked #8679
  frontend/src/_components/SearchBox.jsx
Labels: tested, suspend-review-app

#9448 Notification modal resized
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app

#9446 bugfix: (issue #9388) Input field and cancel button should be disabled when…
  frontend/src/_components/AppModal.jsx
Labels: tested, suspend-review-app

#9152 Sample database main
  frontend/assets/images/Sample data source.png
  frontend/jsconfig.json
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/DataSourceManager/dataSourceManager.theme.scss
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/queryManager.theme.scss
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/editor.theme.scss
  frontend/src/GlobalDatasources/LIstItem/index.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/GlobalDatasources/index.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/_helpers/constants.js
  frontend/src/_services/library-app.service.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/dataSourcesStore.js
  frontend/src/_stores/storeHelper.js
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/queryManager.scss
  frontend/src/_ui/Icon/bulkIcons/AddTemplate.jsx
  frontend/src/_ui/Icon/bulkIcons/InviteCollabarator.jsx
  frontend/src/_ui/Icon/bulkIcons/index.js
  frontend/src/_ui/Icon/solidIcons/InformationCircle.jsx
  frontend/src/_ui/Icon/solidIcons/Open.jsx
  frontend/src/_ui/Icon/solidIcons/TooljetIcon.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  package.json
  server/migrations/1710321318372-AlterTypeColumnOfDataSourceTable.ts
  server/migrations/1712052754411-AddingSampleDBToExistingWorkspace.ts
  server/package-lock.json
  server/scripts/create-database.ts
  server/scripts/database-config-utils.ts
  server/scripts/populate-sample-db.ts
  server/src/assets/sample-data-json-files/sample_data_country_gdp.json
  server/src/assets/sample-data-json-files/sample_data_orders.json
  server/src/assets/sample-data-json-files/sample_data_organizations.json
  server/src/assets/sample-data-json-files/sample_data_product_cars.json
  server/src/assets/sample-data-json-files/sample_data_users.json
  server/src/controllers/library_apps.controller.ts
  server/src/entities/data_source.entity.ts
  server/src/helpers/data_source.constants.ts
  server/src/helpers/utils.helper.ts
  server/src/modules/library_app/library_app.module.ts
  server/src/modules/organizations/organizations.module.ts
  server/src/schedulers/sampleDB.scheduler.ts
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/group_permissions.service.ts
  server/src/services/library_app_creation.service.ts
  server/src/services/organizations.service.ts
  server/templates/sample_app_def.json
Labels: run-ci, suspend-review-app

#9513 Platform release cypress fix
  frontend/src/Editor/Container.jsx
Labels: run-cypress

#9380 [docs]: add sample data sources
  docs/docs/data-sources/sample-data-sources.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/static/img/datasource-reference/sample-data-sources/canvas.png
  docs/static/img/datasource-reference/sample-data-sources/connect-via-canvas.gif
  docs/static/img/datasource-reference/sample-data-sources/connect-via-query-manager.gif
  docs/static/img/datasource-reference/sample-data-sources/create-sample-app.gif
Labels: suspend-review-docs-app

#9218 Fix package lock file
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
Labels: run-ci

#9516 Add sample db condition on all components
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/QueryManager/Components/DataSourcePicker.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
Labels: run-cypress-app-builder

#9519 Fix: app cards loading state color
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_styles/theme.scss
Labels: tested, active-review-app

#9528 Fix : Replaced the icon of clear button in debugger to trash icon from right aligned icon
  frontend/src/Editor/LeftSidebar/SidebarDebugger/SidebarDebuggerHeader.jsx
Labels: bug, run-ci

#9518 chore: Improvements on super store
  .version
  frontend/.version
  frontend/src/App/App.jsx
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/EditorSelecto.jsx
  frontend/src/Editor/Header/AppModeToggle.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger/SidebarDebuggerHeader.jsx
  frontend/src/Editor/LeftSidebar/SidebarDebugger/useDebugger.js
  frontend/src/Editor/ManageAppUsers.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_contexts/ModuleContext.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/appVersionStore.js
  frontend/src/_stores/currentStateStore.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/dataSourcesStore.js
  frontend/src/_stores/editorStore.js
  frontend/src/_stores/queryPanelStore.js
  frontend/src/_stores/storeHelper.js
  frontend/src/_stores/superStore.js
  frontend/src/index.jsx
  server/.version
Labels: run-cypress

#9493 Release: Platform Community (v2.38.0)
  .version
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/workspace/userPermissions.cy.js
  frontend/.version
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/_components/AppModal.jsx
  frontend/src/_components/SearchBox.jsx
  frontend/src/_styles/theme.scss
  server/.version
Labels: run-ci, run-cypress

#9279 feat : Primary key feature in ToolJet database
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateTableDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Icons/ArrowRight.svg
  frontend/src/TooljetDatabase/Icons/ColumnName.svg
  frontend/src/TooljetDatabase/Icons/Fk-relation.svg
  frontend/src/TooljetDatabase/Icons/Select-column.svg
  frontend/src/TooljetDatabase/Icons/Student.svg
  frontend/src/TooljetDatabase/Icons/Unique-menu.svg
  frontend/src/TooljetDatabase/Table/ActionsPopover/UniqueConstraintPopOver.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/Table/Header.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/TooljetDatabase/constants.js
  frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
  frontend/src/_components/ConfirmDialog.jsx
  frontend/src/_components/ToolTip.jsx
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  frontend/src/_ui/Drawer/DrawerFooter/styles.scss
  frontend/src/_ui/Drawer/index.jsx
  frontend/src/_ui/Icon/solidIcons/PrimaryKey.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/src/controllers/tooljet_db.controller.ts
  server/src/dto/tooljet-db.dto.ts
  server/src/filters/tooljetdb-exception-filter.ts
  server/src/helpers/tjdb_dto_transforms.ts
  server/src/services/tooljet_db.service.ts
Labels: testing, suspend-review-app, database

#9106 Fix : cell select focus border issue in ToolJet database
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app, database

#9462 [docs]: Edit the formatting of Print Data from Multiple Tabs
  docs/docs/how-to/print-multitabs.md
  docs/static/img/how-to/print-multitabs/appui-v2.png
  docs/static/img/how-to/print-multitabs/buttonevents-v2.png
  docs/static/img/how-to/print-multitabs/controlcomp2-v2.png
  docs/static/img/how-to/print-multitabs/data-v2.png
  docs/static/img/how-to/print-multitabs/gettabshtml-v2.png
  docs/static/img/how-to/print-multitabs/q1-v2.png
  docs/static/img/how-to/print-multitabs/q2-v2.png
  docs/static/img/how-to/print-multitabs/q3-v2.png
  docs/static/img/how-to/print-multitabs/unsetvar1-v2.png
  docs/static/img/how-to/print-multitabs/unsetvar2-v2.png
  docs/versioned_docs/version-2.30.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.33.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.34.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.35.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.36.0/how-to/print-multitabs.md
Labels: suspend-review-docs-app

#9463 [docs]: Update the formatting of Setup Syslog from the "How To" section
  docs/docs/how-to/setup-syslog.md
  docs/versioned_docs/version-2.30.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.33.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.34.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.35.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.36.0/how-to/setup-syslog.md
Labels: active-review-docs-app

#9464 [docs]: Enhance Dynamically Change Cell Colors in Table section
  docs/docs/how-to/access-cellvalue-rowdata.md
  docs/versioned_docs/version-2.30.0/how-to/access-cellvalue-rowdata.md
  docs/versioned_docs/version-2.33.0/how-to/access-cellvalue-rowdata.md
  docs/versioned_docs/version-2.34.0/how-to/access-cellvalue-rowdata.md
  docs/versioned_docs/version-2.35.0/how-to/access-cellvalue-rowdata.md
  docs/versioned_docs/version-2.36.0/how-to/access-cellvalue-rowdata.md
Labels: active-review-docs-app

#9480 [docs]: Update the formatting of "Conditional Formatting in Table" from the "How To" section
  docs/docs/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.30.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.33.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.34.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.35.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.36.0/how-to/conditionally-format-table.md
Labels: active-review-docs-app

#9490 [docs]: Enhanced the formatting of "Translating JavaScript Objects to Python in RunPy" in the "How To" section
  docs/docs/how-to/use-to-py.md
  docs/versioned_docs/version-2.30.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.33.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.34.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.35.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.36.0/how-to/use-to-py.md
Labels: active-review-docs-app

#9527 [docs]: Revamped appwrite and baserow data sources from the docs
  docs/docs/data-sources/appwrite.md
  docs/docs/data-sources/baserow.md
  docs/static/img/datasource-reference/appwrite/add-v3.png
  docs/static/img/datasource-reference/appwrite/bulk-v3.png
  docs/static/img/datasource-reference/appwrite/connect-v3.png
  docs/static/img/datasource-reference/appwrite/del-v3.png
  docs/static/img/datasource-reference/appwrite/get-v3.png
  docs/static/img/datasource-reference/appwrite/list-v3.png
  docs/static/img/datasource-reference/appwrite/querying-v3.png
  docs/static/img/datasource-reference/appwrite/upd-v3.png
  docs/static/img/datasource-reference/baserow/baserow-create-row-v2.png
  docs/static/img/datasource-reference/baserow/baserow-delete-row-v2.png
  docs/static/img/datasource-reference/baserow/baserow-get-row-v2.png
  docs/static/img/datasource-reference/baserow/baserow-list-fields-v2.png
  docs/static/img/datasource-reference/baserow/baserow-list-rows-v2.png
  docs/static/img/datasource-reference/baserow/baserow-move-row-v2.png
  docs/static/img/datasource-reference/baserow/baserow-update-row-v2.png
  docs/versioned_docs/version-2.30.0/data-sources/appwrite.md
  docs/versioned_docs/version-2.30.0/data-sources/baserow.md
  docs/versioned_docs/version-2.33.0/data-sources/appwrite.md
  docs/versioned_docs/version-2.33.0/data-sources/baserow.md
  docs/versioned_docs/version-2.34.0/data-sources/appwrite.md
  docs/versioned_docs/version-2.34.0/data-sources/baserow.md
  docs/versioned_docs/version-2.35.0/data-sources/appwrite.md
  docs/versioned_docs/version-2.35.0/data-sources/baserow.md
  docs/versioned_docs/version-2.36.0/data-sources/appwrite.md
  docs/versioned_docs/version-2.36.0/data-sources/baserow.md
Labels: active-review-docs-app
