Repository ToolJet/ToolJet, pull requests merged in 2024-02, with the labels that each got.

#8407 fixes: app versioning with kanban children and import export apps
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
Labels: tested

#8671 test: Add automation for text-input revamp.
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/texts/button.js
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
  cypress-tests/cypress/fixtures/fake.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/editor/inputFieldUtils.js
  cypress-tests/cypress/support/utils/textInput.js
  docs/src/components/DocsCard/DocsCardList.jsx
  frontend/assets/translations/en.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Checkbox.jsx
  frontend/src/Editor/CodeBuilder/Elements/Icon.jsx
  frontend/src/Editor/CodeBuilder/Elements/Input.jsx
  frontend/src/Editor/CodeBuilder/Elements/Slider.jsx
  frontend/src/Editor/CodeBuilder/Elements/Switch.jsx
  frontend/src/Editor/CodeBuilder/Elements/Visibility.jsx
  frontend/src/Editor/CodeBuilder/TypeMapping.js
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Form/FormUtils.js
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/numberinput.scss
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/Elements/Components/ToolTip.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/ToolJetUI/Loader/Loader.jsx
  frontend/src/ToolJetUI/Loader/Loader.scss
  frontend/src/ToolJetUI/SwitchGroup/ToggleGroup.jsx
  frontend/src/ToolJetUI/SwitchGroup/ToggleGroupItem.jsx
  frontend/src/ToolJetUI/SwitchGroup/toggleGroup.scss
  frontend/src/ToolJetUI/Tabs/tabs.scss
  frontend/src/_helpers/utils.js
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Accordion/AccordionItem.js
  frontend/src/_ui/CustomInput/CustomInput.scss
  frontend/src/_ui/CustomInput/index.js
  frontend/src/_ui/Icon/solidIcons/AlignLeftinspector.jsx
  frontend/src/_ui/Icon/solidIcons/AlignRightinspector.jsx
  frontend/src/_ui/Icon/solidIcons/CheveronDown.jsx
  frontend/src/_ui/Icon/solidIcons/CheveronUp.jsx
  frontend/src/_ui/Icon/solidIcons/Eye1.jsx
  frontend/src/_ui/Icon/solidIcons/EyeDisable.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/migrations/1701335703893-TextInputMaxHeight.ts
  server/migrations/1705162272372-numberInputMinMaxValidation.ts
Labels: cypress

#8241 feat: Getter functions for query data and variables
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
Labels: run-ci, tested, suspend-review-app, documented

#8664 Fix : All fx code blocks are getting active when fxActive is true for a table column
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleProperties.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: bug, run-ci, tested, Table component

#8287 feat: Add transformations feature to table columns
  frontend/assets/translations/en.json
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
Labels: tested, suspend-review-app

#8525 feat:Allow custom id for dynamically generated columns
  frontend/src/Editor/Components/Table/columns/autogenerateColumns.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: tested, suspend-review-app

#8163 fix: Only one of the events trigger when multiple events with debounce is created
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, appbuilder

#8616 feat: Fire row click event on checkbox click in table
  frontend/src/Editor/Components/Table/IndeterminateCheckbox.jsx
  frontend/src/Editor/Components/Table/Table.jsx
Labels: tested

#8588 feat: Add loader when creating and updating events
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/ManageEventButton.jsx
  frontend/src/ToolJetUI/Buttons/AddNewButton/AddNewButton.jsx
  frontend/src/_stores/appDataStore.js
Labels: tested

#8079 feat: Textinput , Passwordinput , Numberinput revamp
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Checkbox.jsx
  frontend/src/Editor/CodeBuilder/Elements/Slider.jsx
  frontend/src/Editor/CodeBuilder/Elements/Slider.scss
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/ToolJetUI/SwitchGroup/toggleGroup.scss
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app, appbuilder

#8637 feat: Add setFilters and clearFilters CSA in table
  frontend/src/Editor/Components/Table/Filter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: active-review-app, documented, appbuilder

#8347 Feat: query parameters for all queries
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/CodeHinterContext.js
  frontend/src/Editor/QueryManager/Components/ParameterDetails.jsx
  frontend/src/Editor/QueryManager/Components/ParameterForm.jsx
  frontend/src/Editor/QueryManager/Components/ParameterList.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Runjs/Runjs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/utils.js
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/constants.js
  frontend/src/Editor/QueryPanel/FilterandSortPopup.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/components.scss
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app, documented

#8581 feat: enable or disable row selection on click of cell using property
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/load-properties-and-styles.js
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: feature request, run-ci, tested, Table component

#8674 feat: CSA to select and deselect all rows in the table component
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
Labels: feature request, run-ci, tested, suspend-review-app, Table component

#8384 feat: Preview App header revamp
  frontend/src/App/App.jsx
  frontend/src/Editor/AppVersionsManager/AppVersionsManager.jsx
  frontend/src/Editor/AppVersionsManager/CustomSelect.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Header/HeaderActions.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/Viewer/DesktopHeader.jsx
  frontend/src/Editor/Viewer/Header.jsx
  frontend/src/Editor/Viewer/MobileHeader.jsx
  frontend/src/Editor/Viewer/MobileNavigationMenu.jsx
  frontend/src/Editor/Viewer/PreviewSettings.jsx
  frontend/src/Editor/Viewer/ViewerNavigation.jsx
  frontend/src/Editor/Viewer/ViewerSidebarNavigation.jsx
  frontend/src/Editor/Viewer/viewer.scss
  frontend/src/_stores/appDataStore.js
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_ui/Icon/solidIcons/TooljetLogoIcon.jsx
  frontend/src/_ui/Icon/solidIcons/TooljetLogoText.jsx
  server/src/controllers/metadata.controller.ts
Labels: tested, suspend-review-app, documented

#8622 Feature: Nullable csv bulk upload
  server/src/services/tooljet_db_bulk_upload.service.ts
Labels: active-review-app

#8705 fix: In mobile view components are not showing up for the launched apps
  frontend/src/Editor/Viewer.jsx
Labels: bug, run-ci, tested, documented

#8097 feat: Text component revamp
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Color.jsx
  frontend/src/Editor/CodeBuilder/Elements/NumberInput.jsx
  frontend/src/Editor/CodeBuilder/Elements/Switch.jsx
  frontend/src/Editor/CodeBuilder/TypeMapping.js
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/ToolJetUI/Loader/Loader.jsx
  frontend/src/ToolJetUI/SwitchGroup/toggleGroup.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/AlignVerticallyBottom.jsx
  frontend/src/_ui/Icon/solidIcons/AlignVerticallyCenter.jsx
  frontend/src/_ui/Icon/solidIcons/AlignVerticallyTop.jsx
  frontend/src/_ui/Icon/solidIcons/Capitalize.jsx
  frontend/src/_ui/Icon/solidIcons/Italic.jsx
  frontend/src/_ui/Icon/solidIcons/Linethrough.jsx
  frontend/src/_ui/Icon/solidIcons/Lowercase.jsx
  frontend/src/_ui/Icon/solidIcons/Oblique.jsx
  frontend/src/_ui/Icon/solidIcons/Overline.jsx
  frontend/src/_ui/Icon/solidIcons/Underline.jsx
  frontend/src/_ui/Icon/solidIcons/Uppercase.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
  frontend/src/_ui/JSONTreeViewer/JSONTreeViewer.jsx
  server/data-migrations/1698663642825-MoveStatesFromStylesToProperties.ts
Labels: tested, suspend-review-app

#8683 feat: Small revamp on Chart component
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Inspector/Components/Chart.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/components.scss
Labels: tested, active-review-app

#8673 [hotfix] : import/export api not picking display preferences of widgets
  .version
  frontend/.version
  server/.version
  server/src/services/app_import_export.service.ts
Labels: tested, hotfix

#8717 fix: query details are not available in the current state before the query is run
  frontend/src/_stores/dataQueriesStore.js
Labels: bug, tested, appbuilder

#8722 Fix: #8647 OAuth code discarded when saving data source through confirm modal
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
Labels: tested

#8715 feat: Added a scrollbar on pages menu in viewer
  frontend/src/Editor/Viewer.jsx
  frontend/src/Editor/Viewer/ViewerSidebarNavigation.jsx
Labels: tested

#8719 fix: Modal crashing , fixes in form with custom schema
  frontend/src/Editor/Components/Form/FormUtils.js
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_ui/JSONTreeViewer/JSONNode.jsx
Labels: tested

#8638 migration: Move visibility and disabled states from style to properties
  server/data-migrations/1706080528978-MoveVisibilityDisabledStatesToProperties.ts
Labels: tested, appbuilder

#8160 feat : New dropdown revamp
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Slider.jsx
  frontend/src/Editor/CodeBuilder/Elements/Visibility.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/Table/SelectComponent.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Components/Select.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/CheckMark.jsx
  server/data-migrations/1706080528978-MoveVisibilityDisabledStatesToProperties.ts
Labels: tested, suspend-review-app

#8714 fix : Darkmode color fix for box shadow and default size fix for labels in input
  frontend/src/Editor/CodeBuilder/Elements/BoxShadow.jsx
  frontend/src/Editor/CodeBuilder/Elements/Icon.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
Labels: tested

#8736 [docs]version fixes in setup guides
  docs/docs/setup/azure-container.md
  docs/docs/setup/client.md
  docs/docs/setup/digitalocean.md
  docs/docs/setup/docker.md
  docs/docs/setup/ec2.md
  docs/docs/setup/ecs.md
  docs/docs/setup/google-cloud-run.md
  docs/docs/setup/helm.md
  docs/docs/setup/kubernetes-aks.md
  docs/docs/setup/kubernetes-gke.md
  docs/docs/setup/kubernetes.md
  docs/docs/setup/openshift.md
  docs/docs/setup/tooljet-subpath.md
  docs/versioned_docs/version-2.24.0/setup/azure-container.md
  docs/versioned_docs/version-2.24.0/setup/client.md
  docs/versioned_docs/version-2.24.0/setup/digitalocean.md
  docs/versioned_docs/version-2.24.0/setup/docker.md
  docs/versioned_docs/version-2.24.0/setup/ec2.md
  docs/versioned_docs/version-2.24.0/setup/ecs.md
  docs/versioned_docs/version-2.24.0/setup/google-cloud-run.md
  docs/versioned_docs/version-2.24.0/setup/helm.md
  docs/versioned_docs/version-2.24.0/setup/kubernetes-aks.md
  docs/versioned_docs/version-2.24.0/setup/kubernetes-gke.md
  docs/versioned_docs/version-2.24.0/setup/kubernetes.md
  docs/versioned_docs/version-2.24.0/setup/openshift.md
  docs/versioned_docs/version-2.24.0/setup/tooljet-subpath.md
  docs/versioned_docs/version-2.25.0/setup/azure-container.md
  docs/versioned_docs/version-2.25.0/setup/client.md
  docs/versioned_docs/version-2.25.0/setup/digitalocean.md
  docs/versioned_docs/version-2.25.0/setup/docker.md
  docs/versioned_docs/version-2.25.0/setup/ec2.md
  docs/versioned_docs/version-2.25.0/setup/ecs.md
  docs/versioned_docs/version-2.25.0/setup/google-cloud-run.md
  docs/versioned_docs/version-2.25.0/setup/helm.md
  docs/versioned_docs/version-2.25.0/setup/kubernetes-aks.md
  docs/versioned_docs/version-2.25.0/setup/kubernetes-gke.md
  docs/versioned_docs/version-2.25.0/setup/kubernetes.md
  docs/versioned_docs/version-2.25.0/setup/openshift.md
  docs/versioned_docs/version-2.25.0/setup/tooljet-subpath.md
  docs/versioned_docs/version-2.27.0/setup/azure-container.md
  docs/versioned_docs/version-2.27.0/setup/client.md
  docs/versioned_docs/version-2.27.0/setup/digitalocean.md
  docs/versioned_docs/version-2.27.0/setup/docker.md
  docs/versioned_docs/version-2.27.0/setup/ec2.md
  docs/versioned_docs/version-2.27.0/setup/ecs.md
  docs/versioned_docs/version-2.27.0/setup/google-cloud-run.md
  docs/versioned_docs/version-2.27.0/setup/helm.md
  docs/versioned_docs/version-2.27.0/setup/kubernetes-aks.md
  docs/versioned_docs/version-2.27.0/setup/kubernetes-gke.md
  docs/versioned_docs/version-2.27.0/setup/kubernetes.md
  docs/versioned_docs/version-2.27.0/setup/openshift.md
  docs/versioned_docs/version-2.27.0/setup/tooljet-subpath.md
Labels: documentation

#8738 test: Add automation for dropdown -specefic cases
  cypress-tests/cypress/e2e/editor/widget/dropdownHappyPath.cy.js
  cypress-tests/cypress/support/utils/dropdown.js
  cypress-tests/cypress/support/utils/events.js
Labels: cypress

#8577 test: Added automation for title verification
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/editor/widget/appTitle.cy.js
Labels: cypress

#8697 test: Text component automation revamp
  cypress-tests/cypress/e2e/editor/widget/textHappyPath.cy.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/inspector.js
Labels: cypress

#8538 Feature: TJDB UX Revamp
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Icons/Enter.svg
  frontend/src/TooljetDatabase/Icons/LeftNav.svg
  frontend/src/TooljetDatabase/Icons/RightNav.svg
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
  frontend/src/TooljetDatabase/Menu/CellEditMenu/styles.scss
  frontend/src/TooljetDatabase/Sidebar/index.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/AddNewDataPopOver.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/Header.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Header/index.jsx
  frontend/src/_ui/Icon/solidIcons/EnterButtonIcon.jsx
  frontend/src/_ui/Icon/solidIcons/Expand.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  frontend/src/_ui/IndeterminateCheckbox/index.jsx
  frontend/src/_ui/Layout/index.jsx
  marketplace/plugins/openai/lib/icon.svg
  server/src/services/tooljet_db_bulk_upload.service.ts
Labels: tested, suspend-review-app

#8757 migration: Move visibility, disabled, and tooltip to properties
  server/data-migrations/1707466537651-MoveVisibilityDisabledStatesToProperties.ts
Labels: tested

#8750 fix: Move visibility, disabled and tooltip from styles to properties in import export
  server/src/services/app_import_export.service.ts
Labels: tested

#8776 Inspector is not positioned properly in firefox
  frontend/src/_styles/popover.scss
Labels: bug, run-ci, tested

#8768 [hot-fix]User couldn't able to export app after creating a new version
  frontend/src/HomePage/ExportAppModal.jsx
Labels: tested

#8778 [hotfix] fixes: mobile view rendering of components
  .version
  frontend/.version
  frontend/src/Editor/Viewer.jsx
  server/.version
Labels: tested, hotfix

#8760 Bugfix/marketplace 1.6 release
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/_ui/Header/index.jsx
Labels: run-ci, active-review-app

#8774 fix: Make label as empty string for older text, password and number input components
  server/src/services/app_import_export.service.ts
Labels: tested

#8737 fix: Integration fixes for inputs ( Alignment issues )
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/CodeBuilder/CodeHinter.jsx
  frontend/src/Editor/CodeBuilder/Elements/Checkbox.jsx
  frontend/src/Editor/CodeBuilder/Elements/NumberInput.jsx
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/Text.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Label.jsx
  server/data-migrations/1707466537651-MoveVisibilityDisabledStatesToProperties.ts
  server/migrations/1701335703893-TextInputMaxHeight.ts
  server/migrations/1705162272372-numberInputMinMaxValidation.ts
Labels: tested, active-review-app, run-cypress-app-builder

#8792 fix : Remove older migration file
  server/data-migrations/1698663642825-MoveStatesFromStylesToProperties.ts
Labels: tested

#8794 fix: Fix import export issue on migrating revamped components
  server/src/services/app_import_export.service.ts
Labels: tested

#8793 fix: Loader position in text widget , migration fixes
  frontend/src/Editor/Components/Text.jsx
  frontend/src/ToolJetUI/Loader/Loader.jsx
  frontend/src/ToolJetUI/Loader/Loader.scss
  server/data-migrations/1707466537651-MoveVisibilityDisabledStatesToProperties.ts
Labels: tested

#8797 test: Appbuilder-1.5 Automation fix.
  cypress-tests/cypress/constants/texts/common.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/editor/text.js
Labels: cypress

#8763 Fixed datasource cypress failure specs
  cypress-tests/cypress/constants/texts/postgreSql.js
  cypress-tests/cypress/e2e/database/database.cy.skip.js
  cypress-tests/cypress/e2e/exportImport/export.cy.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
Labels: active-review-app, run-cypress-marketplace

#8744 Fix: Dark mode issues across the app
  frontend/ee/components/UsersPage/UsersTable.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/ManageOrgUsers/UserGroupsSelect.jsx
  frontend/src/_components/LogoNavDropdown.jsx
  frontend/src/_styles/theme.scss
Labels: tested

#8784 Fix: app loader state in dark mode
  frontend/src/Editor/AppVersionsManager/CustomSelect.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/ManageOrgConstants/EmptyState.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/TJLoader/TJLoader.jsx
  frontend/src/index.ejs
Labels: tested

#8817 fix: Apply transformation to preview data on query run from panel
  frontend/src/_helpers/appUtils.js
Labels: run-ci, tested, appbuilder

#8818 Fixed the automation failure for marketplace 1.6
  cypress-tests/cypress/e2e/editor/data-source/azureBlobStorageHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/bigqueryHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/clickHouseHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/cosmosDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/couchDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/dynamoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/elasticsearchHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/fireStoreHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/influxDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mariaDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/mongoDbHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/mysqlHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/postgresHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/redisHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/rethinkDbHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/editor/data-source/s3HappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/smtpHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/snowflakeHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/sqlServerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/data-source/typeSenseHappyPath.cy.skip.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
Labels: run-cypress-marketplace

#8530 [docs] reset password
  docs/docs/user-authentication/password-login.md
  docs/static/img/sso/general/auto-password.png
  docs/static/img/sso/general/create-password.png
  docs/static/img/sso/general/forgot-password.png
  docs/static/img/sso/general/password-login.png
Labels: documentation, suspend-review-docs-app

#8531 [docs] new edit+archive flow
  docs/docs/Enterprise/superadmin.md
  docs/docs/tutorial/manage-users-groups.md
  docs/static/img/enterprise/superadmin/alluserspage.png
  docs/static/img/enterprise/superadmin/archiveinstance.png
  docs/static/img/enterprise/superadmin/edituserdetailsinstance.png
  docs/static/img/enterprise/superadmin/unarchiveinstance.png
  docs/static/img/tutorial/manage-users-groups/addusers.png
  docs/static/img/tutorial/manage-users-groups/archiveuser.png
  docs/static/img/tutorial/manage-users-groups/bulkinviten.png
  docs/static/img/tutorial/manage-users-groups/copylink.png
  docs/static/img/tutorial/manage-users-groups/edituserdetails.png
  docs/static/img/tutorial/manage-users-groups/invitemodal.png
  docs/static/img/tutorial/manage-users-groups/unarchiveuser.png
  docs/static/img/tutorial/manage-users-groups/users3.png
Labels: documentation, suspend-review-docs-app

#8841 feat: Expose clicked series name in charts
  .version
  frontend/.version
  frontend/src/Editor/Components/Chart.jsx
  server/.version
Labels: run-ci

#8689 Login/SSO revamp
  frontend/assets/images/EditIcon.png
  frontend/assets/images/Github.png
  frontend/assets/images/Google.png
  frontend/src/HomePage/Modal.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/OrganizationLogin/Configuration.css
  frontend/src/_components/OrganizationLogin/DisablePasswordLoginModal.jsx
  frontend/src/_components/OrganizationLogin/EnableModal.jsx
  frontend/src/_components/OrganizationLogin/GithubSsoModal.jsx
  frontend/src/_components/OrganizationLogin/GoogleSsoModal.jsx
  frontend/src/_components/OrganizationLogin/OrganizationLogin.jsx
  frontend/src/_components/OrganizationLogin/SsoConfiguration.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/EditIcon.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/src/services/auth.service.ts
Labels: suspend-review-app

#8847 [docs] platform milestone 11
  docs/docs/Enterprise/superadmin.md
  docs/docs/tutorial/manage-users-groups.md
  docs/docs/user-authentication/password-login.md
  docs/docs/user-authentication/sso/github.md
  docs/docs/user-authentication/sso/openid/setup.md
  docs/static/img/enterprise/superadmin/alluserspage.png
  docs/static/img/enterprise/superadmin/archiveinstance.png
  docs/static/img/enterprise/superadmin/edituserdetailsinstance.png
  docs/static/img/enterprise/superadmin/unarchiveinstance.png
  docs/static/img/sso/general/auto-password.png
  docs/static/img/sso/general/create-password.png
  docs/static/img/sso/general/forgot-password.png
  docs/static/img/sso/general/password-login.png
  docs/static/img/sso/git/gitdev.png
  docs/static/img/sso/git/queryresults.png
  docs/static/img/sso/git/ssogit.png
  docs/static/img/sso/git/ssogithub.png
  docs/static/img/sso/git/workset.png
  docs/static/img/tutorial/manage-users-groups/addusers.png
  docs/static/img/tutorial/manage-users-groups/archiveuser.png
  docs/static/img/tutorial/manage-users-groups/bulkinviten.png
  docs/static/img/tutorial/manage-users-groups/copylink.png
  docs/static/img/tutorial/manage-users-groups/edituserdetails.png
  docs/static/img/tutorial/manage-users-groups/invitemodal.png
  docs/static/img/tutorial/manage-users-groups/unarchiveuser.png
  docs/static/img/tutorial/manage-users-groups/users3.png
  docs/versioned_docs/version-2.29.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.29.0/tutorial/manage-users-groups.md
  docs/versioned_docs/version-2.29.0/user-authentication/password-login.md
  docs/versioned_docs/version-2.29.0/user-authentication/sso/github.md
  docs/versioned_docs/version-2.29.0/user-authentication/sso/openid/setup.md
  docs/versioned_docs/version-2.30.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.30.0/tutorial/manage-users-groups.md
  docs/versioned_docs/version-2.30.0/user-authentication/password-login.md
  docs/versioned_docs/version-2.30.0/user-authentication/sso/github.md
  docs/versioned_docs/version-2.30.0/user-authentication/sso/openid/setup.md
Labels: documentation

#8804 test: Cypress automation revamp appbuilder 1.5
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/e2e/editor/queries/chainingOfQueries.cy.js
  cypress-tests/cypress/e2e/editor/queries/runjsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/runpyHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/appTitle.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentDuplicationHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/csa.cy.js
  cypress-tests/cypress/e2e/editor/widget/datePickerHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/modalHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/multiselectHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/numberInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/e2e/editor/widget/textHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
  cypress-tests/cypress/support/utils/button.js
  cypress-tests/cypress/support/utils/commonWidget.js
  cypress-tests/cypress/support/utils/editor/passwordNumberInput.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/listviewWidget.js
  cypress-tests/cypress/support/utils/modal.js
  cypress-tests/cypress/support/utils/table.js
Labels: suspend-review-app

#8880 [docs] archive/unarchive workspaces: superadmin
  docs/docs/Enterprise/superadmin.md
  docs/static/img/enterprise/superadmin/allusers1.png
  docs/static/img/enterprise/superadmin/allworkspaces.png
  docs/static/img/enterprise/superadmin/archiveusersa.png
  docs/static/img/enterprise/superadmin/instanceoptions.png
  docs/static/img/enterprise/superadmin/settings.png
  docs/static/img/enterprise/superadmin/workspaces1.png
  docs/static/img/enterprise/superadmin/workspaces2.png
  docs/versioned_docs/version-2.29.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.30.0/Enterprise/superadmin.md
Labels: documentation

#8566 [Improvements] Onboarding enter to save changes
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnBoardingRadioInput.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/_styles/onboarding.scss
Labels: suspend-review-app, design-approved

#8665 Removed case-sensitive validation from the folder creation modal and API
  frontend/src/HomePage/Folders.jsx
  frontend/src/_helpers/utils.js
  server/migrations/1706643884614-ChangeTypeOfFolderName.ts
  server/src/dto/create-folder.dto.ts
Labels: tested

#8858 Fix: editor loading state on back to apps redirection
  frontend/src/_components/LogoNavDropdown.jsx
Labels: tested

#8888 chore: Update webpack config only to include sentry when env APM VENDOR is 'sentry'
  frontend/webpack.config.js
Labels: tested

#8890 hotfix: Checked items not getting exposed in treeselect component
  .version
  frontend/.version
  frontend/src/Editor/Components/TreeSelect.jsx
  server/.version
Labels: tested

#8688 [docs] revamped how-to guides
  docs/docs/how-to/access-users-location.md
  docs/docs/how-to/import-external-lib-js.md
  docs/docs/how-to/intentionally-fail-js-query.md
  docs/docs/how-to/run-action-from-runjs.md
  docs/docs/how-to/run-query-at-specified-intervals.md
  docs/docs/how-to/serverside-pagination.md
  docs/docs/how-to/use-to-py.md
  docs/static/img/how-to/access-location/newapp.png
  docs/static/img/how-to/access-location/newdata.png
  docs/static/img/how-to/access-location/newmap.png
  docs/static/img/how-to/access-location/newprompt.png
  docs/static/img/how-to/access-location/runjsq.png
  docs/static/img/how-to/failjs/failjsn.gif
  docs/static/img/how-to/import-js/flattens.png
  docs/static/img/how-to/import-js/importeds.png
  docs/static/img/how-to/import-js/mathjss.png
  docs/static/img/how-to/import-js/neww.png
  docs/static/img/how-to/run-actions-from-runjs/closemodaln.png
  docs/static/img/how-to/run-actions-from-runjs/copytoclip.png
  docs/static/img/how-to/run-actions-from-runjs/generatefilen.png
  docs/static/img/how-to/run-actions-from-runjs/gotoappn.png
  docs/static/img/how-to/run-actions-from-runjs/logoutn.png
  docs/static/img/how-to/run-actions-from-runjs/runqueryn.png
  docs/static/img/how-to/run-actions-from-runjs/setlocaln.png
  docs/static/img/how-to/run-actions-from-runjs/setvariablen.png
  docs/static/img/how-to/run-actions-from-runjs/showalertn.png
  docs/static/img/how-to/run-actions-from-runjs/showmodaln.png
  docs/static/img/how-to/run-actions-from-runjs/unsetvarn.png
  docs/static/img/how-to/setinterval/clearint.png
  docs/static/img/how-to/setinterval/queryp.png
  docs/static/img/how-to/setinterval/queryprev.png
  docs/static/img/how-to/setinterval/settings.png
  docs/static/img/how-to/setinterval/table.png
  docs/static/img/how-to/to_py/topy.gif
  docs/versioned_docs/version-2.25.0/how-to/access-users-location.md
  docs/versioned_docs/version-2.25.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.25.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.25.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.25.0/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-2.25.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.25.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.27.0/how-to/access-users-location.md
  docs/versioned_docs/version-2.27.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.27.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.27.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.27.0/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-2.27.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.27.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.29.0/how-to/access-users-location.md
  docs/versioned_docs/version-2.29.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.29.0/how-to/use-to-py.md
  docs/versioned_docs/version-2.30.0/how-to/access-users-location.md
  docs/versioned_docs/version-2.30.0/how-to/import-external-lib-js.md
  docs/versioned_docs/version-2.30.0/how-to/intentionally-fail-js-query.md
  docs/versioned_docs/version-2.30.0/how-to/run-action-from-runjs.md
  docs/versioned_docs/version-2.30.0/how-to/run-query-at-specified-intervals.md
  docs/versioned_docs/version-2.30.0/how-to/serverside-pagination.md
  docs/versioned_docs/version-2.30.0/how-to/use-to-py.md
Labels: documentation

#8897 hotfix: The slider used for width control in the inspector is breaking the component when moved too quickly.
  frontend/src/Editor/CodeBuilder/Elements/Slider.jsx
Labels: tested, suspend-review-app

#8909 Login SSO configurations UI/UX revamp
  frontend/assets/images/EditIcon.png
  frontend/assets/images/Github.png
  frontend/assets/images/Google.png
  frontend/src/HomePage/Modal.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/OrganizationLogin/Configuration.scss
  frontend/src/_components/OrganizationLogin/DisablePasswordLoginModal.jsx
  frontend/src/_components/OrganizationLogin/GithubSsoModal.jsx
  frontend/src/_components/OrganizationLogin/GoogleSsoModal.jsx
  frontend/src/_components/OrganizationLogin/OrganizationLogin.jsx
  frontend/src/_components/OrganizationLogin/SsoConfiguration.jsx
  frontend/src/_components/OrganizationLogin/WorkspaceSSOEnableModal.jsx
  frontend/src/_styles/theme.scss
  server/src/services/auth.service.ts
Labels: run-ci

#8551 [Improvement] Enter to save
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/ManageOrgConstants/ConstantForm.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnBoardingRadioInput.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/_components/AppModal.jsx
  frontend/src/_components/FormWrapper.jsx
  frontend/src/_components/OrganizationManager/CreateOrganization.jsx
  frontend/src/_styles/onboarding.scss
Labels: suspend-review-app, design-approved

#8908 hotfix: Remove restricted height in inputs
  frontend/src/Editor/Box.jsx
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/ConfigHandle.jsx
  frontend/src/Editor/DraggableBox.jsx
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_styles/theme.scss
Labels: run-ci, tested, hotfix, active-review-app, appbuilder

#8920 Fix for auto handling disabled password login in case all sso's are turned off
  frontend/src/_components/OrganizationLogin/OrganizationLogin.jsx
  frontend/src/_components/OrganizationLogin/SsoConfiguration.jsx
Labels: tested

#8919 Modified cypress test cases for platform release 14
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/ce/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/support/utils/manageUsers.js
  frontend/src/ManageOrgUsers/UserGroupsSelect.jsx
Labels: data-cy, cypress

#8929 App builder automation fixed for platform-v14
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/chainingOfQueries.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/support/utils/button.js
  cypress-tests/cypress/support/utils/editor/passwordNumberInput.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/listviewWidget.js
Labels: cypress

#8911 fix : Adapt current component properties update to codhinter improvements
  frontend/src/Editor/CodeBuilder/Elements/Input.jsx
  frontend/src/Editor/CodeBuilder/Elements/NumberInput.jsx
  frontend/src/Editor/CodeBuilder/Elements/Switch.jsx
  frontend/src/Editor/CodeEditor/PreviewBox.jsx
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/Code.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/WidgetManager/configs/numberinput.js
  frontend/src/Editor/WidgetManager/configs/passwordinput.js
  frontend/src/Editor/WidgetManager/configs/text.js
  frontend/src/Editor/WidgetManager/configs/textinput.js
  frontend/src/_styles/theme.scss
Labels: appbuilder

#8894 Release Platform v14
  .version
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/ce/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/editor/globalSetingsHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/queries/chainingOfQueries.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/listViewHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
  cypress-tests/cypress/e2e/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/support/utils/button.js
  cypress-tests/cypress/support/utils/editor/passwordNumberInput.js
  cypress-tests/cypress/support/utils/events.js
  cypress-tests/cypress/support/utils/listviewWidget.js
  cypress-tests/cypress/support/utils/manageUsers.js
  frontend/.version
  frontend/assets/images/EditIcon.png
  frontend/assets/images/Github.png
  frontend/assets/images/Google.png
  frontend/src/ConfirmationPage/OrganizationInvitationPage.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/Modal.jsx
  frontend/src/ManageOrgConstants/ConstantForm.jsx
  frontend/src/ManageOrgUsers/UserGroupsSelect.jsx
  frontend/src/ManageSSO/Form.jsx
  frontend/src/ManageSSO/GeneralSettings.jsx
  frontend/src/ManageSSO/Git.jsx
  frontend/src/ManageSSO/Google.jsx
  frontend/src/ManageSSO/ManageSSO.jsx
  frontend/src/ManageSSO/index.js
  frontend/src/OnBoardingForm/OnBoardingForm.jsx
  frontend/src/OnBoardingForm/OnBoardingRadioInput.jsx
  frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/_components/AppModal.jsx
  frontend/src/_components/FormWrapper.jsx
  frontend/src/_components/LogoNavDropdown.jsx
  frontend/src/_components/OrganizationLogin/Configuration.scss
  frontend/src/_components/OrganizationLogin/DisablePasswordLoginModal.jsx
  frontend/src/_components/OrganizationLogin/GithubSsoModal.jsx
  frontend/src/_components/OrganizationLogin/GoogleSsoModal.jsx
  frontend/src/_components/OrganizationLogin/OrganizationLogin.jsx
  frontend/src/_components/OrganizationLogin/SsoConfiguration.jsx
  frontend/src/_components/OrganizationLogin/WorkspaceSSOEnableModal.jsx
  frontend/src/_components/OrganizationManager/CreateOrganization.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_styles/onboarding.scss
  frontend/src/_styles/theme.scss
  server/.version
  server/migrations/1706643884614-ChangeTypeOfFolderName.ts
  server/src/dto/create-folder.dto.ts
  server/src/services/auth.service.ts
Labels: run-ci, run-cypress

#8949 [docs] how to-use url params on load
  docs/docs/how-to/use-url-params-on-load.md
  docs/sidebars.js
  docs/static/img/how-to/use-url-params/event.png
  docs/static/img/how-to/use-url-params/form.png
  docs/static/img/how-to/use-url-params/onpageload.png
  docs/static/img/how-to/use-url-params/pages.png
  docs/static/img/how-to/use-url-params/table1.png
  docs/static/img/how-to/use-url-params/table2.png
  docs/static/img/how-to/use-url-params/urlparams.png
  docs/versioned_docs/version-2.29.0/how-to/use-url-params-on-load.md
  docs/versioned_docs/version-2.30.0/how-to/use-url-params-on-load.md
  docs/versioned_sidebars/version-2.29.0-sidebars.json
  docs/versioned_sidebars/version-2.30.0-sidebars.json
Labels: documentation

#8948 hotfix: Chart and image are misaligned due to different default padding
  .version
  frontend/.version
  frontend/src/Editor/Box.jsx
  server/.version
Labels: tested, hotfix, appbuilder

#8769 (wip) [improvement] Implementation of a Mapping Table for Seamless client-server Interaction
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_services/dataquery.service.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/dataQueriesStore.js
  frontend/src/_stores/editorStore.js
  frontend/src/_stores/handleReferenceTransactions.js
  frontend/src/_stores/resolverStore.js
  frontend/src/_stores/utils.js
  server/src/controllers/data_queries.controller.ts
  server/src/dto/data-query.dto.ts
  server/src/services/data_queries.service.ts
Labels: enhancement, draft, suspend-review-app, appbuilder
