Repository ToolJet/ToolJet, pull requests merged in 2024-01, with the labels that each got.

#8419 Fix ToolJet Database edit table name
  server/src/dto/tooljet-db.dto.ts
Labels: tested, active-review-app

#8181 Pagination issue with filter/sort.
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/FilterForm.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
Labels: bug, tested

#8480 [Hotfix]: Action button event is not getting triggered
  .version
  frontend/.version
  frontend/babel.config.js
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/actions.jsx
  server/.version
Labels: run-ci, tested, hotfix, Table component

#8482 Added automation for table server side pagination
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/e2e/editor/widget/tableRegression.cy.js
Labels: cypress

#8255 Column header revamp
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Icons/DeleteIcon.svg
  frontend/src/TooljetDatabase/Icons/DeleteIconNew.svg
  frontend/src/TooljetDatabase/Icons/Edit-information.svg
  frontend/src/TooljetDatabase/Icons/EditColumn.svg
  frontend/src/TooljetDatabase/Icons/Menu.svg
  frontend/src/TooljetDatabase/Table/ActionsPopover/Icons/DeleteColumn.svg
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/constants.js
  frontend/src/_components/ConfirmDialog.jsx
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
Labels: suspend-review-app

#8437 Feature/tjdb create column null constraint
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/_services/tooljetDatabase.service.js
Labels: run-ci, suspend-review-app

#8476 Added automation for Page deletion and disable.
  cypress-tests/cypress/e2e/editor/multipage/multipageHappypath.cy.js
  cypress-tests/cypress/support/utils/multipage.js
Labels: cypress

#8489 Add automation to verify chaining of queries.
  cypress-tests/cypress/commands/apiCommands.js
  cypress-tests/cypress/e2e/editor/queries/chainingOfQueries.cy.js
  cypress-tests/cypress/support/utils/queries.js
Labels: cypress

#8389 Grid migrations for auto layouts and component positioning
  server/data-migrations/1703230364205-BackfillAutoComputeLayout.ts
  server/data-migrations/1703232500904-MigrationForComponentLayoutToApplyGridCompatibility.ts
Labels: needs testing

#8386 [grid] Add support for importing apps With Normalized AppDefinition Schema and legacy imports
  .version
  frontend/.version
  server/.version
  server/src/helpers/utils.helper.ts
  server/src/services/app_import_export.service.ts
Labels: needs testing

#8509 [hotfix] fixes: ordering of event execution & Table switch
  .version
  frontend/.version
  frontend/src/ToolJetUI/SwitchGroup/ToggleGroup.jsx
  frontend/src/_helpers/appUtils.js
  server/.version
Labels: tested, hotfix, appbuilder

#8522 Added automation to verify Copy-Paste and duplication of components
  cypress-tests/cypress/e2e/editor/widget/componentDuplicationHappypath.cy.js
  cypress-tests/cypress/support/utils/button.js
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: cypress

#8529 [docs] minor update in gitsync doc
  docs/docs/gitsync.md
  docs/versioned_docs/version-2.24.0/gitsync.md
  docs/versioned_docs/version-2.25.0/gitsync.md
  docs/versioned_docs/version-2.27.0/gitsync.md
Labels: documentation

#8533 [docs]fixed robots and sitemap
  docs/docusaurus.config.js
  docs/static/robots.txt
Labels: documentation

#8536 Added null tag inside the input field when we select the null value while editing or creating row.
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/_styles/theme.scss
Labels: active-review-app

#8466 Fix: #8423 Link pricing page with badges
  docs/versioned_docs/version-2.27.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.27.0/Enterprise/superadmin.md
  docs/versioned_docs/version-2.27.0/Enterprise/white-label.md
  docs/versioned_docs/version-2.27.0/app-builder/customcss.md
  docs/versioned_docs/version-2.27.0/copilot.md
  docs/versioned_docs/version-2.27.0/org-management/licensing.md
  docs/versioned_docs/version-2.27.0/release-management/multi-env.md
  docs/versioned_docs/version-2.27.0/user-authentication/sso/openid/setup.md
  docs/versioned_docs/version-2.27.0/workflows/overview.md
Labels: active-review-docs-app

#8549 [hotfix]: Prevent Autosave on Client Updates Received via Websockets for MultiEditing
  .version
  frontend/.version
  frontend/src/Editor/Editor.jsx
  server/.version
Labels: tested, hotfix, appbuilder

#8546 Feature sticky column header in ToolJet database
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
Labels: active-review-app

#8562 Hotfix: Template modal on blank slate shows duplicate button
  .version
  frontend/.version
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_styles/theme.scss
  server/.version
Labels: tested, active-review-app

#8346 Automation: Deletion of component from inspector, right side panel & via keyboard actions
  cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
  cypress-tests/cypress/support/utils/inspector.js
Labels: cypress

#8484 [fix] Export modal is showing wrong date for some versions
  frontend/src/HomePage/ExportAppModal.jsx
Labels: tested

#8553 Added window titles according to pages
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/_components/PrivateRoute.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_hoc/withRouter.jsx
  frontend/src/index.ejs
Labels: tested, suspend-review-app

#8540 Rearranges crucial entry points for navigation inside editor and dasbhoard
  frontend/assets/translations/en.json
  frontend/src/App/App.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/GlobalDatasources/index.jsx
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/BlankPage.jsx
  frontend/src/HomePage/FolderFilter/index.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageOrgConstants/ManageOrgConstants.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/WorkspaceConstants/index.jsx
  frontend/src/_components/LogoNavDropdown.jsx
  frontend/src/_components/Settings.jsx
  frontend/src/_helpers/routes.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/_ui/Header/index.jsx
  frontend/src/_ui/Icon/solidIcons/ArrowBackDown.jsx
  frontend/src/_ui/Icon/solidIcons/Datasource.jsx
  frontend/src/_ui/Icon/solidIcons/WorkspaceConstants.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  frontend/src/_ui/Layout/index.jsx
  server/src/controllers/app_environments.controller.ts
  server/src/controllers/organization_constants.controller.ts
  server/src/modules/casl/abilities/org-environment-variables-ability.factory.ts
Labels: suspend-review-app, design-approved

#8598 [docs]fixed broken links
  docs/docs/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.0.0/getting-started.md
  docs/versioned_docs/version-2.1.0/getting-started.md
  docs/versioned_docs/version-2.10.0/getting-started.md
  docs/versioned_docs/version-2.11.0/getting-started.md
  docs/versioned_docs/version-2.12.0/getting-started.md
  docs/versioned_docs/version-2.13.0/getting-started.md
  docs/versioned_docs/version-2.14.0/getting-started.md
  docs/versioned_docs/version-2.15.0/getting-started.md
  docs/versioned_docs/version-2.16.0/getting-started.md
  docs/versioned_docs/version-2.17.0/getting-started.md
  docs/versioned_docs/version-2.18.0/getting-started.md
  docs/versioned_docs/version-2.19.0/getting-started.md
  docs/versioned_docs/version-2.2.0/getting-started.md
  docs/versioned_docs/version-2.22.0/getting-started.md
  docs/versioned_docs/version-2.23.0/getting-started.md
  docs/versioned_docs/version-2.24.0/getting-started.md
  docs/versioned_docs/version-2.25.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.27.0/contributing-guide/marketplace/marketplace-setup.md
  docs/versioned_docs/version-2.3.0/getting-started.md
  docs/versioned_docs/version-2.4.0/getting-started.md
  docs/versioned_docs/version-2.5.0/getting-started.md
  docs/versioned_docs/version-2.6.0/getting-started.md
  docs/versioned_docs/version-2.7.0/getting-started.md
  docs/versioned_docs/version-2.8.0/getting-started.md
  docs/versioned_docs/version-2.9.0/getting-started.md
  docs/versioned_docs/version-2.9.4/getting-started.md
Labels: documentation

#8575 Release group duplication feature
  frontend/assets/translations/en.json
  frontend/src/Editor/Editor.jsx
  frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_components/MultiSelectUser.jsx
  frontend/src/_components/OverflowTooltip.jsx
  frontend/src/_components/ToolTip.jsx
  frontend/src/_services/groupPermission.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_styles/widgets/multi-select.scss
  frontend/src/_ui/FolderList/FolderList.jsx
  frontend/src/_ui/Icon/bulkIcons/Users.jsx
  frontend/src/_ui/Icon/bulkIcons/index.js
  frontend/src/_ui/Icon/solidIcons/Delete.jsx
  frontend/src/_ui/Icon/solidIcons/Options.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  frontend/src/_ui/Modal/index.jsx
  server/src/controllers/group_permissions.controller.ts
  server/src/dto/group-permission.dto.ts
  server/src/helpers/utils.helper.ts
  server/src/services/group_permissions.service.ts
Labels: tested

#8329 Revamp users table and edit organization users drawer
  frontend/assets/translations/en.json
  frontend/ee/components/UsersPage/UsersActionMenu.jsx
  frontend/ee/components/UsersPage/UsersTable.jsx
  frontend/src/ManageOrgUsers/InviteUsersForm.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsersDrawer.jsx
  frontend/src/ManageOrgUsers/UserGroupsSelect.jsx
  frontend/src/OrganizationSettingsPage/index.jsx
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_services/organization_user.service.js
  frontend/src/_styles/theme.scss
  server/src/controllers/organization_users.controller.ts
  server/src/entities/user.entity.ts
  server/src/modules/casl/casl-ability.factory.ts
  server/src/services/organization_users.service.ts
  server/src/services/organizations.service.ts
  server/src/services/users.service.ts
Labels: suspend-review-app, design-approved

#8602 Add title for workspace constants page
  frontend/src/_helpers/utils.js
Labels: tested

#8603 Fixes bugs in user groups dropdown
  frontend/src/ManageOrgUsers/ManageOrgUsersDrawer.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_styles/theme.scss
Labels: tested

#8565 [docs]:update sidebar
  docs/sidebars.js
Labels: suspend-review-docs-app

#8537 Fix: Handle TJDB imports for revised constraints API
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  server/src/helpers/tjdb_dto_transforms.ts
  server/src/helpers/utils.helper.ts
  server/src/services/import_export_resources.service.ts
  server/src/services/library_app_creation.service.ts
  server/src/services/tooljet_db.service.ts
Labels: tested

#8557 Feature sticky row and column creator in ToolJet database
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  plugins/package-lock.json
  server/package-lock.json
  server/src/services/tooljet_db.service.ts
Labels: active-review-app

#8619 Fix: noOptionsMessage is a function, not a string (causing the page to break)
  frontend/src/ManageOrgUsers/UserGroupsSelect.jsx
Labels: tested

#8618 Added data cy for newly added components
  frontend/ee/components/UsersPage/UsersActionMenu.jsx
  frontend/ee/components/UsersPage/UsersTable.jsx
  frontend/src/Editor/Header/index.js
  frontend/src/SettingsPage/SettingsPage.jsx
  frontend/src/_components/LogoNavDropdown.jsx
  frontend/src/_components/Settings.jsx
Labels: data-cy, cypress

#8610 [docs] updated ssoUserInfo
  docs/docs/user-authentication/sso/openid/setup.md
  docs/static/img/sso/openid/ssouserinfon.png
  docs/versioned_docs/version-2.27.0/user-authentication/sso/openid/setup.md
Labels: documentation

#8621 Modified platform cypress test cases for dashboard revamp
  .github/workflows/cypress-platform.yml
  cypress-tests/cypress-workspace.config.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageGroups.js
  cypress-tests/cypress/constants/selectors/profile.js
  cypress-tests/cypress/constants/texts/manageGroups.js
  cypress-tests/cypress/constants/texts/manageUsers.js
  cypress-tests/cypress/constants/texts/profile.js
  cypress-tests/cypress/e2e/authentication/forgotPassword.cy.js
  cypress-tests/cypress/e2e/authentication/signUp.cy.js
  cypress-tests/cypress/e2e/ce/appSlug.cy.js
  cypress-tests/cypress/e2e/ce/globalDataSources/globalDataSourcePermissions.cy.js
  cypress-tests/cypress/e2e/ce/privateAndPublicApp.cy.js
  cypress-tests/cypress/e2e/ce/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/workspace/appCreate.cy.js
  cypress-tests/cypress/e2e/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/e2e/workspace/dashboard.cy.js
  cypress-tests/cypress/e2e/workspace/errorPage.cy.js
  cypress-tests/cypress/e2e/workspace/manageGroups.cy.js
  cypress-tests/cypress/e2e/workspace/manageSSO.cy.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
  cypress-tests/cypress/e2e/workspace/profile.cy.js
  cypress-tests/cypress/e2e/workspace/userPermissions.cy.js
  cypress-tests/cypress/support/utils/common.js
  cypress-tests/cypress/support/utils/manageGroups.js
  cypress-tests/cypress/support/utils/manageUsers.js
  cypress-tests/cypress/support/utils/onboarding.js
  cypress-tests/cypress/support/utils/profile.js
  cypress-tests/cypress/support/utils/userPermissions.js
Labels: cypress, run-cypress-app-builder, run-cypress-workspace, run-cypress-marketplace

#8624 Appbuilder automation fixed for platform-1.2
  cypress-tests/cypress/constants/texts/button.js
  cypress-tests/cypress/e2e/editor/widget/componentsBasicHappypath.cy.js
  cypress-tests/cypress/e2e/editor/widget/multiselectHappyPath.cy.js
  cypress-tests/cypress/e2e/editor/widget/textInputHappyPath.cy.js
Labels: cypress

#8628 Fixed export and import cypress failure
  cypress-tests/cypress/e2e/exportImport/export.cy.js
  cypress-tests/cypress/e2e/exportImport/import.cy.js
Labels: cypress

#8636 [docs] gitsync guide for gitlab
  docs/docs/gitsync.md
  docs/static/img/gitsync/gitlab/activessh.png
  docs/static/img/gitsync/gitlab/addingssh.png
  docs/static/img/gitsync/gitlab/apprename.png
  docs/static/img/gitsync/gitlab/author.png
  docs/static/img/gitsync/gitlab/configfin.png
  docs/static/img/gitsync/gitlab/firstcommit.png
  docs/static/img/gitsync/gitlab/gitlabssh.png
  docs/static/img/gitsync/gitlab/lastcommitmsg.png
  docs/static/img/gitsync/gitlab/message.png
  docs/static/img/gitsync/gitlab/newversion.png
  docs/static/img/gitsync/gitlab/newversion1.png
  docs/static/img/gitsync/gitlab/repo.png
  docs/static/img/gitsync/gitlab/sshkey.png
  docs/versioned_docs/version-2.24.0/gitsync.md
  docs/versioned_docs/version-2.25.0/gitsync.md
  docs/versioned_docs/version-2.27.0/gitsync.md
Labels: documentation

#8645 [docs] whitelabel cloud
  docs/docs/Enterprise/white-label.md
  docs/static/img/enterprise/white-label/whitecloud.png
  docs/versioned_docs/version-2.27.0/Enterprise/white-label.md
Labels: documentation

#8560 Feature cell navigation in ToolJet database
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/_styles/theme.scss
Labels: active-review-app

#8541 Pagination-rewamp in ToolJet database
  frontend/src/TooljetDatabase/Icons/Enter.svg
  frontend/src/TooljetDatabase/Icons/LeftNav.svg
  frontend/src/TooljetDatabase/Icons/RightNav.svg
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/theme.scss
Labels: suspend-review-app

#8635 Fix: App could not save error on resizing column width fixed
  frontend/src/_stores/utils.js
Labels: bug, run-ci, tested

#8644 Added data-cy for group duplication modal
  frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
  frontend/src/_ui/Modal/index.jsx
Labels: data-cy, cypress

#8646 Added cypress test cases for group duplication
  cypress-tests/cypress.config.js
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/constants/selectors/common.js
  cypress-tests/cypress/constants/selectors/manageGroups.js
  cypress-tests/cypress/e2e/ce/groupDuplication.cy.js
  cypress-tests/cypress/e2e/workspace/manageGroups.cy.js
  cypress-tests/cypress/support/utils/manageGroups.js
Labels: cypress

#8651 Added cypress test cases for edit user functionality
  cypress-tests/cypress/constants/selectors/manageUsers.js
  cypress-tests/cypress/e2e/workspace/manageUsers.cy.js
Labels: cypress, run-cypress-workspace

#8413 fix :: Inpsector doesn't get updated when listview children are deleted
  frontend/src/Editor/Components/Listview.jsx
Labels: tested, appbuilder

#8629 Feature/tjdb primarykey column sticky toleft
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_styles/theme.scss
Labels: needs testing, run-ci, active-review-app

#8652 [Hotfix] custom component should be able to bind runQuery action
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
Labels: tested

#8639 [hotfix] fixes: auto save is triggered on key press without any changes
  .version
  frontend/.version
  frontend/src/Editor/Components/CustomComponent/CustomComponent.jsx
  frontend/src/Editor/Editor.jsx
  server/.version
Labels: tested, hotfix

#8528 Feature/tjdb table menu bar revamp
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Filter/index.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Sort/index.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/AddNewDataPopOver.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/Header.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TableListItem/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
  frontend/src/_styles/theme.scss
Labels: needs testing, run-ci, active-review-app

#8656 [docs] how-to: conditionally format cells in table
  docs/docs/how-to/conditionally-format-table.md
  docs/sidebars.js
  docs/static/img/how-to/conditionally-format/cellcv.png
  docs/static/img/how-to/conditionally-format/cellrd.png
  docs/static/img/how-to/conditionally-format/column.png
  docs/static/img/how-to/conditionally-format/query.png
  docs/static/img/how-to/conditionally-format/table.png
  docs/static/img/how-to/conditionally-format/tabledata.png
  docs/static/img/how-to/conditionally-format/textcv.png
  docs/static/img/how-to/conditionally-format/textrd.png
  docs/versioned_docs/version-2.23.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.24.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.25.0/how-to/conditionally-format-table.md
  docs/versioned_docs/version-2.27.0/how-to/conditionally-format-table.md
  docs/versioned_sidebars/version-2.23.0-sidebars.json
  docs/versioned_sidebars/version-2.24.0-sidebars.json
  docs/versioned_sidebars/version-2.25.0-sidebars.json
  docs/versioned_sidebars/version-2.27.0-sidebars.json
Labels: documentation

#8657 [docs] airtable data source
  docs/docs/data-sources/airtable.md
  docs/static/img/datasource-reference/airtable/airtableconnect.gif
  docs/versioned_docs/version-2.27.0/data-sources/airtable.md
Labels: documentation

#8568 Feature/tjdb expandable open drawer for edit
  frontend/src/TooljetDatabase/Drawers/EditRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/index.jsx
  frontend/src/TooljetDatabase/Table/Footer.jsx
  frontend/src/TooljetDatabase/Table/Header.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/Expand.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
Labels: run-ci, active-review-app

#8661 [docs] how-to: setup log file generation(rsyslog)
  docs/docs/Enterprise/audit_logs.md
  docs/docs/how-to/setup-syslog.md
  docs/sidebars.js
  docs/static/img/how-to/setup-rsyslog/envfile.png
  docs/static/img/how-to/setup-rsyslog/folder.png
  docs/static/img/how-to/setup-rsyslog/timestamp.png
  docs/versioned_docs/version-2.23.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.23.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.24.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.24.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.25.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.25.0/how-to/setup-syslog.md
  docs/versioned_docs/version-2.27.0/Enterprise/audit_logs.md
  docs/versioned_docs/version-2.27.0/how-to/setup-syslog.md
  docs/versioned_sidebars/version-2.23.0-sidebars.json
  docs/versioned_sidebars/version-2.24.0-sidebars.json
  docs/versioned_sidebars/version-2.25.0-sidebars.json
  docs/versioned_sidebars/version-2.27.0-sidebars.json
Labels: documentation

#8576 [docs] how-to:print data from multiple tabs
  docs/docs/how-to/print-multitabs.md
  docs/sidebars.js
  docs/static/img/how-to/print-multitabs/appui.png
  docs/static/img/how-to/print-multitabs/buttonevents.png
  docs/static/img/how-to/print-multitabs/controlcomp2.png
  docs/static/img/how-to/print-multitabs/data.png
  docs/static/img/how-to/print-multitabs/gettabshtml.png
  docs/static/img/how-to/print-multitabs/q1.png
  docs/static/img/how-to/print-multitabs/q2.png
  docs/static/img/how-to/print-multitabs/q3.png
  docs/static/img/how-to/print-multitabs/unsetvar1.png
  docs/static/img/how-to/print-multitabs/unsetvar2.png
  docs/versioned_docs/version-2.19.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.22.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.23.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.24.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.25.0/how-to/print-multitabs.md
  docs/versioned_docs/version-2.27.0/how-to/print-multitabs.md
  docs/versioned_sidebars/version-2.19.0-sidebars.json
  docs/versioned_sidebars/version-2.22.0-sidebars.json
  docs/versioned_sidebars/version-2.23.0-sidebars.json
  docs/versioned_sidebars/version-2.24.0-sidebars.json
  docs/versioned_sidebars/version-2.25.0-sidebars.json
  docs/versioned_sidebars/version-2.27.0-sidebars.json
Labels: documentation
