Repository ToolJet/ToolJet, pull requests merged in 2024-06, with the labels that each got.

#9934 [performance] removes current state dependency from resolvers
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Editor/CodeBuilder/utils.js
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Table/AddNewRowComponent.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Header/GlobalSettings.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Components/FilePicker.jsx
  frontend/src/Editor/Inspector/Components/Modal.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/DatepickerProperties.jsx
  frontend/src/Editor/Inspector/Components/Table/ColumnManager/PropertiesTabElements.jsx
  frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleProperties.jsx
  frontend/src/Editor/Inspector/Components/Table/SelectOptionsList/OptionsList.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
  frontend/src/Editor/Inspector/Elements/utils.js
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/index.jsx
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/Middlewares/HydrateWithResolveReferences.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/ManageOrgVars/ManageOrgVars.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/_components/DarkModeToggle.jsx
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/OrgConstantsVariablesResolver/OrgConstantsVariablesPreviewBox.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_helpers/ref_resolver.js
  frontend/src/_helpers/utilities/utils.helpers.js
  frontend/src/_helpers/utils.js
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_stores/resolverStore.js
  frontend/src/_stores/utils.js
  frontend/src/_ui/HttpHeaders/index.js
Labels: performance

#9895 Fix: Remove null values from the foreign key drop-down list
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/TooljetDatabase/Forms/TableKeyRelations.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
Labels: active-review-app, database

#9950 [docs]: add LTS guide
  docs/versioned_docs/version-2.50.0-LTS/setup/azure-container.md
  docs/versioned_docs/version-2.50.0-LTS/setup/client.md
  docs/versioned_docs/version-2.50.0-LTS/setup/digitalocean.md
  docs/versioned_docs/version-2.50.0-LTS/setup/docker.md
  docs/versioned_docs/version-2.50.0-LTS/setup/ec2.md
  docs/versioned_docs/version-2.50.0-LTS/setup/ecs.md
  docs/versioned_docs/version-2.50.0-LTS/setup/google-cloud-run.md
  docs/versioned_docs/version-2.50.0-LTS/setup/helm.md
  docs/versioned_docs/version-2.50.0-LTS/setup/kubernetes-aks.md
  docs/versioned_docs/version-2.50.0-LTS/setup/kubernetes-gke.md
  docs/versioned_docs/version-2.50.0-LTS/setup/kubernetes.md
  docs/versioned_docs/version-2.50.0-LTS/setup/openshift.md
  docs/versioned_docs/version-2.50.0-LTS/setup/upgrade-to-lts.md
  docs/versioned_docs/version-2.50.0-LTS/widgets/kanban-board.md
  docs/versioned_sidebars/version-2.50.0-LTS-sidebars.json
Labels: active-review-docs-app

#9961 [docs]: Update setup docs for LTS version
  docs/docs/setup/azure-container.md
  docs/docs/setup/index.md
  docs/docs/setup/openshift.md
  docs/docs/setup/system-requirements.md
  docs/versioned_docs/version-2.50.0-LTS/setup/azure-container.md
  docs/versioned_docs/version-2.50.0-LTS/setup/ec2.md
  docs/versioned_docs/version-2.50.0-LTS/setup/google-cloud-run.md
  docs/versioned_docs/version-2.50.0-LTS/setup/openshift.md
  docs/versioned_docs/version-2.50.0-LTS/setup/system-requirements.md
  docs/versioned_docs/version-2.50.0-LTS/setup/try-tooljet.md
Labels: active-review-docs-app

#9904 [docs]: updated the media in AzureAD Single Sign-on page
  docs/docs/user-authentication/sso/openid/azuread.md
  docs/static/img/sso/azuread/azure-app-reg-v2.gif
  docs/versioned_docs/version-2.34.0/user-authentication/sso/openid/azuread.md
  docs/versioned_docs/version-2.35.0/user-authentication/sso/openid/azuread.md
  docs/versioned_docs/version-2.36.0/user-authentication/sso/openid/azuread.md
  docs/versioned_docs/version-2.39.0/user-authentication/sso/openid/azuread.md
  docs/versioned_docs/version-2.43.0/user-authentication/sso/openid/azuread.md
  docs/versioned_docs/version-2.50.0-LTS/user-authentication/sso/openid/azuread.md
Labels: active-review-docs-app

#9780 Fix: TJDB icon for "Add relation" button when disabled
  frontend/src/TooljetDatabase/Forms/ForeignKeyRelation.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/_ui/AppButton/AppButton.scss
Labels: tested, suspend-review-app

#9804 Removed unique constraint for boolean columns in edit/create drawers
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
Labels: tested, suspend-review-app

#9791 Shortcut keys for all drawers
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Table/Header.jsx
  frontend/src/TooljetDatabase/constants.js
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  server/src/filters/all-exceptions-filter.ts
Labels: feature request, tested, suspend-review-app

#9747 Fix: Standardise the drawer heading's styles in TJDB
  frontend/src/Editor/DragContainer.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/ForeignKeyRelation.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/constants.js
  frontend/src/_styles/drawer.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/AppButton/AppButton.scss
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
Labels: tested, active-review-app

#9817 Fix: Disable boolean datatype selection for foreign key on create and edit table in TJDB
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/TableDetailsDropdown.jsx
  frontend/src/TooljetDatabase/Forms/TableKeyRelations.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
Labels: tested, suspend-review-app

#9744 Fix: Update the text in delete popup in TJDB
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
Labels: needs testing

#9739 Typeover null values in cell edit and row edit
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
Labels: tested, suspend-review-app

#9661 Fix for missing foreign key constraint on app import
  server/src/services/app_import_export.service.ts
  server/src/services/import_export_resources.service.ts
  server/src/services/tooljet_db.service.ts
  server/src/services/tooljet_db_import_export_service.ts
Labels: tested, active-review-app

#9799 fix : Foreign key dropdown width oversize issue in create and edit row
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
  frontend/src/TooljetDatabase/Menu/CellEditMenu/styles.scss
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_styles/theme.scss
Labels: tested, suspend-review-app, database

#9975 Hotfix : Table crashing on selecting a value using time only datepicker in add new row
  .version
  frontend/.version
  frontend/src/Editor/Components/Table/Datepicker.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  server/.version
Labels: tested

#9785 Feature: Infinite scrolling for searching foreign key values in the ToolJet database.
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableKeyRelations.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  server/src/services/tooljet_db.service.ts
Labels: tested, active-review-app, database

#9979 Updated copyright to No data found for dropdown select in tjdb
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableDetailsDropdown.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
Labels: bug, run-ci

#9965 hotfix : Datepicker popover coming behind other components in viewer mode
  .version
  frontend/.version
  frontend/src/Editor/Container.jsx
  server/.version
Labels: tested

#9995 Updated button UI in add relation button
  frontend/src/TooljetDatabase/Forms/styles.scss
Labels: run-ci, active-review-app

#9996 Fix : Target and actions section getting overlap in fk drawer
  frontend/src/TooljetDatabase/Forms/TableKeyRelations.jsx
Labels: run-ci, hotfix, active-review-app

#9910 Hotfix: Salesforce plugin
  frontend/src/Editor/CodeEditor/CodeHinter.jsx
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/CodeEditor/styles.scss
  frontend/src/_components/DynamicForm.jsx
  marketplace/plugins/salesforce/lib/index.ts
  marketplace/plugins/salesforce/lib/manifest.json
  marketplace/plugins/salesforce/lib/operations.json
Labels: active-review-app, deploy-marketplace-plugin

#9997 fix : Cell edit menu height issue in ToolJet database dashboard
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
  frontend/src/_styles/theme.scss
Labels: active-review-app, database

#10001 LTS: Marketplace fixes ( v2.50.3 )
  .version
  frontend/.version
  frontend/src/Editor/CodeEditor/CodeHinter.jsx
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/CodeEditor/styles.scss
  frontend/src/TooljetDatabase/Forms/TableKeyRelations.jsx
  frontend/src/_components/DynamicForm.jsx
  marketplace/plugins/salesforce/lib/index.ts
  marketplace/plugins/salesforce/lib/manifest.json
  marketplace/plugins/salesforce/lib/operations.json
  server/.version
Labels: run-ci, active-review-app, run-cypress

#9992 Fix: ToolJet database cell edit menu issues
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/index.jsx
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/styles.scss
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  frontend/src/_ui/Drawer/DrawerFooter/styles.scss
Labels: active-review-app, database

#10004 Fix: Entity reference mapping and performance issues on codehinter
  frontend/src/Editor/CodeEditor/PreviewBox.jsx
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/CodeEditor/utils.js
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_stores/currentStateStore.js
  frontend/src/_stores/resolverStore.js
Labels: tested

#9984 Bugfixes: Table crash fixes for LTS / Zindex issue for datepicker
  .version
  frontend/.version
  frontend/src/Editor/CodeEditor/PreviewBox.jsx
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/CodeEditor/utils.js
  frontend/src/Editor/Components/Table/Datepicker.jsx
  frontend/src/Editor/Components/Table/Link.jsx
  frontend/src/Editor/Components/Table/String.jsx
  frontend/src/Editor/Components/Table/Tags.jsx
  frontend/src/Editor/Components/Table/Text.jsx
  frontend/src/Editor/Components/Table/columns/index.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_stores/currentStateStore.js
  frontend/src/_stores/resolverStore.js
  server/.version
Labels: tested

#9285 Appwrite plugin issue fixes and added features
  plugins/packages/appwrite/lib/index.ts
  plugins/packages/appwrite/lib/manifest.json
  plugins/packages/appwrite/lib/operations.json
  plugins/packages/appwrite/lib/operations.ts
  plugins/packages/appwrite/lib/types.ts
  plugins/packages/appwrite/package.json
Labels: active-review-app

#10029 Fix: ToolJet Database dashboard cell edit flaky update
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
Labels: active-review-app

#10028 Chore: Update Appwrite plugin version
  plugins/package-lock.json
  plugins/packages/appwrite/lib/operations.ts
  plugins/packages/appwrite/package-lock.json
  plugins/packages/appwrite/package.json
Labels: active-review-app

#10027 Fix: Global styles for small buttons
  frontend/src/_ui/AppButton/AppButton.scss
Labels: active-review-app

#9082 Fix create app failure issue because TJDB is disabled
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  server/src/services/import_export_resources.service.ts
Labels: active-review-app

#10024 Patch: Marketplace fixes ( v2.61.2 )
  .version
  frontend/.version
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/_ui/AppButton/AppButton.scss
  plugins/package-lock.json
  plugins/packages/appwrite/lib/index.ts
  plugins/packages/appwrite/lib/manifest.json
  plugins/packages/appwrite/lib/operations.json
  plugins/packages/appwrite/lib/operations.ts
  plugins/packages/appwrite/lib/types.ts
  plugins/packages/appwrite/package-lock.json
  plugins/packages/appwrite/package.json
  server/.version
Labels: run-ci, active-review-app, run-cypress

#9818 Fix: selection of copy of selected component for ease
  frontend/src/Editor/Container.jsx
  frontend/src/_helpers/appUtils.js
Labels: suspend-review-app

#9942 Fix: sizing issues in horizontal divider
  frontend/src/Editor/Components/Divider.jsx
  frontend/src/Editor/Components/verticalDivider.jsx
  frontend/src/Editor/WidgetManager/configs/divider.js
Labels: tested

#9943 Add placeholder image instead of default html img fallback in table cell
  frontend/assets/images/image-not-found.svg
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: tested

#9732 Fix: mouse release on canvas when properties/styles values selected
  frontend/src/Editor/Editor.jsx
Labels: tested, suspend-review-app

#9729 Fix: rest api headers empty state while creating new query
  frontend/src/_stores/storeHelper.js
Labels: tested, suspend-review-app, product approved

#9944 fix: selection issue in table row while editing
  frontend/src/Editor/Components/Table/Datepicker.jsx
  frontend/src/Editor/EditorSelecto.jsx
Labels: tested

#9837 Add new revamped multiselect widget
  frontend/assets/images/icons/widgets/dropdownV2.jsx
  frontend/assets/images/icons/widgets/index.jsx
  frontend/assets/images/icons/widgets/multiselectV2.jsx
  frontend/src/Editor/BoxUI.jsx
  frontend/src/Editor/CodeBuilder/Elements/Switch.jsx
  frontend/src/Editor/CodeBuilder/Elements/Toggle.jsx
  frontend/src/Editor/Components/Checkbox.jsx
  frontend/src/Editor/Components/DropdownV2/CustomMenuList.jsx
  frontend/src/Editor/Components/DropdownV2/CustomOption.jsx
  frontend/src/Editor/Components/DropdownV2/CustomValueContainer.jsx
  frontend/src/Editor/Components/DropdownV2/DropdownV2.jsx
  frontend/src/Editor/Components/DropdownV2/dropdownV2.scss
  frontend/src/Editor/Components/DropdownV2/utils.js
  frontend/src/Editor/Components/MultiselectV2/CustomOption.jsx
  frontend/src/Editor/Components/MultiselectV2/CustomValueContainer.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/Editor/Components/MultiselectV2/multiselectV2.scss
  frontend/src/Editor/Components/Table/CustomSelect.jsx
  frontend/src/Editor/Components/ToggleV2.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/ControlledComponentToRender.jsx
  frontend/src/Editor/DragContainer.jsx
  frontend/src/Editor/Inspector/Components/DefaultComponent.jsx
  frontend/src/Editor/Inspector/Components/Select.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/Inspector/Utils.js
  frontend/src/Editor/WidgetBox.jsx
  frontend/src/Editor/WidgetManager.jsx
  frontend/src/Editor/WidgetManager/configs/dropdown.js
  frontend/src/Editor/WidgetManager/configs/dropdownV2.js
  frontend/src/Editor/WidgetManager/configs/index.js
  frontend/src/Editor/WidgetManager/configs/multiselect.js
  frontend/src/Editor/WidgetManager/configs/multiselectV2.js
  frontend/src/Editor/WidgetManager/constants.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_helpers/utils.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/bulkIcons/CheckMark.jsx
  frontend/src/_ui/Icon/bulkIcons/ClearIndicator.jsx
  frontend/src/_ui/Icon/bulkIcons/DropdownIndicator.jsx
  frontend/src/_ui/Icon/bulkIcons/TriangleDownArrow.jsx
  frontend/src/_ui/Icon/bulkIcons/TriangleUpArrow.jsx
  frontend/src/_ui/Icon/solidIcons/CheckMark.jsx
  frontend/src/_ui/Icon/solidIcons/Search01.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
Labels: suspend-review-app

#10047 LTS [Marketplace]: Appwrite patch
  .version
  frontend/.version
  plugins/package-lock.json
  plugins/packages/appwrite/lib/index.ts
  plugins/packages/appwrite/lib/manifest.json
  plugins/packages/appwrite/lib/operations.json
  plugins/packages/appwrite/lib/operations.ts
  plugins/packages/appwrite/lib/types.ts
  plugins/packages/appwrite/package-lock.json
  plugins/packages/appwrite/package.json
  server/.version
Labels: active-review-app, run-cypress

#9786 Fix: remove mandatory key from password input
  frontend/src/Editor/WidgetManager/configs/passwordinput.js
Labels: suspend-review-app

#10080 Hotfix: Import resource with ToolJet Database disabled
  .version
  frontend/.version
  server/.version
  server/src/services/import_export_resources.service.ts
Labels: needs testing, tested, active-review-app

#9823 feat : Query manager separated to different tabs
  frontend/assets/translations/en.json
  frontend/src/Editor/CodeEditor/MultiLineCodeEditor.jsx
  frontend/src/Editor/Components/text.scss
  frontend/src/Editor/DataSourceManager/DataSourceManager.jsx
  frontend/src/Editor/Inspector/Components/Table/NoListItem.jsx
  frontend/src/Editor/Inspector/EventManager.jsx
  frontend/src/Editor/Inspector/ManageEventButton.jsx
  frontend/src/Editor/Inspector/manageEventButton.scss
  frontend/src/Editor/LeftSidebar/index.jsx
  frontend/src/Editor/QueryManager/Components/CustomToggleSwitch.jsx
  frontend/src/Editor/QueryManager/Components/DataSourceSelect.jsx
  frontend/src/Editor/QueryManager/Components/ParameterDetails.jsx
  frontend/src/Editor/QueryManager/Components/ParameterList.jsx
  frontend/src/Editor/QueryManager/Components/Preview.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryManager/Components/SuccessNotificationInputs.jsx
  frontend/src/Editor/QueryManager/Components/Transformation.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/CreateRow.jsx
  frontend/src/Editor/QueryManager/QueryManager.jsx
  frontend/src/Editor/QueryManager/constants.js
  frontend/src/Editor/QueryPanel/FilterandSortPopup.jsx
  frontend/src/Editor/QueryPanel/QueryDataPane.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/ToolJetUI/Buttons/AddNewButton/AddNewButton.jsx
  frontend/src/ToolJetUI/Buttons/AddNewButton/addNewButton.scss
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_stores/queryPanelStore.js
  frontend/src/_styles/colors.scss
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/queryManager.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Icon/solidIcons/ArrowDownTriangle.jsx
  frontend/src/_ui/Icon/solidIcons/Filter.jsx
  frontend/src/_ui/Icon/solidIcons/Plus.jsx
  frontend/src/_ui/Icon/solidIcons/Search.jsx
Labels: suspend-review-app, appbuilder

#10101 Bugfix - perf mapping
  frontend/src/Editor/CodeEditor/MultiLineCodeEditor.jsx
  frontend/src/Editor/CodeEditor/PreviewBox.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#9941 added new loader in export app modal when changing versions
  frontend/src/HomePage/ExportAppModal.jsx
Labels: suspend-review-app

#10072 Added variable background colors to platform bg and navbar
  frontend/src/_styles/componentdesign.scss
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/left-sidebar.scss
  frontend/src/_styles/theme.scss
Labels: suspend-review-app

#9893 Updated workspace signup flow & fixes
  frontend/src/ForgotPassword/ForgotPasswordPage.jsx
  frontend/src/Oauth/Authorize.jsx
  frontend/src/Routes/AuthRoute.jsx
  frontend/src/Routes/OrganizationInviteRoute.jsx
  frontend/src/SignupPage/SignupPage.jsx
  frontend/src/SuccessInfoScreen/SignupInfoScreen.jsx
  frontend/src/SuccessInfoScreen/VerificationSuccessInfoScreen.jsx
  frontend/src/_helpers/platform/utils/auth.utils.js
  frontend/src/_services/app.service.js
  frontend/src/_services/authentication.service.js
  server/ee/services/oauth/oauth.service.ts
  server/migrations/1716975639914-AddSourceToOrganizationUsers.ts
  server/src/controllers/app.controller.ts
  server/src/dto/resend-invite.dto.ts
  server/src/entities/organization_user.entity.ts
  server/src/helpers/user_lifecycle.ts
  server/src/modules/auth/invited-user-session.guard.ts
  server/src/modules/auth/organization-invite-auth.guard.ts
  server/src/services/auth.service.ts
  server/src/services/organization_users.service.ts
Labels: needs testing, tested

#10108 Fixes: select all click behaviour on label
  frontend/src/Editor/Components/DropdownV2/CustomMenuList.jsx
  frontend/src/Editor/WidgetManager/configs/dropdown.js
  frontend/src/Editor/WidgetManager/configs/multiselect.js
  frontend/src/Editor/WidgetManager/configs/toggleswitch.js
  frontend/src/_styles/theme.scss
Labels: tested

#10107 Fix: selecto issue and mouse release event on editor
  frontend/src/Editor/Editor.jsx
Labels: tested

#10040 Fix : Prevent component autofill
  frontend/src/Editor/Components/PasswordInput.jsx
Labels: active-review-app

#10118 feat: skip onDragStop execution if drag event is empty
  frontend/src/Editor/DragContainer.jsx
  frontend/src/_stores/utils.js
Labels: tested

#10129 display query preview data in preview panel and display transformatio…
  frontend/src/_helpers/appUtils.js
Labels: tested

#10112 Fix while adding new rows in table components when ever entered the text and pressed enter it doubles the text
  frontend/src/Editor/Components/Table/String.jsx
  frontend/src/Editor/Components/Table/Text.jsx
Labels: tested

#10109 Integration bugfixes appbuilder 1.8
  frontend/src/Editor/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/Editor/Components/DropdownV2/DropdownV2.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/Editor/Components/Table/GlobalFilter.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/QueryManager/Components/Preview.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DeleteRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/UpdateRows.jsx
  frontend/src/Editor/QueryPanel/QueryPanel.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/Editor/WidgetManager/configs/dropdownV2.js
  frontend/src/Editor/WidgetManager/configs/multiselectV2.js
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/custom.scss
Labels: tested

#10116 Add z-index to app name info header container
  frontend/src/_styles/theme.scss
Labels: tested

#10128 Fix dropdown and multiselect crash on integer labels
  frontend/src/Editor/Components/DropdownV2/CustomOption.jsx
  frontend/src/Editor/Components/DropdownV2/utils.js
  frontend/src/Editor/Components/MultiselectV2/CustomOption.jsx
  frontend/src/Editor/Components/MultiselectV2/CustomValueContainer.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/_styles/table-component.scss
Labels: tested

#10136 Fix: dark mode on preview names
  frontend/src/_styles/queryManager.scss
Labels: tested

#10134 Hotfix: ToolJet Database query import
  server/src/services/app_import_export.service.ts
Labels: tested, active-review-app

#9932 Make modal title text alignment configurable
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/WidgetManager/configs/modal.js
Labels: suspend-review-app

#10076 Make `rowData` available for display text in link column
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: suspend-review-app

#9976 Make accordion trigger only when collapse icon is clicked in inspector
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Accordion/AccordionItem.js
Labels: suspend-review-app

#10106 Add: loading and disable behaviour to action button on change
  frontend/src/Editor/Inspector/EventManager.jsx
Labels: suspend-review-app

#10146 Hotfix [LTS] - Bugfixes
  .version
  frontend/.version
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/ControlledComponentToRender.jsx
  frontend/src/Editor/SubContainer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utility.js
  server/.version
  server/src/services/components.service.ts
Labels: tested

#10173 app viewer fixes
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Header/index.js
Labels: tested

#10156 platform release 18 bug fixes
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/HomePage/ExportAppModal.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/global-datasources.scss
  frontend/src/_styles/tabler.scss
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Card/Card.jsx
  frontend/src/_ui/Pagination/index.jsx
  plugins/packages/grpc/lib/darkIcon.svg
  plugins/packages/influxdb/lib/darkIcon.svg
  plugins/packages/mariadb/lib/darkIcon.svg
  plugins/packages/mysql/lib/darkIcon.svg
  plugins/packages/zendesk/lib/darkIcon.svg
Labels: tested

#9810 Fix: 9809 error not show in toast when clone
  frontend/src/_components/AppModal.jsx
Labels: run-ci

#10183 [docs]: Add user & workspace relations api docs
  docs/docs/tutorial/tooljet-api.md
  docs/sidebars.js
Labels: active-review-docs-app

#10171 LTS - hotfix: Fix for canvas background color & reserved keyword
  .version
  frontend/.version
  frontend/src/Editor/Editor.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/utility.js
  frontend/src/_helpers/utils.js
  server/.version
Labels: tested, hotfix

#10196 hotfix: Events with debounce are not working
  frontend/src/_helpers/appUtils.js
Labels: tested

#10192 Fix: delete on options delete in dropdown
  frontend/src/Editor/Components/DropdownV2/CustomMenuList.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/Editor/Inspector/Components/Select.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/_stores/utils.js
  server/src/services/components.service.ts
Labels: tested

#10185 hotfix : Table breaking on importing older apps with null value in column
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
Labels: tested

#10195 Cypress fix platform v18
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/editor/privateAndPublicApp.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/authentication/forgotPassword.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/authentication/signUp.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/exportImport/export.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/exportImport/import.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/workspace/bulkUserUpload.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/commonTestcases/workspace/inviteflow.cy.js
  cypress-tests/cypress/support/utils/manageSSO.js
  frontend/src/ResetPassword/ResetPasswordPage.jsx
Labels: run-cypress, cypress

#10205 fix: updated parentId check to account for tab children
  .version
  frontend/.version
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/DragContainer.jsx
  frontend/src/Editor/Editor.jsx
  server/.version
Labels: tested

#10044 [docs]: update airtable
  docs/docs/data-sources/airtable.md
  docs/static/img/datasource-reference/airtable/create-record-v2.png
  docs/static/img/datasource-reference/airtable/delete-record-v2.png
  docs/static/img/datasource-reference/airtable/list-records-v2.png
  docs/static/img/datasource-reference/airtable/retrieve-record-v2.png
  docs/static/img/datasource-reference/airtable/update-record-v2.png
  docs/versioned_docs/version-2.43.0/data-sources/airtable.md
  docs/versioned_docs/version-2.50.0-LTS/data-sources/airtable.md
  docs/versioned_docs/version-2.61.0/data-sources/airtable.md
Labels: active-review-docs-app

#9819 [docs]: Salesforce plugin
  docs/docs/marketplace/marketplace_overview.md
  docs/docs/marketplace/plugins/salesforce.md
  docs/sidebars.js
  docs/static/img/marketplace/plugins/salesforce/action-create.png
  docs/static/img/marketplace/plugins/salesforce/action-delete.png
  docs/static/img/marketplace/plugins/salesforce/action-read.png
  docs/static/img/marketplace/plugins/salesforce/action-update.png
  docs/static/img/marketplace/plugins/salesforce/api_settings.png
  docs/static/img/marketplace/plugins/salesforce/setup.png
  docs/static/img/marketplace/plugins/salesforce/soql-query.png
  docs/versioned_docs/version-2.43.0/marketplace/marketplace_overview.md
  docs/versioned_docs/version-2.43.0/marketplace/plugins/salesforce.md
  docs/versioned_docs/version-2.50.0-LTS/marketplace/marketplace_overview.md
  docs/versioned_docs/version-2.50.0-LTS/marketplace/plugins/salesforce.md
  docs/versioned_docs/version-2.61.0/marketplace/marketplace_overview.md
  docs/versioned_docs/version-2.61.0/marketplace/plugins/salesforce.md
  docs/versioned_sidebars/version-2.43.0-sidebars.json
  docs/versioned_sidebars/version-2.50.0-LTS-sidebars.json
  docs/versioned_sidebars/version-2.61.0-sidebars.json
Labels: active-review-docs-app

#8353 add Chinese translation
  frontend/assets/translations/languages.json
  frontend/assets/translations/zh.json
Labels: needs testing
