Repository ToolJet/ToolJet, pull requests merged in 2024-07, with the labels that each got.

#10170 Feat : Introducing Aggregate and group by functionality
  .env.example
  .github/workflows/cypress-appbuilder.yml
  .github/workflows/cypress-marketplace.yml
  .github/workflows/cypress-platform.yml
  .github/workflows/render-preview-deploy.yml
  .github/workflows/review-path-deploy.yml
  .github/workflows/update-lts-test-system.yml
  docker-compose.yaml
  docker/preview.Dockerfile
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/AggregateUI/NoConditionUI.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/AggregateUI/Select.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/AggregateUI/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/AggregateUI/style.scss
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinTable.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ListRows.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  server/migrations/1718264886184-EnableAggregationInTooljetDatabase.ts
  server/ormconfig.ts
  server/src/helpers/tjdb.migration.helper.ts
  server/src/modules/tooljet_db/tooljet-db.types.ts
  server/src/modules/tooljet_db/tooljet_db.module.ts
  server/src/modules/tooljet_db/utils/helper.ts
  server/src/services/tooljet_db.service.ts
  server/src/services/tooljet_db_operations.service.ts
Labels: feature request, needs testing, run-ci, suspend-review-app

#10166 Feature: Add cookies support in the REST API datasource & query builder for static and global datasource
  frontend/assets/images/icons/info.svg
  frontend/src/Editor/CodeEditor/styles.scss
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabContent.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/TabCookies.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/Tabs.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/_ui/HttpHeaders/SourceEditor.jsx
  frontend/src/_ui/HttpHeaders/sourceEditorStyles.scss
  plugins/packages/common/lib/index.ts
  plugins/packages/common/lib/utils.helper.ts
  plugins/packages/restapi/lib/index.ts
  plugins/packages/restapi/lib/manifest.json
Labels: needs testing, suspend-review-app

#9827 Fix: Drag & drop functionality in TJDB dropzone while bulkuploading
  frontend/src/TooljetDatabase/Drawers/BulkUploadDrawer/FileDropzone.jsx
Labels: needs testing, suspend-review-app

#10066 Date with time data type for ToolJet Database
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DateTimePicker/DateTimePicker.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DateTimePicker/index.js
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DateTimePicker/styles.scss
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/util.js
  frontend/src/TooljetDatabase/Drawers/CreateColumnDrawer/index.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableForm.jsx
  frontend/src/TooljetDatabase/Forms/TableKeyRelations.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Icons/Datetime.svg
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/UniqueConstraintPopOver.jsx
  frontend/src/TooljetDatabase/Table/ActionsPopover/styles.scss
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/TableListItem/index.jsx
  frontend/src/TooljetDatabase/constants.js
  frontend/src/TooljetDatabase/index.jsx
  frontend/src/_services/tooljetDatabase.service.js
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  server/data-migrations/1718542399701-UpdateInternalTablesConfigurationsColumn.ts
  server/migrations/1718529294184-AddConfigurationColumnToInternalTables.ts
  server/src/dto/tooljet-db.dto.ts
  server/src/entities/internal_table.entity.ts
  server/src/helpers/utils.helper.ts
  server/src/services/tooljet_db.service.ts
Labels: needs testing, active-review-app

#10219 Refactor: Setup retry initialization within restapi component
  frontend/src/Editor/QueryManager/Components/CustomToggleSwitch.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/constants.js
  frontend/src/Editor/QueryManager/queryManager.theme.scss
  frontend/src/_stores/queryPanelStore.js
  plugins/packages/restapi/lib/index.ts
  plugins/packages/restapi/lib/manifest.json
Labels: suspend-review-app

#10237 fix: removed unused env variable for aggregates
  server/src/modules/tooljet_db/tooljet_db.module.ts
Labels: database

#10260 Fix: Cookies support input box rendering issue in querybuilder
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/constants.js
Labels: active-review-app

#10259 fix: Copying whole component when trying to copy text from query preview
  frontend/src/_helpers/appUtils.js
Labels: tested

#10238 Add server side pagination with `go to page` functionality on table component
  frontend/src/Editor/Components/Table/Pagination.jsx
  frontend/src/Editor/Components/Table/Table.jsx
Labels: active-review-app

#10261 Fix: Validation of aggregate conditions
  server/src/services/tooljet_db.service.ts
  server/src/services/tooljet_db_operations.service.ts
Labels: tested, active-review-app, database

#10239 Fix : Bugs from aggregate feature
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/AggregateUI/Select.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/AggregateUI/index.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinTable.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
Labels: run-ci, tested, active-review-app

#10278 fix: reset pageSwitchInProgress when page switch has already happened
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/Editor.jsx
  server/src/services/app_import_export.service.ts
Labels: tested

#10253 Fixed issues related to date time data type for TJDB
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DateTimePicker/DateTimePicker.jsx
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DateTimePicker/styles.scss
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
  frontend/src/TooljetDatabase/Table/ActionsPopover/UniqueConstraintPopOver.jsx
  frontend/src/TooljetDatabase/Table/Header.jsx
  frontend/src/TooljetDatabase/Table/index.jsx
  frontend/src/TooljetDatabase/Table/styles.scss
  frontend/src/TooljetDatabase/constants.js
  frontend/src/_ui/Drawer/DrawerFooter/index.jsx
  server/src/dto/tooljet-db.dto.ts
  server/src/services/tooljet_db_import_export_service.ts
Labels: tested, suspend-review-app

#10100 Feature: Manual toggle for retrying failed REST-API requests
  frontend/src/Editor/QueryManager/Components/CustomToggleSwitch.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerBody.jsx
  frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
  frontend/src/Editor/QueryManager/constants.js
  frontend/src/Editor/QueryManager/queryManager.theme.scss
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_stores/queryPanelStore.js
  frontend/src/_styles/queryManager.scss
  frontend/src/_ui/Toggle/Toggle.scss
  frontend/src/_ui/Toggle/index.js
  plugins/packages/restapi/lib/index.ts
  plugins/packages/restapi/lib/manifest.json
Labels: tested, suspend-review-app

#10179 Infinite scroll loader fix
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
  frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
  frontend/src/TooljetDatabase/Forms/RowForm.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx
Labels: tested, active-review-app

#9742 Fix for foreign key breaking when column name is changed
  frontend/src/TooljetDatabase/Forms/ColumnsForm.jsx
  frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx
  frontend/src/TooljetDatabase/Forms/TableSchema.jsx
  frontend/src/TooljetDatabase/Forms/styles.scss
Labels: tested, active-review-app

#10315 [docs]: add deploy keys to gitlab
  docs/docs/gitsync.md
  docs/static/img/gitsync/gitlab/deploy-keys.png
  docs/versioned_docs/version-2.50.0-LTS/gitsync.md
  docs/versioned_docs/version-2.61.0/gitsync.md
  docs/versioned_docs/version-2.62.0/gitsync.md
Labels: active-review-docs-app

#10303 Fix: Removed the org id from the query option details of the ToolJet database.
  frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  frontend/src/HomePage/ExportAppModal.jsx
  server/src/services/data_queries.service.ts
  server/src/services/tooljet_db_operations.service.ts
Labels: tested, active-review-app, database

#10295 Fix root error in docker contribution setup
  docker-compose.yaml
Labels: needs documentation

#10325 [docs]: update gitsync docs
  docs/docs/gitsync.md
  docs/versioned_docs/version-2.29.0/gitsync.md
  docs/versioned_docs/version-2.30.0/gitsync.md
  docs/versioned_docs/version-2.33.0/gitsync.md
  docs/versioned_docs/version-2.34.0/gitsync.md
  docs/versioned_docs/version-2.35.0/gitsync.md
  docs/versioned_docs/version-2.36.0/gitsync.md
  docs/versioned_docs/version-2.39.0/gitsync.md
  docs/versioned_docs/version-2.43.0/gitsync.md
  docs/versioned_docs/version-2.50.0-LTS/gitsync.md
  docs/versioned_docs/version-2.61.0/gitsync.md
  docs/versioned_docs/version-2.62.0/gitsync.md
Labels: active-review-docs-app

#10359 [docs]: fix docker LTS tag
  docs/docs/setup/system-requirements.md
  docs/versioned_docs/version-2.50.0-LTS/setup/google-cloud-run.md
  docs/versioned_docs/version-2.50.0-LTS/setup/system-requirements.md
  docs/versioned_docs/version-2.61.0/setup/system-requirements.md
  docs/versioned_docs/version-2.62.0/setup/system-requirements.md
Labels: active-review-docs-app

#10377 [fix] Added rest of the REST API plugin basic auth fixes
  plugins/packages/restapi/lib/index.ts
Labels: active-review-app

#10380 Updated "Test connection" text for datasource automation
  cypress-tests/cypress/constants/texts/postgreSql.js
Labels: run-cypress-marketplace

#10275 Chore: Setup Polly.js for recordable stubs on TJDB specs
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/modules/tooljet_db/tooljet-db.types.ts
  server/src/services/tooljet_db.service.ts
  server/src/services/tooljet_db_bulk_upload.service.ts
  server/test/__fixtures__/TooljetDbOperationsService_2702950297/createRow_4100895903/should-create-a-new-row-and-verify-its-content_3372386196/recording.har
  server/test/__fixtures__/TooljetDbOperationsService_2702950297/deleteRows_617995275/should-delete-rows-and-verify-the-deletion_3165680739/recording.har
  server/test/__fixtures__/TooljetDbOperationsService_2702950297/joinTables_306409236/should-join-tables-and-verify-the-result_3664012573/recording.har
  server/test/__fixtures__/TooljetDbOperationsService_2702950297/listRows_890836256/should-list-rows-correctly_2550208038/recording.har
  server/test/__fixtures__/TooljetDbOperationsService_2702950297/recording.har
  server/test/__fixtures__/TooljetDbOperationsService_2702950297/updateRows_1779216101/should-update-rows-and-verify-the-changes_682898660/recording.har
  server/test/jest-e2e.json
  server/test/services/tooljet_db_operations.service.spec.ts
  server/test/test.helper.ts
  server/test/tooljet-db-test.helper.ts
  server/tsconfig.json
Labels: run-ci

#10387 Modification in docs PR app's bash file to pick last version from doc…
  docs/build-latest-version.sh
Labels: active-review-docs-app

#10382 [docs]: upgrade docusaurus to 3.4.0
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/static/index.html
Labels: active-review-docs-app

#10392 [docs]: fix validation error on local docs build
  docs/docusaurus.config.js
Labels: active-review-docs-app

#10363 Release Platform v19v [v2.65.1]
  .version
  cypress-tests/cypress/constants/texts/postgreSql.js
  frontend/.version
  frontend/src/Editor/DataSourceManager/TestConnection.jsx
  frontend/src/HomePage/FolderMenu.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  plugins/packages/restapi/lib/index.ts
  release-scripts/create-release.sh
  server/.version
  server/ce/apps/services/apps.service.sep.ts
  server/ce/apps/types/OrganizationThemes.ts
  server/src/controllers/app.controller.ts
  server/src/controllers/apps.controller.v2.ts
  server/src/modules/apps/apps.module.ts
  server/src/services/apps.service.ts
  server/src/services/organization_users.service.ts
  server/tsconfig.json
Labels: run-cypress

#10406 Appbuilder priority fix 0.1
  .version
  frontend/.version
  frontend/src/Editor/Components/Statistics.jsx
  frontend/src/Editor/Components/Tags.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/ControlledComponentToRender.jsx
  frontend/src/Editor/DataSourceManager/SourceComponents/Runjs.schema.json
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Middlewares/HydrateWithResolveReferences.jsx
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_helpers/utils.js
  frontend/src/_stores/appDataStore.js
  frontend/src/_stores/utils.js
  server/.version
  server/src/helpers/import_export.helpers.ts
  server/src/services/app_import_export.service.ts
  server/src/services/components.service.ts
  server/src/services/events_handler.service.ts
  server/src/services/page.service.ts
Labels: active-review-app

#10419 Chore: Add jest types dependency
  server/package-lock.json
  server/package.json
  server/tsconfig.build.json
Labels: active-review-app

#10327 fix: Textarea exposed variable not updated on app load
  frontend/src/Editor/Components/TextArea.jsx
Labels: active-review-app

#10379 fix : Exposed actions become unavailable on reload
  frontend/src/Editor/BoxUI.jsx
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/Checkbox.jsx
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/Components/DropdownV2/DropdownV2.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Icon.jsx
  frontend/src/Editor/Components/Kanban/Kanban.jsx
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/ControlledComponentToRender.jsx
Labels: tested

#10381 New loading state UI
  frontend/ee/components/UsersPage/UsersTable.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/_components/OrganizationLogin/OrganizationLogin.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/FolderSkeleton/FolderSkeleton.jsx
  frontend/src/_ui/FolderSkeleton/HeaderSkeleton.jsx
Labels: active-review-app

#10424 Fix chart not updating when using custom schema and dynamic data
  frontend/src/Editor/WidgetManager/configs/chart.js
Labels: tested

#10446 fixed plugin icon and add button rendering
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/_ui/Card/Card.jsx
Labels: active-review-app

#10448 [docs]: Update Calendar and Kanban Banner
  docs/docs/widgets/calendar.md
  docs/docs/widgets/kanban-board.md
  docs/static/img/widgets/calendar/calendar-component-v2.png
  docs/versioned_docs/version-2.10.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.11.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.12.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.13.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.14.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.15.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.16.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.17.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.18.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.19.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.22.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.23.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.24.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.25.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.27.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.29.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.3.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.30.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.33.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.34.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.35.0/widgets/calendar.md
  docs/versioned_docs/version-2.35.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.36.0/widgets/calendar.md
  docs/versioned_docs/version-2.36.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.39.0/widgets/calendar.md
  docs/versioned_docs/version-2.39.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.4.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.43.0/widgets/calendar.md
  docs/versioned_docs/version-2.43.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.5.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.50.0-LTS/widgets/calendar.md
  docs/versioned_docs/version-2.50.0-LTS/widgets/kanban-board.md
  docs/versioned_docs/version-2.6.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.61.0/widgets/calendar.md
  docs/versioned_docs/version-2.61.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.62.0/widgets/calendar.md
  docs/versioned_docs/version-2.62.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.65.0/widgets/calendar.md
  docs/versioned_docs/version-2.65.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.7.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.8.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.9.0/widgets/kanban-board.md
  docs/versioned_docs/version-2.9.4/widgets/kanban-board.md
Labels: active-review-docs-app

#10454 fix : LTS : Z-order of datepicker and multiselect components in subcontainer
  .version
  frontend/.version
  frontend/src/Editor/Components/Datepicker.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/Table/datepicker.scss
  server/.version
Labels: tested

#10421 Release platformv19.1 [2.65.2]
  .version
  frontend/.version
  frontend/ee/components/UsersPage/UsersTable.jsx
  frontend/src/GlobalDatasources/GlobalDataSourcesPage/index.jsx
  frontend/src/GlobalDatasources/List/index.jsx
  frontend/src/HomePage/AppList.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
  frontend/src/_components/OrganizationLogin/OrganizationLogin.jsx
  frontend/src/_styles/theme.scss
  frontend/src/_ui/Card/Card.jsx
  frontend/src/_ui/FolderSkeleton/FolderSkeleton.jsx
  frontend/src/_ui/FolderSkeleton/HeaderSkeleton.jsx
  frontend/src/_ui/Icon/solidIcons/Plus.jsx
  server/.version
Labels: run-ci, run-cypress

#10435 fix label text issue for text, password and number inputs
  frontend/src/Editor/Components/Form/FormUtils.js
  frontend/src/Editor/WidgetManager/configs/form.js
Labels: tested

#10441 Fix/incorrect documentation url
  frontend/src/Editor/Inspector/Inspector.jsx
Labels: tested

#10243 Fix dropdown/multiselect add option
  frontend/src/Editor/CodeBuilder/Elements/Visibility.jsx
  frontend/src/Editor/Components/DropdownV2/DropdownV2.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/Editor/Inspector/Components/Select.jsx
  frontend/src/Editor/WidgetManager/configs/dropdownV2.js
  frontend/src/Editor/WidgetManager/configs/multiselectV2.js
Labels: tested

#10455 fix/tab-switch-event
  frontend/src/Editor/Components/Tabs.jsx
Labels: tested

#10463 [hotfix] : Fix typing delay in text input and textarea
  .version
  frontend/.version
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Inspector/Inspector.jsx
  frontend/src/Editor/component-properties-validation.js
  server/.version
Labels: tested

#10438 fix: column transformations not working
  frontend/src/Editor/Components/Table/Table.jsx
Labels: tested

#10494 add old resolver fallback for non string values
  frontend/src/Editor/CodeEditor/utils.js
Labels: tested

#10476 fix : Transformation code gets cleared on reload after disabling it
  frontend/src/Editor/QueryManager/Components/Transformation.jsx
Labels: tested

#10443 fix/text-csa
  frontend/src/Editor/Components/Text.jsx
Labels: tested

#10464 fixes: if references includes includes a template literal
  frontend/src/Editor/CodeEditor/utils.js
Labels: tested

#10457 fix : Page change doesn't happen for table with CSA in viewer
  frontend/src/_helpers/appUtils.js
Labels: tested

#10439 Fixes box shadow not working for table and Hide fx for Make all columns editable field in table
  frontend/src/Editor/BoxUI.jsx
  frontend/src/Editor/Inspector/Components/Table/Table.jsx
Labels: tested

#10452 fix/decimal-places
  frontend/src/Editor/Components/Table/columns/index.jsx
Labels: tested

#10505 Hotfix: REST API multiform data missing boundary on headers
  .version
  frontend/.version
  plugins/packages/common/lib/oauth.ts
  plugins/packages/common/lib/utils.helper.ts
  plugins/packages/restapi/lib/index.ts
  server/.version
Labels: run-ci, active-review-app, run-cypress

#10523 [docs]: add latest LTS tags
  docs/docs/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.15.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.16.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.17.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.18.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.19.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.22.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.23.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.24.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.25.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.27.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.29.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.30.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.33.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.34.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.35.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.36.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.39.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.43.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.50.0-LTS/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.61.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.62.0/setup/choose-your-tooljet.md
  docs/versioned_docs/version-2.65.0/setup/choose-your-tooljet.md
Labels: active-review-docs-app

#10513 fix/zero-padding
  frontend/src/Editor/component-properties-validation.js
Labels: tested

#10511 Fix container scrollbar issue
  frontend/src/_styles/drawer.scss
Labels: tested, active-review-app

#10509 fix : Icons are not getting hidden in input components
  frontend/src/Editor/Components/NumberInput.jsx
  frontend/src/Editor/Components/PasswordInput.jsx
  frontend/src/Editor/Components/TextInput.jsx
Labels: tested

#10459 fix/tabs-equal-width
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/_styles/theme.scss
Labels: tested

#10478 fix/render-active-tab-default
  frontend/src/Editor/WidgetManager/configs/tabs.js
Labels: tested

#10462 [fix]: Added components exposed values to the suggestions
  frontend/src/Editor/BoxUI.jsx
  frontend/src/Editor/CodeEditor/utils.js
  frontend/src/Editor/Components/Button.jsx
  frontend/src/Editor/Components/Chart.jsx
  frontend/src/Editor/Components/Checkbox.jsx
  frontend/src/Editor/Components/ColorPicker.jsx
  frontend/src/Editor/Components/DropdownV2/DropdownV2.jsx
  frontend/src/Editor/Components/Form/Form.jsx
  frontend/src/Editor/Components/Icon.jsx
  frontend/src/Editor/Components/Kanban/Kanban.jsx
  frontend/src/Editor/Components/Kanban/KanbanBoard.jsx
  frontend/src/Editor/Components/Listview.jsx
  frontend/src/Editor/Components/Modal.jsx
  frontend/src/Editor/Components/Multiselect.jsx
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
  frontend/src/Editor/Components/RadioButton.jsx
  frontend/src/Editor/Components/Table/Table.jsx
  frontend/src/Editor/Components/Tabs.jsx
  frontend/src/Editor/Components/TextArea.jsx
  frontend/src/Editor/Components/TextInput.jsx
  frontend/src/Editor/Components/TreeSelect.jsx
  frontend/src/Editor/Container.jsx
  frontend/src/Editor/ControlledComponentToRender.jsx
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/Viewer.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_helpers/editorHelpers.js
  frontend/src/_stores/resolverStore.js
Labels: tested

#10533 Revert "fix/text-csa"
  frontend/src/Editor/Components/Text.jsx
Labels: tested

#10531 Fix/query state issue
  frontend/src/_stores/currentStateStore.js
Labels: tested

#10491 add live validation for page handler
  frontend/src/Editor/LeftSidebar/SidebarPageSelector/EditInput.jsx
Labels: tested

#10444 fix table mapping for events when cloning and creating new versions
  server/src/services/app_import_export.service.ts
  server/src/services/apps.service.ts
  server/src/services/page.service.ts
Labels: tested

#10522 fix/grid-to-list
  frontend/src/Editor/Container.jsx
Labels: tested

#10526 Fix: default value on legacy dropdown component
  frontend/src/Editor/component-properties-validation.js
Labels: tested

#10516 fix: increase multiselect menu zindex when open
  frontend/src/Editor/Components/Multiselect.jsx
Labels: tested

#10539 fix: increse z-index of datepicker so that it comes on top of others
  frontend/src/Editor/Components/Datepicker.jsx
Labels: tested

#10535 fix: Dropdownand multiselect legacy components doesn't close on clicking menu dropdown icon
  frontend/src/Editor/Components/DropDown.jsx
  frontend/src/Editor/Components/Multiselect.jsx
Labels: tested

#10482 fix : The query in the suggestion does not exist if we rename the query and try to access the suggestions by typing `{{queries`
  frontend/src/Editor/CodeEditor/PreviewBox.jsx
  frontend/src/Editor/QueryManager/Components/QueryManagerHeader.jsx
  frontend/src/Editor/QueryPanel/QueryCard.jsx
  frontend/src/_helpers/appUtils.js
Labels: tested

#10543 fix/multiselect-label
  frontend/src/Editor/Components/MultiselectV2/MultiselectV2.jsx
Labels: tested

#10540 fix: increase color picker zIndex on open
  frontend/src/Editor/Components/ColorPicker.jsx
Labels: tested

#10525 Fix: navigation alignment of list view component
  frontend/src/Editor/Components/Listview.jsx
Labels: tested

#10499 Fix/inspector query run preview
  frontend/src/Editor/Editor.jsx
  frontend/src/Editor/LeftSidebar/SidebarInspector.jsx
Labels: tested

#10534 Fix: dropdown icon state on open and close
  frontend/src/Editor/Components/DropDown.jsx
Labels: tested

#10542 Fix: Icons for legacy components
  frontend/assets/images/icons/widgets/index.jsx
Labels: tested
