Repository ToolJet/ToolJet, pull requests merged in 2025-10, with the labels that each got.

#14236 Data-source connection failing Fix
  server/src/modules/data-sources/service.ts
  server/src/modules/data-sources/util.service.ts
Labels: tested, active-ce-review-app, active-ee-review-app, ready-to-merge

#14274 Add workspace constants test cases for enterprise
  .github/workflows/cypress-platform.yml
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/workspace/envWorkspaceConstants.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/workspace/workspaceConstants.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/workspace/workspaceConstantsFunctionality.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/workspace/workspaceConstantsUI.cy.js
  cypress-tests/cypress/support/utils/workspaceConstants.js
Labels: run-cypress-platform-ce, run-cypress-platform-ee

#14209 Feat: Support for service account authentication in google sheet datasource
  frontend/src/_components/Googlesheets.jsx
  frontend/src/modules/dataSources/components/DataSourceManager/DataSourceManager.jsx
  plugins/package-lock.json
  plugins/packages/googlesheets/lib/index.ts
  plugins/packages/googlesheets/lib/manifest.json
  plugins/packages/googlesheets/package-lock.json
  plugins/packages/googlesheets/package.json
  server/data-migrations/1759169380218-BackfillGoogleSheetDatasourceAuthenticationType.ts
Labels: suspend-ee-review-app, suspend-ce-review-app

#14277 Hotfix: MariaDB datasource connection handling
  plugins/packages/mariadb/lib/index.ts
  plugins/packages/mariadb/lib/manifest.json
Labels: active-ce-review-app, active-ee-review-app

#14213 Hotfix/added version name in global state
  frontend/src/AppBuilder/Header/CreateVersionModal.jsx
  frontend/src/AppBuilder/_hooks/useAppData.js
Labels: tested
