Repository ToolJet/ToolJet, pull requests merged in 2025-07, with the labels that each got.

#13113 [fix]: Form bug on refresh fields
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/_components/ColumnMappingComponent.jsx
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/_hooks/useFormLogic.js
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/handlers/parameterHandlers.js
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/utils/utils.js
  frontend/src/AppBuilder/RightSideBar/Inspector/Inspector.jsx
Labels: tested

#12994 Modules : Platform Functionality
  frontend/assets/images/icons/empty-modules.svg
  frontend/src/AppBuilder/AppCanvas/appCanvasUtils.js
  frontend/src/AppBuilder/RightSideBar/ComponentManagerTab/ComponentModuleTab/ComponentModuleTab.jsx
  frontend/src/AppBuilder/RightSideBar/ComponentManagerTab/ComponentsManagerTab.jsx
  frontend/src/AppBuilder/RightSideBar/ComponentManagerTab/DragLayer.jsx
  frontend/src/AppBuilder/_hooks/useAppData.js
  frontend/src/HomePage/AppCard.jsx
  frontend/src/HomePage/AppMenu.jsx
  frontend/src/HomePage/ExportAppModal.jsx
  frontend/src/HomePage/Folders.jsx
  frontend/src/HomePage/Header.jsx
  frontend/src/HomePage/HomePage.jsx
  frontend/src/_services/apps.service.js
  frontend/src/_stores/licenseStore.js
  frontend/src/_styles/modules.scss
  frontend/src/_ui/Breadcrumbs/index.jsx
  frontend/src/modules/common/components/BaseImportAppMenu/BaseImportAppMenu.jsx
  server/src/modules/app-environments/util.service.ts
  server/src/modules/app/constants/module-info.ts
  server/src/modules/apps/service.ts
  server/src/modules/apps/services/app-import-export.service.ts
  server/src/modules/apps/util.service.ts
  server/src/modules/modules/ability/guard.ts
  server/src/modules/modules/ability/index.ts
  server/src/modules/modules/constants/feature.ts
  server/src/modules/modules/constants/index.ts
  server/src/modules/modules/module.ts
  server/src/modules/modules/types/index.ts
  server/src/modules/versions/ability/guard.ts
  server/src/modules/versions/ability/utility.ts
Labels: active-ee-review-app, ready-to-merge

#13134 [docs]: Access SSO User Info
  docs/docs/user-management/sso/oidc/ssouserinfo.md
  docs/sidebars.js
  docs/versioned_docs/version-2.50.0-LTS/setup/kubernetes-gke.md
Labels: active-review-docs-app

#13146 Fixes for cloud instance level licensing
  server/src/modules/app/guards/ability.guard.ts
  server/src/modules/licensing/controllers/audit-logs.controller.ts
  server/src/modules/licensing/controllers/organization.controller.ts
  server/src/modules/licensing/guards/app.guard.ts
  server/src/modules/licensing/guards/auditLog.guard.ts
  server/src/modules/licensing/guards/table.guard.ts
  server/src/modules/licensing/interfaces/IController.ts
  server/src/modules/licensing/interfaces/IService.ts
  server/src/modules/licensing/services/count.service.ts
  server/src/modules/licensing/services/init.service.ts
  server/src/modules/licensing/services/terms.service.ts
  server/src/modules/setup-organization/util.service.ts
Labels: ready-to-merge

#13147 Add data-cy for new editor components
  frontend/src/AppBuilder/QueryPanel/QueryCard.jsx
  frontend/src/AppBuilder/RightSideBar/SidebarItem.jsx
Labels: run-cypress-ce

#13132 Added chart border property and removed white background color
  frontend/src/AppBuilder/WidgetManager/widgets/chart.js
  frontend/src/Editor/Components/Chart.jsx
  server/src/modules/apps/services/widget-config/chart.js
Labels: tested, run-cypress-ce

#13181 Appbuilder prerelease bug fixes
  frontend/src/AppBuilder/AppCanvas/AppCanvas.jsx
  frontend/src/AppBuilder/RightSideBar/RightSidebarToggle.jsx
  frontend/src/AppBuilder/_contexts/ModuleContext.jsx
Labels: run-cypress-ce

#13161 Feature: Prometheus plugin
  frontend/src/AppBuilder/CodeEditor/CodeHinter.jsx
  frontend/src/AppBuilder/CodeEditor/styles.scss
  frontend/src/_components/DynamicForm.jsx
  marketplace/plugins/prometheus/.gitignore
  marketplace/plugins/prometheus/README.md
  marketplace/plugins/prometheus/__tests__/index.js
  marketplace/plugins/prometheus/lib/icon.svg
  marketplace/plugins/prometheus/lib/index.ts
  marketplace/plugins/prometheus/lib/manifest.json
  marketplace/plugins/prometheus/lib/operations.json
  marketplace/plugins/prometheus/lib/query_operations.ts
  marketplace/plugins/prometheus/lib/types.ts
  marketplace/plugins/prometheus/package.json
  marketplace/plugins/prometheus/tsconfig.json
  server/src/assets/marketplace/plugins.json
Labels: tested, suspend-ee-review-app

#13163 Feature : Host and database can be dynamically configured in query builder for PostgreSQL and MySQL data sources
  frontend/src/_components/DynamicForm.jsx
  plugins/packages/mysql/lib/index.ts
  plugins/packages/mysql/lib/manifest.json
  plugins/packages/mysql/lib/operations.json
  plugins/packages/mysql/lib/types.ts
  plugins/packages/postgresql/lib/index.ts
  plugins/packages/postgresql/lib/manifest.json
  plugins/packages/postgresql/lib/operations.json
  plugins/packages/postgresql/lib/types.ts
Labels: tested, suspend-ee-review-app, suspend-ce-review-app

#13167 Fix: PostgreSQL datasource tries to establish an SSL connection even when the SSL toggle is off
  plugins/packages/postgresql/lib/index.ts
Labels: tested, suspend-ee-review-app, suspend-ce-review-app

#13166 Feat: The ability to provide a partition key for deleting items in CosmosDB datasource has been enabled
  plugins/packages/cosmosdb/lib/index.ts
  plugins/packages/cosmosdb/lib/operations.json
  plugins/packages/cosmosdb/lib/operations.ts
  plugins/packages/cosmosdb/lib/types.ts
Labels: tested, suspend-ce-review-app

#12862 Fix: Ensure secrets and constants mapped to encrypted fields are correctly imported with the app
  cypress-tests/cypress/commands/commands.js
  cypress-tests/cypress/e2e/happyPath/marketplace/commonTestcases/data-source/airTableHappyPath.cy.js
  cypress-tests/cypress/e2e/happyPath/marketplace/commonTestcases/data-source/postgresHappyPath.cy.js
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/DynamicFormV2.jsx
  frontend/src/_ui/Input-V3/index.js
  frontend/src/_ui/Input/index.js
  frontend/src/components/ui/Input/CommonInput/Index.jsx
  frontend/src/components/ui/Input/Input.jsx
  frontend/src/modules/dataSources/components/DataSourceManager/DataSourceManager.jsx
  marketplace/plugins/qdrant/lib/manifest.json
  plugins/packages/common/lib/index.ts
  plugins/packages/common/lib/utils.helper.ts
  plugins/packages/mssql/lib/index.ts
  plugins/packages/mysql/lib/index.ts
  plugins/packages/oracledb/lib/index.ts
  plugins/packages/postgresql/lib/index.ts
  plugins/packages/snowflake/lib/index.ts
  server/src/modules/app/module.ts
  server/src/modules/apps/services/app-import-export.service.ts
  server/src/modules/data-sources/module.ts
  server/src/modules/data-sources/util.service.ts
  server/src/modules/inMemoryCache/in-memory-cache.service.ts
  server/src/modules/inMemoryCache/interfaces/IUtilService.ts
  server/src/modules/inMemoryCache/module.ts
Labels: tested, marketplace-plugin-deployed, active-ce-review-app, active-ee-review-app, run-cypress-platform-ce, run-cypress-marketplace-ce

#13223 Feature: Optional SQL mode for ToolJet Database
  frontend/src/AppBuilder/QueryManager/QueryEditors/TooljetDatabase/ToolJetDbOperations.jsx
  server/data-migrations/1721236971725-MoveToolJetDatabaseTablesFromPublicToTenantSchema.ts
  server/src/helpers/tooljet_db.helper.ts
  server/src/modules/tooljet-db/helper.ts
  server/src/modules/tooljet-db/module.ts
  server/src/modules/tooljet-db/services/postgrest-proxy.service.ts
  server/src/modules/tooljet-db/services/tooljet-db-data-operations.service.ts
  server/src/modules/tooljet-db/services/tooljet-db-table-operations.service.ts
Labels: active-ee-review-app, ready-to-merge

#13271 Platform cypress fix
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/apps/privateAndpublicApps.cy.js
  cypress-tests/cypress/e2e/happyPath/platform/ceTestcases/workspace/workspaceConstants.cy.js
Labels: run-cypress-platform-ce

#13230 Fix: Avoid setting Content-Type header for requests without body and configure different host for all environments in OpenAPI [PRE-RELEASE]
  frontend/src/AppBuilder/QueryManager/QueryEditors/Openapi.jsx
  frontend/src/_ui/Select/styles.js
  plugins/packages/openapi/lib/index.ts
  plugins/packages/openapi/lib/manifest.json
  plugins/packages/openapi/lib/types.ts
Labels: tested, active-ee-review-app, suspend-ce-review-app

#13284 fix: remove incorrect second parameter from setSelectedQuery call
  frontend/src/AppBuilder/_stores/slices/dataQuerySlice.js
Labels: tested

#13162 Feat: New fields 'client id' and 'client secret' have been introduced in the Slack datasource configuration page in pre-release
  frontend/src/_components/Slack.jsx
  plugins/packages/slack/lib/index.ts
  plugins/packages/slack/lib/manifest.json
  server/data-migrations/1747338135635-BackfillSlackAppOption.ts
Labels: tested, active-ce-review-app, active-ee-review-app

#13300 Fix: Error message not getting displayed in app builder when query fails
  frontend/src/AppBuilder/_stores/slices/queryPanelSlice.js
Labels: active-ee-review-app

#12948 CI/CD GitSync
  server/src/modules/apps/repository.ts
  server/src/modules/apps/util.service.ts
  server/src/modules/external-apis/ability/index.ts
  server/src/modules/external-apis/constants/feature.ts
  server/src/modules/external-apis/constants/index.ts
  server/src/modules/external-apis/dto/index.ts
  server/src/modules/external-apis/module.ts
  server/src/modules/external-apis/types/index.ts
  server/src/modules/git-sync/util.service.ts
  server/src/modules/group-permissions/repository.ts
  server/src/modules/organizations/repository.ts
  server/src/modules/versions/repository.ts
Labels: ready-to-merge

#13351 Fix link widget issues
  frontend/src/AppBuilder/WidgetManager/widgets/link.js
  frontend/src/Editor/Components/Link/Link.jsx
  frontend/src/Editor/Components/Link/link.scss
  server/src/modules/apps/services/widget-config/link.js
Labels: tested

#13291 Enhance: Extract the general OAuth flow for plugins [PRE-RELEASE]
  frontend/src/_components/DynamicForm.jsx
  frontend/src/_components/OAuthWrapper.jsx
  frontend/src/_helpers/utils.js
  frontend/src/_ui/OAuth/Authentication.jsx
  frontend/src/_ui/OAuth/GrantTypes.jsx
  frontend/src/_ui/OAuth/index.js
  frontend/src/modules/dataSources/components/DataSourceManager/DataSourceManager.jsx
  server/src/modules/data-sources/dto/index.ts
  server/src/modules/data-sources/interfaces/IUtilService.ts
  server/src/modules/data-sources/util.service.ts
Labels: tested, suspend-ee-review-app, suspend-ce-review-app

#13333 Show guidelines when dropping the component from right sidebar
  .vscode/settings.json
  frontend/package-lock.json
  frontend/src/AppBuilder/AppCanvas/AppCanvas.jsx
  frontend/src/AppBuilder/AppCanvas/Container.jsx
  frontend/src/AppBuilder/AppCanvas/GhostWidgets.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/gridUtils.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useDropVirtualMoveableGhost.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useElementGuidelines.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useGhostMoveable.js
  frontend/src/AppBuilder/AppCanvas/WidgetWrapper.jsx
  frontend/src/AppBuilder/AppCanvas/appCanvasUtils.js
  frontend/src/AppBuilder/AppCanvas/useCanvasDropHandler.js
  frontend/src/AppBuilder/RightSideBar/ComponentManagerTab/DragLayer.jsx
  frontend/src/AppBuilder/_stores/slices/gridSlice.js
  frontend/src/_stores/gridStore.js
  frontend/src/modules/common/components/BaseColorSwatches/BaseColorSwatches.jsx
Labels: tested

#13319 [docs]: Google Calendar Plugin
  docs/docs/marketplace/marketplace_overview.md
  docs/docs/marketplace/plugins/google-calendar.md
  docs/sidebars.js
  docs/static/img/marketplace/plugins/googlecal/client-id.png
  docs/static/img/marketplace/plugins/googlecal/clients.png
  docs/static/img/marketplace/plugins/googlecal/connection.png
  docs/static/img/marketplace/plugins/googlecal/create-oauth.png
  docs/static/img/marketplace/plugins/googlecal/gc-new-project.png
  docs/static/img/marketplace/plugins/googlecal/oauth-type.png
  docs/versioned_docs/version-3.5.0-LTS/marketplace/marketplace_overview.md
  docs/versioned_docs/version-3.5.0-LTS/marketplace/plugins/google-calendar.md
  docs/versioned_sidebars/version-3.5.0-LTS-sidebars.json
Labels: active-review-docs-app

#13202 Fix grid related bugs
  frontend/assets/images/icons/widgets/index.jsx
  frontend/src/AppBuilder/AppCanvas/Container.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/gridUtils.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useElementGuidelines.js
  frontend/src/AppBuilder/AppCanvas/WidgetWrapper.jsx
  frontend/src/AppBuilder/AppCanvas/appCanvasUtils.js
  frontend/src/AppBuilder/CodeEditor/SingleLineCodeEditor.jsx
  frontend/src/AppBuilder/RightSideBar/ComponentManagerTab/DragLayer.jsx
  frontend/src/AppBuilder/WidgetManager/widgets/listview.js
  frontend/src/AppBuilder/WidgetManager/widgets/modalV2.js
  frontend/src/AppBuilder/Widgets/Container/Container.jsx
  frontend/src/AppBuilder/Widgets/Form/Components/HorizontalSlot.jsx
  frontend/src/AppBuilder/Widgets/Listview.jsx
  frontend/src/AppBuilder/Widgets/Modal.jsx
  frontend/src/AppBuilder/Widgets/ModalV2/ModalV2.jsx
  frontend/src/AppBuilder/Widgets/PasswordInput.jsx
  frontend/src/AppBuilder/_stores/slices/gridSlice.js
  frontend/src/Editor/WidgetManager/configs/listview.js
  frontend/src/Editor/WidgetManager/configs/modalV2.js
  server/src/modules/apps/services/widget-config/listview.js
  server/src/modules/apps/services/widget-config/modalV2.js
Labels: tested

#13367 Fix tabs not changing on selected query change
  frontend/src/AppBuilder/QueryManager/QueryManager.jsx
Labels: tested

#13267 [fix]: Form bug fixes for the LTS
  frontend/src/AppBuilder/CodeBuilder/Elements/DropdownMenu/DropdownMenu.jsx
  frontend/src/AppBuilder/CodeBuilder/Elements/DropdownMenu/styles.scss
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/_components/ColumnMappingComponent.jsx
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/_components/DataSectionUI.jsx
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/_components/FieldPopoverContent.jsx
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/handlers/jsonDataHandlers.js
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/handlers/parameterHandlers.js
  frontend/src/AppBuilder/WidgetManager/widgets/form.js
  frontend/src/AppBuilder/Widgets/Form/Form.jsx
  frontend/src/_styles/dropdown-custom.scss
  frontend/src/_styles/popover.scss
  frontend/src/components/ui/Dropdown/DropdownProvider.jsx
  frontend/src/components/ui/Dropdown/Index.jsx
  frontend/src/components/ui/Dropdown/Select.jsx
  server/src/modules/apps/services/widget-config/form.js
Labels: tested

#13440 Updates the step counter to account for a removed step in the app builder's guided walkthrough
  frontend/src/AppBuilder/RightSideBar/RightSidebarToggle.jsx
  frontend/src/AppBuilder/_helpers/createWalkThrough.js
Labels: active-ee-review-app

#13431 Fix Modalv2 bugs
  frontend/src/AppBuilder/AppCanvas/AppCanvas.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useDropVirtualMoveableGhost.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useElementGuidelines.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useGhostMoveable.js
  frontend/src/AppBuilder/AppCanvas/RenderWidget.jsx
  frontend/src/AppBuilder/RightSideBar/Inspector/EventManager.jsx
  frontend/src/AppBuilder/WidgetManager/widgets/form.js
  frontend/src/AppBuilder/WidgetManager/widgets/modalV2.js
  frontend/src/AppBuilder/Widgets/Container/Container.jsx
  frontend/src/AppBuilder/Widgets/Modal.jsx
  frontend/src/AppBuilder/Widgets/ModalV2/Components/Modal.jsx
  frontend/src/AppBuilder/Widgets/ModalV2/ModalV2.jsx
  frontend/src/AppBuilder/Widgets/ModalV2/helpers/stylesFactory.js
  frontend/src/AppBuilder/Widgets/ModalV2/helpers/utils.js
  frontend/src/Editor/WidgetManager/configs/form.js
  frontend/src/Editor/WidgetManager/configs/modalV2.js
  server/src/modules/apps/services/widget-config/form.js
  server/src/modules/apps/services/widget-config/modalV2.js
Labels: tested

#13462 added external API controller base
  server/src/modules/external-apis/Interfaces/IController.ts
  server/src/modules/external-apis/controllers/apps.controller.ts
Labels: ready-to-merge

#13467 Fix for license issues on version creation
  server/src/modules/apps/interfaces/services/IPageService.ts
Labels: ready-to-merge

#13451 Fix: Minor LTS Bugs
  frontend/src/AppBuilder/Widgets/Date/DaterangePicker.jsx
  frontend/src/AppBuilder/Widgets/PhoneCurrency/CurrencyInput.jsx
  frontend/src/Editor/Components/Datepicker.jsx
Labels: tested, active-ce-review-app

#13426 [docs]: Add migration guide for 3.16
  docs/docs/setup/upgrade-to-v3.16.md
  docs/sidebars.js
Labels: suspend-review-docs-app

#13499 Added logs for log to file module
  release-scripts/resolve-conflicts-submodules.sh
  server/src/modules/app-environments/util.service.ts
  server/src/modules/app/decorators/ability.decorator.ts
  server/src/modules/app/decorators/app.decorator.ts
  server/src/modules/app/decorators/data-source.decorator.ts
  server/src/modules/app/decorators/user-permission.decorator.ts
  server/src/modules/app/decorators/user.decorator.ts
  server/src/modules/auth/decorators/ai-cookie.decorator.ts
  server/src/modules/group-permissions/decorators/group.decorator.ts
  server/src/modules/log-to-file/constants/index.ts
  server/src/modules/session/decorators/invited-user.decorator.ts
Labels: ready-to-merge

#13517 Fix: Minor LTS Bugs 02
  frontend/src/AppBuilder/RightSideBar/WidgetBox/WidgetBox.jsx
  frontend/src/AppBuilder/Widgets/NewTable/_components/TableExposedVariables/TableExposedVariables.jsx
  frontend/src/AppBuilder/_stores/slices/queryPanelSlice.js
Labels: tested, active-ce-review-app

#13519 Fix form resizer handle not appearing on header and footer
  frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx
  frontend/src/AppBuilder/Widgets/Form/Form.jsx
Labels: tested

#13528 Chat component
  frontend/assets/images/icons/widgets/chat.jsx
  frontend/assets/images/icons/widgets/index.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/ArrayNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/BooleanNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/FunctionNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/NullNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/NumberNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/ObjectNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/Components/StringNode.jsx
  frontend/src/AppBuilder/LeftSidebar/LeftSidebarInspector/CustomJSONViewer/styles.scss
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Chat.jsx
  frontend/src/AppBuilder/RightSideBar/Inspector/Inspector.jsx
  frontend/src/AppBuilder/RightSideBar/WidgetBox/WidgetBox.jsx
  frontend/src/AppBuilder/WidgetManager/configs/widgetConfig.js
  frontend/src/AppBuilder/WidgetManager/widgets/chat.js
  frontend/src/AppBuilder/WidgetManager/widgets/index.js
  frontend/src/AppBuilder/Widgets/Chat/components/Avatar.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/ChatHeader.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/ChatInput.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/ChatMessage.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/LoadingMessageSkeleton.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/MarkdownMessage.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/MessageAvatar.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/MessageHeader.jsx
  frontend/src/AppBuilder/Widgets/Chat/components/RespondentLoadingMessage.jsx
  frontend/src/AppBuilder/Widgets/Chat/hooks/useComputedStyles.js
  frontend/src/AppBuilder/Widgets/Chat/index.js
  frontend/src/AppBuilder/Widgets/Chat/utils/helpers.js
  frontend/src/AppBuilder/Widgets/NewTable/_components/DataTypes/JSON.jsx
  frontend/src/AppBuilder/Widgets/NewTable/_components/Footer/_components/ControlButtons.jsx
  frontend/src/AppBuilder/Widgets/NewTable/_utils/buildTableColumn.js
  frontend/src/AppBuilder/_helpers/editorHelpers.js
  frontend/src/AppBuilder/_stores/slices/eventsSlice.js
  frontend/src/Editor/WidgetManager/configs/chat.js
  frontend/src/Editor/WidgetManager/configs/index.js
  frontend/src/Editor/WidgetManager/widgetConfig.js
  frontend/src/_components/OverflowTooltip.jsx
  frontend/src/_helpers/appUtils.js
  frontend/src/_styles/designtheme.scss
  frontend/src/_styles/table-component.scss
  frontend/src/_styles/theme.scss
  frontend/src/_styles/typography.scss
  frontend/src/_styles/widgets/chat.scss
  frontend/src/_ui/Icon/solidIcons/ClearHistory.jsx
  frontend/src/_ui/Icon/solidIcons/DefaultResponseAvatar.jsx
  frontend/src/_ui/Icon/solidIcons/DefaultSenderChatIcon.jsx
  frontend/src/_ui/Icon/solidIcons/LoadingState.jsx
  frontend/src/_ui/Icon/solidIcons/PageDownload.jsx
  frontend/src/_ui/Icon/solidIcons/Send.jsx
  frontend/src/_ui/Icon/solidIcons/index.js
  server/src/modules/apps/services/widget-config/chat.js
  server/src/modules/apps/services/widget-config/index.js
Labels: active-ee-review-app, run-cypress-ce

#13531 [docs]: Snowflakes and Salesforce Multi Auth
  docs/docs/data-sources/snowflake.md
  docs/docs/marketplace/plugins/salesforce.md
  docs/static/img/datasource-reference/snowflake/snowflake-connect-v3.png
  docs/static/img/marketplace/plugins/salesforce/setup-v2.png
  docs/versioned_docs/version-3.5.0-LTS/data-sources/snowflake.md
  docs/versioned_docs/version-3.5.0-LTS/marketplace/plugins/salesforce.md
Labels: suspend-review-docs-app

#13407 [Fix] : Viewer header dark theme issue
  frontend/src/App/App.jsx
  frontend/src/AppBuilder/Viewer/PreviewSettings.jsx
  frontend/src/AppBuilder/Viewer/viewer.scss
  frontend/src/MarketplacePage/InstalledPlugins.jsx
  frontend/src/_components/_styles/search-box.scss
  frontend/src/_styles/pages-sidebar.scss
  frontend/src/_styles/theme.scss
Labels: suspend-ee-review-app, ready-to-merge

#13551 fix for get data sources from public app editor
  server/src/modules/app/guards/ability.guard.ts
  server/src/modules/data-sources/constants/feature.ts
Labels: active-ee-review-app

#13550 Toggle bg fix
  frontend/src/_ui/Toggle/Toggle.scss
Labels: tested, active-ee-review-app

#13559 [fix]: Crash on form component while creating the custom radio button
  frontend/src/AppBuilder/RightSideBar/Inspector/Components/Form/utils/fieldOperations.js
  frontend/src/AppBuilder/Widgets/Form/Form.jsx
Labels: tested

#13534 Fix dropping a widget on grid being slow intermittenlty
  frontend/src/AppBuilder/AppCanvas/Container.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/Grid.css
  frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useDropVirtualMoveableGhost.js
  frontend/src/AppBuilder/AppCanvas/Grid/hooks/useElementGuidelines.js
Labels: tested

#13569 Fix: Set default fileType validation to image/* for filepicker widget
  frontend/src/AppBuilder/WidgetManager/widgets/filepicker.js
  server/src/modules/apps/services/widget-config/filepicker.js
Labels: tested

#13590 Pagination fix
  frontend/src/_styles/theme.scss
Labels: tested
